import GSTClassicalHodgeMinimalAlgebraicPrimitiveQuotient
import GSTClassicalHodgeAtomicAnnihilator

/-!
# GST CLASSICAL HODGE — PRIMITIVE ALGEBRAIC DEFECT

At the least bad Hodge weight, all cross-weight geometry has already been
removed and proved algebraic.  The remaining obstruction therefore lives in
the genuine primitive Hodge quotient

  H_prim := H^(p,p)_Q / L,

where `L` is the lower-generated algebraic Hodge submodule.

This file removes one final ambiguity: not every class of `H_prim` is
necessarily nonalgebraic.  The image of the full algebraic Hodge subspace in
`H_prim` is a distinguished submodule `A_prim`.  A minimal separator kills
`A_prim`, while the offending primitive basis class survives outside it.

Hence any classical Hodge failure produces a genuinely nonzero quotient

  H_prim / A_prim,

with a nonzero descended detector.  This quotient is the exact same-weight
primitive algebraic defect.  Everything already generated by lower weights
and everything already algebraic in the bad weight has been factored out.

No matrix-unit naturality, seed, projective externalization, mass law or Hodge
surjectivity hypothesis is added.  The construction uses only the actual
atomic algebraic span, minimality, and quotient linear algebra.
-/

set_option maxHeartbeats 90000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgePrimitiveAlgebraicDefect

open GSTProjectiveOverC
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeAtomicSpan
open GSTClassicalHodgeAtomicAnnihilator
open GSTClassicalHodgeRankFreeArsenalIrreducibility
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeMinimalPrimitiveSeparatorGhost
open GSTClassicalHodgeGeometricPrimitiveQuotient
open GSTClassicalHodgeMinimalAlgebraicPrimitiveQuotient

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}

/-- The algebraic part that remains after passing to the minimal genuine
primitive Hodge quotient.  It is the image of the complete algebraic Hodge
subspace, not merely the lower-generated part already divided out. -/
noncomputable def primitiveAlgebraicRemainder
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    Submodule ℚ (MinimalPrimitiveHodgeQuotient G M) :=
  Submodule.map (primitiveHodgeClass G M)
    (AlgebraicHodgeSubspace V H M.weight)

/-- The minimal separator restricted to the Hodge fiber kills every algebraic
Hodge class.  This is just the atomic-annihilator property expressed on the
intrinsic Hodge subspace. -/
theorem AlgebraicHodgeSubspace_le_minimalGhostHodgeDetector_kernel
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    AlgebraicHodgeSubspace V H M.weight ≤
      LinearMap.ker (minimalGhostHodgeDetector G M) := by
  have hker :
      pointCycleClassSpan M.weight (H.cycleClass M.weight) ≤
        LinearMap.ker M.separator.detector :=
    (annihilatesPointCycles_iff_atomicSpan_le_ker
      M.weight (H.cycleClass M.weight) M.separator.detector).mp
      M.separator.annihilates_atoms
  intro alpha halpha
  exact hker halpha

/-- The descended primitive detector kills the complete primitive algebraic
remainder. -/
theorem primitiveAlgebraicRemainder_le_detectorKernel
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    primitiveAlgebraicRemainder G M ≤
      LinearMap.ker (minimalPrimitiveHodgeDetector G M) := by
  rintro y ⟨alpha, halpha, rfl⟩
  rw [minimalPrimitiveHodgeDetector_primitiveHodgeClass]
  exact AlgebraicHodgeSubspace_le_minimalGhostHodgeDetector_kernel G M halpha

/-- The offending primitive basis class is not contained in the algebraic
remainder.  Otherwise the descended separator would both vanish and detect it. -/
theorem minimalGhost_primitiveHodgeClass_not_mem_algebraicRemainder
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    primitiveHodgeClass G M
        (classicalHodgeBasis V H M.weight M.sheet) ∉
      primitiveAlgebraicRemainder G M := by
  intro hmem
  have hzero := primitiveAlgebraicRemainder_le_detectorKernel G M hmem
  have hdetect :
      minimalPrimitiveHodgeDetector G M
        (primitiveHodgeClass G M
          (classicalHodgeBasis V H M.weight M.sheet)) ≠ 0 := by
    rw [minimalPrimitiveHodgeDetector_primitiveHodgeClass]
    exact M.separator.detects_basis
  exact hdetect hzero

/-- Therefore the primitive algebraic remainder is a proper submodule of the
minimal primitive Hodge quotient. -/
theorem primitiveAlgebraicRemainder_ne_top
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    primitiveAlgebraicRemainder G M ≠ ⊤ := by
  intro htop
  apply minimalGhost_primitiveHodgeClass_not_mem_algebraicRemainder G M
  rw [htop]
  trivial

/-- The final same-weight primitive algebraic defect quotient.  Both all
lower-generated algebraic geometry and all algebraic Hodge classes already
present in the bad weight have now been divided out. -/
abbrev PrimitiveAlgebraicDefectQuotient
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :=
  MinimalPrimitiveHodgeQuotient G M ⧸ primitiveAlgebraicRemainder G M

/-- Canonical projection to the final primitive algebraic defect quotient. -/
noncomputable def primitiveAlgebraicDefectClass
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    MinimalPrimitiveHodgeQuotient G M →ₗ[ℚ]
      PrimitiveAlgebraicDefectQuotient G M :=
  (primitiveAlgebraicRemainder G M).mkQ

/-- The offending minimal sheet remains nonzero even after quotienting by all
algebraic Hodge classes present in the primitive quotient. -/
theorem minimalGhost_primitiveAlgebraicDefectClass_ne_zero
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    primitiveAlgebraicDefectClass G M
      (primitiveHodgeClass G M
        (classicalHodgeBasis V H M.weight M.sheet)) ≠ 0 := by
  intro hz
  have hmem :
      primitiveHodgeClass G M
          (classicalHodgeBasis V H M.weight M.sheet) ∈
        primitiveAlgebraicRemainder G M := by
    exact (Submodule.Quotient.mk_eq_zero
      (primitiveAlgebraicRemainder G M)).mp hz
  exact minimalGhost_primitiveHodgeClass_not_mem_algebraicRemainder G M hmem

/-- The primitive separator descends one final time to the primitive algebraic
defect quotient, because it annihilates the whole primitive algebraic
remainder. -/
noncomputable def primitiveAlgebraicDefectDetector
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    PrimitiveAlgebraicDefectQuotient G M →ₗ[ℚ] ℚ :=
  (primitiveAlgebraicRemainder G M).liftQ
    (minimalPrimitiveHodgeDetector G M)
    (primitiveAlgebraicRemainder_le_detectorKernel G M)

@[simp]
theorem primitiveAlgebraicDefectDetector_apply
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G)
    (x : MinimalPrimitiveHodgeQuotient G M) :
    primitiveAlgebraicDefectDetector G M
        (primitiveAlgebraicDefectClass G M x) =
      minimalPrimitiveHodgeDetector G M x := by
  exact Submodule.liftQ_apply
    (primitiveAlgebraicRemainder G M)
    (minimalPrimitiveHodgeDetector G M) x

/-- The final descended detector is nonzero. -/
theorem primitiveAlgebraicDefectDetector_ne_zero
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    primitiveAlgebraicDefectDetector G M ≠ 0 := by
  intro hz
  have hval := LinearMap.congr_fun hz
    (primitiveAlgebraicDefectClass G M
      (primitiveHodgeClass G M
        (classicalHodgeBasis V H M.weight M.sheet)))
  rw [primitiveAlgebraicDefectDetector_apply] at hval
  rw [minimalPrimitiveHodgeDetector_primitiveHodgeClass] at hval
  exact M.separator.detects_basis hval

/-- Vanishing of the final primitive algebraic defect quotient is incompatible
with a minimal Hodge failure. -/
theorem primitiveAlgebraicDefectQuotient_ne_zero
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    Nontrivial (PrimitiveAlgebraicDefectQuotient G M) := by
  exact ⟨⟨0,
    primitiveAlgebraicDefectClass G M
      (primitiveHodgeClass G M
        (classicalHodgeBasis V H M.weight M.sheet)),
    by
      intro h
      exact minimalGhost_primitiveAlgebraicDefectClass_ne_zero G M
        h.symm⟩⟩

/-- **FINAL PRIMITIVE DEFECT PACKET.**
Every failure of the Stage-2G Hodge statement produces one nontrivial
same-weight primitive algebraic defect quotient, a nonzero class in it, and a
nonzero detector on it.  Thus any future cosmological/geometry extinction law
need only rule out this one sharply isolated object. -/
theorem not_hodge_yields_nontrivial_primitiveAlgebraicDefect
    (G : GeometricCycleClassSpine V H)
    (hnot : ¬ BigradedBettiHodgeStatement V H) :
    ∃ M : MinimalPrimitiveGhost G,
      primitiveAlgebraicDefectClass G M
          (primitiveHodgeClass G M
            (classicalHodgeBasis V H M.weight M.sheet)) ≠ 0
      ∧ primitiveAlgebraicDefectDetector G M ≠ 0
      ∧ primitiveAlgebraicRemainder G M ≠ ⊤ := by
  let M := minimalPrimitiveGhostOfFailure G hnot
  exact ⟨M,
    minimalGhost_primitiveAlgebraicDefectClass_ne_zero G M,
    primitiveAlgebraicDefectDetector_ne_zero G M,
    primitiveAlgebraicRemainder_ne_top G M⟩

#check primitiveAlgebraicRemainder
#check AlgebraicHodgeSubspace_le_minimalGhostHodgeDetector_kernel
#check primitiveAlgebraicRemainder_le_detectorKernel
#check minimalGhost_primitiveHodgeClass_not_mem_algebraicRemainder
#check primitiveAlgebraicRemainder_ne_top
#check PrimitiveAlgebraicDefectQuotient
#check primitiveAlgebraicDefectClass
#check minimalGhost_primitiveAlgebraicDefectClass_ne_zero
#check primitiveAlgebraicDefectDetector
#check primitiveAlgebraicDefectDetector_ne_zero
#check not_hodge_yields_nontrivial_primitiveAlgebraicDefect

#print axioms primitiveAlgebraicRemainder_le_detectorKernel
#print axioms minimalGhost_primitiveHodgeClass_not_mem_algebraicRemainder
#print axioms minimalGhost_primitiveAlgebraicDefectClass_ne_zero
#print axioms primitiveAlgebraicDefectDetector_ne_zero
#print axioms not_hodge_yields_nontrivial_primitiveAlgebraicDefect

end GSTClassicalHodgePrimitiveAlgebraicDefect
