import GSTClassicalHodgeProjectiveSeparatorKrull
import GSTClassicalHodgePrincipalSectionNoetherian
import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial
import Mathlib.AlgebraicGeometry.Pullbacks

/-!
# GST CLASSICAL HODGE — PRINCIPAL CUTS INSIDE GENERIC-POINT CLOSURES

To iterate the projective cutting construction through codimension, the cut
must be taken inside the irreducible closed subvariety represented by the
current generic point, not repeatedly inside the whole carrier.

For every point `x : V.X` this module constructs the reduced closed subscheme
whose support is `closure {x}`.  It then intersects that closure subscheme
scheme-theoretically with the generator-specific principal section chosen by
`x`, using a pullback over `V.X`.

Thus a codimension-p generic point acquires an actual principal-cut scheme
inside its own irreducible closure.  This is the geometric carrier on which
Krull's principal ideal theorem supplies codimension-p+1 components.

No Hodge data or cycle-class map is used.
-/

set_option maxHeartbeats 30000000
set_option maxRecDepth 1000000

noncomputable section

open CategoryTheory Limits
open AlgebraicGeometry
open TopologicalSpace
open GSTProjectiveOverC
open GSTClassicalHodgeProjectivePrincipalSection

namespace GSTClassicalHodgePointClosurePrincipalCut

/-- Closed subset underlying the irreducible closure generated by a point. -/
noncomputable def pointClosureClosed
    (V : SmoothProjectiveComplexScheme) (x : V.X) : Closeds V.X :=
  ⟨closure ({x} : Set V.X), isClosed_closure⟩

/-- Reduced ideal sheaf cutting out the point closure. -/
noncomputable def pointClosureIdeal
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    V.X.IdealSheafData :=
  Scheme.IdealSheafData.vanishingIdeal (pointClosureClosed V x)

/-- Actual reduced closed subscheme represented by the closure of `x`. -/
noncomputable def pointClosureScheme
    (V : SmoothProjectiveComplexScheme) (x : V.X) : Scheme :=
  (pointClosureIdeal V x).subscheme

/-- Closed immersion of the point-closure subscheme into the projective carrier. -/
noncomputable def pointClosureι
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    pointClosureScheme V x ⟶ V.X :=
  (pointClosureIdeal V x).subschemeι

instance pointClosure_isClosedImmersion
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    IsClosedImmersion (pointClosureι V x) :=
  inferInstanceAs (IsClosedImmersion
    (Scheme.IdealSheafData.subschemeι (pointClosureIdeal V x)))

/-- Scheme-theoretic intersection of the irreducible point closure with the
source-specific projective principal section. -/
noncomputable def closurePrincipalCut
    (V : SmoothProjectiveComplexScheme) (x : V.X) : Scheme :=
  pullback (pointClosureι V x) (principalSectionAtι V x)

/-- Projection of the closure-principal intersection back to the point closure. -/
noncomputable def closurePrincipalCutToClosure
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    closurePrincipalCut V x ⟶ pointClosureScheme V x :=
  pullback.fst (pointClosureι V x) (principalSectionAtι V x)

/-- Projection of the closure-principal intersection to the principal section. -/
noncomputable def closurePrincipalCutToSection
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    closurePrincipalCut V x ⟶ principalSectionAt V x :=
  pullback.snd (pointClosureι V x) (principalSectionAtι V x)

/-- The two projections agree after inclusion into the ambient carrier. -/
theorem closurePrincipalCut_condition
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    closurePrincipalCutToClosure V x ≫ pointClosureι V x =
      closurePrincipalCutToSection V x ≫ principalSectionAtι V x :=
  pullback.condition

/-- The principal cut remains a closed immersion after restriction to the
point closure. -/
instance closurePrincipalCutToClosure_isClosedImmersion
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    IsClosedImmersion (closurePrincipalCutToClosure V x) := by
  dsimp [closurePrincipalCutToClosure]
  infer_instance

/-- The same intersection is also closed inside the principal section. -/
instance closurePrincipalCutToSection_isClosedImmersion
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    IsClosedImmersion (closurePrincipalCutToSection V x) := by
  dsimp [closurePrincipalCutToSection]
  infer_instance

/-- The point closure is itself compact as a closed subspace of a smooth
projective carrier. -/
noncomputable def pointClosureCompactSpace
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    CompactSpace (pointClosureScheme V x) := by
  letI : CompactSpace V.X := GSTCompactNativeCyclePresentation.smoothProjectiveCompactSpace V
  letI : IsClosedImmersion (pointClosureι V x) := pointClosure_isClosedImmersion V x
  refine ⟨?_⟩
  have hpre :=
    QuasiCompact.isCompact_preimage
      (f := pointClosureι V x)
      Set.univ isOpen_univ (isCompact_univ : IsCompact (Set.univ : Set V.X))
  simpa using hpre

/-- The point closure is locally Noetherian. -/
noncomputable def pointClosureIsLocallyNoetherian
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    IsLocallyNoetherian (pointClosureScheme V x) := by
  letI : IsLocallyNoetherian V.X := GSTSmoothProjectiveNoetherian.smoothProjectiveIsLocallyNoetherian V
  letI : IsClosedImmersion (pointClosureι V x) := pointClosure_isClosedImmersion V x
  letI : LocallyOfFiniteType (pointClosureι V x) := by infer_instance
  exact LocallyOfFiniteType.isLocallyNoetherian (pointClosureι V x)

/-- Hence every generic-point closure is a Noetherian projective closed carrier. -/
noncomputable def pointClosureIsNoetherian
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    IsNoetherian (pointClosureScheme V x) := by
  letI : IsLocallyNoetherian (pointClosureScheme V x) :=
    pointClosureIsLocallyNoetherian V x
  letI : CompactSpace (pointClosureScheme V x) :=
    pointClosureCompactSpace V x
  exact { }

/-- The restricted principal cut is Noetherian as a closed subscheme of the
Noetherian point closure. -/
noncomputable def closurePrincipalCutIsNoetherian
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    IsNoetherian (closurePrincipalCut V x) := by
  letI : IsNoetherian (pointClosureScheme V x) := pointClosureIsNoetherian V x
  letI : IsLocallyNoetherian (pointClosureScheme V x) := inferInstance
  letI : IsClosedImmersion (closurePrincipalCutToClosure V x) :=
    closurePrincipalCutToClosure_isClosedImmersion V x
  letI : LocallyOfFiniteType (closurePrincipalCutToClosure V x) := by infer_instance
  letI : IsLocallyNoetherian (closurePrincipalCut V x) :=
    LocallyOfFiniteType.isLocallyNoetherian (closurePrincipalCutToClosure V x)
  letI : CompactSpace (pointClosureScheme V x) := pointClosureCompactSpace V x
  letI : CompactSpace (closurePrincipalCut V x) := by
    refine ⟨?_⟩
    have hpre :=
      QuasiCompact.isCompact_preimage
        (f := closurePrincipalCutToClosure V x)
        Set.univ isOpen_univ
        (isCompact_univ : IsCompact (Set.univ : Set (pointClosureScheme V x)))
    simpa using hpre
  exact { }

/-- Closure-cut geometry crown. -/
theorem point_closure_principal_cut_crown
    (V : SmoothProjectiveComplexScheme) (x : V.X) :
    IsClosedImmersion (closurePrincipalCutToClosure V x)
      ∧ IsClosedImmersion (closurePrincipalCutToSection V x) := by
  exact ⟨inferInstance, inferInstance⟩

#check pointClosureClosed
#check pointClosureIdeal
#check pointClosureScheme
#check pointClosureι
#check closurePrincipalCut
#check closurePrincipalCutToClosure
#check closurePrincipalCutToSection
#check pointClosureIsNoetherian
#check closurePrincipalCutIsNoetherian
#check point_closure_principal_cut_crown

#print axioms pointClosureCompactSpace
#print axioms pointClosureIsNoetherian
#print axioms closurePrincipalCutIsNoetherian
#print axioms point_closure_principal_cut_crown

end GSTClassicalHodgePointClosurePrincipalCut
