import GSTClassicalHodgeOmniversalSeparatorGhostCrown
import GSTClassicalHodgeLimitlessSpinePropagation

/-!
# GST CLASSICAL HODGE — GHOST / SPINE MULTIPLICITY SEPARATION

Native mass already proves that the canonical normalized projective spine is
nonzero in every weight.  A hypothetical Hodge obstruction is represented by
an omniversal separator ghost whose detector annihilates every genuine cycle
class while detecting one Hodge basis sheet.

The canonical spine itself is an actual cycle class.  Therefore every ghost
detector kills the spine.  Since it does not kill its detected basis sheet,
that sheet cannot even lie on the rational line generated by the spine.

Thus a surviving Hodge counterexample is forced into a genuine fixed-weight
multiplicity phenomenon: at the obstructed weight there are two nonzero Hodge
directions, the canonical native spine and the ghost-detected direction, and
the latter is not a scalar multiple of the former.

This removes one more false frontier.  The unresolved geometry is not seed
existence, tower nonvanishing, or codimension propagation.  It is horizontal
native coupling between genuinely independent Hodge multiplicity directions.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeGhostSpineMultiplicity

open GSTProjectiveOverC
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeAtomicSpan
open GSTClassicalHodgeAtomicAnnihilator
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeLimitlessSpinePropagation
open GSTClassicalHodgeOmniversalSeparatorGhostCrown

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}

/-- Every omniversal separator annihilates the canonical projective-spine
Hodge state at its own weight, because that state is the exact class of the
native spine cycle. -/
theorem ghost_detector_kills_spine
    (G : GeometricCycleClassSpine V H)
    (E : OmniversalSeparatorGhost G) :
    E.separator.detector (spineHodgeSeed G E.weight).1 = 0 := by
  have hker :
      pointCycleClassSpan E.weight (H.cycleClass E.weight) ≤
        LinearMap.ker E.separator.detector :=
    (annihilatesPointCycles_iff_atomicSpan_le_ker
      E.weight (H.cycleClass E.weight) E.separator.detector).mp
      E.separator.annihilates_atoms
  apply hker
  rw [← smoothProjective_cycleClass_range_eq_atomic_span V H E.weight]
  exact ⟨spineNativeTower G E.weight,
    spineNativeTower_cycleClass G E.weight⟩

/-- **GHOST SHEET IS NOT ON THE NATIVE SPINE LINE.**
The Hodge basis sheet detected by an omniversal ghost cannot be any rational
multiple of the canonical native spine state. -/
theorem ghost_basis_not_scalar_spine
    (G : GeometricCycleClassSpine V H)
    (E : OmniversalSeparatorGhost G) :
    ¬ ∃ c : ℚ,
      classicalHodgeBasis V H E.weight E.sheet =
        c • spineHodgeSeed G E.weight := by
  rintro ⟨c, hc⟩
  have hread := congrArg
    (fun z : ClassicalHodgeFiber V H E.weight =>
      E.separator.detector z.1) hc
  have hspine := ghost_detector_kills_spine G E
  have hzero :
      E.separator.detector
        (classicalHodgeBasis V H E.weight E.sheet).1 = 0 := by
    simpa [hspine] using hread
  exact E.separator.detects_basis hzero

/-- The basis sheet detected by a ghost is itself nonzero. -/
theorem ghost_basis_ne_zero
    (G : GeometricCycleClassSpine V H)
    (E : OmniversalSeparatorGhost G) :
    classicalHodgeBasis V H E.weight E.sheet ≠ 0 := by
  intro hz
  have hread := congrArg
    (fun z : ClassicalHodgeFiber V H E.weight =>
      E.separator.detector z.1) hz
  apply E.separator.detects_basis
  simpa using hread

/-- A compact witness that the obstructed weight contains a genuine Hodge
multiplicity direction outside the canonical native spine line. -/
structure GhostSpineMultiplicityWitness
    (G : GeometricCycleClassSpine V H) where
  ghost : OmniversalSeparatorGhost G
  spine_ne_zero : spineHodgeSeed G ghost.weight ≠ 0
  basis_ne_zero :
    classicalHodgeBasis V H ghost.weight ghost.sheet ≠ 0
  basis_not_scalar_spine :
    ¬ ∃ c : ℚ,
      classicalHodgeBasis V H ghost.weight ghost.sheet =
        c • spineHodgeSeed G ghost.weight

/-- Native mass upgrades every omniversal ghost to a genuine two-direction
multiplicity witness. -/
noncomputable def OmniversalSeparatorGhost.toSpineMultiplicityWitness
    (G : GeometricCycleClassSpine V H)
    (M : NativeMassCycleClassBridge V H)
    (E : OmniversalSeparatorGhost G) :
    GhostSpineMultiplicityWitness G where
  ghost := E
  spine_ne_zero := M.spineHodgeSeed_ne_zero G E.weight
  basis_ne_zero := ghost_basis_ne_zero G E
  basis_not_scalar_spine := ghost_basis_not_scalar_spine G E

/-- **FAILURE FORCES GENUINE FIXED-WEIGHT MULTIPLICITY.**
After native-mass nonvanishing is available, every genuine Stage-2G Hodge
failure produces one obstructed weight carrying a nonzero native spine and a
second nonzero Hodge basis direction outside the rational spine line. -/
theorem failure_yields_ghostSpineMultiplicity
    (G : GeometricCycleClassSpine V H)
    (M : NativeMassCycleClassBridge V H)
    (hnot : ¬ BigradedBettiHodgeStatement V H) :
    Nonempty (GhostSpineMultiplicityWitness G) := by
  rcases (not_hodge_iff_nonempty_omniversalSeparatorGhost G).mp hnot with ⟨E⟩
  exact ⟨E.toSpineMultiplicityWitness G M⟩

/-- Contrapositive crown: if native mass holds and no weight admits the
multiplicity pattern forced by a ghost, then Stage-2G Hodge is true. -/
theorem bigradedBettiHodge_of_no_ghostSpineMultiplicity
    (G : GeometricCycleClassSpine V H)
    (M : NativeMassCycleClassBridge V H)
    (hno : IsEmpty (GhostSpineMultiplicityWitness G)) :
    BigradedBettiHodgeStatement V H := by
  by_contra hnot
  exact isEmpty_iff.mp hno
    (Classical.choice (failure_yields_ghostSpineMultiplicity G M hnot))

#check ghost_detector_kills_spine
#check ghost_basis_not_scalar_spine
#check ghost_basis_ne_zero
#check GhostSpineMultiplicityWitness
#check OmniversalSeparatorGhost.toSpineMultiplicityWitness
#check failure_yields_ghostSpineMultiplicity
#check bigradedBettiHodge_of_no_ghostSpineMultiplicity

#print axioms ghost_detector_kills_spine
#print axioms ghost_basis_not_scalar_spine
#print axioms ghost_basis_ne_zero
#print axioms failure_yields_ghostSpineMultiplicity
#print axioms bigradedBettiHodge_of_no_ghostSpineMultiplicity

end GSTClassicalHodgeGhostSpineMultiplicity
