import GSTClassicalHodgeSingleStateBareLefschetzExtinction
import GSTClassicalHodgeProjectiveWordOrbit

/-!
# GST CLASSICAL HODGE — LOCAL-SEED PROJECTIVE-WORD EXTINCTION

The single-state bare-Lefschetz reduction shows that a hypothetical minimal
primitive Hodge ghost can be killed from one nonzero algebraic source state.
The projective-word orbit machinery gives a second, even more geometric route:
an arbitrary finite noncommutative word in genuine projective self-transports
may be evaluated on one synchronized native/Hodge source and normalized to an
actual target-basis cycle.

This file splices the two interfaces.

A `MinimalGhostLocalSeed` already contains a nonzero algebraic Hodge source.
Using the exact equality between the actual cycle-class range and the atomic
algebraic span, choose one genuine native cycle representing that source.  This
produces a `NativeHodgeOrbitSeed` without any Hodge-surjectivity assumption.
If one projective operator word sends its selected live source coordinate to
the basis sheet detected by the minimal ghost, the projective-word extraction
theorem returns an actual native cycle representing that sheet.  But the ghost
separator annihilates every algebraic point-cycle class while detecting the
same sheet nontrivially, contradiction.

Hence the full operator-natural bare-`L^2` requirement can be bypassed by a
strictly local geometric target: construct one finite word in genuine
projective self-transports with the required action on one live source state.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeLocalSeedProjectiveWordExtinction

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeAtomicSpan
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeMinimalPrimitiveSeparatorGhost
open GSTClassicalHodgeLocalSeedBareLefschetzExtinction
open GSTClassicalHodgeSynchronizedDefectOrbit
open GSTClassicalHodgeProjectiveWordOrbit

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}

/-- Every local minimal-ghost seed has a genuine synchronized native-cycle
representative.  The choice is made only inside the already-proved
cycle-class range; no basis vector is assumed algebraic. -/
noncomputable def orbitSeedOfLocalSeed
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G)
    (S : MinimalGhostLocalSeed G M) :
    NativeHodgeOrbitSeed (V := V) (H := H) (p := M.weight) := by
  have hrange : S.source.1 ∈ LinearMap.range (H.cycleClass M.weight) := by
    rw [smoothProjective_cycleClass_range_eq_atomic_span V H M.weight]
    exact S.source_algebraic
  let Z : codimensionCycles V.X M.weight := Classical.choose hrange
  have hZ : H.cycleClass M.weight Z = S.source.1 :=
    Classical.choose_spec hrange
  refine {
    cycle := Z
    hodge := S.source
    hodge_ne_zero := ?_
    class_eq := hZ
  }
  intro hzero
  apply S.sourceCoefficient_ne_zero
  rw [hzero]
  simp [GSTClassicalHodgeRankFreeArsenalIrreducibility.hodgeCoordinate]

/-- **ONE PROJECTIVE WORD KILLS THE MINIMAL GHOST.**

No ambient operator naturality is requested.  It is enough to construct one
finite noncommutative word generated by genuine projective self-transports
whose canonical cohomological realization has the required source-to-ghost
sheet action on the single synchronized algebraic source. -/
theorem minimalGhost_false_of_localSeed_projectiveWord
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G)
    (S : MinimalGhostLocalSeed G M)
    (R : ProjectiveWordLiveSourceTarget G
      (orbitSeedOfLocalSeed G M S) M.sheet) : False := by
  let O := orbitSeedOfLocalSeed G M S
  let Ztarget : codimensionCycles V.X M.weight := R.targetCycle
  have hclass :
      H.cycleClass M.weight Ztarget =
        (GSTClassicalHodgeRankFreeArsenalIrreducibility.classicalHodgeBasis
          V H M.weight M.sheet).1 := by
    simpa [O, Ztarget] using R.targetCycle_spec
  have hatomic :
      H.cycleClass M.weight Ztarget ∈
        pointCycleClassSpan M.weight (H.cycleClass M.weight) := by
    rw [← smoothProjective_cycleClass_range_eq_atomic_span V H M.weight]
    exact ⟨Ztarget, rfl⟩
  have hker :
      pointCycleClassSpan M.weight (H.cycleClass M.weight) ≤
        LinearMap.ker M.separator.detector :=
    (GSTClassicalHodgeAtomicAnnihilator.annihilatesPointCycles_iff_atomicSpan_le_ker
      M.weight (H.cycleClass M.weight) M.separator.detector).mp
      M.separator.annihilates_atoms
  have hzero := hker hatomic
  rw [hclass] at hzero
  exact M.separator.detects_basis hzero

#check orbitSeedOfLocalSeed
#check minimalGhost_false_of_localSeed_projectiveWord

#print axioms orbitSeedOfLocalSeed
#print axioms minimalGhost_false_of_localSeed_projectiveWord

end GSTClassicalHodgeLocalSeedProjectiveWordExtinction
