import GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra
import GSTClassicalHodgeSynchronizedDefectOrbit
import GSTClassicalHodgePiUnboundedOmniverseCrown
import GSTClassicalHodgePiOmniverseCanonicalSupportSpectral
import GSTClassicalHodgeExactClayStatement

/-!
# GST CLASSICAL HODGE — PI ONE-SOURCE COMPOSITIONAL-CORRESPONDENCE FINALE

This file removes the overstrong pointwise matrix-unit requirement from the
preceding finite-correspondence finale.

At one live Hodge weight we retain only one already genuine algebraic Hodge
source `S`.  For each requested Hodge basis sheet `j`, geometry supplies one
expression in the FULL noncommutative algebra generated by actual realized
finite closed correspondences under rational scaling, addition and ordered
composition.  The expression is required to hit the single source by a
nonzero rational scalar:

    E_j (cl(S.cycle)) = c_j * basis_j,   c_j != 0.

Nothing is required about the action of `E_j` on any other point, cycle or
Hodge vector.  Because every realized expression already has an exact native /
cohomological commuting square, applying `E_j` to the actual native source
cycle and dividing by `c_j` constructs the target basis cycle directly.

This is strictly weaker than:
* materializing every GST branch event;
* realizing a matrix unit on the whole Hodge fiber;
* realizing it on every native point atom;
* supplying an arbitrary ambient cohomology endomorphism;
* supplying target basis cycles.

Once the basis cycles are obtained, finite Hodge support reconstructs every
class.  The internal GST machinery is then used at full strength without
being confused with algebraicity: the same source/target branch exists in all
three sectors, the canonical live window carries its exact N-cohomology packet,
and every target persists through all finite levels of the unbounded higher-
causal cosmos.
-/

set_option maxHeartbeats 280000000
set_option maxRecDepth 1000000

noncomputable section

open scoped BigOperators
open AlgebraicGeometry

namespace GSTClassicalHodgePiOneSourceCompositionalCorrespondenceFinale

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeRankFreeArsenalIrreducibility
open GSTClassicalHodgeSynchronizedDefectOrbit
open GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra
open GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra.RealizedCorrespondenceExpr
open GSTClassicalHodgeOmniverseCausalBranchPacket
open GSTClassicalHodgePiOmniverseCanonicalSupportSpectral
open GSTClassicalHodgePiUnboundedOmniverseCrown
open GSTClassicalHodgeExactClayStatement
open GSTGraphV2OmniversalCore

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-- The minimal same-source geometric packet for one live weight.

`seed` is an actual native algebraic cycle synchronized with a nonzero genuine
Hodge state.  Each target is reached only on that one source by one actual
compositional correspondence expression. -/
structure OneSourceCompositionalCorrespondenceRealization (p : Nat) where
  seed : NativeHodgeOrbitSeed (V := V) (H := H) (p := p)
  expression :
    ∀ j : ClassicalHodgeBasisIndex V H p,
      RealizedCorrespondenceExpr V H p
  scalar : ClassicalHodgeBasisIndex V H p → ℚ
  scalar_ne_zero : ∀ j, scalar j ≠ 0
  source_hit :
    ∀ j : ClassicalHodgeBasisIndex V H p,
      (expression j).cohomologyOperator seed.hodge.1 =
        scalar j • (classicalHodgeBasis V H p j).1

namespace OneSourceCompositionalCorrespondenceRealization

/-- Execute the genuine correspondence expression on the actual native source
and normalize by the nonzero target scalar. -/
noncomputable def basisCycle
    (R : OneSourceCompositionalCorrespondenceRealization
      (V := V) (H := H) p)
    (j : ClassicalHodgeBasisIndex V H p) :
    codimensionCycles V.X p :=
  (R.scalar j)⁻¹ • (R.expression j).cycleOperator R.seed.cycle

/-- **ONE-SOURCE COMPOSITIONAL HIT -> EXACT NATIVE BASIS CYCLE.** -/
theorem basisCycle_spec
    (R : OneSourceCompositionalCorrespondenceRealization
      (V := V) (H := H) p)
    (j : ClassicalHodgeBasisIndex V H p) :
    H.cycleClass p (R.basisCycle j) =
      (classicalHodgeBasis V H p j).1 := by
  have hnat := (R.expression j).cycleClass_natural R.seed.cycle
  rw [R.seed.class_eq, R.source_hit j] at hnat
  unfold basisCycle
  rw [LinearMap.map_smul, hnat]
  simp [R.scalar_ne_zero j, smul_smul]

/-- Every genuine Hodge basis direction is therefore in the true cycle-class
range. -/
theorem basis_mem_cycleClassRange
    (R : OneSourceCompositionalCorrespondenceRealization
      (V := V) (H := H) p)
    (j : ClassicalHodgeBasisIndex V H p) :
    (classicalHodgeBasis V H p j).1 ∈
      LinearMap.range (H.cycleClass p) :=
  ⟨R.basisCycle j, R.basisCycle_spec j⟩

/-- Finite-support native reconstruction of an arbitrary Hodge class. -/
noncomputable def collapseCycle
    (R : OneSourceCompositionalCorrespondenceRealization
      (V := V) (H := H) p)
    (alpha : ClassicalHodgeFiber V H p) :
    codimensionCycles V.X p :=
  ∑ j ∈ ((classicalHodgeBasis V H p).repr alpha).support,
    ((classicalHodgeBasis V H p).repr alpha j) • R.basisCycle j

/-- The reconstructed native cycle has exactly the requested Hodge class. -/
theorem collapseCycle_spec
    (R : OneSourceCompositionalCorrespondenceRealization
      (V := V) (H := H) p)
    (alpha : ClassicalHodgeFiber V H p) :
    H.cycleClass p (R.collapseCycle alpha) = alpha.1 := by
  rw [collapseCycle, map_sum]
  simp only [LinearMap.map_smul]
  rw [show alpha =
      ∑ j ∈ ((classicalHodgeBasis V H p).repr alpha).support,
        ((classicalHodgeBasis V H p).repr alpha j) •
          classicalHodgeBasis V H p j by
    exact (classicalHodgeBasis V H p).sum_repr alpha]
  simp only [Submodule.coe_sum, Submodule.coe_smul_of_tower]
  apply Finset.sum_congr rfl
  intro j hj
  rw [R.basisCycle_spec j]

/-- Exact fixed-weight Stage-2G landing. -/
theorem hodge_weight
    (R : OneSourceCompositionalCorrespondenceRealization
      (V := V) (H := H) p) :
    rationalHodgeSubspace (H.hodgeBigrading p) ≤
      LinearMap.range (H.cycleClass p) := by
  intro alpha halpha
  let alphaH : ClassicalHodgeFiber V H p := ⟨alpha, halpha⟩
  exact ⟨R.collapseCycle alphaH, R.collapseCycle_spec alphaH⟩

/-- Once algebraicity has been established by the genuine correspondence
expression, the associated GST matrix-unit target is algebraic in every sector
and persists through every finite higher-causal level. -/
theorem target_allSectors_unbounded
    (R : OneSourceCompositionalCorrespondenceRealization
      (V := V) (H := H) p)
    (s : Sector)
    (j : ClassicalHodgeBasisIndex V H p) :
    let target : HodgeBranchNode (V := V) (H := H) (p := p) :=
      ⟨s, hodgeMatrixUnit R.seed.sourceIndex j R.seed.hodge⟩
    AlgebraicBranchNode (V := V) (H := H) (p := p) target
      ∧ (hodgeBranchGraph (V := V) (H := H) (p := p)).Event
          ⟨Sector.gstPlus, R.seed.hodge⟩ target
      ∧ ∀ n : Nat,
        ∃ c : (hodgeHigherCausalCosmos (V := V) (H := H) (p := p)).Cell n,
          c = target ∧ AlgebraicBranchNode (V := V) (H := H) (p := p) c := by
  dsimp
  let a : ℚ :=
    (classicalHodgeBasis V H p).repr R.seed.hodge R.seed.sourceIndex
  have hbasis := R.basis_mem_cycleClassRange j
  have hscaled :=
    (LinearMap.range (H.cycleClass p)).smul_mem a hbasis
  have hAlg :
      (hodgeMatrixUnit R.seed.sourceIndex j R.seed.hodge).1 ∈
        LinearMap.range (H.cycleClass p) := by
    simpa [a, hodgeMatrixUnit_apply, hodgeCoordinate] using hscaled
  have hEvent :
      (hodgeBranchGraph (V := V) (H := H) (p := p)).Event
        ⟨Sector.gstPlus, R.seed.hodge⟩
        ⟨s, hodgeMatrixUnit R.seed.sourceIndex j R.seed.hodge⟩ :=
    HodgeBranchEvent.matrixUnit R.seed.hodge R.seed.sourceIndex j s
  exact ⟨hAlg, hEvent,
    algebraicBranch_has_unbounded_higher_certificate
      (V := V) (H := H) (p := p)
      ⟨s, hodgeMatrixUnit R.seed.sourceIndex j R.seed.hodge⟩ hAlg⟩

end OneSourceCompositionalCorrespondenceRealization

/-- Pi-wide realization principle at the sharp same-source correspondence
frontier.  Dead Hodge weights require no source. -/
def PiOneSourceCompositionalCorrespondenceRealization : Prop :=
  ∀ q : Nat,
    rationalHodgeSubspace (H.hodgeBigrading q) ≠ ⊥ →
      Nonempty
        (OneSourceCompositionalCorrespondenceRealization
          (V := V) (H := H) q)

/-- **PI-WIDE EXACT STAGE-2G LANDING.** -/
theorem bigradedBettiHodge_of_piOneSourceCompositionalCorrespondences
    (R : PiOneSourceCompositionalCorrespondenceRealization
      (V := V) (H := H)) :
    BigradedBettiHodgeStatement V H := by
  intro q alpha halpha
  by_cases hq : rationalHodgeSubspace (H.hodgeBigrading q) = ⊥
  · have hzero : alpha = 0 := by
      have : alpha ∈
          (⊥ : Submodule ℚ
            (RationalSingularCohomology H.analytification (2 * q))) := by
        simpa [hq] using halpha
      simpa using this
    subst alpha
    exact LinearMap.zero_mem _
  · let W := Classical.choice (R q hq)
    exact W.hodge_weight halpha

/-- Exact Clay finite-rational-combination formulation. -/
theorem everyHodgeClassIsFiniteRationalCombination_of_piOneSourceCompositionalCorrespondences
    (R : PiOneSourceCompositionalCorrespondenceRealization
      (V := V) (H := H)) :
    EveryHodgeClassIsFiniteRationalCombination H := by
  exact (exact_rational_hodge_conjecture_finite_sum H).1
    (bigradedBettiHodge_of_piOneSourceCompositionalCorrespondences R)

/-- Exact N-cohomology packet on the canonical finite live support of an
arbitrary requested Hodge state. -/
theorem exact_ncohomology_packet
    (depth : Nat)
    (alpha : ClassicalHodgeFiber V H p) :
    ∃ basis : Fin (liveRank alpha) →
        GSTNCohomology.nCohoClasses depth (liveSupportNShape alpha) 1,
      ∀ i : Fin (liveRank alpha),
        (basis i).1 i =
          GSTNCohomology.towerWindow depth
            ((liveSupportNShape alpha).channel i) 1 := by
  simpa using canonicalWindow_has_ncohomology_packet
    (V := V) (H := H) (p := p) depth alpha

/-- **FULL PI / COMPOSITIONAL-CORRESPONDENCE / GST OMNIVERSE CROWN.**
One actual algebraic source and source-specific realized correspondence hits
simultaneously give an explicit native representative, exact N-cohomology, and
algebraic target branches in all sectors at every finite causal depth. -/
theorem pi_oneSourceCompositional_unbounded_crown
    (depth : Nat)
    (R : OneSourceCompositionalCorrespondenceRealization
      (V := V) (H := H) p)
    (alpha : ClassicalHodgeFiber V H p) :
    (∃ Z : codimensionCycles V.X p,
      H.cycleClass p Z = alpha.1)
    ∧ (∃ basis : Fin (liveRank alpha) →
        GSTNCohomology.nCohoClasses depth (liveSupportNShape alpha) 1,
      ∀ i : Fin (liveRank alpha),
        (basis i).1 i =
          GSTNCohomology.towerWindow depth
            ((liveSupportNShape alpha).channel i) 1)
    ∧ (∀ s : Sector, ∀ j : ClassicalHodgeBasisIndex V H p,
      let target : HodgeBranchNode (V := V) (H := H) (p := p) :=
        ⟨s, hodgeMatrixUnit R.seed.sourceIndex j R.seed.hodge⟩
      AlgebraicBranchNode (V := V) (H := H) (p := p) target
        ∧ (hodgeBranchGraph (V := V) (H := H) (p := p)).Event
            ⟨Sector.gstPlus, R.seed.hodge⟩ target
        ∧ ∀ n : Nat,
          ∃ c : (hodgeHigherCausalCosmos
            (V := V) (H := H) (p := p)).Cell n,
            c = target ∧
              AlgebraicBranchNode (V := V) (H := H) (p := p) c) := by
  refine ⟨⟨R.collapseCycle alpha, R.collapseCycle_spec alpha⟩,
    exact_ncohomology_packet depth alpha, ?_⟩
  intro s j
  exact R.target_allSectors_unbounded s j

#check OneSourceCompositionalCorrespondenceRealization
#check OneSourceCompositionalCorrespondenceRealization.basisCycle
#check OneSourceCompositionalCorrespondenceRealization.basisCycle_spec
#check OneSourceCompositionalCorrespondenceRealization.collapseCycle
#check OneSourceCompositionalCorrespondenceRealization.collapseCycle_spec
#check OneSourceCompositionalCorrespondenceRealization.hodge_weight
#check OneSourceCompositionalCorrespondenceRealization.target_allSectors_unbounded
#check PiOneSourceCompositionalCorrespondenceRealization
#check bigradedBettiHodge_of_piOneSourceCompositionalCorrespondences
#check everyHodgeClassIsFiniteRationalCombination_of_piOneSourceCompositionalCorrespondences
#check exact_ncohomology_packet
#check pi_oneSourceCompositional_unbounded_crown

#print axioms OneSourceCompositionalCorrespondenceRealization.basisCycle_spec
#print axioms OneSourceCompositionalCorrespondenceRealization.collapseCycle_spec
#print axioms OneSourceCompositionalCorrespondenceRealization.hodge_weight
#print axioms OneSourceCompositionalCorrespondenceRealization.target_allSectors_unbounded
#print axioms bigradedBettiHodge_of_piOneSourceCompositionalCorrespondences
#print axioms everyHodgeClassIsFiniteRationalCombination_of_piOneSourceCompositionalCorrespondences
#print axioms pi_oneSourceCompositional_unbounded_crown

end GSTClassicalHodgePiOneSourceCompositionalCorrespondenceFinale
