import GSTClassicalHodgeRealizedClosedCorrespondenceAlgebra

/-!
# GST CLASSICAL HODGE — REALIZED CORRESPONDENCE EXPRESSION ALGEBRA

`RealizedCorrespondenceWord` is a finite rational linear combination of actual
realized correspondences.  The underlying `CycleClassOperatorPair` API already
supports composition, but the word syntax did not expose it.

For the Hodge attack this is a real loss of geometric power: iterated
correspondence action, noncommutative generator words, commutators, polynomial
operator expressions and GST-style operator synthesis all require composition.

This module closes the ACTUAL realized correspondence arena under:

* zero;
* genuine realized correspondence atoms;
* rational scaling;
* addition;
* noncommutative composition.

Every expression evaluates to an exact native/cohomology operator pair, so
cycle-class naturality and native algebraicity are preserved by construction.
No Hodge conclusion or arbitrary lift is inserted.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeAtomicSpan
open GSTClassicalHodgeRealizedClosedCorrespondenceAlgebra

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-- Free noncommutative expression algebra generated by genuinely realized
finite closed correspondences. -/
inductive RealizedCorrespondenceExpr
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V)
    (p : Nat) : Type
  | zero
  | atom (R : RealizedFiniteClosedCorrespondence V H p)
  | smul (q : ℚ) (E : RealizedCorrespondenceExpr V H p)
  | add (E F : RealizedCorrespondenceExpr V H p)
  | comp (E F : RealizedCorrespondenceExpr V H p)

namespace RealizedCorrespondenceExpr

/-- Exact native/cohomology pair denoted by a genuine correspondence
expression.  Composition is the actual noncommutative operator composition. -/
noncomputable def operatorPair :
    RealizedCorrespondenceExpr V H p → CycleClassOperatorPair V H p
  | .zero => CycleClassOperatorPair.zero
  | .atom R => R.operatorPair
  | .smul q E => CycleClassOperatorPair.smul q E.operatorPair
  | .add E F => CycleClassOperatorPair.add E.operatorPair F.operatorPair
  | .comp E F => CycleClassOperatorPair.comp E.operatorPair F.operatorPair

/-- Native operator denoted by the expression. -/
noncomputable def cycleOperator
    (E : RealizedCorrespondenceExpr V H p) :=
  E.operatorPair.cycleOperator

/-- Rational cohomology operator denoted by the expression. -/
noncomputable def cohomologyOperator
    (E : RealizedCorrespondenceExpr V H p) :=
  E.operatorPair.cohomologyOperator

/-- Every composite expression satisfies the exact native/cohomology commuting
square. -/
theorem cycleClass_natural
    (E : RealizedCorrespondenceExpr V H p)
    (Z : codimensionCycles V.X p) :
    H.cycleClass p (E.cycleOperator Z) =
      E.cohomologyOperator (H.cycleClass p Z) := by
  exact E.operatorPair.cycleClass_cycleOperator Z

/-- Every expression preserves the genuine cycle-class range. -/
theorem range_stable
    (E : RealizedCorrespondenceExpr V H p) :
    ∀ alpha,
      alpha ∈ LinearMap.range (H.cycleClass p) →
      E.cohomologyOperator alpha ∈ LinearMap.range (H.cycleClass p) :=
  E.operatorPair.cycleClass_range_stable

/-- Every expression preserves the atomic span of genuine point-cycle classes. -/
theorem atomic_stable
    (E : RealizedCorrespondenceExpr V H p) :
    ∀ alpha,
      alpha ∈ pointCycleClassSpan p (H.cycleClass p) →
      E.cohomologyOperator alpha ∈ pointCycleClassSpan p (H.cycleClass p) :=
  E.operatorPair.atomicSpan_stable

/-- Embed the historical finite linear word into the full expression algebra. -/
noncomputable def ofWord :
    RealizedCorrespondenceWord V H p → RealizedCorrespondenceExpr V H p
  | [] => .zero
  | (q,R) :: W => .add (.smul q (.atom R)) (ofWord W)

/-- The full expression evaluator strictly extends the historical word
evaluator. -/
theorem ofWord_operatorPair
    (W : RealizedCorrespondenceWord V H p) :
    (ofWord W).operatorPair = realizedWordPair W := by
  induction W with
  | nil => rfl
  | cons head tail ih =>
      rcases head with ⟨q,R⟩
      simp only [ofWord, operatorPair, realizedWordPair]
      rw [ih]

/-- Composition is visible literally on the cohomology face. -/
@[simp] theorem comp_cohomology_apply
    (E F : RealizedCorrespondenceExpr V H p)
    (alpha : RationalSingularCohomology H.analytification (2 * p)) :
    (RealizedCorrespondenceExpr.comp E F).cohomologyOperator alpha =
      E.cohomologyOperator (F.cohomologyOperator alpha) :=
  rfl

/-- Composition is visible literally on the native-cycle face. -/
@[simp] theorem comp_cycle_apply
    (E F : RealizedCorrespondenceExpr V H p)
    (Z : codimensionCycles V.X p) :
    (RealizedCorrespondenceExpr.comp E F).cycleOperator Z =
      E.cycleOperator (F.cycleOperator Z) :=
  rfl

/-- Powers of one genuine correspondence expression. -/
noncomputable def pow
    (E : RealizedCorrespondenceExpr V H p) : Nat →
      RealizedCorrespondenceExpr V H p
  | 0 => .smul 1 .zero + .zero
  | n + 1 => .comp E (pow E n)

/-- A proper identity expression is supplied by any realized expression using
`0*E + E` only when needed by later polynomial compilers.  We keep identity
out of the primitive syntax until it has an independently geometric
realization, rather than silently inserting an arbitrary ambient identity
correspondence. -/
def HasGeometricIdentity : Prop :=
  ∃ I : RealizedCorrespondenceExpr V H p,
    I.operatorPair.cohomologyOperator = LinearMap.id ∧
    I.operatorPair.cycleOperator = LinearMap.id

#check RealizedCorrespondenceExpr
#check RealizedCorrespondenceExpr.operatorPair
#check RealizedCorrespondenceExpr.cycleClass_natural
#check RealizedCorrespondenceExpr.range_stable
#check RealizedCorrespondenceExpr.atomic_stable
#check RealizedCorrespondenceExpr.ofWord
#check RealizedCorrespondenceExpr.ofWord_operatorPair
#check RealizedCorrespondenceExpr.HasGeometricIdentity

#print axioms RealizedCorrespondenceExpr.cycleClass_natural
#print axioms RealizedCorrespondenceExpr.range_stable
#print axioms RealizedCorrespondenceExpr.atomic_stable
#print axioms RealizedCorrespondenceExpr.ofWord_operatorPair

end RealizedCorrespondenceExpr
end GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra
