import GSTClassicalHodgePointNormalForm
import GSTCompactNativeCyclePresentation
import GSTClassicalHodgePointKernelOperatorLift

/-!
# GST CLASSICAL HODGE — GEOMETRIC CYCLE-CLASS POINT RIGIDITY

Stage 2G still stores `H.cycleClass` as a linear map.  On a smooth projective
carrier, however, the repository has already proved an exact compact point
normal form: every native codimension-p algebraic cycle is a finite rational
sum of genuine codimension-p irreducible point cycles.

Therefore the entire cycle-class map is FORCED by the fundamental Betti class
assigned to each codimension-p point.  There is no residual linear freedom on
native cycles once the point classes are fixed.

This file constructs the unique linear cycle-class map generated by a point
fundamental-class assignment and proves extensional rigidity against the
Stage-2G supplied map.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry
open GSTClassicalHodgePointKernelOperatorLift

namespace GSTClassicalHodgeGeometricCycleClassPointRigidity

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTNativeCodimensionCyclePresentation
open GSTCompactNativeCyclePresentation
open GSTClassicalHodgePointNormalForm

local instance (V : SmoothProjectiveComplexScheme) : CompactSpace V.X :=
  smoothProjectiveCompactSpace V

variable {V : SmoothProjectiveComplexScheme}
variable (p : Nat)

/-- A geometric point-class assignment is the genuinely local datum: the Betti
fundamental class of every irreducible codimension-p point/subvariety. -/
abbrev PointBettiClass
    (A : AnalytificationData V) :=
  CodimensionPoint V.X p → RationalSingularCohomology A (2 * p)

/-- **CYCLE CLASS GENERATED FROM POINT FUNDAMENTAL CLASSES.**
Extend the point-class assignment linearly through the exact compact native
cycle/presentation equivalence.  This is a construction, not a supplied map. -/
noncomputable def cycleClassFromPointGeometry
    (A : AnalytificationData V)
    (pt : PointBettiClass (V := V) p A) :
    codimensionCycles V.X p →ₗ[ℚ]
      RationalSingularCohomology A (2 * p) := by
  letI : CompactSpace V.X := smoothProjectiveCompactSpace V
  let evalPresentation :
      FiniteCodimensionPresentation V.X p →ₗ[ℚ]
        RationalSingularCohomology A (2 * p) :=
    Finsupp.linearCombination ℚ pt
  exact evalPresentation.comp
    (compactCyclePresentationLinearEquiv V.X p).symm.toLinearMap

/-- The constructed cycle class takes a point atom to exactly its supplied
geometric fundamental class. -/
@[simp]
theorem cycleClassFromPointGeometry_point
    (A : AnalytificationData V)
    (pt : PointBettiClass (V := V) p A)
    (x : CodimensionPoint V.X p) :
    cycleClassFromPointGeometry (V := V) p A pt
        (codimensionPointCycle V.X p x) = pt x := by
  letI : CompactSpace V.X := smoothProjectiveCompactSpace V
  show (Finsupp.linearCombination ℚ pt)
      (presentationOfNativeCycle V.X p (codimensionPointCycle V.X p x)) = pt x
  rw [presentationOfNativeCycle_point]
  simp [Finsupp.linearCombination]

/-- Two rational cycle-class maps agreeing on genuine codimension-p point
fundamental classes agree on EVERY native cycle. -/
theorem cycleClass_ext_points
    {M : Type*} [AddCommGroup M] [Module ℚ M]
    (F G : codimensionCycles V.X p →ₗ[ℚ] M)
    (h : ∀ x : CodimensionPoint V.X p,
      F (codimensionPointCycle V.X p x) =
        G (codimensionPointCycle V.X p x)) :
    F = G := by
  have hz : F - G = 0 := by
    apply nativeLinearMap_eq_zero_of_points V p
    intro x
    simp [h x]
  exact sub_eq_zero.mp hz

/-- **STAGE-2G CYCLE-CLASS RIGIDITY.**
Once the Stage-2G cycle class agrees with the genuine point fundamental class
construction, it is definitionally forced on the whole algebraic cycle space.
There is no remaining zero-map/arbitrary-map freedom. -/
theorem suppliedCycleClass_eq_geometric
    (H : HodgeBigradedBettiData V)
    (pt : PointBettiClass (V := V) p H.analytification)
    (hpoint : ∀ x : CodimensionPoint V.X p,
      H.cycleClass p (codimensionPointCycle V.X p x) = pt x) :
    H.cycleClass p =
      cycleClassFromPointGeometry (V := V) p H.analytification pt := by
  apply cycleClass_ext_points (V := V) p
  intro x
  rw [hpoint x, cycleClassFromPointGeometry_point]

/-- General presentation-realization roundtrip: every finite presentation is
recovered exactly from the native cycle it realizes. -/
theorem presentationOfNativeCycle_realize
    (X : Scheme.{u}) [CompactSpace X] (p : Nat)
    (φ : FiniteCodimensionPresentation X p) :
    presentationOfNativeCycle X p
      (realizeFiniteCodimensionPresentation X p φ) = φ := by
  classical
  ext y
  rw [presentationOfNativeCycle_apply,
    realizeFiniteCodimensionPresentation_apply X p φ y.1]
  simp only [Finsupp.sum]
  by_cases hy : y ∈ φ.support
  · refine (Finset.sum_eq_single y ?_ ?_).trans ?_
    · intro b _ hb
      have hne : y.1 ≠ b.1 := fun heq => hb (Subtype.ext heq.symm)
      simp [hne]
    · intro hout
      exact absurd hy hout
    · simp [hy]
  · rw [Finsupp.notMem_support_iff.mp hy]
    refine Finset.sum_eq_zero ?_
    intro x hx
    have hne : y.1 ≠ x.1 := by
      intro heq
      apply hy
      rw [Subtype.ext heq]
      exact hx
    simp [hne]

/-- Expanded finite-sum formula for the geometrically generated cycle class. -/
theorem cycleClassFromPointGeometry_eq_finite_sum
    (A : AnalytificationData V)
    (pt : PointBettiClass (V := V) p A)
    (Z : codimensionCycles V.X p) :
    cycleClassFromPointGeometry (V := V) p A pt Z =
      (presentationOfNativeCycle V.X p Z).sum
        (fun x q => q • pt x) := by
  letI : CompactSpace V.X := smoothProjectiveCompactSpace V
  rw [← realize_presentationOfNativeCycle V.X p Z]
  rw [linearMap_realizeFiniteCodimensionPresentation]
  rw [presentationOfNativeCycle_realize V.X p
    (presentationOfNativeCycle V.X p Z)]
  simp [cycleClassFromPointGeometry_point]

/-- Hence the supplied Stage-2G map itself has the same finite geometric point
formula as soon as its point classes have been identified. -/
theorem suppliedCycleClass_eq_finite_geometric_sum
    (H : HodgeBigradedBettiData V)
    (pt : PointBettiClass (V := V) p H.analytification)
    (hpoint : ∀ x : CodimensionPoint V.X p,
      H.cycleClass p (codimensionPointCycle V.X p x) = pt x)
    (Z : codimensionCycles V.X p) :
    H.cycleClass p Z =
      (presentationOfNativeCycle V.X p Z).sum
        (fun x q => q • pt x) := by
  letI : CompactSpace V.X := smoothProjectiveCompactSpace V
  rw [suppliedCycleClass_eq_geometric (V := V) p H pt hpoint]
  exact cycleClassFromPointGeometry_eq_finite_sum
    (V := V) p H.analytification pt Z

#check cycleClassFromPointGeometry
#check cycleClassFromPointGeometry_point
#check cycleClass_ext_points
#check suppliedCycleClass_eq_geometric
#check cycleClassFromPointGeometry_eq_finite_sum
#check suppliedCycleClass_eq_finite_geometric_sum

#print axioms cycleClass_ext_points
#print axioms suppliedCycleClass_eq_geometric
#print axioms suppliedCycleClass_eq_finite_geometric_sum

end GSTClassicalHodgeGeometricCycleClassPointRigidity
