import GSTClassicalHodgeGSTSpineGlobalSource
import GSTClassicalHodgeRankFreeLefschetzPoincareGeneration

/-!
# GST CLASSICAL HODGE — GLOBAL SHEET SATURATION

The total fibered Hodge address is not merely bookkeeping.  At each fixed
weight it is the exact rational span of the genuine Hodge sheets, and the
same-weight global read/write operators act irreducibly on that span.

The important point for the GST-first route is that these global matrix units
are not an extra abstract arsenal.  On the true Hodge fiber they are exactly
the rank-free matrix units, and those matrix units are already proved to be
finite localizations of words generated by the native GST Lefschetz and
Poincare operators.

Consequently one nonzero canonical spine address plus stability under the
same-weight GST read/write algebra saturates the entire weight-p sheet cosmos.
The remaining geometric problem is only to synchronize those source-specific
GST words with genuine native-cycle programs; no new linear-algebra arsenal is
needed.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open scoped BigOperators
open AlgebraicGeometry

namespace GSTClassicalHodgeGlobalSheetSaturation

open GSTProjectiveOverC
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeFiberedTransferCompletion
open GSTClassicalHodgeGlobalSheetCosmos
open GSTClassicalHodgeGSTSpineGlobalSource
open GSTClassicalHodgeLimitlessSpinePropagation
open GSTClassicalHodgeRankFreeArsenalIrreducibility
open GSTClassicalHodgeRankFreeLefschetzPoincareGeneration

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}

/-- The exact total-address subspace supported over one Hodge weight. -/
def FixedWeightSheetSubspace (p : Nat) :
    Submodule ℚ (FiberedHodgeAddress V H) where
  carrier := {phi | IsFiberedTransferHodge p phi}
  zero_mem' := by
    intro s hs
    rfl
  add_mem' := by
    intro phi psi hphi hpsi s hs
    simp [hphi s hs, hpsi s hs]
  smul_mem' := by
    intro q phi hphi s hs
    simp [hphi s hs]

/-- The fixed-weight sheet span generated by all genuine basis sheets. -/
noncomputable def FixedWeightGeneratorSpan (p : Nat) :
    Submodule ℚ (FiberedHodgeAddress V H) :=
  Submodule.span ℚ
    (Set.range (fun i : ClassicalHodgeBasisIndex V H p =>
      fiberedSheetGenerator V H (⟨p,i⟩ : FiberedHodgeIndex V H)))

/-- Every genuine sheet generator lies in the fixed-weight support subspace. -/
theorem sheetGenerator_mem_fixedWeight
    (p : Nat)
    (i : ClassicalHodgeBasisIndex V H p) :
    fiberedSheetGenerator V H (⟨p,i⟩ : FiberedHodgeIndex V H) ∈
      FixedWeightSheetSubspace (V := V) (H := H) p := by
  exact fiberedSheetGenerator_isHodge V H p i

/-- Every genuine Hodge state embeds into the exact fixed-weight sheet
subspace. -/
theorem fiberedWeightCoordinates_mem_fixedWeight
    (p : Nat)
    (alpha : ClassicalHodgeFiber V H p) :
    fiberedWeightCoordinates V H p alpha ∈
      FixedWeightSheetSubspace (V := V) (H := H) p := by
  exact fiberedWeightCoordinates_isHodge V H p alpha

/-- The span of the genuine basis sheets is contained in the exact
weight-support subspace. -/
theorem generatorSpan_le_fixedWeight
    (p : Nat) :
    FixedWeightGeneratorSpan (V := V) (H := H) p ≤
      FixedWeightSheetSubspace (V := V) (H := H) p := by
  apply Submodule.span_le.2
  intro phi hphi
  rcases hphi with ⟨i, rfl⟩
  exact sheetGenerator_mem_fixedWeight p i

/-- Conversely every finite address supported at weight p is a finite rational
sum of genuine weight-p sheet generators. -/
theorem fixedWeight_le_generatorSpan
    (p : Nat) :
    FixedWeightSheetSubspace (V := V) (H := H) p ≤
      FixedWeightGeneratorSpan (V := V) (H := H) p := by
  intro phi hphi
  rw [fiberedAddress_sheet_decomposition V H phi]
  classical
  apply Submodule.sum_mem
  intro s hs
  apply Submodule.smul_mem
  rcases s with ⟨q,i⟩
  have hqp : q = p := by
    by_contra hne
    have hz := hphi ⟨q,i⟩ hne
    have hnz : phi ⟨q,i⟩ ≠ 0 := by
      exact Finsupp.mem_support_iff.mp hs
    exact hnz hz
  subst q
  exact Submodule.subset_span ⟨i, rfl⟩

/-- Exact identification: the weight-p GST sheet universe is precisely the
span of its genuine Hodge-sheet basis generators. -/
theorem fixedWeight_eq_generatorSpan
    (p : Nat) :
    FixedWeightSheetSubspace (V := V) (H := H) p =
      FixedWeightGeneratorSpan (V := V) (H := H) p := by
  apply le_antisymm
  · exact fixedWeight_le_generatorSpan p
  · exact generatorSpan_le_fixedWeight p

/-- Stability of a total-address subspace under every same-weight GST matrix
unit. -/
def SameWeightGSTStable
    (p : Nat)
    (W : Submodule ℚ (FiberedHodgeAddress V H)) : Prop :=
  ∀ i j : ClassicalHodgeBasisIndex V H p,
  ∀ phi : FiberedHodgeAddress V H,
    phi ∈ W →
      sheetMatrixUnit
          (⟨p,i⟩ : FiberedHodgeIndex V H)
          (⟨p,j⟩ : FiberedHodgeIndex V H) phi ∈ W

/-- One nonzero canonical spine source plus same-weight GST stability forces
every genuine target sheet generator into the subspace. -/
theorem every_sheet_mem_of_spine_and_stable
    (G : GSTClassicalHodgeGeometricCycleClassSpine.GeometricCycleClassSpine V H)
    (M : NativeMassCycleClassBridge V H)
    (p : Nat)
    (W : Submodule ℚ (FiberedHodgeAddress V H))
    (hsource : globalSpineAddress G M p ∈ W)
    (hstable : SameWeightGSTStable (V := V) (H := H) p W) :
    ∀ j : ClassicalHodgeBasisIndex V H p,
      fiberedSheetGenerator V H (⟨p,j⟩ : FiberedHodgeIndex V H) ∈ W := by
  intro j
  let i := (globalSpineOrbitSeed G M p).sourceIndex
  let c : ℚ :=
    sheetProbe (globalSpineSourceSheet G M p)
      (globalSpineAddress G M p)
  have hc : c ≠ 0 := globalSpineSourceProbe_ne_zero G M p
  have hmove := hstable i j (globalSpineAddress G M p) hsource
  have heq :
      sheetMatrixUnit
          (⟨p,i⟩ : FiberedHodgeIndex V H)
          (⟨p,j⟩ : FiberedHodgeIndex V H)
          (globalSpineAddress G M p) =
        c • fiberedSheetGenerator V H ⟨p,j⟩ := by
    simpa [i, c, globalSpineSourceSheet] using
      globalSpine_matrixUnit_hits_target G M p j
  rw [heq] at hmove
  have hscaled := W.smul_mem c⁻¹ hmove
  simpa [hc, smul_smul] using hscaled

/-- **GLOBAL GST FIXED-WEIGHT SATURATION.**  A subspace containing the one
canonical algebraic spine address and stable under the full same-weight GST
read/write algebra contains every weight-p Hodge sheet address. -/
theorem fixedWeight_le_of_spine_and_stable
    (G : GSTClassicalHodgeGeometricCycleClassSpine.GeometricCycleClassSpine V H)
    (M : NativeMassCycleClassBridge V H)
    (p : Nat)
    (W : Submodule ℚ (FiberedHodgeAddress V H))
    (hsource : globalSpineAddress G M p ∈ W)
    (hstable : SameWeightGSTStable (V := V) (H := H) p W) :
    FixedWeightSheetSubspace (V := V) (H := H) p ≤ W := by
  rw [fixedWeight_eq_generatorSpan p]
  apply Submodule.span_le.2
  intro phi hphi
  rcases hphi with ⟨j, rfl⟩
  exact every_sheet_mem_of_spine_and_stable G M p W hsource hstable j

/-- **FULL GST LEFSCHETZ/POINCARE IDENTIFICATION.**
On a true Hodge state the global total-sheet matrix unit is not a primitive
black box: it is exactly the finite localization of the already-proved GST
Lefschetz/Poincare word. -/
theorem globalMatrixUnit_eq_LPWord_on_hodge
    (p : Nat)
    (i j : ClassicalHodgeBasisIndex V H p)
    (alpha : ClassicalHodgeFiber V H p) :
    sheetMatrixUnit
        (⟨p,i⟩ : FiberedHodgeIndex V H)
        (⟨p,j⟩ : FiberedHodgeIndex V H)
        (fiberedWeightCoordinates V H p alpha) =
      fiberedWeightCoordinates V H p
        (liftedLefschetzPoincareWord
          (pairBasisIndex i j) sourceSlot targetSlot alpha) := by
  rw [liftedLefschetzPoincareWord_eq_matrixUnit]
  exact sheetMatrixUnit_intertwines_hodgeMatrixUnit p i j alpha

/-- In the universal two-slot localization the same global sheet move is
literally the normalized GST Lefschetz forward shift. -/
theorem globalMatrixUnit_eq_twoSlotLefschetz_on_hodge
    (p : Nat)
    (i j : ClassicalHodgeBasisIndex V H p)
    (alpha : ClassicalHodgeFiber V H p) :
    sheetMatrixUnit
        (⟨p,i⟩ : FiberedHodgeIndex V H)
        (⟨p,j⟩ : FiberedHodgeIndex V H)
        (fiberedWeightCoordinates V H p alpha) =
      fiberedWeightCoordinates V H p
        (liftFiniteHodgeOperator (pairBasisIndex i j)
          (GSTClassicalHodgeFullArsenalIrreducibility.pureForwardShift 2)
          alpha) := by
  rw [rankFreeMatrixUnit_eq_twoSlot_Lefschetz]
  exact sheetMatrixUnit_intertwines_hodgeMatrixUnit p i j alpha

#check FixedWeightSheetSubspace
#check FixedWeightGeneratorSpan
#check fixedWeight_eq_generatorSpan
#check SameWeightGSTStable
#check every_sheet_mem_of_spine_and_stable
#check fixedWeight_le_of_spine_and_stable
#check globalMatrixUnit_eq_LPWord_on_hodge
#check globalMatrixUnit_eq_twoSlotLefschetz_on_hodge

#print axioms fixedWeight_eq_generatorSpan
#print axioms every_sheet_mem_of_spine_and_stable
#print axioms fixedWeight_le_of_spine_and_stable
#print axioms globalMatrixUnit_eq_LPWord_on_hodge

end GSTClassicalHodgeGlobalSheetSaturation
