import GSTClassicalHodgeSeparatorAmbientCoheightExact
import GSTClassicalHodgePrincipalCutFlagNativeReturn

/-!
# GST CLASSICAL HODGE — SEPARATOR NORMAL ENERGY

This module pushes the single-separator geometry directly into the native
principal-cut incidence/transpose cosmology.

The older Gram and flag-normal nonvanishing crowns were stated under the
stronger `RelativeSuccessorAmbientExact` hypothesis, which requires every
selected relative successor to land in ambient codimension `p+1`, together
with a separate nonemptiness hypothesis.

The single-separator branch no longer needs either global requirement.  A
projectively live source has one canonical relative height-one separator; the
ambient-coheight theorem puts that one separator in exact codimension `p+1`,
and `SingleExactSuccessorSurvival` already proves that this single contribution
makes the native successor operator nonzero.

A nonzero successor presentation has strictly positive squared incidence
energy.  Therefore one canonical live separator is enough to force the
finite-incidence Gram diagonal and the native flag-normal diagonal to be
nonzero on every finite chart containing the source.

No Hodge basis, cycle-class surjectivity, defect-quotient action, Poincare
identity, or cohomological extension is used here.  This is a pure geometric
upgrade of the principal-cut normal operator.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry
open GSTProjectiveOverC
open GSTNativeCodimensionCyclePresentation
open GSTClassicalHodgePrincipalCutSuccessorOperator
open GSTClassicalHodgePrincipalCutIncidenceTransposeCosmology
open GSTClassicalHodgePrincipalCutFlagNativeReturn
open GSTClassicalHodgeSeparatorAmbientCoheightExact

namespace GSTClassicalHodgeSeparatorNormalEnergy

/-- One exact canonical separator already forces the complete successor
presentation of a projectively live source to be nonzero.  No exactness law
for the other selected successors is required. -/
theorem separator_successorPresentation_ne_zero
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (x : CodimensionPoint V.X p)
    (hlive : ProjectivelyLiveSource V.projective.n (V.projective.immersion x.1)) :
    successorPresentation V p x ≠ 0 := by
  have hnative :
      successorNativeOperator V p (codimensionPointCycle V.X p x) ≠ 0 :=
    (separator_successor_survives V p x hlive).2
  intro hzero
  apply hnative
  rw [successorNativeOperator_point, hzero]
  simp

/-- The canonical separator therefore gives strictly positive principal-cut
Gram energy.  This is stronger than mere nonvanishing and is obtained before
any cohomological externalization. -/
theorem separator_successorSelfEnergy_pos
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (x : CodimensionPoint V.X p)
    (hlive : ProjectivelyLiveSource V.projective.n (V.projective.immersion x.1)) :
    0 < successorSelfEnergy V p x := by
  exact successorSelfEnergy_pos_of_presentation_ne_zero V p x
    (separator_successorPresentation_ne_zero V p x hlive)

/-- Nonzero form of the separator-generated self-energy. -/
theorem separator_successorSelfEnergy_ne_zero
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (x : CodimensionPoint V.X p)
    (hlive : ProjectivelyLiveSource V.projective.n (V.projective.immersion x.1)) :
    successorSelfEnergy V p x ≠ 0 :=
  ne_of_gt (separator_successorSelfEnergy_pos V p x hlive)

/-- **ONE-SEPARATOR INCIDENCE-TRANSPOSE CROWN.**

For every finite source chart containing a projectively live source, the
incidence normal operator has a nonzero diagonal coefficient generated by the
canonical separator.  The remainder is still exactly off-diagonal at the
source.  This removes the previous all-successors exactness and explicit
nonemptiness hypotheses from the Gram crown. -/
theorem separator_incidenceTranspose_live_crown
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (sigma : Finset (CodimensionPoint V.X p))
    (x : CodimensionPoint V.X p)
    (hx : x ∈ sigma)
    (hlive : ProjectivelyLiveSource V.projective.n (V.projective.immersion x.1)) :
    let lambda := successorSelfEnergy V p x
    lambda ≠ 0
      ∧ localSuccessorNormal V p sigma (Finsupp.single x (1 : ℚ)) =
          lambda • Finsupp.single x (1 : ℚ) + successorCrossTalk V p sigma x
      ∧ successorCrossTalk V p sigma x x = 0 := by
  dsimp
  exact ⟨
    separator_successorSelfEnergy_ne_zero V p x hlive,
    localSuccessorNormal_decomposition V p sigma x,
    successorCrossTalk_apply_self V p sigma x hx⟩

/-- **ONE-SEPARATOR NATIVE FLAG-NORMAL CROWN.**

The same strengthening after realization as actual algebraic cycles.  A single
canonical projective separator forces a nonzero diagonal coefficient in the
native round trip `KᵗK` on the source point-cycle, plus one genuine algebraic
off-diagonal correction cycle whose source coefficient vanishes. -/
theorem separator_localFlagNormalNative_live_crown
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (sigma : Finset (CodimensionPoint V.X p))
    (x : CodimensionPoint V.X p)
    (hx : x ∈ sigma)
    (hlive : ProjectivelyLiveSource V.projective.n (V.projective.immersion x.1)) :
    let lambda := successorSelfEnergy V p x
    lambda ≠ 0
      ∧ localFlagNormalNative V p sigma (codimensionPointCycle V.X p x) =
          lambda • codimensionPointCycle V.X p x +
            crossTalkCycle V p sigma x
      ∧ (letI : CompactSpace V.X := smoothProjectiveCompactSpace V
          presentationOfNativeCycle V.X p (crossTalkCycle V p sigma x) x = 0) := by
  dsimp
  exact ⟨
    separator_successorSelfEnergy_ne_zero V p x hlive,
    localFlagNormalNative_point_decomposition V p sigma x,
    crossTalkCycle_sourceCoefficient_zero V p sigma x hx⟩

#check separator_successorPresentation_ne_zero
#check separator_successorSelfEnergy_pos
#check separator_successorSelfEnergy_ne_zero
#check separator_incidenceTranspose_live_crown
#check separator_localFlagNormalNative_live_crown

#print axioms separator_successorPresentation_ne_zero
#print axioms separator_successorSelfEnergy_pos
#print axioms separator_incidenceTranspose_live_crown
#print axioms separator_localFlagNormalNative_live_crown

end GSTClassicalHodgeSeparatorNormalEnergy
