import GSTClassicalHodgeFullArsenalIrreducibility
import GSTClassicalHodgeAtomicDefectDuality

/-!
# GST CLASSICAL HODGE — RANK-FREE ARSENAL IRREDUCIBILITY

Finite GST windows are observation charts; the genuine classical Hodge fiber
may have arbitrary basis cardinality.  This module removes the finite-window
restriction from the irreducibility statement.

The unrestricted chosen basis of the genuine rational `(p,p)` Hodge fiber
supplies rank-free matrix units directly.  Each matrix unit reads one basis
coordinate and writes it into another basis sheet.  Every individual vector
still has finite support, so all actual calculations remain finite.

The finite GST theorem in `GSTClassicalHodgeFullArsenalIrreducibility` explains
how each finite restriction of this matrix-unit algebra is generated by the
sheet-projector / Lefschetz / Poincare arsenal.  The theorem here is the
limitless colimit statement: any nonzero rational submodule of the genuine
Hodge fiber stable under all those local matrix units is the full Hodge fiber.

Applied to the intersection of the actual cycle-class range with the Hodge
fiber, this means that one nonzero algebraic seed plus full-arsenal naturality
forces every rational `(p,p)` direction to be algebraic.
-/

set_option maxHeartbeats 20000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry
open GSTProjectiveOverC
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeAtomicSpan
open GSTClassicalHodgeAtomicDefectDuality
open GSTClassicalHodgeFullArsenalIrreducibility

namespace GSTClassicalHodgeRankFreeArsenalIrreducibility

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-- Coordinate functional of one genuine Hodge basis direction. -/
noncomputable def hodgeCoordinate
    (i : ClassicalHodgeBasisIndex V H p) :
    ClassicalHodgeFiber V H p →ₗ[ℚ] ℚ :=
  (Finsupp.lapply i ℚ).comp
    (classicalHodgeBasis V H p).repr.toLinearMap

@[simp]
theorem hodgeCoordinate_basis_self
    (i : ClassicalHodgeBasisIndex V H p) :
    hodgeCoordinate i (classicalHodgeBasis V H p i) = 1 := by
  simp [hodgeCoordinate]

@[simp]
theorem hodgeCoordinate_basis_other
    (i j : ClassicalHodgeBasisIndex V H p) (hji : j ≠ i) :
    hodgeCoordinate i (classicalHodgeBasis V H p j) = 0 := by
  simp [hodgeCoordinate, hji]

/-- Rank-free matrix unit on the genuine Hodge fiber: read coordinate `i`,
write that scalar into basis direction `j`. -/
noncomputable def hodgeMatrixUnit
    (i j : ClassicalHodgeBasisIndex V H p) :
    Module.End ℚ (ClassicalHodgeFiber V H p) :=
  LinearMap.smulRight (hodgeCoordinate i)
    (classicalHodgeBasis V H p j)

@[simp]
theorem hodgeMatrixUnit_apply
    (i j : ClassicalHodgeBasisIndex V H p)
    (alpha : ClassicalHodgeFiber V H p) :
    hodgeMatrixUnit i j alpha =
      hodgeCoordinate i alpha • classicalHodgeBasis V H p j := by
  rfl

@[simp]
theorem hodgeMatrixUnit_basis_source
    (i j : ClassicalHodgeBasisIndex V H p) :
    hodgeMatrixUnit i j (classicalHodgeBasis V H p i) =
      classicalHodgeBasis V H p j := by
  simp [hodgeMatrixUnit]

@[simp]
theorem hodgeMatrixUnit_basis_other
    (i j k : ClassicalHodgeBasisIndex V H p)
    (hki : k ≠ i) :
    hodgeMatrixUnit i j (classicalHodgeBasis V H p k) = 0 := by
  simp [hodgeMatrixUnit, hki]

/-- Stability under the limitless local matrix-unit arsenal. -/
def RankFreeArsenalInvariant
    (S : Submodule ℚ (ClassicalHodgeFiber V H p)) : Prop :=
  ∀ i j : ClassicalHodgeBasisIndex V H p,
    ∀ alpha ∈ S, hodgeMatrixUnit i j alpha ∈ S

/-- Every nonzero genuine Hodge class has a nonzero basis coordinate. -/
theorem exists_nonzero_hodgeCoordinate
    {alpha : ClassicalHodgeFiber V H p}
    (halpha : alpha ≠ 0) :
    ∃ i : ClassicalHodgeBasisIndex V H p,
      hodgeCoordinate i alpha ≠ 0 := by
  by_contra h
  push_neg at h
  apply halpha
  apply (classicalHodgeBasis V H p).repr.injective
  apply Finsupp.ext
  intro i
  simpa [hodgeCoordinate] using h i

/-- **RANK-FREE LIMITLESS IRREDUCIBILITY.**
A nonzero Hodge submodule invariant under all local GST matrix units is the
whole genuine Hodge fiber, regardless of its basis cardinality. -/
theorem rankFreeArsenalInvariant_eq_top
    (S : Submodule ℚ (ClassicalHodgeFiber V H p))
    (hstable : RankFreeArsenalInvariant S)
    (hne : S ≠ ⊥) :
    S = ⊤ := by
  apply top_unique
  intro alpha _
  have hex : ∃ x : ClassicalHodgeFiber V H p, x ∈ S ∧ x ≠ 0 := by
    by_contra h
    push_neg at h
    apply hne
    ext x
    constructor
    · intro hx
      have hx0 := h x hx
      simpa [hx0]
    · intro hx
      simpa using hx
  obtain ⟨x, hxS, hx0⟩ := hex
  obtain ⟨i, hi⟩ := exists_nonzero_hodgeCoordinate hx0
  have hbasis : ∀ j : ClassicalHodgeBasisIndex V H p,
      classicalHodgeBasis V H p j ∈ S := by
    intro j
    have hmove := hstable i j x hxS
    have hscaled : hodgeCoordinate i x •
        classicalHodgeBasis V H p j ∈ S := by
      simpa [hodgeMatrixUnit_apply] using hmove
    have hinv := S.smul_mem ((hodgeCoordinate i x)⁻¹) hscaled
    simpa [hi] using hinv
  have hrepr := (classicalHodgeBasis V H p).sum_repr alpha
  rw [← hrepr]
  exact S.sum_mem fun j hj =>
    S.smul_mem (((classicalHodgeBasis V H p).repr alpha) j)
      (hbasis j)

/-- Equivalent zero-or-everything dichotomy. -/
theorem rankFreeArsenalInvariant_bot_or_top
    (S : Submodule ℚ (ClassicalHodgeFiber V H p))
    (hstable : RankFreeArsenalInvariant S) :
    S = ⊥ ∨ S = ⊤ := by
  by_cases hzero : S = ⊥
  · exact Or.inl hzero
  · exact Or.inr (rankFreeArsenalInvariant_eq_top S hstable hzero)

/-- Pull the actual point-cycle span back to the genuine Hodge fiber.  These
are exactly the Hodge classes already known to be algebraic. -/
noncomputable def AlgebraicHodgeSubspace
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V)
    (p : Nat) :
    Submodule ℚ (ClassicalHodgeFiber V H p) :=
  (pointCycleClassSpan p (H.cycleClass p)).comap
    (rationalHodgeSubspace (H.hodgeBigrading p)).subtype

@[simp]
theorem mem_AlgebraicHodgeSubspace_iff
    (alpha : ClassicalHodgeFiber V H p) :
    alpha ∈ AlgebraicHodgeSubspace V H p ↔
      alpha.1 ∈ pointCycleClassSpan p (H.cycleClass p) :=
  Iff.rfl

/-- **ONE SEED + FULL ARSENAL SATURATES THE GENUINE HODGE FIBER.** -/
theorem algebraicHodgeSubspace_eq_top_of_seed_and_arsenal
    (hstable : RankFreeArsenalInvariant
      (AlgebraicHodgeSubspace V H p))
    (hseed : AlgebraicHodgeSubspace V H p ≠ ⊥) :
    AlgebraicHodgeSubspace V H p = ⊤ :=
  rankFreeArsenalInvariant_eq_top
    (AlgebraicHodgeSubspace V H p) hstable hseed

/-- Under seed + arsenal stability the atomic defect map vanishes in weight p. -/
theorem atomicDefect_eq_zero_of_seed_and_arsenal
    (hstable : RankFreeArsenalInvariant
      (AlgebraicHodgeSubspace V H p))
    (hseed : AlgebraicHodgeSubspace V H p ≠ ⊥) :
    atomicDefectLinearMap V H p = 0 := by
  apply (atomicDefectLinearMap_eq_zero_iff V H p).2
  intro alpha halpha
  let alphaH : ClassicalHodgeFiber V H p := ⟨alpha, halpha⟩
  have htop := algebraicHodgeSubspace_eq_top_of_seed_and_arsenal
    (V := V) (H := H) (p := p) hstable hseed
  have : alphaH ∈ AlgebraicHodgeSubspace V H p := by
    rw [htop]
    trivial
  exact this

/-- Family crown: if every weight has one nonzero algebraic seed and is stable
under the limitless matrix-unit arsenal, the exact Stage-2G Hodge statement
follows. -/
theorem bigradedBettiHodge_of_rankFree_arsenal
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V)
    (hstable : ∀ p : Nat,
      RankFreeArsenalInvariant (AlgebraicHodgeSubspace V H p))
    (hseed : ∀ p : Nat,
      rationalHodgeSubspace (H.hodgeBigrading p) ≠ ⊥ →
      AlgebraicHodgeSubspace V H p ≠ ⊥) :
    BigradedBettiHodgeStatement V H := by
  apply (bigradedBettiHodgeStatement_iff_atomicDefect_zero V H).2
  intro p
  by_cases hH : rationalHodgeSubspace (H.hodgeBigrading p) = ⊥
  · apply LinearMap.ext
    intro alpha
    have ha : alpha = 0 := by
      apply Subtype.ext
      have : alpha.1 ∈ (⊥ : Submodule ℚ
        (RationalSingularCohomology H.analytification (2 * p))) := by
        simpa [hH] using alpha.2
      simpa using this
    subst alpha
    simp
  · exact atomicDefect_eq_zero_of_seed_and_arsenal
      (V := V) (H := H) (p := p) (hstable p) (hseed p hH)

#check hodgeCoordinate
#check hodgeMatrixUnit
#check RankFreeArsenalInvariant
#check rankFreeArsenalInvariant_eq_top
#check AlgebraicHodgeSubspace
#check algebraicHodgeSubspace_eq_top_of_seed_and_arsenal
#check atomicDefect_eq_zero_of_seed_and_arsenal
#check bigradedBettiHodge_of_rankFree_arsenal

#print axioms rankFreeArsenalInvariant_eq_top
#print axioms algebraicHodgeSubspace_eq_top_of_seed_and_arsenal
#print axioms atomicDefect_eq_zero_of_seed_and_arsenal
#print axioms bigradedBettiHodge_of_rankFree_arsenal

end GSTClassicalHodgeRankFreeArsenalIrreducibility
