import GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra
import GSTClassicalHodgeExactClayStatement

/-!
# GST CLASSICAL HODGE — COMPOSITIONAL CORRESPONDENCE CYCLIC ATTACK

The linear-word arena is not the full correspondence algebra.  This file uses
the noncommutative expression algebra generated by actual realized finite
closed correspondences under rational scaling, addition, and composition.

A single genuine algebraic Hodge seed is enough if its orbit under this full
geometric expression algebra reaches the Hodge fiber.  Every expression has an
exact cycle-class commuting square, so algebraicity propagates through the
whole orbit automatically.

The only remaining content of the cyclicity statement is therefore geometric:
actual correspondences must generate enough motion.  No basis-cycle witness or
arbitrary cohomology lift is built into the statement.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeCompositionalCorrespondenceCyclicAttack

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeRankFreeArsenalIrreducibility
open GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra
open GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra.RealizedCorrespondenceExpr
open GSTClassicalHodgeExactClayStatement

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-- Exact reachability by the full noncommutative algebra of genuine realized
correspondences. -/
def ExprReaches
    (seed alpha : ClassicalHodgeFiber V H p) : Prop :=
  ∃ E : RealizedCorrespondenceExpr V H p,
    E.cohomologyOperator seed.1 = alpha.1

/-- One genuine algebraic seed is cyclic under the full compositional
correspondence algebra. -/
def IsCompositionalCyclicSeed
    (seed : ClassicalHodgeFiber V H p) : Prop :=
  seed ∈ AlgebraicHodgeSubspace V H p ∧
  ∀ alpha : ClassicalHodgeFiber V H p, ExprReaches seed alpha

/-- Every target reached by a genuine compositional expression from an
algebraic seed remains algebraic. -/
theorem algebraic_of_exprReaches
    (seed alpha : ClassicalHodgeFiber V H p)
    (hseed : seed ∈ AlgebraicHodgeSubspace V H p)
    (hreach : ExprReaches seed alpha) :
    alpha ∈ AlgebraicHodgeSubspace V H p := by
  rcases hreach with ⟨E, hE⟩
  rcases hseed with ⟨Z, hZ⟩
  have hseedRange : seed.1 ∈ LinearMap.range (H.cycleClass p) :=
    ⟨Z, hZ⟩
  have hout := E.range_stable seed.1 hseedRange
  rw [hE] at hout
  exact hout

/-- A compositional cyclic algebraic seed makes the complete Hodge fiber
algebraic. -/
theorem algebraicHodgeSubspace_eq_top_of_compositionalCyclicSeed
    (seed : ClassicalHodgeFiber V H p)
    (hcyc : IsCompositionalCyclicSeed seed) :
    AlgebraicHodgeSubspace V H p = ⊤ := by
  apply top_unique
  intro alpha _
  exact algebraic_of_exprReaches seed alpha hcyc.1 (hcyc.2 alpha)

/-- Full exact Hodge statement from one compositional cyclic algebraic seed in
each weight. -/
theorem exactHodge_of_compositionalCyclicSeeds
    (seed : ∀ q : Nat, ClassicalHodgeFiber V H q)
    (hcyc : ∀ q : Nat, IsCompositionalCyclicSeed (seed q)) :
    EveryHodgeClassIsRationalAlgebraic H := by
  rw [everyHodgeClassIsRationalAlgebraic_iff_stage2G]
  intro q alpha halpha
  let a : ClassicalHodgeFiber V H q := ⟨alpha, halpha⟩
  have htop := algebraicHodgeSubspace_eq_top_of_compositionalCyclicSeed
    (seed q) (hcyc q)
  have ha : a ∈ AlgebraicHodgeSubspace V H q := by
    rw [htop]
    trivial
  rcases ha with ⟨Z, hZ⟩
  exact ⟨Z, hZ⟩

/-- Literal finite rational-combination form. -/
theorem finiteCombination_of_compositionalCyclicSeeds
    (seed : ∀ q : Nat, ClassicalHodgeFiber V H q)
    (hcyc : ∀ q : Nat, IsCompositionalCyclicSeed (seed q)) :
    EveryHodgeClassIsFiniteRationalCombination H := by
  rw [← rationalAlgebraic_iff_finiteRationalCombination]
  exact exactHodge_of_compositionalCyclicSeeds seed hcyc

/-- Historical linear correspondence words embed into the compositional orbit. -/
theorem exprReaches_of_wordReaches
    (seed alpha : ClassicalHodgeFiber V H p)
    (h : ∃ W : GSTClassicalHodgeRealizedClosedCorrespondenceAlgebra.RealizedCorrespondenceWord V H p,
      (GSTClassicalHodgeRealizedClosedCorrespondenceAlgebra.realizedWordPair W).
        cohomologyOperator seed.1 = alpha.1) :
    ExprReaches seed alpha := by
  rcases h with ⟨W,hW⟩
  refine ⟨RealizedCorrespondenceExpr.ofWord W, ?_⟩
  rw [RealizedCorrespondenceExpr.ofWord_operatorPair]
  exact hW

#check ExprReaches
#check IsCompositionalCyclicSeed
#check algebraic_of_exprReaches
#check algebraicHodgeSubspace_eq_top_of_compositionalCyclicSeed
#check exactHodge_of_compositionalCyclicSeeds
#check finiteCombination_of_compositionalCyclicSeeds
#check exprReaches_of_wordReaches

#print axioms algebraic_of_exprReaches
#print axioms algebraicHodgeSubspace_eq_top_of_compositionalCyclicSeed
#print axioms exactHodge_of_compositionalCyclicSeeds
#print axioms finiteCombination_of_compositionalCyclicSeeds

end GSTClassicalHodgeCompositionalCorrespondenceCyclicAttack
