import GSTClassicalHodgeNativeGeneratorNaturality
import GSTClassicalHodgeCanonicalCosmicRealizationEquivalence
import GSTClassicalHodgeSynchronizedDefectOrbit

/-!
# GST CLASSICAL HODGE — POINTWISE NATIVE COSMIC CLOSURE

The existing projective externalization layers package a global native
operator before proving that its cohomological action agrees with a limitless
GST matrix unit.  That is stronger than the algebraicity argument consumes.

On a smooth projective carrier the atomic algebraic Hodge space is generated by
genuine codimension-p point-cycle classes.  Therefore, for one canonical
cosmic matrix unit E_{i,j}, it is enough to prove the following generatorwise
statement:

  for every genuine codimension-p point x,
  there exists some actual native codimension-p cycle Z_x such that

    cl(Z_x) = E_{i,j}(cl([x])).

No global native endomorphism, kernel-stability theorem, projective self-map,
or common point-transition kernel is required.  The compact native-generator
naturality theorem turns these point lifts directly into invariance of the
complete atomic span.

The reduction sharpens again in the presence of one nonzero algebraic Hodge
seed.  The seed canonically selects one live source coordinate i.  Matrix-unit
algebra then needs only source-to-target point lifts E_{i,j}, one family indexed
by the target sheet j.  Applying E_{i,j} to the seed produces a nonzero scalar
multiple of basis j, hence every Hodge basis direction is algebraic.

This is the smallest externalization interface currently needed by the
limitless GST saturation engine.
-/

set_option maxHeartbeats 70000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgePointwiseNativeCosmicClosure

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTNativeCodimensionCyclePresentation
open GSTClassicalHodgeAtomicSpan
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeNativeGeneratorNaturality
open GSTClassicalHodgeCanonicalCosmicRealizationEquivalence
open GSTClassicalHodgeGeneratorwiseAtomicStability
open GSTClassicalHodgeRankFreeArsenalIrreducibility
open GSTClassicalHodgeSynchronizedDefectOrbit

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-- Smallest generatorwise geometric externalization law for one canonical
limitless matrix unit. -/
def CosmicNativePointLifts
    (i j : ClassicalHodgeBasisIndex V H p) : Prop :=
  HasNativePointLifts
    (p := p) (cl := H.cycleClass p)
    (canonicalCosmicAmbient i j)

/-- Elementwise spelling: every transformed genuine point class has an actual
native algebraic-cycle representative. -/
theorem cosmicNativePointLifts_iff
    (i j : ClassicalHodgeBasisIndex V H p) :
    CosmicNativePointLifts (V := V) (H := H) i j ↔
      ∀ x : CodimensionPoint V.X p,
        ∃ Z : codimensionCycles V.X p,
          H.cycleClass p Z =
            canonicalCosmicAmbient i j
              (H.cycleClass p (codimensionPointCycle V.X p x)) :=
  Iff.rfl

/-- Pointwise native lifts force the corresponding limitless cosmic matrix
unit to preserve the complete actual atomic cycle-class span. -/
theorem cosmic_atomicSpanStable
    (i j : ClassicalHodgeBasisIndex V H p)
    (hij : CosmicNativePointLifts (V := V) (H := H) i j) :
    AtomicSpanStable
      (p := p) (cl := H.cycleClass p)
      (canonicalCosmicAmbient i j) := by
  exact (smoothProjective_atomicStable_iff_nativePointLifts
    (V := V) (H := H) (p := p)
    (canonicalCosmicAmbient i j)).2 hij

/-- Consequently the corresponding genuine Hodge matrix unit preserves the
algebraic Hodge subspace. -/
theorem hodgeMatrixUnit_mem_algebraic_of_pointLifts
    (i j : ClassicalHodgeBasisIndex V H p)
    (hij : CosmicNativePointLifts (V := V) (H := H) i j)
    (alpha : ClassicalHodgeFiber V H p)
    (halpha : alpha ∈ AlgebraicHodgeSubspace V H p) :
    hodgeMatrixUnit i j alpha ∈ AlgebraicHodgeSubspace V H p := by
  have hstable := cosmic_atomicSpanStable i j hij
  have himage := hstable alpha.1 halpha
  rw [canonicalCosmicAmbient_on_hodge i j alpha] at himage
  rw [mem_AlgebraicHodgeSubspace_iff]
  rw [GSTClassicalHodgeLimitlessTwoSlotFailureDichotomy.hodgeMatrixUnit_eq_lift_limitless_cosmic]
  exact himage

/-- A nonzero algebraic seed determines one live source coordinate.  Native
point lifts are needed only from that source to each target basis sheet. -/
theorem every_basis_algebraic_of_liveSource_pointLifts
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (hLift : ∀ j : ClassicalHodgeBasisIndex V H p,
      CosmicNativePointLifts (V := V) (H := H) S.sourceIndex j) :
    ∀ j : ClassicalHodgeBasisIndex V H p,
      (classicalHodgeBasis V H p j).1 ∈
        pointCycleClassSpan p (H.cycleClass p) := by
  intro j
  have hseedAlg : S.hodge ∈ AlgebraicHodgeSubspace V H p := by
    rw [mem_AlgebraicHodgeSubspace_iff]
    rw [← smoothProjective_cycleClass_range_eq_atomic_span V H p]
    exact ⟨S.cycle, S.class_eq⟩
  have hmove :=
    hodgeMatrixUnit_mem_algebraic_of_pointLifts
      S.sourceIndex j (hLift j) S.hodge hseedAlg
  let c : ℚ :=
    (classicalHodgeBasis V H p).repr S.hodge S.sourceIndex
  have hc : c ≠ 0 := S.sourceCoefficient_ne_zero
  have hmatrix :
      hodgeMatrixUnit S.sourceIndex j S.hodge =
        c • classicalHodgeBasis V H p j := by
    apply Subtype.ext
    simp [hodgeMatrixUnit_apply, hodgeCoordinate, c]
  rw [hmatrix] at hmove
  have hscaled :=
    (AlgebraicHodgeSubspace V H p).smul_mem (c⁻¹) hmove
  simpa [hc, smul_smul] using hscaled

/-- Source-to-target point lifts from one arbitrary nonzero algebraic seed
already saturate the complete genuine Hodge fiber. -/
theorem hodge_weight_of_liveSource_pointLifts
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (hLift : ∀ j : ClassicalHodgeBasisIndex V H p,
      CosmicNativePointLifts (V := V) (H := H) S.sourceIndex j) :
    rationalHodgeSubspace (H.hodgeBigrading p) ≤
      LinearMap.range (H.cycleClass p) := by
  intro alpha halpha
  let alphaH : ClassicalHodgeFiber V H p := ⟨alpha, halpha⟩
  have hbasis : ∀ j : ClassicalHodgeBasisIndex V H p,
      (classicalHodgeBasis V H p j).1 ∈
        pointCycleClassSpan p (H.cycleClass p) :=
    every_basis_algebraic_of_liveSource_pointLifts S hLift
  have halg : alpha ∈ pointCycleClassSpan p (H.cycleClass p) := by
    have h1 : alphaH = (classicalHodgeBasis V H p).repr.symm
        ((classicalHodgeBasis V H p).repr alphaH) := by
      simp
    have h2 : (classicalHodgeBasis V H p).repr.symm
        ((classicalHodgeBasis V H p).repr alphaH) =
      ∑ j ∈ ((classicalHodgeBasis V H p).repr alphaH).support,
        ((classicalHodgeBasis V H p).repr alphaH j) •
          classicalHodgeBasis V H p j := by
      rw [(classicalHodgeBasis V H p).repr_symm_apply]
      simp only [Finsupp.linearCombination_apply, Finsupp.sum]
    show (alphaH : ClassicalHodgeFiber V H p).val ∈
      pointCycleClassSpan p (H.cycleClass p)
    rw [h1, h2]
    simp only [Submodule.coe_sum, Submodule.coe_smul_of_tower]
    apply Submodule.sum_mem
    intro j hj
    exact (pointCycleClassSpan p (H.cycleClass p)).smul_mem
      ((classicalHodgeBasis V H p).repr alphaH j) (hbasis j)
  rw [← smoothProjective_cycleClass_range_eq_atomic_span V H p] at halg
  exact halg

/-- Exact native representative for each target basis sheet, obtained only
from live-source generatorwise cosmic lifts. -/
theorem basis_native_cycle_of_liveSource_pointLifts
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (hLift : ∀ j : ClassicalHodgeBasisIndex V H p,
      CosmicNativePointLifts (V := V) (H := H) S.sourceIndex j)
    (j : ClassicalHodgeBasisIndex V H p) :
    ∃ Z : codimensionCycles V.X p,
      H.cycleClass p Z = (classicalHodgeBasis V H p j).1 := by
  have hmem := every_basis_algebraic_of_liveSource_pointLifts S hLift j
  exact pointCycleClassSpan_le_cycleClass_range p (H.cycleClass p) hmem

/-- Family crown: one nonzero algebraic seed per live Hodge weight and only
live-source-to-target pointwise native cosmic lifts close the exact Stage-2G
statement. -/
theorem bigradedBettiHodge_of_liveSource_pointLifts
    (seed : ∀ q : Nat,
      rationalHodgeSubspace (H.hodgeBigrading q) ≠ ⊥ →
        NativeHodgeOrbitSeed (V := V) (H := H) (p := q))
    (hLift : ∀ q : Nat,
      ∀ hq : rationalHodgeSubspace (H.hodgeBigrading q) ≠ ⊥,
      ∀ j : ClassicalHodgeBasisIndex V H q,
        CosmicNativePointLifts (V := V) (H := H)
          (seed q hq).sourceIndex j) :
    BigradedBettiHodgeStatement V H := by
  intro q alpha halpha
  by_cases hq : rationalHodgeSubspace (H.hodgeBigrading q) = ⊥
  · have hz : alpha = 0 := by
      have : alpha ∈ (⊥ : Submodule ℚ
          (RationalSingularCohomology H.analytification (2 * q))) := by
        simpa [hq] using halpha
      simpa using this
    subst alpha
    exact ⟨0, by simp⟩
  · exact (hodge_weight_of_liveSource_pointLifts
      (seed q hq) (hLift q hq)) halpha

#check CosmicNativePointLifts
#check cosmicNativePointLifts_iff
#check cosmic_atomicSpanStable
#check hodgeMatrixUnit_mem_algebraic_of_pointLifts
#check every_basis_algebraic_of_liveSource_pointLifts
#check hodge_weight_of_liveSource_pointLifts
#check basis_native_cycle_of_liveSource_pointLifts
#check bigradedBettiHodge_of_liveSource_pointLifts

#print axioms cosmic_atomicSpanStable
#print axioms hodgeMatrixUnit_mem_algebraic_of_pointLifts
#print axioms every_basis_algebraic_of_liveSource_pointLifts
#print axioms hodge_weight_of_liveSource_pointLifts
#print axioms bigradedBettiHodge_of_liveSource_pointLifts

end GSTClassicalHodgePointwiseNativeCosmicClosure
