import GSTClassicalHodgeDirectOrbitWordSaturation
import GSTClassicalHodgeProjectiveCorrespondenceCosmicRealization
import GSTClassicalHodgeProjectiveCorrespondenceAlgebra
import GSTClassicalHodgeProjectiveWordOrbit

/-!
# GST CLASSICAL HODGE — PROJECTIVE SPAN -> WORD -> DIRECT ORBIT SATURATION

This layer removes another artificial interface from the geometry-first Hodge
route.

The repository already contains two native geometric languages at one weight:

* the rational projective-correspondence span generated by actual scheme
  endomorphisms of the smooth projective carrier;
* the free finite projective-word algebra generated by the same actual scheme
  endomorphisms, with rational scaling and addition available as constructors.

These are not independent geometric assumptions.  Every element of the
projective-correspondence span is, by the very meaning of span, a finite
rational linear combination of genuine geometric generators.  Hence it can be
compiled into one explicit finite `ProjectiveOperatorWord` with exactly the
same native action.

This compilation lets us formulate a strictly more native Hodge input.  For a
synchronized live source `S` and target Hodge basis sheet `j`, we request only:

* one operator already known to lie in the genuine projective-correspondence
  span;
* one native cycle-class equation saying that this operator sends the live
  source cycle to the correct scalar multiple of the target basis sheet.

No ambient cohomological operator is supplied.  No matrix-unit action on the
whole Hodge fiber is supplied.  No projective word syntax is supplied.  The
word is compiled from span membership, and its cohomological action is then
manufactured automatically from kernel stability and the geometric
cycle-class spine.

Once this source equation is available for every target direction, the direct
orbit saturation layer absorbs the compiled words into the graded geometric
program algebra, so every rational Hodge class lies in the genuine algebraic
orbit.
-/

set_option maxHeartbeats 90000000
set_option maxRecDepth 1000000

noncomputable section

open CategoryTheory
open AlgebraicGeometry

namespace GSTClassicalHodgeProjectiveSpanWordSaturation

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeSynchronizedDefectOrbit
open GSTClassicalHodgeLimitlessSpinePropagation
open GSTClassicalHodgeProjectiveCorrespondenceAlgebra
open GSTClassicalHodgePrimitivePushforwardNaturality
open GSTClassicalHodgeProjectiveCorrespondenceCosmicRealization
open GSTClassicalHodgeProjectiveWordOrbit
open GSTClassicalHodgeDirectOrbitWordSaturation

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-! ## Every projective-span operator has a finite geometric word -/

/-- **SPAN-TO-WORD COMPILATION EXISTENCE.**
Every native operator in the rational span of genuine projective
self-transports is represented exactly by one finite projective operator word.

The proof is the universal-property induction of `Submodule.span`: generators
compile to `.geometric`, zero to a zero-scaled identity, sums to `.add`, and
rational scalar multiples to `.smul`. -/
theorem exists_projectiveOperatorWord_of_mem_span
    (A : NativeCycleEnd V p)
    (hA : A ∈ projectiveCorrespondenceSpan V p) :
    ∃ W : ProjectiveOperatorWord V p, W.eval = A := by
  classical
  refine Submodule.span_induction hA ?_ ?_ ?_ ?_
  · intro T hT
    rcases hT with ⟨f, rfl⟩
    exact ⟨.geometric f, rfl⟩
  · refine ⟨.smul 0 .id, ?_⟩
    simp [ProjectiveOperatorWord.eval]
  · intro A B hAw hBw
    rcases hAw with ⟨WA, hWA⟩
    rcases hBw with ⟨WB, hWB⟩
    refine ⟨.add WA WB, ?_⟩
    simp [ProjectiveOperatorWord.eval, hWA, hWB]
  · intro a A hAw
    rcases hAw with ⟨WA, hWA⟩
    refine ⟨.smul a WA, ?_⟩
    simp [ProjectiveOperatorWord.eval, hWA]

/-- Canonically choose one finite projective word for a genuine projective
correspondence-span operator. -/
noncomputable def compileProjectiveNativeKernelWord
    (K : ProjectiveNativeKernel V p) :
    ProjectiveOperatorWord V p :=
  Classical.choose (exists_projectiveOperatorWord_of_mem_span K.1 K.2)

/-- The chosen compiled word has exactly the native action of the source
projective-correspondence operator. -/
theorem compileProjectiveNativeKernelWord_eval
    (K : ProjectiveNativeKernel V p) :
    (compileProjectiveNativeKernelWord K).eval = K.1 :=
  Classical.choose_spec (exists_projectiveOperatorWord_of_mem_span K.1 K.2)

/-! ## Native one-source target certificate -/

/-- Purely native projective-span reachability of one target Hodge basis sheet.

The only comparison law is the cycle-class equation on the single synchronized
source cycle.  In particular, no ambient cohomological action and no action on
arbitrary Hodge vectors is part of the data. -/
structure ProjectiveSpanLiveSourceTarget
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (j : ClassicalHodgeBasisIndex V H p) where
  kernel : ProjectiveNativeKernel V p
  native_source_class :
    H.cycleClass p (kernel.1 S.cycle) =
      (classicalHodgeBasis V H p).repr S.hodge S.sourceIndex •
        (classicalHodgeBasis V H p j).1

namespace ProjectiveSpanLiveSourceTarget

/-- Compile the native projective-span target certificate to the weaker
projective-word live-source interface.

The cohomological source action is not assumed: it is recovered from the
word's automatic cycle-class naturality and the one native source equation. -/
noncomputable def toWordLiveSourceTarget
    (G : GeometricCycleClassSpine V H)
    {S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p)}
    {j : ClassicalHodgeBasisIndex V H p}
    (R : ProjectiveSpanLiveSourceTarget S j) :
    ProjectiveWordLiveSourceTarget G S j where
  word := compileProjectiveNativeKernelWord R.kernel
  source_action := by
    have hnat :=
      (compileProjectiveNativeKernelWord R.kernel).cycleClass_eval G S.cycle
    rw [compileProjectiveNativeKernelWord_eval R.kernel] at hnat
    rw [S.class_eq] at hnat
    rw [R.native_source_class] at hnat
    exact hnat.symm

/-- Therefore one native projective-span target certificate reaches its target
basis sheet through the direct graded geometry orbit. -/
theorem basis_mem_direct_geometric_orbit
    (G : GeometricCycleClassSpine V H)
    (D : SpineTowerConservedCharge G)
    (q : Nat)
    (j : ClassicalHodgeBasisIndex V H q)
    (R : ProjectiveSpanLiveSourceTarget (conservedSpineOrbitSeed G D q) j) :
    (classicalHodgeBasis V H q j).1 ∈
      GSTClassicalHodgeGradedGeometricOrbitAlgebra.geometricProgramOrbitModule G q := by
  exact basis_mem_geometricProgramOrbitModule G D q j
    (R.toWordLiveSourceTarget G)

end ProjectiveSpanLiveSourceTarget

/-! ## Direct projective-span Hodge crowns -/

/-- **PROJECTIVE-SPAN DIRECT-ORBIT CROWN.**
A native correspondence-span operator from the canonical live source to each
basis direction is sufficient for the full Stage-2G Hodge statement.

Compared with the projective-word route, the words themselves are no longer
external data.  Compared with projective cosmic realization, no operator action
on the whole Hodge fiber is requested. -/
theorem bigradedBettiHodge_of_projectiveSpan_live_source
    (G : GeometricCycleClassSpine V H)
    (D : SpineTowerConservedCharge G)
    (R : ∀ q : Nat,
      ∀ j : ClassicalHodgeBasisIndex V H q,
        ProjectiveSpanLiveSourceTarget (conservedSpineOrbitSeed G D q) j) :
    BigradedBettiHodgeStatement V H := by
  exact bigradedBettiHodge_of_direct_orbit_projective_words G D
    (fun q j => (R q j).toWordLiveSourceTarget G)

/-- Elementwise native-cycle witness form of the projective-span crown. -/
theorem every_hodge_class_has_native_cycle_of_projectiveSpan_live_source
    (G : GeometricCycleClassSpine V H)
    (D : SpineTowerConservedCharge G)
    (R : ∀ q : Nat,
      ∀ j : ClassicalHodgeBasisIndex V H q,
        ProjectiveSpanLiveSourceTarget (conservedSpineOrbitSeed G D q) j)
    (q : Nat)
    (alpha : RationalSingularCohomology H.analytification (2 * q))
    (halpha : alpha ∈ rationalHodgeSubspace (H.hodgeBigrading q)) :
    ∃ Z : codimensionCycles V.X q,
      H.cycleClass q Z = alpha := by
  exact bigradedBettiHodge_of_projectiveSpan_live_source G D R q alpha halpha

/-- Native-mass form: the conserved live spine source is manufactured
internally, while the target transports remain purely native projective-span
certificates. -/
theorem bigradedBettiHodge_of_native_mass_projectiveSpan
    (G : GeometricCycleClassSpine V H)
    (M : NativeMassCycleClassBridge V H)
    (R : ∀ q : Nat,
      ∀ j : ClassicalHodgeBasisIndex V H q,
        ProjectiveSpanLiveSourceTarget
          (conservedSpineOrbitSeed G (M.toConservedCharge G) q) j) :
    BigradedBettiHodgeStatement V H := by
  exact bigradedBettiHodge_of_projectiveSpan_live_source
    G (M.toConservedCharge G) R

/-! ## Old cosmic realization is strictly stronger than the new native input -/

/-- Every previous all-Hodge-vector projective cosmic realization supplies the
new one-source native projective-span certificate.

This theorem records the strict interface reduction: whole-fiber cosmic action
implies the single native source equation used above. -/
noncomputable def ProjectiveCosmicRealization.toSpanLiveSourceTarget
    (G : GeometricCycleClassSpine V H)
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (j : ClassicalHodgeBasisIndex V H p)
    (R : ProjectiveCosmicRealization G S.sourceIndex j) :
    ProjectiveSpanLiveSourceTarget S j where
  kernel := R.kernel
  native_source_class := by
    have hpair :=
      (projectiveCorrespondencePair G R.kernel).cycleClass_cycleOperator S.cycle
    rw [S.class_eq] at hpair
    rw [R.acts_as_cosmic S.hodge] at hpair
    rw [GSTClassicalHodgeCanonicalCosmicRealizationEquivalence.canonicalCosmicAmbient]
      at hpair
    rw [GSTClassicalHodgeRankFreePrimitiveGeneration.extendHodgeEndomorphism_on_hodge]
      at hpair
    simpa [GSTClassicalHodgeRankFreeArsenalIrreducibility.hodgeMatrixUnit_apply,
      GSTClassicalHodgeRankFreeArsenalIrreducibility.hodgeCoordinate] using hpair

#check exists_projectiveOperatorWord_of_mem_span
#check compileProjectiveNativeKernelWord
#check compileProjectiveNativeKernelWord_eval
#check ProjectiveSpanLiveSourceTarget
#check ProjectiveSpanLiveSourceTarget.toWordLiveSourceTarget
#check ProjectiveSpanLiveSourceTarget.basis_mem_direct_geometric_orbit
#check bigradedBettiHodge_of_projectiveSpan_live_source
#check every_hodge_class_has_native_cycle_of_projectiveSpan_live_source
#check bigradedBettiHodge_of_native_mass_projectiveSpan
#check ProjectiveCosmicRealization.toSpanLiveSourceTarget

#print axioms exists_projectiveOperatorWord_of_mem_span
#print axioms compileProjectiveNativeKernelWord_eval
#print axioms ProjectiveSpanLiveSourceTarget.toWordLiveSourceTarget
#print axioms bigradedBettiHodge_of_projectiveSpan_live_source
#print axioms bigradedBettiHodge_of_native_mass_projectiveSpan
#print axioms ProjectiveCosmicRealization.toSpanLiveSourceTarget

end GSTClassicalHodgeProjectiveSpanWordSaturation
