import GSTClassicalHodgeFullArsenalIrreducibility
import GSTClassicalHodgeRankFreeArsenalIrreducibility
import GSTClassicalHodgeLocalCyclicCriterion
import GSTClassicalHodgeLefschetzTomography
import GSTClassicalHodgeLiveSheetIntertwining

/-!
# GST CLASSICAL HODGE — FINITE-SUPPORT ARSENAL CONJUGATION

Every genuine rational Hodge class has finite support in the chosen classical
Hodge basis.  The limitless classical fiber therefore has a canonical local
finite window for every individual state.  This module identifies that local
window with the rational pure-Hodge window on which the existing GST
projector/Lefschetz/Poincare arsenal generates all matrix units.

The point is structural: the rank-free matrix units used in the global
irreducibility theorem are not independent abstract operators.  On every live
finite support they are exactly the conjugates of the finite pure-window
matrix units already generated by the GST arsenal.
-/

set_option maxHeartbeats 20000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry
open GSTProjectiveOverC
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeLocalCyclicCriterion
open GSTClassicalHodgeFiniteSupportChart
open GSTClassicalHodgeLefschetzTomography
open GSTClassicalHodgeLiveSheetIntertwining
open GSTClassicalHodgeFullArsenalIrreducibility
open GSTClassicalHodgeRankFreeArsenalIrreducibility

namespace GSTClassicalHodgeFiniteSupportArsenalConjugation

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-- Number of live classical Hodge-basis directions of one genuine class. -/
def liveRank (alpha : ClassicalHodgeFiber V H p) : Nat :=
  Fintype.card (HodgeSupportIndex alpha)

/-- Canonical enumeration of the live classical Hodge basis directions. -/
noncomputable def liveEquivFin
    (alpha : ClassicalHodgeFiber V H p) :
    HodgeSupportIndex alpha ≃ Fin (liveRank alpha) :=
  Fintype.equivFin (HodgeSupportIndex alpha)

/-- The actual global Hodge-basis index occupying one finite live slot. -/
noncomputable def liveBasisIndex
    (alpha : ClassicalHodgeFiber V H p)
    (r : Fin (liveRank alpha)) :
    ClassicalHodgeBasisIndex V H p :=
  ((liveEquivFin alpha).symm r).1

/-- Finite coordinate vector obtained by restricting the genuine basis
coordinates to the live support. -/
noncomputable def liveCoordinateVector
    (alpha : ClassicalHodgeFiber V H p) :
    RationalPureWindow (liveRank alpha) :=
  fun r => (classicalHodgeBasis V H p).repr alpha (liveBasisIndex alpha r)

/-- Every coordinate of the live vector is nonzero by construction. -/
theorem liveCoordinateVector_ne_zero_at
    (alpha : ClassicalHodgeFiber V H p)
    (r : Fin (liveRank alpha)) :
    liveCoordinateVector alpha r ≠ 0 := by
  let i : HodgeSupportIndex alpha := (liveEquivFin alpha).symm r
  simpa [liveCoordinateVector, liveBasisIndex, i] using
    support_coefficient_ne_zero alpha i

/-- The classical Hodge basis vector occupying one live finite slot. -/
noncomputable def liveBasisVector
    (alpha : ClassicalHodgeFiber V H p)
    (r : Fin (liveRank alpha)) : ClassicalHodgeFiber V H p :=
  classicalHodgeBasis V H p (liveBasisIndex alpha r)

/-- One finite GST matrix unit, transported back to the genuine Hodge fiber
through the live-basis enumeration. -/
noncomputable def conjugatedMatrixUnit
    (alpha : ClassicalHodgeFiber V H p)
    (r s : Fin (liveRank alpha)) :
    Module.End ℚ (ClassicalHodgeFiber V H p) :=
  hodgeMatrixUnit (liveBasisIndex alpha r) (liveBasisIndex alpha s)

@[simp]
theorem conjugatedMatrixUnit_live_source
    (alpha : ClassicalHodgeFiber V H p)
    (r s : Fin (liveRank alpha)) :
    conjugatedMatrixUnit alpha r s (liveBasisVector alpha r) =
      liveBasisVector alpha s := by
  simp [conjugatedMatrixUnit, liveBasisVector]

@[simp]
theorem conjugatedMatrixUnit_live_other
    (alpha : ClassicalHodgeFiber V H p)
    (r s t : Fin (liveRank alpha))
    (htr : t ≠ r) :
    conjugatedMatrixUnit alpha r s (liveBasisVector alpha t) = 0 := by
  apply hodgeMatrixUnit_basis_other
  intro hidx
  apply htr
  apply (liveEquivFin alpha).symm.injective
  apply Subtype.ext
  simpa [liveBasisIndex] using hidx

/-- Exact finite-window conjugation receipt: both the GST pure matrix unit and
the transported classical matrix unit send their source basis sheet to the
target sheet. -/
theorem finite_arsenal_source_conjugation
    (alpha : ClassicalHodgeFiber V H p)
    (r s : Fin (liveRank alpha)) :
    conjugatedMatrixUnit alpha r s (liveBasisVector alpha r) =
      liveBasisVector alpha s
    ∧ pureMatrixUnit r s (rationalPureBasis r) = rationalPureBasis s := by
  exact ⟨conjugatedMatrixUnit_live_source alpha r s,
    pureMatrixUnit_basis_source r s⟩

/-- Exact off-source conjugation receipt: both finite and classical matrix
units kill every other enumerated live basis sheet. -/
theorem finite_arsenal_off_source_conjugation
    (alpha : ClassicalHodgeFiber V H p)
    (r s t : Fin (liveRank alpha))
    (htr : t ≠ r) :
    conjugatedMatrixUnit alpha r s (liveBasisVector alpha t) = 0
    ∧ pureMatrixUnit r s (rationalPureBasis t) = 0 := by
  exact ⟨conjugatedMatrixUnit_live_other alpha r s t htr,
    pureMatrixUnit_basis_other r s t htr⟩

/-- The local finite GST arsenal therefore realizes the complete matrix-unit
pattern of the actual live classical support.  This is the finite observation
form of the rank-free colimit action. -/
theorem live_support_full_arsenal_receipt
    (alpha : ClassicalHodgeFiber V H p) :
    ∀ r s : Fin (liveRank alpha),
      conjugatedMatrixUnit alpha r s (liveBasisVector alpha r) =
        liveBasisVector alpha s
      ∧ ∀ t : Fin (liveRank alpha), t ≠ r →
        conjugatedMatrixUnit alpha r s (liveBasisVector alpha t) = 0 := by
  intro r s
  refine ⟨conjugatedMatrixUnit_live_source alpha r s, ?_⟩
  intro t htr
  exact conjugatedMatrixUnit_live_other alpha r s t htr

/-- The live-support finite coordinate vector is exactly the vector read by
the existing finite GST tomography layer.  Thus the same finite support is
simultaneously visible to the full matrix-unit arsenal and to the exact
Lefschetz kernel. -/
theorem live_support_tomography_nonzero
    (alpha : ClassicalHodgeFiber V H p)
    (halpha : alpha ≠ 0) :
    ∃ q : Fin
        (fiberedSupportSize (fiberedWeightCoordinates V H p alpha)),
      lefschetzTomography
        (supportCoordinateVector (fiberedWeightCoordinates V H p alpha)) q ≠ 0 :=
  nonzero_hodgeClass_has_nonzero_lefschetzMoment V H p alpha halpha

/-- Crown: every nonzero genuine Hodge class has a finite GST observation in
which (i) Lefschetz tomography detects it and (ii) the full GST arsenal acts
with the exact matrix-unit pattern of its genuine classical live basis. -/
theorem finite_support_arsenal_conjugation_crown
    (alpha : ClassicalHodgeFiber V H p)
    (halpha : alpha ≠ 0) :
    (∃ q : Fin
        (fiberedSupportSize (fiberedWeightCoordinates V H p alpha)),
      lefschetzTomography
        (supportCoordinateVector (fiberedWeightCoordinates V H p alpha)) q ≠ 0)
    ∧ (∀ r s : Fin (liveRank alpha),
      conjugatedMatrixUnit alpha r s (liveBasisVector alpha r) =
        liveBasisVector alpha s
      ∧ ∀ t : Fin (liveRank alpha), t ≠ r →
        conjugatedMatrixUnit alpha r s (liveBasisVector alpha t) = 0) := by
  exact ⟨live_support_tomography_nonzero alpha halpha,
    live_support_full_arsenal_receipt alpha⟩

#check liveRank
#check liveEquivFin
#check liveBasisIndex
#check liveCoordinateVector
#check conjugatedMatrixUnit
#check finite_arsenal_source_conjugation
#check finite_arsenal_off_source_conjugation
#check live_support_full_arsenal_receipt
#check finite_support_arsenal_conjugation_crown

#print axioms finite_arsenal_source_conjugation
#print axioms finite_arsenal_off_source_conjugation
#print axioms live_support_full_arsenal_receipt
#print axioms finite_support_arsenal_conjugation_crown

end GSTClassicalHodgeFiniteSupportArsenalConjugation
