import GSTClassicalHodgeProjectivePointTransport
import GSTClassicalHodgePointKernelOperatorLift
import GSTClassicalHodgeAtomicOperatorAlgebra

/-!
# GST CLASSICAL HODGE — PROJECTIVE CORRESPONDENCE ALGEBRA

The limitless operator calculus needs an external geometric counterpart.  This
module builds it entirely inside the native codimension-p cycle space of an
actual smooth projective complex scheme.

Each actual scheme endomorphism of `V.X` acts on codimension-p cycles through
the residue-degree point transport constructed in
`GSTClassicalHodgeProjectivePointTransport`.  We then take the rational linear
span of those genuine geometric transports inside the full endomorphism
space of native codimension-p cycles.

This gives a concrete projective-correspondence operator sector which is:

* generated by actual scheme morphisms;
* closed under rational linear combination by construction;
* represented exactly on finite point presentations;
* therefore compatible with the free point-transition language used by the
  classical Hodge spectral machinery.

No cohomology action is assumed here.  This file constructs the native
geometric operator algebra first; the external-realization layer will prove
which cohomological operators are induced by it.
-/

set_option maxHeartbeats 10000000
set_option maxRecDepth 1000000

noncomputable section

open CategoryTheory
open AlgebraicGeometry
open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTNativeCodimensionCyclePresentation
open GSTCompactNativeCyclePresentation
open GSTClassicalHodgePointNormalForm
open GSTClassicalHodgePointKernelOperatorLift
open GSTClassicalHodgeProjectivePointTransport

namespace GSTClassicalHodgeProjectiveCorrespondenceAlgebra

variable (V : SmoothProjectiveComplexScheme) (p : Nat)

abbrev NativeCycleSpace := codimensionCycles V.X p
abbrev NativeCycleEnd := Module.End ℚ (NativeCycleSpace V p)

/-- Native operator induced by one actual scheme endomorphism. -/
noncomputable def geometricGenerator
    (f : V.X ⟶ V.X) : NativeCycleEnd V p :=
  smoothProjectiveNativePushforward V f p

/-- Set of all native codimension-p operators obtained from actual scheme
endomorphisms. -/
def geometricGeneratorSet : Set (NativeCycleEnd V p) :=
  Set.range (geometricGenerator V p)

/-- Rational projective-correspondence sector generated by actual geometric
endomorphisms. -/
noncomputable def projectiveCorrespondenceSpan :
    Submodule ℚ (NativeCycleEnd V p) :=
  Submodule.span ℚ (geometricGeneratorSet V p)

/-- Every genuine scheme endomorphism contributes an operator to the
projective-correspondence sector. -/
theorem geometricGenerator_mem
    (f : V.X ⟶ V.X) :
    geometricGenerator V p f ∈ projectiveCorrespondenceSpan V p := by
  apply Submodule.subset_span
  exact ⟨f, rfl⟩

/-- The projective-correspondence sector is closed under rational linear
combination. -/
theorem add_mem
    {A B : NativeCycleEnd V p}
    (hA : A ∈ projectiveCorrespondenceSpan V p)
    (hB : B ∈ projectiveCorrespondenceSpan V p) :
    A + B ∈ projectiveCorrespondenceSpan V p :=
  (projectiveCorrespondenceSpan V p).add_mem hA hB

/-- Rational rescaling stays geometric at the correspondence-span level. -/
theorem smul_mem
    (q : ℚ) {A : NativeCycleEnd V p}
    (hA : A ∈ projectiveCorrespondenceSpan V p) :
    q • A ∈ projectiveCorrespondenceSpan V p :=
  (projectiveCorrespondenceSpan V p).smul_mem q hA

/-- Finite rational linear combinations of actual scheme transports stay in
one concrete native operator sector. -/
theorem finset_sum_mem
    {ι : Type*} [DecidableEq ι]
    (s : Finset ι)
    (A : ι → NativeCycleEnd V p)
    (hA : ∀ i ∈ s, A i ∈ projectiveCorrespondenceSpan V p) :
    ∑ i ∈ s, A i ∈ projectiveCorrespondenceSpan V p := by
  exact Submodule.sum_mem (projectiveCorrespondenceSpan V p)
    (fun i hi => Submodule.sum_mem (projectiveCorrespondenceSpan V p)
      (fun _ _ => hA i hi))

/-- Point-presentation kernel of one actual scheme endomorphism. -/
noncomputable def geometricPresentationKernel
    (f : V.X ⟶ V.X) :
    CodimensionPoint V.X p → FiniteCodimensionPresentation V.X p :=
  pointPushforwardPresentation f p

/-- The native geometric generator acts on a point cycle by realizing the
explicit residue-degree point presentation. -/
theorem geometricGenerator_point
    (f : V.X ⟶ V.X)
    (x : CodimensionPoint V.X p) :
    geometricGenerator V p f (codimensionPointCycle V.X p x) =
      realizeFiniteCodimensionPresentation V.X p
        (geometricPresentationKernel V p f x) := by
  simpa [geometricGenerator, geometricPresentationKernel,
    nativePointPushforward] using
    smoothProjectiveNativePushforward_point V f p x

/-- Every native geometric generator has an explicit finite point
presentation on every point generator. -/
theorem geometricGenerator_has_point_presentation
    (f : V.X ⟶ V.X)
    (x : CodimensionPoint V.X p) :
    ∃ φ : FiniteCodimensionPresentation V.X p,
      realizeFiniteCodimensionPresentation V.X p φ =
        geometricGenerator V p f (codimensionPointCycle V.X p x) := by
  exact ⟨geometricPresentationKernel V p f x,
    (geometricGenerator_point V p f x).symm⟩

/-- Any native linear operator, in particular every projective-correspondence
operator, admits a canonical finite point presentation after acting on a point
generator because the projective carrier is compact. -/
noncomputable def operatorPointPresentation
    (A : NativeCycleEnd V p)
    (x : CodimensionPoint V.X p) :
    FiniteCodimensionPresentation V.X p := by
  letI : CompactSpace V.X := smoothProjectiveCompactSpace V
  exact presentationOfNativeCycle V.X p
    (A (codimensionPointCycle V.X p x))

/-- The canonical point presentation reconstructs the operator image exactly. -/
theorem operatorPointPresentation_realize
    (A : NativeCycleEnd V p)
    (x : CodimensionPoint V.X p) :
    realizeFiniteCodimensionPresentation V.X p
        (operatorPointPresentation V p A x) =
      A (codimensionPointCycle V.X p x) := by
  letI : CompactSpace V.X := smoothProjectiveCompactSpace V
  exact realize_presentationOfNativeCycle V.X p
    (A (codimensionPointCycle V.X p x))

/-- Projective-correspondence operators therefore carry an intrinsic finite
point-transition kernel on the native cycle side. -/
noncomputable def ProjectiveNativeKernel :=
  { A : NativeCycleEnd V p // A ∈ projectiveCorrespondenceSpan V p }

namespace ProjectiveNativeKernel

/-- Underlying native operator. -/
noncomputable def operator
    (K : ProjectiveNativeKernel V p) : NativeCycleEnd V p := K.1

/-- Canonical finite transition presentation for each genuine point atom. -/
noncomputable def transition
    (K : ProjectiveNativeKernel V p)
    (x : CodimensionPoint V.X p) :
    FiniteCodimensionPresentation V.X p :=
  operatorPointPresentation V p K.1 x

/-- Native realization of the transition is exactly the native geometric
operator applied to the point atom. -/
theorem transition_realize
    (K : ProjectiveNativeKernel V p)
    (x : CodimensionPoint V.X p) :
    realizeFiniteCodimensionPresentation V.X p (K.transition x) =
      K.operator (codimensionPointCycle V.X p x) := by
  exact operatorPointPresentation_realize V p K.1 x

end ProjectiveNativeKernel

#check geometricGenerator
#check projectiveCorrespondenceSpan
#check geometricGenerator_mem
#check geometricPresentationKernel
#check geometricGenerator_point
#check operatorPointPresentation
#check ProjectiveNativeKernel
#check ProjectiveNativeKernel.transition
#check ProjectiveNativeKernel.transition_realize

#print axioms geometricGenerator_point
#print axioms operatorPointPresentation_realize
#print axioms ProjectiveNativeKernel.transition_realize

end GSTClassicalHodgeProjectiveCorrespondenceAlgebra
