import GSTClassicalHodgeTwoGeneratorPointKernelSaturation
import GSTClassicalHodgePrimitiveArsenalRationalization
import GSTClassicalHodgeRepairToolkit

/-!
# GST CLASSICAL HODGE — TWO-SLOT CODE IS LEFSCHETZ–POINCARE GENERATED

The two-generator externalization package uses the finite two-slot code
observable

    D = diag(0,1)

and the two-step pure-diagonal Lefschetz operator.  In the actual 2-slot GST
world, however, `D` is not an independent primitive.

Let `P` be square-world Poincare reversal.  On the ordered basis `(e₀,e₁)`:

    P e₀ = e₁,      P e₁ = e₀,
    L² e₀ = 2 e₁,  L² e₁ = 0.

Therefore

    (1/2) L² P = D.

This file records that identity exactly and lifts it to every ordered pair of
genuine classical Hodge sheets.  Consequently the finite algebraic engine is
intrinsically generated by the same two primitives appearing in the limitless
GST cosmology: Lefschetz propagation and Poincare reversal.  The code/projector
language is derived polynomial/composite syntax in the two-slot chart.

This does not assume native classical externalization of Poincare.  It sharpens
the remaining geometry target by showing what the minimal GST operator content
actually is.
-/

set_option maxHeartbeats 70000000
set_option maxRecDepth 1000000

noncomputable section

open GSTClassicalHodgeFullArsenalIrreducibility
open GSTClassicalHodgeExplicitArsenalGeneration
open GSTClassicalHodgePrimitiveArsenalRationalization
open GSTClassicalHodgeRankFreePrimitiveGeneration
open GSTClassicalHodgeTwoGeneratorNativeArsenal
open GSTClassicalHodgeUniversalTwoSlotNativeClosure
open GSTPureHodgeLefschetzKernel

namespace GSTClassicalHodgeTwoSlotLefschetzPoincareGeneration

/-- **TWO-SLOT CODE GENERATION.**
The target-sheet code projector is one half of two-step Lefschetz propagation
after Poincare reversal. -/
theorem twoSlotCode_eq_half_lefschetz_comp_poincare :
    twoSlotCode =
      ((2 : ℚ)⁻¹ •
        ((diagonalLefschetzQ 2 2).comp
          (poincareReverseQ 2).toLinearMap)) := by
  apply LinearMap.ext
  intro a
  funext r
  have e01 : worldAct 2 2 ((L 2 2)^(2 : Nat))
      (worldBasis (pureDiagonalState (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨0, by omega⟩)))
      (pureDiagonalState (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨1, by omega⟩))
      = (2 : ℤ) := by
    have h := pure_diagonal_lefschetz_forward_exact (A := 2) (B := 2)
      (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨0, by omega⟩)
      (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨1, by omega⟩) (by decide)
    have hgap : pureWeightGap
        (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨0, by omega⟩)
        (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨1, by omega⟩) = 1 := by
      decide
    rw [hgap] at h
    norm_num at h ⊢
    exact h
  have e00 : worldAct 2 2 ((L 2 2)^(2 : Nat))
      (worldBasis (pureDiagonalState (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨0, by omega⟩)))
      (pureDiagonalState (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨0, by omega⟩))
      = (0 : ℤ) :=
    pure_diagonal_lefschetz_wrong_time_zero (A := 2) (B := 2) (n := 2)
      (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨0, by omega⟩)
      (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨0, by omega⟩)
      (by decide) (by decide)
  have e10 : worldAct 2 2 ((L 2 2)^(2 : Nat))
      (worldBasis (pureDiagonalState (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨1, by omega⟩)))
      (pureDiagonalState (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨0, by omega⟩))
      = (0 : ℤ) :=
    pure_diagonal_lefschetz_backward_zero (A := 2) (B := 2) (n := 2)
      (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨1, by omega⟩)
      (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨0, by omega⟩)
      (by decide)
  have e11 : worldAct 2 2 ((L 2 2)^(2 : Nat))
      (worldBasis (pureDiagonalState (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨1, by omega⟩)))
      (pureDiagonalState (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨1, by omega⟩))
      = (0 : ℤ) :=
    pure_diagonal_lefschetz_wrong_time_zero (A := 2) (B := 2) (n := 2)
      (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨1, by omega⟩)
      (Fin.castLE (show 2 ≤ min 2 2 by omega) ⟨1, by omega⟩)
      (by decide) (by decide)
  fin_cases r
  · simp only [twoSlotCode, LinearMap.smul_apply, LinearMap.coe_comp,
      LinearMap.comp_apply, diagonalLefschetzQ, poincareReverseQ,
      windowMirror, Fin.isValue, Fin.sum_univ_two]
    rw [e00, e10]
    simp
    norm_num
  · simp only [twoSlotCode, LinearMap.smul_apply, LinearMap.coe_comp,
      LinearMap.comp_apply, diagonalLefschetzQ, poincareReverseQ,
      windowMirror, Fin.isValue, Fin.sum_univ_two]
    rw [e01, e11]
    simp
    norm_num

/-- Equivalent projector formulation. -/
theorem sheetProjectorQ_target_eq_half_lefschetz_comp_poincare :
    sheetProjectorQ targetSlot =
      ((2 : ℚ)⁻¹ •
        ((diagonalLefschetzQ 2 2).comp
          (poincareReverseQ 2).toLinearMap)) := by
  rw [sheetProjectorQ_target_eq_code]
  exact twoSlotCode_eq_half_lefschetz_comp_poincare

/-- Source projector is therefore generated by identity, Lefschetz and
Poincare alone. -/
theorem sheetProjectorQ_source_eq_id_sub_half_lefschetz_comp_poincare :
    sheetProjectorQ sourceSlot =
      LinearMap.id -
        ((2 : ℚ)⁻¹ •
          ((diagonalLefschetzQ 2 2).comp
            (poincareReverseQ 2).toLinearMap)) := by
  rw [sheetProjectorQ_source_eq_id_sub_code]
  rw [twoSlotCode_eq_half_lefschetz_comp_poincare]

/-- Classical Hodge specialization: the lifted two-slot code operator is the
lift of the same Lefschetz–Poincare composite in every ordered basis chart. -/
theorem twoSlotCodeHodge_eq_lift_half_lefschetz_comp_poincare
    {V : GSTProjectiveOverC.SmoothProjectiveComplexScheme}
    {H : GSTGeometricRealizationStage2G.HodgeBigradedBettiData V}
    {p : Nat}
    (i j : GSTClassicalHodgeFiberedCosmology.ClassicalHodgeBasisIndex V H p) :
    twoSlotCodeHodge i j =
      liftFiniteHodgeOperator (pairBasisIndex i j)
        ((2 : ℚ)⁻¹ •
          ((diagonalLefschetzQ 2 2).comp
            (poincareReverseQ 2).toLinearMap)) := by
  unfold twoSlotCodeHodge twoSlotHodgeOperator
  rw [twoSlotCode_eq_half_lefschetz_comp_poincare]

/-- The finite primitive crown: both sheet projectors are generated from the
same Lefschetz/Poincare pair. -/
theorem two_slot_lefschetz_poincare_generation_crown :
    sheetProjectorQ targetSlot =
      ((2 : ℚ)⁻¹ •
        ((diagonalLefschetzQ 2 2).comp
          (poincareReverseQ 2).toLinearMap))
    ∧ sheetProjectorQ sourceSlot =
      LinearMap.id -
        ((2 : ℚ)⁻¹ •
          ((diagonalLefschetzQ 2 2).comp
            (poincareReverseQ 2).toLinearMap)) := by
  exact ⟨
    sheetProjectorQ_target_eq_half_lefschetz_comp_poincare,
    sheetProjectorQ_source_eq_id_sub_half_lefschetz_comp_poincare⟩

#check twoSlotCode_eq_half_lefschetz_comp_poincare
#check sheetProjectorQ_target_eq_half_lefschetz_comp_poincare
#check sheetProjectorQ_source_eq_id_sub_half_lefschetz_comp_poincare
#check twoSlotCodeHodge_eq_lift_half_lefschetz_comp_poincare
#check two_slot_lefschetz_poincare_generation_crown

#print axioms twoSlotCode_eq_half_lefschetz_comp_poincare
#print axioms twoSlotCodeHodge_eq_lift_half_lefschetz_comp_poincare
#print axioms two_slot_lefschetz_poincare_generation_crown

end GSTClassicalHodgeTwoSlotLefschetzPoincareGeneration
