import GSTClassicalHodgePrincipalCutSuccessorOperator
import GSTClassicalHodgeRelativeSuccessorExactStratum

/-!
# GST CLASSICAL HODGE — PRINCIPAL-CUT INCIDENCE TRANSPOSE COSMOLOGY

This module expands the native principal-cut cosmology by constructing the
finite-support transpose of the already geometric successor kernel.

For a finite source chart `σ` of codimension-p points, the principal-cut
successor operator has a finite incidence matrix

    K(x,y) = successorPresentation V p x y.

The transpose is constructed directly from this incidence matrix, without any
Hodge basis, cycle-class surjectivity, or abstract matrix-unit assumption.
The resulting normal operator `KᵗK` has the exact Gram kernel

    G(x,z) = Σ_y K(x,y) K(z,y).

On one source atom its return therefore splits canonically as

    KᵗK(e_x) = λ_x e_x + crossTalk_x,

where `λ_x = Σ_y K(x,y)^2` and the cross-talk has zero x-coordinate.  If the
exact-stratum principal cut of x is nonempty, then λ_x is strictly positive.

This is the native geometric analogue of the diagonal-modulo-remainder law in
the first-failure transpose reduction.  Crucially, it is proved before any
cohomological externalization: the nonzero return scalar is generated by the
principal-cut incidence geometry itself.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry
open scoped BigOperators

namespace GSTClassicalHodgePrincipalCutIncidenceTransposeCosmology

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTNativeCodimensionCyclePresentation
open GSTClassicalHodgePrincipalCutSuccessorOperator
open GSTClassicalHodgeRelativeSuccessorExactStratum

/-- One column of the finite-support transpose of the principal-cut incidence
kernel.  Only source points in the finite chart `σ` are retained. -/
noncomputable def localTransposeColumn
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (σ : Finset (CodimensionPoint V.X p))
    (y : CodimensionPoint V.X (p + 1)) :
    FiniteCodimensionPresentation V.X p :=
  ∑ x in σ,
    (successorPresentation V p x y) • Finsupp.single x (1 : ℚ)

/-- Finite-support transpose of the geometric successor presentation operator. -/
noncomputable def localSuccessorTranspose
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (σ : Finset (CodimensionPoint V.X p)) :
    FiniteCodimensionPresentation V.X (p + 1) →ₗ[ℚ]
      FiniteCodimensionPresentation V.X p where
  toFun ψ := ψ.sum fun y q => q • localTransposeColumn V p σ y
  map_add' := by
    intro a b
    classical
    refine Finsupp.sum_add_index (fun y _ => zero_smul _ _) ?_
    intro y _ qa qb
    exact add_smul qa qb (localTransposeColumn V p σ y)
  map_smul' := by
    intro q a
    classical
    apply Finsupp.ext
    intro x
    simp [localTransposeColumn, Finsupp.sum, smul_smul,
      mul_assoc, Finset.mul_sum]

/-- Native principal-cut normal operator on one finite source chart. -/
noncomputable def localSuccessorNormal
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (σ : Finset (CodimensionPoint V.X p)) :
    FiniteCodimensionPresentation V.X p →ₗ[ℚ]
      FiniteCodimensionPresentation V.X p :=
  (localSuccessorTranspose V p σ).comp
    (successorPresentationOperator V p)

/-- Exact Gram coefficient of two source points under the principal-cut
incidence kernel. -/
noncomputable def successorGramCoefficient
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (x z : CodimensionPoint V.X p) : ℚ :=
  (successorPresentation V p x).sum fun y q =>
    q * successorPresentation V p z y

/-- Self-Gram coefficient, i.e. squared incidence energy of one source point. -/
noncomputable def successorSelfEnergy
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (x : CodimensionPoint V.X p) : ℚ :=
  successorGramCoefficient V p x x

/-- The transpose column really reads the original incidence coefficient on
any source point belonging to the local chart. -/
theorem localTransposeColumn_apply_of_mem
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (σ : Finset (CodimensionPoint V.X p))
    (x : CodimensionPoint V.X p)
    (y : CodimensionPoint V.X (p + 1))
    (hx : x ∈ σ) :
    localTransposeColumn V p σ y x = successorPresentation V p x y := by
  classical
  simp [localTransposeColumn, hx]

/-- Outside the chosen source chart the transpose column vanishes exactly. -/
theorem localTransposeColumn_apply_of_not_mem
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (σ : Finset (CodimensionPoint V.X p))
    (x : CodimensionPoint V.X p)
    (y : CodimensionPoint V.X (p + 1))
    (hx : x ∉ σ) :
    localTransposeColumn V p σ y x = 0 := by
  classical
  simp [localTransposeColumn, hx]

/-- Pointwise formula for the finite-support transpose. -/
theorem localSuccessorTranspose_apply_of_mem
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (σ : Finset (CodimensionPoint V.X p))
    (ψ : FiniteCodimensionPresentation V.X (p + 1))
    (x : CodimensionPoint V.X p)
    (hx : x ∈ σ) :
    localSuccessorTranspose V p σ ψ x =
      ψ.sum (fun y q => q * successorPresentation V p x y) := by
  classical
  simp [localSuccessorTranspose, localTransposeColumn_apply_of_mem,
    localTransposeColumn, hx, smul_eq_mul]

/-- The local normal operator has the exact principal-cut Gram matrix on source
atoms. -/
theorem localSuccessorNormal_single_apply
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (σ : Finset (CodimensionPoint V.X p))
    (x z : CodimensionPoint V.X p)
    (hx : x ∈ σ)
    (hz : z ∈ σ)
    (q : ℚ) :
    localSuccessorNormal V p σ (Finsupp.single x q) z =
      q * successorGramCoefficient V p x z := by
  classical
  rw [localSuccessorNormal, LinearMap.comp_apply]
  rw [successorPresentationOperator_single]
  rw [map_smul]
  rw [localSuccessorTranspose_apply_of_mem V p σ _ z hz]
  simp [successorGramCoefficient, Finsupp.sum, mul_assoc, mul_left_comm,
    mul_comm]

/-- In particular the diagonal return coefficient is the self-incidence
energy. -/
theorem localSuccessorNormal_single_self
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (σ : Finset (CodimensionPoint V.X p))
    (x : CodimensionPoint V.X p)
    (hx : x ∈ σ) :
    localSuccessorNormal V p σ (Finsupp.single x (1 : ℚ)) x =
      successorSelfEnergy V p x := by
  simpa [successorSelfEnergy] using
    localSuccessorNormal_single_apply V p σ x x hx hx 1

/-- Off-diagonal cross-talk after removing the canonical diagonal return. -/
noncomputable def successorCrossTalk
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (σ : Finset (CodimensionPoint V.X p))
    (x : CodimensionPoint V.X p) :
    FiniteCodimensionPresentation V.X p :=
  localSuccessorNormal V p σ (Finsupp.single x (1 : ℚ)) -
    successorSelfEnergy V p x • Finsupp.single x (1 : ℚ)

/-- Exact normal-form decomposition: diagonal return plus cross-talk. -/
theorem localSuccessorNormal_decomposition
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (σ : Finset (CodimensionPoint V.X p))
    (x : CodimensionPoint V.X p) :
    localSuccessorNormal V p σ (Finsupp.single x (1 : ℚ)) =
      successorSelfEnergy V p x • Finsupp.single x (1 : ℚ) +
        successorCrossTalk V p σ x := by
  unfold successorCrossTalk
  abel

/-- The remainder is genuinely off-diagonal at the distinguished source. -/
theorem successorCrossTalk_apply_self
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (σ : Finset (CodimensionPoint V.X p))
    (x : CodimensionPoint V.X p)
    (hx : x ∈ σ) :
    successorCrossTalk V p σ x x = 0 := by
  rw [successorCrossTalk, Finsupp.sub_apply]
  rw [localSuccessorNormal_single_self V p σ x hx]
  simp

/-- A nonzero successor presentation has strictly positive self-incidence
energy over Q. -/
theorem successorSelfEnergy_pos_of_presentation_ne_zero
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (x : CodimensionPoint V.X p)
    (hpres : successorPresentation V p x ≠ 0) :
    0 < successorSelfEnergy V p x := by
  classical
  unfold successorSelfEnergy successorGramCoefficient
  rw [Finsupp.sum]
  have hsupp : (successorPresentation V p x).support.Nonempty := by
    rw [Finset.nonempty_iff_ne_empty]
    intro hempty
    apply hpres
    apply Finsupp.ext
    intro y
    have hy : y ∉ (successorPresentation V p x).support := by
      simp [hempty]
    exact Finsupp.notMem_support_iff.mp hy
  apply Finset.sum_pos
  · intro y hy
    exact mul_self_nonneg _
  · rcases hsupp with ⟨y, hy⟩
    refine ⟨y, hy, ?_⟩
    exact mul_self_pos.mpr (Finsupp.mem_support_iff.mp hy)

/-- Exact-stratum nonempty principal-cut geometry forces the successor
presentation itself to be nonzero. -/
theorem successorPresentation_ne_zero_of_exact_nonempty
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (x : CodimensionPoint V.X p)
    (hExact : RelativeSuccessorAmbientExact V p x)
    (hNonempty : (relativeCodimensionOneFinset V x.1).Nonempty) :
    successorPresentation V p x ≠ 0 := by
  intro hzero
  have hnative := successorNativeOperator_point_ne_zero
    V p x hExact hNonempty
  apply hnative
  rw [successorNativeOperator_point, hzero]
  simp

/-- Therefore every live exact principal cut carries a genuinely nonzero
normal-return scalar. -/
theorem successorSelfEnergy_ne_zero_of_exact_nonempty
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (x : CodimensionPoint V.X p)
    (hExact : RelativeSuccessorAmbientExact V p x)
    (hNonempty : (relativeCodimensionOneFinset V x.1).Nonempty) :
    successorSelfEnergy V p x ≠ 0 := by
  exact ne_of_gt
    (successorSelfEnergy_pos_of_presentation_ne_zero V p x
      (successorPresentation_ne_zero_of_exact_nonempty
        V p x hExact hNonempty))

/-- **PRINCIPAL-CUT INCIDENCE-TRANSPOSE CROWN.**
For every chart containing an exact live source, the geometric round trip has
an exact nonzero diagonal coefficient and a remainder whose distinguished
source coordinate is zero. -/
theorem principalCut_incidenceTranspose_crown
    (V : SmoothProjectiveComplexScheme)
    (p : Nat)
    (σ : Finset (CodimensionPoint V.X p))
    (x : CodimensionPoint V.X p)
    (hx : x ∈ σ)
    (hExact : RelativeSuccessorAmbientExact V p x)
    (hNonempty : (relativeCodimensionOneFinset V x.1).Nonempty) :
    let λ := successorSelfEnergy V p x
    λ ≠ 0
      ∧ localSuccessorNormal V p σ (Finsupp.single x (1 : ℚ)) =
          λ • Finsupp.single x (1 : ℚ) + successorCrossTalk V p σ x
      ∧ successorCrossTalk V p σ x x = 0 := by
  dsimp
  exact ⟨
    successorSelfEnergy_ne_zero_of_exact_nonempty
      V p x hExact hNonempty,
    localSuccessorNormal_decomposition V p σ x,
    successorCrossTalk_apply_self V p σ x hx⟩

#check localTransposeColumn
#check localSuccessorTranspose
#check localSuccessorNormal
#check successorGramCoefficient
#check successorSelfEnergy
#check localSuccessorNormal_single_apply
#check successorCrossTalk
#check successorSelfEnergy_ne_zero_of_exact_nonempty
#check principalCut_incidenceTranspose_crown

#print axioms localSuccessorNormal_single_apply
#print axioms successorCrossTalk_apply_self
#print axioms successorSelfEnergy_pos_of_presentation_ne_zero
#print axioms successorSelfEnergy_ne_zero_of_exact_nonempty
#print axioms principalCut_incidenceTranspose_crown

end GSTClassicalHodgePrincipalCutIncidenceTransposeCosmology
