import GSTClassicalHodgeFirstFailurePrimitiveImage
import GSTClassicalHodgePrimitiveProjectiveDefectModule

/-!
# GST CLASSICAL HODGE — FIRST PRIMITIVE PROJECTIVE SECTOR

The least-failure analysis identified the entire realized Hodge-defect sector
with the primitive defect image.  Genuine projective words already act
functorially on Hodge classes and equivariantly on atomic defects.  Therefore
the realized Hodge-defect image is automatically invariant under every actual
projective word.

Combining the two facts gives a stronger residual normal form:

  the whole first primitive defect image is a nonzero invariant submodule for
  the genuine projective word algebra (modulo atomic classes).

This is strictly stronger than taking the orbit span of one chosen ghost.  In
particular, every projective orbit generated by a first-failure tomography
ghost is contained in this canonical primitive residual sector.

No projective irreducibility or prescribed matrix-unit action is assumed.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeFirstPrimitiveProjectiveSector

open GSTProjectiveOverC
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeAtomicDefectDuality
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgePrimitiveAtomicDefectReduction
open GSTClassicalHodgeHodgeFunctorialProjectiveDynamics
open GSTClassicalHodgePrimitiveProjectiveDefectModule
open GSTClassicalHodgeHodgeDefectImageFunctoriality
open GSTClassicalHodgeFirstPrimitiveProjectiveFailure
open GSTClassicalHodgeFirstFailurePrimitiveImage
open GSTClassicalHodgeTraceZeroPrimitiveTomographyGhost

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

namespace HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord

/-- Every genuine projective word preserves the submodule of atomic defects
which are actually represented by Hodge classes. -/
theorem HodgeDefectImage_invariant
    {R : HodgeFunctorialGeometricSemantics V H}
    {p : Nat}
    (w : ProjectiveHodgeWord R p) :
    ∀ z ∈ HodgeDefectImage V H p,
      w.defectOperator z ∈ HodgeDefectImage V H p := by
  intro z hz
  rcases hz with ⟨alpha, halpha⟩
  refine ⟨(eval w).hodge alpha, ?_⟩
  rw [w.defect_equivariant alpha, halpha]

/-- Canonical restriction of a genuine projective word to the realized
Hodge-defect sector. -/
noncomputable def onHodgeDefectImage
    {R : HodgeFunctorialGeometricSemantics V H}
    {p : Nat}
    (w : ProjectiveHodgeWord R p) :
    Module.End ℚ (HodgeDefectImage V H p) where
  toFun z := ⟨w.defectOperator z.1,
    HodgeDefectImage_invariant w z.1 z.2⟩
  map_add' := by
    intro a b
    apply Subtype.ext
    exact map_add _ _ _
  map_smul' := by
    intro c a
    apply Subtype.ext
    exact map_smul _ _ _

@[simp]
theorem onHodgeDefectImage_coe
    {R : HodgeFunctorialGeometricSemantics V H}
    {p : Nat}
    (w : ProjectiveHodgeWord R p)
    (z : HodgeDefectImage V H p) :
    (w.onHodgeDefectImage z).1 = w.defectOperator z.1 := by
  rfl

end HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord

/-- At a first bad successor weight, every genuine projective word preserves
the *entire* primitive defect image. -/
theorem firstFailure_PrimitiveDefectImage_projective_invariant
    {R : HodgeFunctorialGeometricSemantics V H}
    (F : FirstAtomicDefectWeight V H)
    {p : Nat}
    (hp : F.weight = p + 1)
    (D : LefschetzPrimitiveDecomposition R.spine)
    (w : HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord R (p + 1)) :
    ∀ z ∈ PrimitiveDefectImage D (p + 1),
      w.defectOperator z ∈ PrimitiveDefectImage D (p + 1) := by
  intro z hz
  have heq :
      PrimitiveDefectImage D (p + 1) = HodgeDefectImage V H (p + 1) :=
    firstFailure_PrimitiveDefectImage_eq_HodgeDefectImage F hp D
  have hzHodge : z ∈ HodgeDefectImage V H (p + 1) := by
    rw [← heq]
    exact hz
  have hout :=
    HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.HodgeDefectImage_invariant
      w z hzHodge
  rw [← heq] at hout
  exact hout

/-- Restriction of a genuine projective word to the canonical first primitive
residual sector. -/
noncomputable def firstPrimitiveProjectiveOperator
    {R : HodgeFunctorialGeometricSemantics V H}
    (F : FirstAtomicDefectWeight V H)
    {p : Nat}
    (hp : F.weight = p + 1)
    (D : LefschetzPrimitiveDecomposition R.spine)
    (w : HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord R (p + 1)) :
    Module.End ℚ (PrimitiveDefectImage D (p + 1)) where
  toFun z := ⟨w.defectOperator z.1,
    firstFailure_PrimitiveDefectImage_projective_invariant F hp D w z.1 z.2⟩
  map_add' := by
    intro a b
    apply Subtype.ext
    exact map_add _ _ _
  map_smul' := by
    intro c a
    apply Subtype.ext
    exact map_smul _ _ _

@[simp]
theorem firstPrimitiveProjectiveOperator_coe
    {R : HodgeFunctorialGeometricSemantics V H}
    (F : FirstAtomicDefectWeight V H)
    {p : Nat}
    (hp : F.weight = p + 1)
    (D : LefschetzPrimitiveDecomposition R.spine)
    (w : HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord R (p + 1))
    (z : PrimitiveDefectImage D (p + 1)) :
    (firstPrimitiveProjectiveOperator F hp D w z).1 =
      w.defectOperator z.1 := by
  rfl

/-- The defect state of a trace-zero primitive ghost at the first failure lies
in the canonical primitive residual sector. -/
theorem firstFailure_ghost_defectState_mem_PrimitiveDefectImage
    {R : HodgeFunctorialGeometricSemantics V H}
    {T : GSTClassicalHodgeProjectiveDegreeTrace.ProjectiveDegreeTraceSemantics V H}
    (F : FirstAtomicDefectWeight V H)
    {p : Nat}
    (hp : F.weight = p + 1)
    (D : LefschetzPrimitiveDecomposition R.spine)
    (A : GSTClassicalHodgeAtomicDefectTraceNormalization.TraceAnchor
      R.spine T (p + 1))
    (E : TraceZeroPrimitiveTomographyGhost A D) :
    E.defectState ∈ PrimitiveDefectImage D (p + 1) := by
  have hHodge : E.defectState ∈ HodgeDefectImage V H (p + 1) := by
    exact ⟨E.traceZeroClass, rfl⟩
  rw [firstFailure_PrimitiveDefectImage_eq_HodgeDefectImage F hp D]
  exact hHodge

/-- Every actual projective orbit generated by a first-failure primitive ghost
is contained in the canonical primitive residual sector. -/
theorem firstFailure_ghost_defectOrbitModule_le_PrimitiveDefectImage
    {R : HodgeFunctorialGeometricSemantics V H}
    {T : GSTClassicalHodgeProjectiveDegreeTrace.ProjectiveDegreeTraceSemantics V H}
    (F : FirstAtomicDefectWeight V H)
    {p : Nat}
    (hp : F.weight = p + 1)
    (D : LefschetzPrimitiveDecomposition R.spine)
    (A : GSTClassicalHodgeAtomicDefectTraceNormalization.TraceAnchor
      R.spine T (p + 1))
    (E : TraceZeroPrimitiveTomographyGhost A D) :
    HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.defectOrbitModule
        (R := R) E.defectState ≤ PrimitiveDefectImage D (p + 1) := by
  apply Submodule.span_le.mpr
  intro y hy
  rcases hy with ⟨w, rfl⟩
  exact firstFailure_PrimitiveDefectImage_projective_invariant
    F hp D w E.defectState
    (firstFailure_ghost_defectState_mem_PrimitiveDefectImage F hp D A E)

/-- Canonical representation-theoretic residual normal form: the first
primitive defect image is nonzero and invariant under all genuine projective
words. -/
theorem firstFailure_nonzero_projective_invariant_primitive_sector
    {R : HodgeFunctorialGeometricSemantics V H}
    (F : FirstAtomicDefectWeight V H)
    {p : Nat}
    (hp : F.weight = p + 1)
    (D : LefschetzPrimitiveDecomposition R.spine) :
    PrimitiveDefectImage D (p + 1) ≠ ⊥
      ∧ (∀ w : HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord R (p + 1),
          ∀ z ∈ PrimitiveDefectImage D (p + 1),
            w.defectOperator z ∈ PrimitiveDefectImage D (p + 1)) := by
  exact ⟨firstFailure_PrimitiveDefectImage_ne_bot F hp D,
    fun w => firstFailure_PrimitiveDefectImage_projective_invariant F hp D w⟩

#check HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.HodgeDefectImage_invariant
#check HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.onHodgeDefectImage
#check firstFailure_PrimitiveDefectImage_projective_invariant
#check firstPrimitiveProjectiveOperator
#check firstFailure_ghost_defectState_mem_PrimitiveDefectImage
#check firstFailure_ghost_defectOrbitModule_le_PrimitiveDefectImage
#check firstFailure_nonzero_projective_invariant_primitive_sector

#print axioms HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.HodgeDefectImage_invariant
#print axioms firstFailure_PrimitiveDefectImage_projective_invariant
#print axioms firstFailure_ghost_defectOrbitModule_le_PrimitiveDefectImage
#print axioms firstFailure_nonzero_projective_invariant_primitive_sector

end GSTClassicalHodgeFirstPrimitiveProjectiveSector
