import GSTClassicalHodgeSpectralSeparatorCollision

/-!
# GST CLASSICAL HODGE — GENERATORWISE ATOMIC STABILITY

The atomic-stability condition on a cohomological observable is global in its
original form: every vector in the span of all genuine codimension-p point
cycle classes must remain in that span.

Because the atomic submodule is literally generated by those point classes,
linearity compresses the condition completely.  It is enough — and necessary
— to check the observable on each genuine point-cycle generator.

Using the exact finite-presentation normal form of the atomic span, this can
be sharpened to a concrete transition statement:

  for every genuine codimension-p point x,
  T(cl[x]) is the class of a finite rational point-cycle presentation.

Thus an arbitrary-submodule preservation theorem is equivalent to a family
of finite transition equations on geometric generators.  This is the natural
interface for GST projectors, Lefschetz transport, world transitions and any
other finite combinatorial evolution law.
-/

set_option maxHeartbeats 10000000
set_option maxRecDepth 1000000

noncomputable section

open scoped BigOperators
open AlgebraicGeometry
open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTNativeCodimensionCyclePresentation
open GSTClassicalHodgeAtomicSpan
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeCyclicSpectralGeneration
open GSTClassicalHodgeSingleSheetCrown
open GSTClassicalHodgeSpectralSeparatorCollision

namespace GSTClassicalHodgeGeneratorwiseAtomicStability

universe u v

variable {X : Scheme.{u}}
variable {Coh : Type v} [AddCommGroup Coh] [Module ℚ Coh]
variable {p : Nat}
variable {cl : codimensionCycles X p →ₗ[ℚ] Coh}

/-- Global preservation of the genuine point-cycle atomic span. -/
def AtomicSpanStable (T : Coh →ₗ[ℚ] Coh) : Prop :=
  ∀ y : Coh,
    y ∈ pointCycleClassSpan p cl →
      T y ∈ pointCycleClassSpan p cl

/-- Generatorwise form: every genuine point-cycle class is sent back into the
atomic span. -/
def PointGeneratorStable (T : Coh →ₗ[ℚ] Coh) : Prop :=
  ∀ x : CodimensionPoint X p,
    T (cl (codimensionPointCycle X p x)) ∈
      pointCycleClassSpan p cl

/-- **GENERATORWISE ATOMIC-STABILITY EQUIVALENCE.**
A rational linear observable preserves the entire atomic span iff it preserves
each genuine point-cycle generator. -/
theorem atomicSpanStable_iff_pointGeneratorStable
    (T : Coh →ₗ[ℚ] Coh) :
    AtomicSpanStable (p := p) (cl := cl) T ↔
      PointGeneratorStable (p := p) (cl := cl) T := by
  constructor
  · intro h x
    apply h
    apply Submodule.subset_span
    exact ⟨x, rfl⟩
  · intro h
    intro y hy
    have hle :
        pointCycleClassSpan p cl ≤
          (pointCycleClassSpan p cl).comap T := by
      rw [pointCycleClassSpan]
      apply Submodule.span_le.mpr
      rintro z ⟨x, rfl⟩
      exact h x
    exact hle hy

/-- Concrete finite-transition form of generatorwise stability. -/
def HasFinitePointTransitions (T : Coh →ₗ[ℚ] Coh) : Prop :=
  ∀ x : CodimensionPoint X p,
    ∃ φ : FiniteCodimensionPresentation X p,
      finitePointCycleClassMap p cl φ =
        T (cl (codimensionPointCycle X p x))

/-- One generator lies in the atomic span iff it admits an explicit finite
point-cycle presentation. -/
theorem pointGenerator_mem_atomicSpan_iff_exists_presentation
    (T : Coh →ₗ[ℚ] Coh)
    (x : CodimensionPoint X p) :
    T (cl (codimensionPointCycle X p x)) ∈ pointCycleClassSpan p cl ↔
      ∃ φ : FiniteCodimensionPresentation X p,
        finitePointCycleClassMap p cl φ =
          T (cl (codimensionPointCycle X p x)) := by
  rw [← range_finitePointCycleClassMap p cl]
  rfl

/-- **FINITE-TRANSITION NORMAL FORM.**
Global atomic-span preservation is exactly equivalent to the existence of a
finite point-cycle transition for every genuine point generator. -/
theorem atomicSpanStable_iff_finitePointTransitions
    (T : Coh →ₗ[ℚ] Coh) :
    AtomicSpanStable (p := p) (cl := cl) T ↔
      HasFinitePointTransitions (p := p) (cl := cl) T := by
  rw [atomicSpanStable_iff_pointGeneratorStable]
  constructor
  · intro h x
    exact (pointGenerator_mem_atomicSpan_iff_exists_presentation
      (p := p) (cl := cl) T x).mp (h x)
  · intro h x
    exact (pointGenerator_mem_atomicSpan_iff_exists_presentation
      (p := p) (cl := cl) T x).mpr (h x)

/-- A chosen transition kernel: for each genuine codimension-p point it gives
an explicit finite rational point-cycle presentation of the transformed
cohomology class. -/
structure PointClassTransitionKernel
    (T : Coh →ₗ[ℚ] Coh) where
  transition :
    CodimensionPoint X p → FiniteCodimensionPresentation X p
  transition_spec : ∀ x,
    finitePointCycleClassMap p cl (transition x) =
      T (cl (codimensionPointCycle X p x))

namespace PointClassTransitionKernel

/-- A point-class transition kernel immediately gives all finite transitions. -/
theorem hasFinitePointTransitions
    {T : Coh →ₗ[ℚ] Coh}
    (K : PointClassTransitionKernel (p := p) (cl := cl) T) :
    HasFinitePointTransitions (p := p) (cl := cl) T := by
  intro x
  exact ⟨K.transition x, K.transition_spec x⟩

/-- **KERNEL-TO-GLOBAL STABILITY.**
An explicit transition law on genuine point-cycle generators forces invariance
of the complete atomic span. -/
theorem atomicSpanStable
    {T : Coh →ₗ[ℚ] Coh}
    (K : PointClassTransitionKernel (p := p) (cl := cl) T) :
    AtomicSpanStable (p := p) (cl := cl) T :=
  (atomicSpanStable_iff_finitePointTransitions
    (p := p) (cl := cl) T).mpr K.hasFinitePointTransitions

end PointClassTransitionKernel

/-! ## Stage-2G specialization and separator collision -/

open GSTClassicalHodgeSpectralSeparatorCollision.RawClassicalHodgeSpectralObservable

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}

/-- Point-transition kernel specialized to a raw classical Hodge spectral
observable. -/
abbrev RawClassicalHodgeSpectralObservable.PointTransitionKernel
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (S : RawClassicalHodgeSpectralObservable V H p ι) :=
  PointClassTransitionKernel
    (p := p) (cl := H.cycleClass p) S.observable

/-- Generatorwise finite point transitions automatically supply the exact
atomic-stability field needed by the spectral Hodge engine. -/
theorem RawClassicalHodgeSpectralObservable.atomicStable_of_pointTransitionKernel
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (S : RawClassicalHodgeSpectralObservable V H p ι)
    (K : S.PointTransitionKernel) :
    S.AtomicStable := by
  exact K.atomicSpanStable

/-- **TRANSITION-KERNEL SEPARATOR COLLISION.**
A raw spectral observable with an explicit point-class transition kernel and
one cyclic atomic seed admits no separator on any selected Hodge sheet. -/
theorem RawClassicalHodgeSpectralObservable.isEmpty_basisAtomicSeparator_of_transitionKernel
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (S : RawClassicalHodgeSpectralObservable V H p ι)
    (K : S.PointTransitionKernel)
    (a : ι → ℚ)
    (ha : ∀ j, a j ≠ 0)
    (hseed :
      ∑ j : ι,
        a j • (classicalHodgeBasis V H p (S.basisIndex j)).1 ∈
          pointCycleClassSpan p (H.cycleClass p))
    (i : ι) :
    IsEmpty (BasisAtomicSeparator V H p (S.basisIndex i)) := by
  exact S.isEmpty_basisAtomicSeparator_of_stable_seed
    (S.atomicStable_of_pointTransitionKernel K) a ha hseed i

/-- Family form: a point-transition kernel plus cyclic seed makes every
selected sheet atomic-algebraic. -/
theorem RawClassicalHodgeSpectralObservable.selected_basis_mem_atomic_of_transitionKernel
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (S : RawClassicalHodgeSpectralObservable V H p ι)
    (K : S.PointTransitionKernel)
    (a : ι → ℚ)
    (ha : ∀ j, a j ≠ 0)
    (hseed :
      ∑ j : ι,
        a j • (classicalHodgeBasis V H p (S.basisIndex j)).1 ∈
          pointCycleClassSpan p (H.cycleClass p)) :
    ∀ i : ι,
      (classicalHodgeBasis V H p (S.basisIndex i)).1 ∈
        pointCycleClassSpan p (H.cycleClass p) := by
  let Sop := S.toClassicalHodgeSpectralOperator
    (S.atomicStable_of_pointTransitionKernel K)
  have h := Sop.selected_basis_algebraic_of_cyclic_seed a ha
  simpa [Sop] using h hseed

#check AtomicSpanStable
#check PointGeneratorStable
#check atomicSpanStable_iff_pointGeneratorStable
#check HasFinitePointTransitions
#check pointGenerator_mem_atomicSpan_iff_exists_presentation
#check atomicSpanStable_iff_finitePointTransitions
#check PointClassTransitionKernel
#check PointClassTransitionKernel.atomicSpanStable
#check RawClassicalHodgeSpectralObservable.PointTransitionKernel
#check RawClassicalHodgeSpectralObservable.atomicStable_of_pointTransitionKernel
#check RawClassicalHodgeSpectralObservable.isEmpty_basisAtomicSeparator_of_transitionKernel
#check RawClassicalHodgeSpectralObservable.selected_basis_mem_atomic_of_transitionKernel

#print axioms atomicSpanStable_iff_pointGeneratorStable
#print axioms atomicSpanStable_iff_finitePointTransitions
#print axioms PointClassTransitionKernel.atomicSpanStable
#print axioms RawClassicalHodgeSpectralObservable.atomicStable_of_pointTransitionKernel
#print axioms RawClassicalHodgeSpectralObservable.isEmpty_basisAtomicSeparator_of_transitionKernel
#print axioms RawClassicalHodgeSpectralObservable.selected_basis_mem_atomic_of_transitionKernel

end GSTClassicalHodgeGeneratorwiseAtomicStability
