import GSTClassicalHodgeGeometricCycleClassSpine
import GSTClassicalHodgeLimitlessTowerOrbitCrown
import GSTClassicalHodgeLimitlessProjectiveLefschetzTower
import GSTClassicalHodgeRankFreeArsenalIrreducibility
import GSTClassicalHodgeNativeCycleCosmicShadow
import GSTClassicalHodgeNativeOperatorCohomologyRealization

/-!
# GST CLASSICAL HODGE — LIMITLESS SPINE PROPAGATION

The earlier projective/cosmic tower crown packaged a family of Hodge seeds and
its successor formula as data.  That is unnecessary once the genuine
cycle-class spine has been constructed.

The native projective successor operator already exists geometrically.  The
spine gives its exact cohomological realization and proves Hodge-sector
preservation.  The limitless cosmic Lefschetz theory supplies the canonical
nonzero successor scalar.  Therefore both the native tower and its Hodge state
can be generated recursively with no separately supplied seed family or
intertwining structure.

At every step we normalize by the inverse cosmic coefficient.  Naturality of
the spine then proves that the recursively generated native cycle has exactly
the recursively generated Hodge class.

The strengthened layer below also isolates a conserved geometric charge.  A
single native readout, a compatible cohomological readout, one nonzero base
value, and one successor transport law force the normalized charge to remain
constant through the entire unbounded projective tower.  Consequently the
cycle class of every tower level is nonzero.  This reduces infinitely many
nonvanishing obligations to one base case and one recursive geometric law.

Finally, the native-cycle cosmic-shadow calculus constructs that conserved
charge from the canonical native mass.  The only residual semantic laws are:

* native mass vanishes on the kernel of the genuine cycle-class map;
* the codimension-zero fundamental cycle has nonzero native mass;
* every genuine point successor has the already-proved limitless successor
  scalar as its native mass.

The point-normal-form theorem upgrades the last pointwise law to every native
cycle.  Kernel annihilation makes native mass descend through the actual
cycle-class range, and ordinary rational-linear extension manufactures the
ambient cohomological readout.  Thus `SpineTowerConservedCharge` is no longer
an independent package once these three native geometric laws are supplied.
-/

set_option maxHeartbeats 90000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeLimitlessSpinePropagation

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeRankFreeArsenalIrreducibility
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTNativeCodimensionCyclePresentation
open GSTClassicalHodgePrincipalCutSuccessorOperator
open GSTClassicalHodgeCodimensionZeroFundamentalCycle
open GSTClassicalHodgeLimitlessTowerOrbitCrown
open GSTClassicalHodgeNativeCycleCosmicShadow
open GSTClassicalHodgeNativeOperatorCohomologyRealization

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}

/-- Canonical Hodge state generated recursively by the genuine projective
principal-cut cohomology action and normalized by the true limitless cosmic
Lefschetz coefficient. -/
noncomputable def spineHodgeSeed
    (G : GeometricCycleClassSpine V H) :
    (p : Nat) → ClassicalHodgeFiber V H p
  | 0 =>
      ⟨H.cycleClass 0 (codimensionZeroFundamentalCycle V),
        G.codimensionZeroFundamentalClass_is_hodge⟩
  | p + 1 =>
      let prev := spineHodgeSeed G p
      let raw := (G.principalCutPair p).cohomologyOperator prev.1
      ⟨(successorScalar p)⁻¹ • raw,
        (rationalHodgeSubspace (H.hodgeBigrading (p + 1))).smul_mem
          ((successorScalar p)⁻¹)
          (G.principalCut_hodge p prev.1 prev.2)⟩

/-- Canonical native cycle generated by the same recursively normalized
projective principal-cut operator. -/
noncomputable def spineNativeTower
    (G : GeometricCycleClassSpine V H) :
    (p : Nat) → codimensionCycles V.X p
  | 0 => codimensionZeroFundamentalCycle V
  | p + 1 =>
      (successorScalar p)⁻¹ •
        successorNativeOperator V p (spineNativeTower G p)

@[simp]
theorem spineHodgeSeed_zero
    (G : GeometricCycleClassSpine V H) :
    spineHodgeSeed G 0 =
      ⟨H.cycleClass 0 (codimensionZeroFundamentalCycle V),
        G.codimensionZeroFundamentalClass_is_hodge⟩ := by
  rfl

@[simp]
theorem spineNativeTower_zero
    (G : GeometricCycleClassSpine V H) :
    spineNativeTower G 0 = codimensionZeroFundamentalCycle V := by
  rfl

/-- The unnormalized cohomological principal-cut image is exactly the true
cosmic successor coefficient times the normalized next Hodge seed. -/
theorem spineHodgeSeed_successor_formula
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    (G.principalCutPair p).cohomologyOperator (spineHodgeSeed G p).1 =
      successorScalar p • (spineHodgeSeed G (p + 1)).1 := by
  change (G.principalCutPair p).cohomologyOperator (spineHodgeSeed G p).1 =
    successorScalar p •
      ((successorScalar p)⁻¹ •
        (G.principalCutPair p).cohomologyOperator (spineHodgeSeed G p).1)
  rw [smul_smul]
  simp [successorScalar_ne_zero]

/-- Native recursion law. -/
theorem spineNativeTower_succ
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    spineNativeTower G (p + 1) =
      (successorScalar p)⁻¹ •
        successorNativeOperator V p (spineNativeTower G p) := by
  rfl

/-- **EXACT SPINE-TOWER CYCLE-CLASS LAW.**
The recursively generated native projective cycle has cycle class exactly equal
to the recursively generated genuine Hodge state in every weight. -/
theorem spineNativeTower_cycleClass
    (G : GeometricCycleClassSpine V H) :
    ∀ p : Nat,
      H.cycleClass p (spineNativeTower G p) = (spineHodgeSeed G p).1 := by
  intro p
  induction p with
  | zero => rfl
  | succ p ih =>
      rw [spineNativeTower_succ]
      rw [LinearMap.map_smul]
      have hnat := (G.principalCutPair p).cycleClass_natural
        (spineNativeTower G p)
      rw [G.principalCutPair_native p] at hnat
      rw [hnat, ih]
      rfl

/-- Every recursively generated Hodge state is algebraic, because it is the
actual class of the recursively generated native projective cycle. -/
theorem spineHodgeSeed_algebraic
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    spineHodgeSeed G p ∈ AlgebraicHodgeSubspace V H p := by
  rw [mem_AlgebraicHodgeSubspace_iff]
  rw [← GSTClassicalHodgeAtomicSpan.smoothProjective_cycleClass_range_eq_atomic_span
    V H p]
  exact ⟨spineNativeTower G p, spineNativeTower_cycleClass G p⟩

/-- Nonvanishing of the recursively generated cycle class is exactly
nonvanishing of the corresponding Hodge seed. -/
theorem spineHodgeSeed_ne_zero_iff_cycleClass_ne_zero
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    spineHodgeSeed G p ≠ 0 ↔
      H.cycleClass p (spineNativeTower G p) ≠ 0 := by
  rw [spineNativeTower_cycleClass G p]
  constructor
  · intro h hval
    apply h
    apply Subtype.ext
    exact hval
  · intro h hseed
    apply h
    simpa [hseed]

/-- Whenever the canonical spine tower is nonzero in a weight, it supplies the
nontrivial algebraic Hodge subspace required by rank-free limitless
irreducibility. -/
theorem algebraicHodgeSubspace_ne_bot_of_spineSeed
    (G : GeometricCycleClassSpine V H)
    (p : Nat)
    (hne : spineHodgeSeed G p ≠ 0) :
    AlgebraicHodgeSubspace V H p ≠ ⊥ := by
  intro hbot
  have hmem := spineHodgeSeed_algebraic G p
  rw [hbot] at hmem
  have hz : spineHodgeSeed G p = 0 := by simpa using hmem
  exact hne hz

/-! ## Conserved geometric charge -/

/-- A conserved native/cohomological charge for the canonical projective spine. -/
structure SpineTowerConservedCharge
    (G : GeometricCycleClassSpine V H) where
  nativeRead :
    ∀ p : Nat, codimensionCycles V.X p →ₗ[ℚ] ℚ
  cohomologyRead :
    ∀ p : Nat,
      RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ] ℚ
  cycleClass_read :
    ∀ p : Nat, ∀ Z : codimensionCycles V.X p,
      cohomologyRead p (H.cycleClass p Z) = nativeRead p Z
  base_ne_zero :
    nativeRead 0 (codimensionZeroFundamentalCycle V) ≠ 0
  successor_read :
    ∀ p : Nat, ∀ Z : codimensionCycles V.X p,
      nativeRead (p + 1) (successorNativeOperator V p Z) =
        successorScalar p * nativeRead p Z

namespace SpineTowerConservedCharge

/-- **CONSERVATION LAW.**  The normalized projective tower has exactly the
same native charge in every weight as its codimension-zero fundamental seed. -/
theorem nativeRead_spineNativeTower
    (D : SpineTowerConservedCharge (V := V) (H := H) G) :
    ∀ p : Nat,
      D.nativeRead p (spineNativeTower G p) =
        D.nativeRead 0 (codimensionZeroFundamentalCycle V) := by
  intro p
  induction p with
  | zero => rfl
  | succ p ih =>
      rw [spineNativeTower_succ]
      rw [LinearMap.map_smul]
      rw [D.successor_read p (spineNativeTower G p)]
      simp [successorScalar_ne_zero, ih]

/-- The conserved native charge is nonzero at every level of the unbounded
normalized projective tower. -/
theorem nativeRead_spineNativeTower_ne_zero
    (D : SpineTowerConservedCharge (V := V) (H := H) G)
    (p : Nat) :
    D.nativeRead p (spineNativeTower G p) ≠ 0 := by
  rw [D.nativeRead_spineNativeTower p]
  exact D.base_ne_zero

/-- Compatibility of the charge with the actual cycle-class map converts the
native conservation law into genuine cohomological nonvanishing. -/
theorem cycleClass_spineNativeTower_ne_zero
    (D : SpineTowerConservedCharge (V := V) (H := H) G)
    (p : Nat) :
    H.cycleClass p (spineNativeTower G p) ≠ 0 := by
  intro hz
  have hcompat := D.cycleClass_read p (spineNativeTower G p)
  rw [hz] at hcompat
  simp only [LinearMap.map_zero] at hcompat
  exact D.nativeRead_spineNativeTower_ne_zero p hcompat.symm

/-- **SEMANTIC ZERO-MAP EXCLUSION.**
A conserved geometric charge makes the zero cycle-class map impossible in
every weight. -/
theorem cycleClass_ne_zero
    (D : SpineTowerConservedCharge (V := V) (H := H) G)
    (p : Nat) :
    H.cycleClass p ≠ 0 := by
  intro hzero
  apply D.cycleClass_spineNativeTower_ne_zero p
  rw [hzero]
  rfl

/-- Hence every recursively generated Hodge seed is nonzero. -/
theorem spineHodgeSeed_ne_zero
    (D : SpineTowerConservedCharge (V := V) (H := H) G)
    (p : Nat) :
    spineHodgeSeed G p ≠ 0 :=
  (spineHodgeSeed_ne_zero_iff_cycleClass_ne_zero G p).2
    (D.cycleClass_spineNativeTower_ne_zero p)

/-- The conserved charge simultaneously certifies that the algebraic Hodge
subspace is nontrivial in every weight. -/
theorem algebraicHodgeSubspace_ne_bot
    (D : SpineTowerConservedCharge (V := V) (H := H) G)
    (p : Nat) :
    AlgebraicHodgeSubspace V H p ≠ ⊥ :=
  algebraicHodgeSubspace_ne_bot_of_spineSeed G p
    (D.spineHodgeSeed_ne_zero p)

end SpineTowerConservedCharge

/-! ## Native mass manufactures the conserved charge

The unrestricted cosmic shadow already assigns every native cycle a canonical
rational mass.  We isolate only the three geometric facts required to make that
mass a separating, conserved cycle-class charge.  In particular no ambient
cohomological functional is supplied: it is constructed by descending mass to
the actual cycle-class range and extending linearly. -/

/-- Minimal native-mass laws needed by the limitless spine.

`kernel_mass_zero` says native mass depends only on the genuine cycle class.
`base_mass_ne_zero` is one codimension-zero geometric nonemptiness statement.
`successor_point_mass` is pointwise and is promoted to every native cycle by
exact point normal form. -/
structure NativeMassCycleClassBridge
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V) where
  kernel_mass_zero :
    ∀ p : Nat, ∀ Z : codimensionCycles V.X p,
      H.cycleClass p Z = 0 → nativeCycleMass V p Z = 0
  base_mass_ne_zero :
    nativeCycleMass V 0 (codimensionZeroFundamentalCycle V) ≠ 0
  successor_point_mass :
    ∀ p : Nat, ∀ x : CodimensionPoint V.X p,
      successorMass V p x = successorScalar p

namespace NativeMassCycleClassBridge

/-- Equal genuine cycle classes have equal canonical native mass. -/
theorem mass_congr
    (M : NativeMassCycleClassBridge V H)
    (p : Nat)
    {Z W : codimensionCycles V.X p}
    (hZW : H.cycleClass p Z = H.cycleClass p W) :
    nativeCycleMass V p Z = nativeCycleMass V p W := by
  have hker : H.cycleClass p (Z - W) = 0 := by
    simp [hZW]
  have hmass := M.kernel_mass_zero p (Z - W) hker
  have hmass' : nativeCycleMass V p Z - nativeCycleMass V p W = 0 := by
    simpa using hmass
  linarith

/-- Native mass descended to the actual cycle-class range. -/
noncomputable def rangeMassRead
    (M : NativeMassCycleClassBridge V H)
    (p : Nat) :
    LinearMap.range (H.cycleClass p) →ₗ[ℚ] ℚ where
  toFun := fun x => nativeCycleMass V p (rangeRepresentative x)
  map_add' := by
    intro x y
    have hrep :
        H.cycleClass p (rangeRepresentative (x + y)) =
          H.cycleClass p (rangeRepresentative x + rangeRepresentative y) := by
      simp [rangeRepresentative_spec]
    rw [M.mass_congr p hrep]
    simp
  map_smul' := by
    intro q x
    have hrep :
        H.cycleClass p (rangeRepresentative (q • x)) =
          H.cycleClass p (q • rangeRepresentative x) := by
      simp [rangeRepresentative_spec]
    rw [M.mass_congr p hrep]
    simp

/-- Extend the descended native mass from the actual cycle-class range to the
whole ambient rational cohomology space. -/
noncomputable def ambientMassRead
    (M : NativeMassCycleClassBridge V H)
    (p : Nat) :
    RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ] ℚ :=
  Classical.choose (LinearMap.exists_extend (M.rangeMassRead p))

/-- The ambient mass extension agrees with descended mass on the actual
cycle-class range. -/
theorem ambientMassRead_comp_rangeSubtype
    (M : NativeMassCycleClassBridge V H)
    (p : Nat) :
    (M.ambientMassRead p).comp (LinearMap.range (H.cycleClass p)).subtype =
      M.rangeMassRead p :=
  Classical.choose_spec (LinearMap.exists_extend (M.rangeMassRead p))

/-- The manufactured ambient readout evaluates every genuine cycle class to
exactly its canonical native mass. -/
theorem ambientMassRead_cycleClass
    (M : NativeMassCycleClassBridge V H)
    (p : Nat)
    (Z : codimensionCycles V.X p) :
    M.ambientMassRead p (H.cycleClass p Z) = nativeCycleMass V p Z := by
  have hcomp := LinearMap.congr_fun (M.ambientMassRead_comp_rangeSubtype p)
    ((H.cycleClass p).rangeRestrict Z)
  have hrep :
      H.cycleClass p
        (rangeRepresentative ((H.cycleClass p).rangeRestrict Z)) =
        H.cycleClass p Z := by
    exact rangeRepresentative_spec _
  have hmass := M.mass_congr p hrep
  simpa [rangeMassRead, hmass] using hcomp

/-- **NATIVE-MASS CHARGE CONSTRUCTION.**
The canonical native mass, together with the three minimal bridge laws,
manufactures the complete conserved spine charge.  In particular the ambient
cohomological readout and the all-native-cycle successor law are theorems. -/
noncomputable def toConservedCharge
    (M : NativeMassCycleClassBridge V H)
    (G : GeometricCycleClassSpine V H) :
    SpineTowerConservedCharge G where
  nativeRead := nativeCycleMass V
  cohomologyRead := M.ambientMassRead
  cycleClass_read := by
    intro p Z
    exact M.ambientMassRead_cycleClass p Z
  base_ne_zero := M.base_mass_ne_zero
  successor_read := by
    intro p Z
    exact nativeCycleMass_successor_of_pointMass V p
      (M.successor_point_mass p) Z

/-- The native-mass bridge rules out zero cycle-class semantics in every
weight without separately supplying a cohomological detector. -/
theorem cycleClass_ne_zero
    (M : NativeMassCycleClassBridge V H)
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    H.cycleClass p ≠ 0 :=
  (M.toConservedCharge G).cycleClass_ne_zero p

/-- Native mass also manufactures unconditional nonvanishing of every
normalized projective spine seed. -/
theorem spineHodgeSeed_ne_zero
    (M : NativeMassCycleClassBridge V H)
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    spineHodgeSeed G p ≠ 0 :=
  (M.toConservedCharge G).spineHodgeSeed_ne_zero p

/-- Therefore every algebraic Hodge fiber contains a nonzero canonical spine
class once the native-mass bridge laws hold. -/
theorem algebraicHodgeSubspace_ne_bot
    (M : NativeMassCycleClassBridge V H)
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    AlgebraicHodgeSubspace V H p ≠ ⊥ :=
  (M.toConservedCharge G).algebraicHodgeSubspace_ne_bot p

end NativeMassCycleClassBridge

/-- The old tower-intertwining successor formula is now a theorem generated
from the spine rather than supplied as data. -/
theorem spine_limitless_successor_crown
    (G : GeometricCycleClassSpine V H) :
    ∀ p : Nat,
      (G.principalCutPair p).cohomologyOperator (spineHodgeSeed G p).1 =
        successorScalar p • (spineHodgeSeed G (p + 1)).1
      ∧ H.cycleClass (p + 1) (spineNativeTower G (p + 1)) =
        (spineHodgeSeed G (p + 1)).1 := by
  intro p
  exact ⟨spineHodgeSeed_successor_formula G p,
    spineNativeTower_cycleClass G (p + 1)⟩

#check spineHodgeSeed
#check spineNativeTower
#check spineHodgeSeed_successor_formula
#check spineNativeTower_cycleClass
#check spineHodgeSeed_algebraic
#check spineHodgeSeed_ne_zero_iff_cycleClass_ne_zero
#check algebraicHodgeSubspace_ne_bot_of_spineSeed
#check SpineTowerConservedCharge
#check SpineTowerConservedCharge.nativeRead_spineNativeTower
#check SpineTowerConservedCharge.nativeRead_spineNativeTower_ne_zero
#check SpineTowerConservedCharge.cycleClass_spineNativeTower_ne_zero
#check SpineTowerConservedCharge.cycleClass_ne_zero
#check SpineTowerConservedCharge.spineHodgeSeed_ne_zero
#check SpineTowerConservedCharge.algebraicHodgeSubspace_ne_bot
#check NativeMassCycleClassBridge
#check NativeMassCycleClassBridge.mass_congr
#check NativeMassCycleClassBridge.rangeMassRead
#check NativeMassCycleClassBridge.ambientMassRead
#check NativeMassCycleClassBridge.ambientMassRead_cycleClass
#check NativeMassCycleClassBridge.toConservedCharge
#check NativeMassCycleClassBridge.cycleClass_ne_zero
#check NativeMassCycleClassBridge.spineHodgeSeed_ne_zero
#check NativeMassCycleClassBridge.algebraicHodgeSubspace_ne_bot
#check spine_limitless_successor_crown

#print axioms spineHodgeSeed_successor_formula
#print axioms spineNativeTower_cycleClass
#print axioms spineHodgeSeed_algebraic
#print axioms algebraicHodgeSubspace_ne_bot_of_spineSeed
#print axioms SpineTowerConservedCharge.nativeRead_spineNativeTower
#print axioms SpineTowerConservedCharge.cycleClass_spineNativeTower_ne_zero
#print axioms SpineTowerConservedCharge.cycleClass_ne_zero
#print axioms SpineTowerConservedCharge.spineHodgeSeed_ne_zero
#print axioms SpineTowerConservedCharge.algebraicHodgeSubspace_ne_bot
#print axioms NativeMassCycleClassBridge.mass_congr
#print axioms NativeMassCycleClassBridge.ambientMassRead_cycleClass
#print axioms NativeMassCycleClassBridge.toConservedCharge
#print axioms NativeMassCycleClassBridge.cycleClass_ne_zero
#print axioms NativeMassCycleClassBridge.spineHodgeSeed_ne_zero
#print axioms NativeMassCycleClassBridge.algebraicHodgeSubspace_ne_bot
#print axioms spine_limitless_successor_crown

end GSTClassicalHodgeLimitlessSpinePropagation