import GSTClassicalHodgeFullArsenalIrreducibility
import GSTSquarePureHodgeDuality
import GSTPureHodgeLefschetzKernel

/-!
# GST CLASSICAL HODGE — EXPLICIT ARSENAL GENERATION

`GSTClassicalHodgeFullArsenalIrreducibility` established the exact Lefschetz
matrix coefficients and the irreducibility of the matrix-unit action, but the
matrix units themselves were still introduced by their coordinate formula.
This module removes that compression.

We rationalize the *actual* finite-world Lefschetz action on the pure diagonal.
For `p <= q`, the operator word

  P_q ∘ L^(2(q-p)) ∘ P_p

is the central-binomial scalar times the matrix unit E_pq.  Since that scalar
is positive, it is invertible over Q and E_pq is literally generated by the
GST sheet projectors and the native universal Lefschetz operator.  Backward
matrix units are obtained by conjugating the corresponding forward word by
square-world Poincare reversal.

Thus the full finite matrix algebra used in the Hodge attack is not an
independent coordinate gadget: it lies in the operator algebra generated by
the existing GST projector/Lefschetz/Poincare universe.
-/

set_option maxHeartbeats 30000000
set_option maxRecDepth 1000000

noncomputable section

open scoped BigOperators
open GSTWorldCosmology
open GSTWorldPoincareDuality
open GSTDimensionFreeHodgeDiagonal
open GSTGlobalPureHodgeCosmology
open GSTTruncatedWorldCohomologyRing
open GSTUniversalLefschetzKernel
open GSTPureHodgeLefschetzKernel
open GSTSquarePureHodgeDuality
open GSTClassicalHodgeFullArsenalIrreducibility

namespace GSTClassicalHodgeExplicitArsenalGeneration

/-- Rationalization of the actual `L^t` action, restricted to the complete
pure diagonal of one finite square world. -/
noncomputable def diagonalLefschetzQ
    (N t : Nat) : Module.End ℚ (RationalPureWindow N) where
  toFun a := fun q =>
    ∑ p : Fin N,
      (worldAct N N ((L N N)^t)
        (worldBasis (pureDiagonalState p))
        (pureDiagonalState q) : ℚ) * a p
  map_add' := by
    intro a b
    funext q
    simp [mul_add, Finset.sum_add_distrib]
  map_smul' := by
    intro c a
    funext q
    simp [mul_assoc, Finset.mul_sum]

/-- Rational Poincare reversal on the finite pure window. -/
noncomputable def poincareReverseQ
    (N : Nat) :
    RationalPureWindow N ≃ₗ[ℚ] RationalPureWindow N where
  toFun a := fun q => a (pureMirror q)
  invFun a := fun q => a (pureMirror q)
  left_inv := by
    intro a
    funext q
    simp
  right_inv := by
    intro a
    funext q
    simp
  map_add' := by
    intro a b
    rfl
  map_smul' := by
    intro c a
    rfl

@[simp]
theorem poincareReverseQ_basis
    {N : Nat} (p : Fin N) :
    poincareReverseQ N (rationalPureBasis p) =
      rationalPureBasis (pureMirror p) := by
  funext q
  simp [poincareReverseQ, rationalPureBasis]
  constructor
  · intro h
    apply pureMirror_involutive p ▸ congrArg pureMirror h
  · intro h
    simpa [h]

/-- Raw forward arsenal word before central-binomial normalization. -/
noncomputable def rawForwardWord
    {N : Nat} (p q : Fin N) : Module.End ℚ (RationalPureWindow N) :=
  (sheetProjectorQ q).comp
    ((diagonalLefschetzQ N (2 * pureWeightGap p q)).comp
      (sheetProjectorQ p))

/-- The raw forward word has the exact GST central-binomial coefficient on its
source sheet. -/
theorem rawForwardWord_basis_source
    {N : Nat} (p q : Fin N) (hpq : p.1 ≤ q.1) :
    rawForwardWord p q (rationalPureBasis p) =
      (forwardScalar p q : ℚ) • rationalPureBasis q := by
  funext r
  by_cases hrq : r = q
  · subst r
    simp [rawForwardWord, diagonalLefschetzQ, sheetProjectorQ,
      rationalPureBasis]
    rw [gst_forward_scalar_receipt p q hpq]
    norm_num
  · simp [rawForwardWord, diagonalLefschetzQ, sheetProjectorQ,
      rationalPureBasis, hrq]

/-- The raw forward word kills every other pure source sheet because the first
factor is the exact source projector. -/
theorem rawForwardWord_basis_other
    {N : Nat} (p q r : Fin N) (hrp : r ≠ p) :
    rawForwardWord p q (rationalPureBasis r) = 0 := by
  simp [rawForwardWord, sheetProjectorQ_basis_other p r hrp]

/-- Normalized forward GST word. -/
noncomputable def forwardArsenalWord
    {N : Nat} (p q : Fin N) : Module.End ℚ (RationalPureWindow N) :=
  (forwardScalar p q : ℚ)⁻¹ • rawForwardWord p q

/-- **FORWARD MATRIX UNIT IS AN ACTUAL GST OPERATOR WORD.** -/
theorem forwardArsenalWord_eq_matrixUnit
    {N : Nat} (p q : Fin N) (hpq : p.1 ≤ q.1) :
    forwardArsenalWord p q = pureMatrixUnit p q := by
  apply LinearMap.ext
  intro a
  rw [rationalPureWindow_eq_sum_basis a]
  simp only [map_sum, map_smul]
  apply Finset.sum_congr rfl
  intro r _
  by_cases hrp : r = p
  · subst r
    rw [rawForwardWord_basis_source p q hpq]
    have hscalar : (forwardScalar p q : ℚ) ≠ 0 := by
      exact_mod_cast (ne_of_gt (forwardScalar_pos p q))
    simp [forwardArsenalWord, pureMatrixUnit_basis_source, hscalar]
  · rw [rawForwardWord_basis_other p q r hrp]
    simp [forwardArsenalWord, pureMatrixUnit_basis_other p q r hrp]

/-- Poincare conjugate of an operator on a finite pure window. -/
noncomputable def poincareConjugate
    {N : Nat} (T : Module.End ℚ (RationalPureWindow N)) :
    Module.End ℚ (RationalPureWindow N) :=
  (poincareReverseQ N).toLinearMap.comp
    (T.comp (poincareReverseQ N).toLinearMap)

/-- Poincare conjugation turns the mirrored matrix unit back into the original
matrix unit. -/
theorem poincareConjugate_matrixUnit
    {N : Nat} (p q : Fin N) :
    poincareConjugate
        (pureMatrixUnit (pureMirror p) (pureMirror q)) =
      pureMatrixUnit p q := by
  apply LinearMap.ext
  intro a
  rw [rationalPureWindow_eq_sum_basis a]
  simp only [map_sum, map_smul]
  apply Finset.sum_congr rfl
  intro r _
  by_cases hrp : r = p
  · subst r
    simp [poincareConjugate]
  · have hmirror : pureMirror r ≠ pureMirror p := by
      intro h
      apply hrp
      simpa using congrArg pureMirror h
    simp [poincareConjugate, pureMatrixUnit_basis_other, hrp, hmirror]

/-- Backward GST word: mirror, perform the now-forward transfer, mirror back. -/
noncomputable def backwardArsenalWord
    {N : Nat} (p q : Fin N) : Module.End ℚ (RationalPureWindow N) :=
  poincareConjugate
    (forwardArsenalWord (pureMirror p) (pureMirror q))

/-- **BACKWARD MATRIX UNIT IS AN ACTUAL GST OPERATOR WORD.** -/
theorem backwardArsenalWord_eq_matrixUnit
    {N : Nat} (p q : Fin N) (hqp : q.1 ≤ p.1) :
    backwardArsenalWord p q = pureMatrixUnit p q := by
  have hforward : (pureMirror p).1 ≤ (pureMirror q).1 :=
    mirror_turns_backward_forward p q hqp
  rw [backwardArsenalWord,
    forwardArsenalWord_eq_matrixUnit (pureMirror p) (pureMirror q) hforward]
  exact poincareConjugate_matrixUnit p q

/-- Every finite matrix unit is generated by the actual GST
projector/Lefschetz/Poincare operator algebra. -/
theorem matrixUnit_generated_by_GST_arsenal
    {N : Nat} (p q : Fin N) :
    (p.1 ≤ q.1 ∧ forwardArsenalWord p q = pureMatrixUnit p q)
    ∨ (q.1 ≤ p.1 ∧ backwardArsenalWord p q = pureMatrixUnit p q) := by
  by_cases hpq : p.1 ≤ q.1
  · exact Or.inl ⟨hpq, forwardArsenalWord_eq_matrixUnit p q hpq⟩
  · have hqp : q.1 ≤ p.1 := by omega
    exact Or.inr ⟨hqp, backwardArsenalWord_eq_matrixUnit p q hqp⟩

/-- Explicit full-arsenal generation crown. -/
theorem explicit_arsenal_generation_crown :
    ∀ N (p q : Fin N),
      (p.1 ≤ q.1 ∧ forwardArsenalWord p q = pureMatrixUnit p q)
      ∨ (q.1 ≤ p.1 ∧ backwardArsenalWord p q = pureMatrixUnit p q) :=
  fun _ p q => matrixUnit_generated_by_GST_arsenal p q

#check diagonalLefschetzQ
#check poincareReverseQ
#check rawForwardWord
#check forwardArsenalWord
#check forwardArsenalWord_eq_matrixUnit
#check backwardArsenalWord
#check backwardArsenalWord_eq_matrixUnit
#check matrixUnit_generated_by_GST_arsenal

#print axioms forwardArsenalWord_eq_matrixUnit
#print axioms backwardArsenalWord_eq_matrixUnit
#print axioms matrixUnit_generated_by_GST_arsenal
#print axioms explicit_arsenal_generation_crown

end GSTClassicalHodgeExplicitArsenalGeneration
