import GSTClassicalHodgeGradedGeometricProgramOrbit
import GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra
import GSTClassicalHodgeExactClayStatement

/-!
# GST CLASSICAL HODGE — GRADED FULL-CORRESPONDENCE PROGRAM ORBIT

The previous graded program algebra combined principal cuts with projective
self-map words.  The realized closed-correspondence arena is strictly larger:
one source point may have several correspondence images, and the new
expression algebra is closed under noncommutative composition.

This file fuses the two geometries.

A graded full-correspondence program is generated by:

* identity;
* any genuine realized finite closed-correspondence expression inside one
  codimension;
* the genuine principal-cut successor p -> p+1;
* rational scaling and addition;
* ordered composition across matching weights.

Every constructor carries an exact native/cohomology commuting square.  Thus
the entire program orbit of the codimension-zero fundamental cycle is genuinely
algebraic by construction.  The exact Hodge conjecture is reduced to one
noncircular geometric generation statement: every rational Hodge state lies in
this verified graded correspondence orbit.
-/

set_option maxHeartbeats 120000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeGradedCorrespondenceProgramOrbit

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeCodimensionZeroFundamentalCycle
open GSTClassicalHodgeGradedGeometricProgramOrbit
open GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra
open GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra.RealizedCorrespondenceExpr
open GSTClassicalHodgeExactClayStatement

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}

/-- Full graded program language generated by actual finite closed
correspondences and genuine principal cuts. -/
inductive GradedCorrespondenceProgram
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V) : Nat → Nat → Type
  | id (p : Nat) : GradedCorrespondenceProgram V H p p
  | correspondence {p : Nat}
      (E : RealizedCorrespondenceExpr V H p) :
      GradedCorrespondenceProgram V H p p
  | cut (p : Nat) : GradedCorrespondenceProgram V H p (p + 1)
  | add {p q : Nat}
      (A B : GradedCorrespondenceProgram V H p q) :
      GradedCorrespondenceProgram V H p q
  | smul {p q : Nat}
      (a : ℚ) (A : GradedCorrespondenceProgram V H p q) :
      GradedCorrespondenceProgram V H p q
  | comp {p q r : Nat}
      (A : GradedCorrespondenceProgram V H p q)
      (B : GradedCorrespondenceProgram V H q r) :
      GradedCorrespondenceProgram V H p r

namespace GradedCorrespondenceProgram

/-- Interpret every full program as one exact graded cycle-class-natural pair. -/
noncomputable def toPair
    (G : GeometricCycleClassSpine V H) :
    {p q : Nat} → GradedCorrespondenceProgram V H p q →
      GSTClassicalHodgeCrossWeightNativePropagation.GradedCycleClassOperatorPair
        V H p q
  | _, _, .id p =>
      GradedCycleClassOperatorPair.idPair V H p
  | _, _, .correspondence E =>
      { cycleOperator := E.cycleOperator
        cohomologyOperator := E.cohomologyOperator
        cycleClass_natural := fun Z => E.cycleClass_natural Z }
  | _, _, .cut p => G.principalCutPair p
  | _, _, .add A B =>
      GradedCycleClassOperatorPair.addPair (toPair G A) (toPair G B)
  | _, _, .smul a A =>
      GradedCycleClassOperatorPair.smulPair a (toPair G A)
  | _, _, .comp A B =>
      GradedCycleClassOperatorPair.compPair (toPair G A) (toPair G B)

/-- Native execution. -/
noncomputable def cycleEval
    (G : GeometricCycleClassSpine V H)
    {p q : Nat}
    (P : GradedCorrespondenceProgram V H p q) :
    codimensionCycles V.X p →ₗ[ℚ] codimensionCycles V.X q :=
  (P.toPair G).cycleOperator

/-- Rational cohomology execution. -/
noncomputable def cohomologyEval
    (G : GeometricCycleClassSpine V H)
    {p q : Nat}
    (P : GradedCorrespondenceProgram V H p q) :
    RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ]
      RationalSingularCohomology H.analytification (2 * q) :=
  (P.toPair G).cohomologyOperator

/-- Master naturality theorem for the enlarged program algebra. -/
theorem cycleClass_cycleEval
    (G : GeometricCycleClassSpine V H)
    {p q : Nat}
    (P : GradedCorrespondenceProgram V H p q)
    (Z : codimensionCycles V.X p) :
    H.cycleClass q (P.cycleEval G Z) =
      P.cohomologyEval G (H.cycleClass p Z) := by
  exact (P.toPair G).cycleClass_natural Z

/-- Every full-program image of an actual cycle class is again an actual cycle
class in the target weight. -/
theorem cohomologyEval_mem_cycleClass_range
    (G : GeometricCycleClassSpine V H)
    {p q : Nat}
    (P : GradedCorrespondenceProgram V H p q)
    (Z : codimensionCycles V.X p) :
    P.cohomologyEval G (H.cycleClass p Z) ∈
      LinearMap.range (H.cycleClass q) := by
  exact ⟨P.cycleEval G Z, P.cycleClass_cycleEval G Z⟩

end GradedCorrespondenceProgram

/-- Canonical algebraic origin. -/
noncomputable def correspondenceGeometricOriginClass
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V) :
    RationalSingularCohomology H.analytification 0 :=
  H.cycleClass 0 (codimensionZeroFundamentalCycle V)

/-- States reached from the canonical origin by one full graded program. -/
def fullCorrespondenceOrbitSet
    (G : GeometricCycleClassSpine V H)
    (q : Nat) :
    Set (RationalSingularCohomology H.analytification (2 * q)) :=
  {alpha | ∃ P : GradedCorrespondenceProgram V H 0 q,
      alpha = P.cohomologyEval G
        (correspondenceGeometricOriginClass V H)}

/-- Rational hull of the complete verified full-correspondence orbit. -/
noncomputable def fullCorrespondenceOrbitSubspace
    (G : GeometricCycleClassSpine V H)
    (q : Nat) :
    Submodule ℚ (RationalSingularCohomology H.analytification (2 * q)) :=
  Submodule.span ℚ (fullCorrespondenceOrbitSet G q)

/-- Every orbit generator is a genuine algebraic cycle class. -/
theorem fullOrbitGenerator_mem_cycleClass_range
    (G : GeometricCycleClassSpine V H)
    (q : Nat)
    {alpha : RationalSingularCohomology H.analytification (2 * q)}
    (halpha : alpha ∈ fullCorrespondenceOrbitSet G q) :
    alpha ∈ LinearMap.range (H.cycleClass q) := by
  rcases halpha with ⟨P, rfl⟩
  exact P.cohomologyEval_mem_cycleClass_range G
    (codimensionZeroFundamentalCycle V)

/-- The entire enlarged orbit remains inside the true cycle-class range. -/
theorem fullCorrespondenceOrbitSubspace_le_cycleClass_range
    (G : GeometricCycleClassSpine V H)
    (q : Nat) :
    fullCorrespondenceOrbitSubspace G q ≤
      LinearMap.range (H.cycleClass q) := by
  apply Submodule.span_le.2
  intro alpha halpha
  exact fullOrbitGenerator_mem_cycleClass_range G q halpha

/-- Exact remaining generation statement in the strongest verified geometric
program language currently present in the repository. -/
def FullCorrespondenceOrbitCyclic
    (G : GeometricCycleClassSpine V H) : Prop :=
  ∀ q : Nat,
    rationalHodgeSubspace (H.hodgeBigrading q) ≤
      fullCorrespondenceOrbitSubspace G q

/-- Full correspondence-orbit cyclicity proves the literal rational Hodge
conjecture. -/
theorem exactHodge_of_fullCorrespondenceOrbitCyclic
    (G : GeometricCycleClassSpine V H)
    (hcyc : FullCorrespondenceOrbitCyclic G) :
    EveryHodgeClassIsRationalAlgebraic H := by
  rw [everyHodgeClassIsRationalAlgebraic_iff_stage2G]
  intro q alpha halpha
  exact fullCorrespondenceOrbitSubspace_le_cycleClass_range G q
    (hcyc q halpha)

/-- Literal finite rational-combination formulation. -/
theorem finiteCombination_of_fullCorrespondenceOrbitCyclic
    (G : GeometricCycleClassSpine V H)
    (hcyc : FullCorrespondenceOrbitCyclic G) :
    EveryHodgeClassIsFiniteRationalCombination H := by
  rw [← rationalAlgebraic_iff_finiteRationalCombination]
  exact exactHodge_of_fullCorrespondenceOrbitCyclic G hcyc

#check GradedCorrespondenceProgram
#check GradedCorrespondenceProgram.toPair
#check GradedCorrespondenceProgram.cycleClass_cycleEval
#check fullCorrespondenceOrbitSubspace
#check fullCorrespondenceOrbitSubspace_le_cycleClass_range
#check FullCorrespondenceOrbitCyclic
#check exactHodge_of_fullCorrespondenceOrbitCyclic
#check finiteCombination_of_fullCorrespondenceOrbitCyclic

#print axioms GradedCorrespondenceProgram.cycleClass_cycleEval
#print axioms fullCorrespondenceOrbitSubspace_le_cycleClass_range
#print axioms exactHodge_of_fullCorrespondenceOrbitCyclic
#print axioms finiteCombination_of_fullCorrespondenceOrbitCyclic

end GSTClassicalHodgeGradedCorrespondenceProgramOrbit
