import GSTClassicalHodgeProjectiveCorrespondenceAlgebra
import GSTClassicalHodgeFiniteClosedCorrespondenceOperator

/-!
# GST CLASSICAL HODGE — CORRESPONDENCE SEMANTIC FIREWALL

There are three mathematically different notions in the Hodge development:

1. an arbitrary rational-linear endomorphism of the native cycle space;
2. an operator lying in the span of transports induced by actual self-maps;
3. an operator induced by an actual finite closed correspondence.

A finite point presentation does **not** separate these notions.  Compactness
of the smooth projective carrier gives such a presentation for the image of
every point atom under every native linear operator.  Consequently a proof
which only manufactures finite point-presentation data has not yet produced
geometric correspondence data.

This file makes that logical boundary explicit.  The presentation predicate is
proved universal, while the self-map-generated and genuine-correspondence
predicates retain their geometric witnesses.  Downstream arguments can import
this file as a semantic firewall against accidentally upgrading finite linear
algebra into projective geometry.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open CategoryTheory
open AlgebraicGeometry

namespace GSTClassicalHodgeCorrespondenceSemanticFirewall

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTNativeCodimensionCyclePresentation
open GSTClassicalHodgeProjectiveCorrespondenceAlgebra
open GSTClassicalHodgeFiniteClosedCorrespondence
open GSTClassicalHodgeFiniteClosedCorrespondenceOperator

variable (V : SmoothProjectiveComplexScheme) (p : Nat)

/-- The ambient rational-linear native operator space. -/
abbrev NativeOperator := Module.End ℚ (codimensionCycles V.X p)

/-- Merely having a finite point presentation on every point atom.

This predicate deliberately records no geometric origin for the operator. -/
def FinitePointPresentable (A : NativeOperator V p) : Prop :=
  ∀ x : CodimensionPoint V.X p,
    ∃ φ : FiniteCodimensionPresentation V.X p,
      realizeFiniteCodimensionPresentation V.X p φ =
        A (codimensionPointCycle V.X p x)

/-- Geometric tier 1: the operator lies in the rational span generated by
actual scheme endomorphisms. -/
def SelfMapGenerated (A : NativeOperator V p) : Prop :=
  A ∈ projectiveCorrespondenceSpan V p

/-- Geometric tier 2: the operator is induced by one actual finite closed
correspondence. -/
def GenuineFiniteCorrespondenceGenerated (A : NativeOperator V p) : Prop :=
  ∃ K : FiniteClosedCorrespondence V,
    A = nativeCorrespondenceOperator K p

/-- **FINITE PRESENTATION IS UNIVERSAL.**
Every rational-linear native operator is finitely point-presentable.  This is
pure compact-support linear algebra and uses no correspondence witness. -/
theorem finitePointPresentable_all
    (A : NativeOperator V p) :
    FinitePointPresentable V p A := by
  intro x
  exact ⟨operatorPointPresentation V p A x,
    operatorPointPresentation_realize V p A x⟩

/-- The presentation predicate therefore carries no discriminatory geometric
content: for an arbitrary native operator it is equivalent to `True`. -/
theorem finitePointPresentable_iff_true
    (A : NativeOperator V p) :
    FinitePointPresentable V p A ↔ True := by
  constructor
  · intro _
    trivial
  · intro _
    exact finitePointPresentable_all V p A

/-- Self-map-generated operators are finitely point-presentable, but the proof
uses only the universal presentation theorem.  The geometric content remains
in the separate `SelfMapGenerated` witness. -/
theorem selfMapGenerated_finitePointPresentable
    (A : NativeOperator V p)
    (_hA : SelfMapGenerated V p A) :
    FinitePointPresentable V p A :=
  finitePointPresentable_all V p A

/-- Operators induced by genuine finite closed correspondences are finitely
point-presentable.  Again, the finite presentation itself is not the geometric
certificate; the existential correspondence witness is. -/
theorem genuineFiniteCorrespondence_finitePointPresentable
    (A : NativeOperator V p)
    (_hA : GenuineFiniteCorrespondenceGenerated V p A) :
    FinitePointPresentable V p A :=
  finitePointPresentable_all V p A

/-- A genuine finite correspondence carries an explicit geometric operator
witness in addition to the automatic finite presentation. -/
theorem nativeCorrespondenceOperator_is_genuine
    (K : FiniteClosedCorrespondence V) :
    GenuineFiniteCorrespondenceGenerated V p
      (nativeCorrespondenceOperator K p) := by
  exact ⟨K, rfl⟩

/-- The native operator of a genuine finite correspondence acts on point atoms
by its actual correspondence-theoretic point image, not merely by an arbitrary
chosen finite presentation. -/
theorem genuineCorrespondence_point_action
    (K : FiniteClosedCorrespondence V)
    (x : CodimensionPoint V.X p) :
    nativeCorrespondenceOperator K p
        (codimensionPointCycle V.X p x) =
      K.nativePointImage p x :=
  nativeCorrespondenceOperator_point K p x

#check FinitePointPresentable
#check SelfMapGenerated
#check GenuineFiniteCorrespondenceGenerated
#check finitePointPresentable_all
#check finitePointPresentable_iff_true
#check selfMapGenerated_finitePointPresentable
#check genuineFiniteCorrespondence_finitePointPresentable
#check nativeCorrespondenceOperator_is_genuine
#check genuineCorrespondence_point_action

#print axioms finitePointPresentable_all
#print axioms finitePointPresentable_iff_true
#print axioms nativeCorrespondenceOperator_is_genuine
#print axioms genuineCorrespondence_point_action

end GSTClassicalHodgeCorrespondenceSemanticFirewall
