import GSTClassicalHodgeFiberedNativeTensorArsenal
import GSTClassicalHodgeNativePointRelationDescent

/-!
# GST coherent native descent

An isolated tensor word can fail to descend even when a coherent collection
does descend. We classify ALL labelled operators by their native columns,
construct nonzero routed lifts for arbitrary label maps, and determine exactly
when a finite tensor block descends. A second classification separates native
descent from descent through the actual cycle-class map.

The finite-block section alone uses a finite label type. The general column,
routing, and cycle-class laws allow arbitrarily many labels. No Hodge
completeness, chosen target representative, or strict carrier is assumed.
-/

noncomputable section

open AlgebraicGeometry
open scoped BigOperators
open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTNativeCodimensionCyclePresentation
open GSTCompactNativeCyclePresentation
open GSTClassicalHodgePointNormalForm
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeFiberedNativePullback
open GSTClassicalHodgeFiberedNativeOperatorLift
open GSTClassicalHodgeFiberedNativeTensorArsenal
open GSTClassicalHodgePointKernelOperatorLift
open GSTClassicalHodgeNativePointRelationDescent

namespace GSTClassicalHodgeCoherentNativeDescent

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V} {p : Nat}

/-- Reuse the already-compiled exact native coefficient normal form. -/
def finiteNativeEquiv (V : SmoothProjectiveComplexScheme) (p : Nat) :
    FiniteCodimensionPresentation V.X p ≃ₗ[ℚ] codimensionCycles V.X p := by
  letI : CompactSpace V.X := smoothProjectiveCompactSpace V
  exact compactCyclePresentationLinearEquiv V.X p

@[simp] theorem finiteNativeEquiv_single
    (x : CodimensionPoint V.X p) (q : ℚ) :
    finiteNativeEquiv V p (Finsupp.single x q) =
      q • codimensionPointCycle V.X p x :=
  realizeFiniteCodimensionPresentation_single V.X p x q

/-- Attach a fixed label to a genuine cycle using its exact native point
coefficients. This is a section of native projection, not of cycle class. -/
def nativeSection (i : ClassicalHodgeBasisIndex V H p) :
    codimensionCycles V.X p →ₗ[ℚ] FiberedNativeAddress V H p :=
  (labelPresentation i).comp (finiteNativeEquiv V p).symm.toLinearMap

@[simp] theorem nativeSection_point
    (i : ClassicalHodgeBasisIndex V H p) (x : CodimensionPoint V.X p) :
    nativeSection i (codimensionPointCycle V.X p x) = atom V H p i x := by
  have hx : (finiteNativeEquiv V p).symm (codimensionPointCycle V.X p x) =
      Finsupp.single x 1 := by
    apply (finiteNativeEquiv V p).injective
    simp
  simp [nativeSection, hx]

@[simp] theorem toNativeCycle_nativeSection
    (i : ClassicalHodgeBasisIndex V H p) (Z : codimensionCycles V.X p) :
    toNativeCycle V H p (nativeSection i Z) = Z := by
  change toNativeCycle V H p
    (labelPresentation i ((finiteNativeEquiv V p).symm Z)) = Z
  rw [toNativeCycle_labelPresentation]
  exact (finiteNativeEquiv V p).apply_symm_apply Z

/-- Extract the label information lost by the genuine native projection. -/
def nativeResidual (i₀ : ClassicalHodgeBasisIndex V H p) :
    Module.End ℚ (FiberedNativeAddress V H p) :=
  LinearMap.id - (nativeSection i₀).comp (toNativeCycle V H p)

@[simp] theorem nativeResidual_atom
    (i₀ i : ClassicalHodgeBasisIndex V H p) (x : CodimensionPoint V.X p) :
    nativeResidual i₀ (atom V H p i x) = sheetDifference i i₀ x := by
  simp [nativeResidual, sheetDifference]

@[simp] theorem nativeResidual_nativeFace
    (i₀ : ClassicalHodgeBasisIndex V H p) (Φ : FiberedNativeAddress V H p) :
    toNativeCycle V H p (nativeResidual i₀ Φ) = 0 := by
  simp [nativeResidual]

theorem nativeResidual_eq_self_iff
    (i₀ : ClassicalHodgeBasisIndex V H p) (Φ : FiberedNativeAddress V H p) :
    nativeResidual i₀ Φ = Φ ↔ toNativeCycle V H p Φ = 0 := by
  constructor
  · intro h
    rw [← h]
    exact nativeResidual_nativeFace i₀ Φ
  · intro h
    simp [nativeResidual, h]

/-- **NATIVE KERNEL GENERATION.** All label ambiguity is generated by
differences between two labels attached to the SAME genuine native point. -/
theorem nativeKernel_eq_sheetDifferenceSpan
    (i₀ : ClassicalHodgeBasisIndex V H p) :
    (toNativeCycle V H p).ker = Submodule.span ℚ
      (Set.range (fun ix : FiberedNativeAtom V H p => sheetDifference ix.1 i₀ ix.2)) := by
  apply le_antisymm
  · intro Φ hΦ
    have hfix := (nativeResidual_eq_self_iff i₀ Φ).mpr hΦ
    have hsum : nativeResidual i₀ Φ =
        Φ.sum (fun ix q => q • sheetDifference ix.1 i₀ ix.2) := by
      have hΦsum : Φ = Φ.sum (fun ix q => q • atom V H p ix.1 ix.2) := by
        classical
        simp [atom]
      calc
        nativeResidual i₀ Φ =
            nativeResidual i₀ (Φ.sum (fun ix q => q • atom V H p ix.1 ix.2)) :=
          congrArg _ hΦsum
        _ = _ := by
          rw [map_finsuppSum]
          simp only [map_smul, nativeResidual_atom]
    rw [← hfix, hsum]
    apply Submodule.sum_mem
    intro ix _
    apply Submodule.smul_mem
    exact Submodule.subset_span (Set.mem_range_self ix)
  · apply Submodule.span_le.mpr
    rintro _ ⟨ix, rfl⟩
    exact sheetDifference_nativeFace ix.1 i₀ ix.2

/-- Atom tests determine any linear map out of the GST labelled universe. -/
theorem labelledLinearMap_ext
    {M : Type*} [AddCommGroup M] [Module ℚ M]
    {F G : FiberedNativeAddress V H p →ₗ[ℚ] M}
    (h : ∀ i x, F (atom V H p i x) = G (atom V H p i x)) : F = G := by
  refine LinearMap.ext fun Φ => ?_
  classical
  induction Φ using Finsupp.induction_linear with
  | zero => simp
  | add a b ha hb => simp [ha, hb]
  | single ix q =>
    rw [show Finsupp.single ix q = q • atom V H p ix.1 ix.2 by simp [atom]]
    simp only [map_smul, h]

theorem nativeLinearMap_ext
    {M : Type*} [AddCommGroup M] [Module ℚ M]
    {F G : codimensionCycles V.X p →ₗ[ℚ] M}
    (h : ∀ x, F (codimensionPointCycle V.X p x) =
      G (codimensionPointCycle V.X p x)) : F = G := by
  have hz : F - G = 0 := nativeLinearMap_eq_zero_of_points V p (F - G)
    (by intro x; simp [h x])
  exact sub_eq_zero.mp hz

/-- Column i is the genuine native output of an operator on sheet i. -/
def nativeColumn (i : ClassicalHodgeBasisIndex V H p)
    (U : Module.End ℚ (FiberedNativeAddress V H p)) :
    Module.End ℚ (codimensionCycles V.X p) :=
  (toNativeCycle V H p).comp (U.comp (nativeSection i))

@[simp] theorem nativeColumn_point
    (i : ClassicalHodgeBasisIndex V H p)
    (U : Module.End ℚ (FiberedNativeAddress V H p))
    (x : CodimensionPoint V.X p) :
    nativeColumn i U (codimensionPointCycle V.X p x) =
      toNativeCycle V H p (U (atom V H p i x)) := by
  simp [nativeColumn]

/-- **NATIVE COLUMN LAW.** An arbitrary labelled operator has native action B
exactly when every source sheet has the same actual native column B. -/
theorem native_factorization_iff_columns
    (U : Module.End ℚ (FiberedNativeAddress V H p))
    (B : Module.End ℚ (codimensionCycles V.X p)) :
    (toNativeCycle V H p).comp U = B.comp (toNativeCycle V H p) ↔
      ∀ i : ClassicalHodgeBasisIndex V H p, nativeColumn i U = B := by
  constructor
  · intro h i
    ext Z
    have hz := LinearMap.congr_fun h (nativeSection i Z)
    simp only [nativeColumn]
    rw [← hz]
  · intro h
    apply labelledLinearMap_ext
    intro i x
    have hx := LinearMap.congr_fun (h i) (codimensionPointCycle V.X p x)
    simpa using hx

/-- **COHERENT DESCENT CLASSIFICATION.** Equality of native columns is
sufficient and necessary. In particular, no all-target realization is hidden
in the descent condition, and the descended native action is unique. -/
theorem native_descent_iff_constant_columns
    (i₀ : ClassicalHodgeBasisIndex V H p)
    (U : Module.End ℚ (FiberedNativeAddress V H p)) :
    (∃ B : Module.End ℚ (codimensionCycles V.X p),
      (toNativeCycle V H p).comp U = B.comp (toNativeCycle V H p)) ↔
      ∀ i : ClassicalHodgeBasisIndex V H p, nativeColumn i U = nativeColumn i₀ U := by
  constructor
  · rintro ⟨B, hB⟩
    have h := (native_factorization_iff_columns U B).mp hB
    intro i
    exact (h i).trans (h i₀).symm
  · intro h
    exact ⟨nativeColumn i₀ U, (native_factorization_iff_columns U _).mpr h⟩

/-- The old sheet-difference obstruction is now an exact test for every
labelled operator, rather than only for a single tensor word. -/
theorem native_descent_iff_sheetDifferences
    (i₀ : ClassicalHodgeBasisIndex V H p)
    (U : Module.End ℚ (FiberedNativeAddress V H p)) :
    (∃ B : Module.End ℚ (codimensionCycles V.X p),
      (toNativeCycle V H p).comp U = B.comp (toNativeCycle V H p)) ↔
      ∀ i x, toNativeCycle V H p (U (sheetDifference i i₀ x)) = 0 := by
  rw [native_descent_iff_constant_columns i₀ U]
  constructor
  · intro h i x
    have hx := LinearMap.congr_fun (h i) (codimensionPointCycle V.X p x)
    simpa [sheetDifference, sub_eq_zero] using hx
  · intro h i
    apply nativeLinearMap_ext
    intro x
    simpa [sheetDifference, sub_eq_zero] using h i x

theorem native_descent_unique
    (i₀ : ClassicalHodgeBasisIndex V H p)
    (U : Module.End ℚ (FiberedNativeAddress V H p))
    (B C : Module.End ℚ (codimensionCycles V.X p))
    (hB : (toNativeCycle V H p).comp U = B.comp (toNativeCycle V H p))
    (hC : (toNativeCycle V H p).comp U = C.comp (toNativeCycle V H p)) : B = C := by
  exact ((native_factorization_iff_columns U B).mp hB i₀).symm.trans
    ((native_factorization_iff_columns U C).mp hC i₀)

/-- Descent survives composition, with the exact native composition law. -/
theorem native_descent_comp
    (U W : Module.End ℚ (FiberedNativeAddress V H p))
    (B C : Module.End ℚ (codimensionCycles V.X p))
    (hU : (toNativeCycle V H p).comp U = B.comp (toNativeCycle V H p))
    (hW : (toNativeCycle V H p).comp W = C.comp (toNativeCycle V H p)) :
    (toNativeCycle V H p).comp (W.comp U) =
      (C.comp B).comp (toNativeCycle V H p) := by
  refine LinearMap.ext fun Φ => ?_
  have hu := LinearMap.congr_fun hU Φ
  have hw := LinearMap.congr_fun hW (U Φ)
  simpa only [LinearMap.comp_apply, hu] using hw

/-- A total label routing can accompany ANY native operator. Unlike a
single selected-source matrix unit, it processes every source sheet. -/
def routedNativeOperator
    (ρ : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p)
    (A : Module.End ℚ (codimensionCycles V.X p)) :
    Module.End ℚ (FiberedNativeAddress V H p) where
  toFun Φ := Φ.sum (fun ix q => q • nativeSection (ρ ix.1)
    (A (codimensionPointCycle V.X p ix.2)))
  map_add' := by
    intro Φ Ψ
    classical
    simp [add_smul]
  map_smul' := by
    intro q Φ
    classical
    simp [smul_smul]

@[simp] theorem routedNativeOperator_atom
    (ρ : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p)
    (A : Module.End ℚ (codimensionCycles V.X p))
    (i : ClassicalHodgeBasisIndex V H p) (x : CodimensionPoint V.X p) :
    routedNativeOperator ρ A (atom V H p i x) =
      nativeSection (ρ i) (A (codimensionPointCycle V.X p x)) := by
  classical
  simp [routedNativeOperator, atom]

/-- **UNRESTRICTED ROUTING LAW.** Every total routing has exactly native
action A; injectivity, surjectivity, or finiteness of the routing is unnecessary. -/
theorem routedNativeOperator_descends
    (ρ : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p)
    (A : Module.End ℚ (codimensionCycles V.X p)) :
    (toNativeCycle V H p).comp (routedNativeOperator ρ A) =
      A.comp (toNativeCycle V H p) := by
  apply (native_factorization_iff_columns _ A).mpr
  intro i
  apply nativeLinearMap_ext
  intro x
  simp

theorem routedNativeOperator_nativeSection
    (ρ : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p)
    (A : Module.End ℚ (codimensionCycles V.X p))
    (i : ClassicalHodgeBasisIndex V H p) (Z : codimensionCycles V.X p) :
    routedNativeOperator ρ A (nativeSection i Z) = nativeSection (ρ i) (A Z) := by
  have h : (routedNativeOperator ρ A).comp (nativeSection i) =
      (nativeSection (ρ i)).comp A := by
    apply nativeLinearMap_ext
    intro x
    simp
  exact LinearMap.congr_fun h Z

/-- Routing and native transformation compose strictly on the whole labelled
universe, not merely after projection. -/
theorem routedNativeOperator_comp
    (ρ τ : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p)
    (A B : Module.End ℚ (codimensionCycles V.X p)) :
    (routedNativeOperator τ B).comp (routedNativeOperator ρ A) =
      routedNativeOperator (τ ∘ ρ) (B.comp A) := by
  apply labelledLinearMap_ext
  intro i x
  simp [routedNativeOperator_nativeSection, Function.comp_def]

theorem routedNativeOperator_id :
    routedNativeOperator (V := V) (H := H) (p := p) id LinearMap.id =
      LinearMap.id := by
  apply labelledLinearMap_ext
  intro i x
  simp

/-- Routing cannot annihilate a nonzero native operator, even when it sends
every source label to one target label. This supplies nontrivial coherent
descenders without requiring any multiplicity basis cycle. -/
theorem routedNativeOperator_eq_zero_iff
    (i₀ : ClassicalHodgeBasisIndex V H p)
    (ρ : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p)
    (A : Module.End ℚ (codimensionCycles V.X p)) :
    routedNativeOperator ρ A = 0 ↔ A = 0 := by
  constructor
  · intro h
    have hc := (native_factorization_iff_columns (routedNativeOperator ρ A) A).mp
      (routedNativeOperator_descends ρ A) i₀
    have hz : nativeColumn i₀ (routedNativeOperator ρ A) = 0 := by
      simp [h, nativeColumn]
    exact hc.symm.trans hz
  · rintro rfl
    apply labelledLinearMap_ext
    intro i x
    simp

/-- **ALL COHERENT LIFTS.** Every labelled realization of native action A
is one explicitly constructed routed lift plus a native-invisible operator.
This classifies the complete freedom in the lift, including cancellations
between tensor words which cannot descend separately. -/
theorem native_lift_normal_form_iff
    (ρ : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p)
    (A : Module.End ℚ (codimensionCycles V.X p))
    (U : Module.End ℚ (FiberedNativeAddress V H p)) :
    (toNativeCycle V H p).comp U = A.comp (toNativeCycle V H p) ↔
      ∃ W : Module.End ℚ (FiberedNativeAddress V H p),
        (toNativeCycle V H p).comp W = 0 ∧ U = routedNativeOperator ρ A + W := by
  constructor
  · intro hU
    refine ⟨U - routedNativeOperator ρ A, ?_, ?_⟩
    · refine LinearMap.ext fun Φ => ?_
      have hu := LinearMap.congr_fun hU Φ
      have hr := LinearMap.congr_fun (routedNativeOperator_descends ρ A) Φ
      change toNativeCycle V H p (U Φ - routedNativeOperator ρ A Φ) = 0
      rw [map_sub]
      simpa only [LinearMap.comp_apply] using sub_eq_zero.mpr (hu.trans hr.symm)
    · abel
  · rintro ⟨W, hW, rfl⟩
    refine LinearMap.ext fun Φ => ?_
    have hw := LinearMap.congr_fun hW Φ
    have hr := LinearMap.congr_fun (routedNativeOperator_descends ρ A) Φ
    change toNativeCycle V H p (routedNativeOperator ρ A Φ + W Φ) =
      A (toNativeCycle V H p Φ)
    rw [map_add]
    simpa only [LinearMap.comp_apply, LinearMap.zero_apply, hw, add_zero] using hr

/-- Label recoordination on either side preserves the exact native action.
The statement also allows nonbijective routing: its proof never uses an
inverse chart, a target basis representative, or a class-surjectivity premise. -/
theorem native_descent_routing_invariant
    (ρ τ : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p)
    (U : Module.End ℚ (FiberedNativeAddress V H p))
    (A : Module.End ℚ (codimensionCycles V.X p))
    (hU : (toNativeCycle V H p).comp U = A.comp (toNativeCycle V H p)) :
    (toNativeCycle V H p).comp
        ((routedNativeOperator τ LinearMap.id).comp
          (U.comp (routedNativeOperator ρ LinearMap.id))) =
      A.comp (toNativeCycle V H p) := by
  have hpre := native_descent_comp (routedNativeOperator ρ LinearMap.id) U
    LinearMap.id A (routedNativeOperator_descends ρ LinearMap.id) hU
  have hpost := native_descent_comp (U.comp (routedNativeOperator ρ LinearMap.id))
    (routedNativeOperator τ LinearMap.id) (A.comp LinearMap.id) LinearMap.id
    hpre (routedNativeOperator_descends τ LinearMap.id)
  simpa using hpost

/-- Target-label cancellation can remove the native obstruction even when
each individual selected-source tensor word fails to descend. -/
theorem tensorTargetCancellation_nativeFace
    (i j k : ClassicalHodgeBasisIndex V H p)
    (A : Module.End ℚ (codimensionCycles V.X p)) :
    (toNativeCycle V H p).comp (tensorWord i j A - tensorWord i k A) = 0 := by
  apply labelledLinearMap_ext
  intro l x
  by_cases hli : l = i
  · subst l
    simp [tensorWord_nativeFace_atom_source]
  · simp only [LinearMap.comp_apply, LinearMap.sub_apply, map_sub, LinearMap.zero_apply]
    rw [tensorWord_nativeFace, tensorWord_nativeFace]
    simp [multiplicityMatrixUnit_atom_other i j l hli,
      multiplicityMatrixUnit_atom_other i k l hli]

/-! ## Exact cycle-class descent: two independent obstructions -/

/-- **TWO-OBSTRUCTION LAW.** Cycle-class descent requires precisely
(1) column agreement AFTER actual cycle class, and
(2) preservation of cycle-class equivalence by the common native column.
Native columns need not be literally equal. The ambient action is constructed
using native-first finite-relation descent only after these tests pass. -/
theorem cycleClass_descent_iff
    (i₀ : ClassicalHodgeBasisIndex V H p)
    (U : Module.End ℚ (FiberedNativeAddress V H p)) :
    (∃ T : Module.End ℚ (RationalSingularCohomology H.analytification (2*p)),
      ((H.cycleClass p).comp (toNativeCycle V H p)).comp U =
        T.comp ((H.cycleClass p).comp (toNativeCycle V H p))) ↔
      (∀ i : ClassicalHodgeBasisIndex V H p,
        (H.cycleClass p).comp (nativeColumn i U) =
          (H.cycleClass p).comp (nativeColumn i₀ U)) ∧
        NativeClassKernelStable (H.cycleClass p) (nativeColumn i₀ U) := by
  constructor
  · rintro ⟨T, hT⟩
    have hc : ∀ i : ClassicalHodgeBasisIndex V H p,
        (H.cycleClass p).comp (nativeColumn i U) = T.comp (H.cycleClass p) := by
      intro i
      ext Z
      have hz := LinearMap.congr_fun hT (nativeSection i Z)
      simpa [nativeColumn] using hz
    constructor
    · intro i
      exact (hc i).trans (hc i₀).symm
    · intro Z hZ
      have hz := LinearMap.congr_fun (hc i₀) Z
      simpa [hZ] using hz
  · rintro ⟨hc, hk⟩
    let T := nativeAmbientAction (H.cycleClass p) (nativeColumn i₀ U) hk
    refine ⟨T, ?_⟩
    apply labelledLinearMap_ext
    intro i x
    have hcol := LinearMap.congr_fun (hc i) (codimensionPointCycle V.X p x)
    have hext :=
      nativeAmbientAction_natural (H.cycleClass p)
        (nativeColumn i₀ U) hk (codimensionPointCycle V.X p x)
    simpa only [LinearMap.comp_apply, nativeColumn_point, toNativeCycle_atom]
      using hcol.trans hext.symm

/-- Total routing has no label obstruction; its exact remaining obstruction
is the native operator's preservation of cycle-class equivalence. -/
theorem routedNativeOperator_cycleClass_descent_iff
    (i₀ : ClassicalHodgeBasisIndex V H p)
    (ρ : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p)
    (A : Module.End ℚ (codimensionCycles V.X p)) :
    (∃ T : Module.End ℚ (RationalSingularCohomology H.analytification (2*p)),
      ((H.cycleClass p).comp (toNativeCycle V H p)).comp (routedNativeOperator ρ A) =
        T.comp ((H.cycleClass p).comp (toNativeCycle V H p))) ↔
      NativeClassKernelStable (H.cycleClass p) A := by
  have hc := (native_factorization_iff_columns (routedNativeOperator ρ A) A).mp
    (routedNativeOperator_descends ρ A)
  rw [cycleClass_descent_iff i₀]
  simp only [hc]
  simp

/-- The ambient extension may have freedom outside native classes, but its
action on every genuine cycle class is uniquely determined by the labelled
operator. The uniqueness claim stops exactly at the proved range. -/
theorem cycleClass_descent_range_unique
    (i₀ : ClassicalHodgeBasisIndex V H p)
    (U : Module.End ℚ (FiberedNativeAddress V H p))
    (T R : Module.End ℚ (RationalSingularCohomology H.analytification (2*p)))
    (hT : ((H.cycleClass p).comp (toNativeCycle V H p)).comp U =
      T.comp ((H.cycleClass p).comp (toNativeCycle V H p)))
    (hR : ((H.cycleClass p).comp (toNativeCycle V H p)).comp U =
      R.comp ((H.cycleClass p).comp (toNativeCycle V H p)))
    (Z : codimensionCycles V.X p) : T (H.cycleClass p Z) = R (H.cycleClass p Z) := by
  have ht := LinearMap.congr_fun hT (nativeSection i₀ Z)
  have hr := LinearMap.congr_fun hR (nativeSection i₀ Z)
  simpa using ht.symm.trans hr

/-! ## Finite tensor blocks: cancellation is governed by column sums -/

section FiniteBlocks

variable [Fintype (ClassicalHodgeBasisIndex V H p)]

/-- A complete finite block of native tensor words, indexed source then target. -/
def finiteTensorBlock
    (A : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p →
      Module.End ℚ (codimensionCycles V.X p)) :
    Module.End ℚ (FiberedNativeAddress V H p) :=
  ∑ i, ∑ j, tensorWord i j (A i j)

/-- All target-labelled contributions of one source sheet after labels vanish. -/
def tensorColumnSum
    (A : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p →
      Module.End ℚ (codimensionCycles V.X p))
    (i : ClassicalHodgeBasisIndex V H p) :
    Module.End ℚ (codimensionCycles V.X p) := ∑ j, A i j

theorem finiteTensorBlock_nativeFace_atom
    (A : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p →
      Module.End ℚ (codimensionCycles V.X p))
    (i : ClassicalHodgeBasisIndex V H p) (x : CodimensionPoint V.X p) :
    toNativeCycle V H p (finiteTensorBlock A (atom V H p i x)) =
      tensorColumnSum A i (codimensionPointCycle V.X p x) := by
  classical
  change toNativeCycle V H p
    ((∑ k, ∑ j, tensorWord k j (A k j)) (atom V H p i x)) = _
  simp only [LinearMap.sum_apply, map_sum]
  rw [Finset.sum_eq_single i]
  · simp only [tensorWord_nativeFace_atom_source, tensorColumnSum, LinearMap.sum_apply]
  · intro k _ hki
    apply Finset.sum_eq_zero
    intro j _
    rw [tensorWord_nativeFace]
    simp [multiplicityMatrixUnit_atom_other k j i (Ne.symm hki)]
  · intro hi
    exact False.elim (hi (Finset.mem_univ i))

theorem finiteTensorBlock_nativeColumn
    (A : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p →
      Module.End ℚ (codimensionCycles V.X p))
    (i : ClassicalHodgeBasisIndex V H p) :
    nativeColumn i (finiteTensorBlock A) = tensorColumnSum A i := by
  apply nativeLinearMap_ext
  intro x
  rw [nativeColumn_point, finiteTensorBlock_nativeFace_atom]

/-- **COHERENT TENSOR COLUMN-SUM LAW.** Individual tensor summands may fail
to descend, while their complete sum descends exactly when every native
column sum agrees. This is a constructive classification of the allowed sums. -/
theorem finiteTensorBlock_descends_iff
    (i₀ : ClassicalHodgeBasisIndex V H p)
    (A : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p →
      Module.End ℚ (codimensionCycles V.X p)) :
    (∃ B : Module.End ℚ (codimensionCycles V.X p),
      (toNativeCycle V H p).comp (finiteTensorBlock A) =
        B.comp (toNativeCycle V H p)) ↔
      ∀ i, tensorColumnSum A i = tensorColumnSum A i₀ := by
  rw [native_descent_iff_constant_columns i₀]
  simp only [finiteTensorBlock_nativeColumn]

/-- The cycle-class version allows column discrepancies invisible to class,
but still requires preservation of the native class kernel. -/
theorem finiteTensorBlock_cycleClass_descent_iff
    (i₀ : ClassicalHodgeBasisIndex V H p)
    (A : ClassicalHodgeBasisIndex V H p → ClassicalHodgeBasisIndex V H p →
      Module.End ℚ (codimensionCycles V.X p)) :
    (∃ T : Module.End ℚ (RationalSingularCohomology H.analytification (2*p)),
      ((H.cycleClass p).comp (toNativeCycle V H p)).comp (finiteTensorBlock A) =
        T.comp ((H.cycleClass p).comp (toNativeCycle V H p))) ↔
      (∀ i, (H.cycleClass p).comp (tensorColumnSum A i) =
        (H.cycleClass p).comp (tensorColumnSum A i₀)) ∧
        NativeClassKernelStable (H.cycleClass p) (tensorColumnSum A i₀) := by
  rw [cycleClass_descent_iff i₀]
  simp only [finiteTensorBlock_nativeColumn]

end FiniteBlocks

#print axioms native_descent_iff_constant_columns
#print axioms nativeKernel_eq_sheetDifferenceSpan
#print axioms native_descent_iff_sheetDifferences
#print axioms native_descent_unique
#print axioms routedNativeOperator_descends
#print axioms routedNativeOperator_comp
#print axioms routedNativeOperator_eq_zero_iff
#print axioms native_lift_normal_form_iff
#print axioms native_descent_routing_invariant
#print axioms tensorTargetCancellation_nativeFace
#print axioms cycleClass_descent_iff
#print axioms cycleClass_descent_range_unique
#print axioms finiteTensorBlock_descends_iff
#print axioms finiteTensorBlock_cycleClass_descent_iff

end GSTClassicalHodgeCoherentNativeDescent
