import GSTClassicalHodgePlaneCompletenessMinimality
import GSTClassicalHodgeOmniverseStrictEventStability
import GSTClassicalHodgeProjectiveTwoGeneratorExternalization

/-!
# GST CLASSICAL HODGE — PRIMITIVE INCIDENCE PLANE COMPLETENESS

The common-class and trace formulations still package a cohomological relation
as an input.  The exact base commit already contains a lower geometric layer:
`StrictlyMaterializedBranch`.  Its witness is not a target algebraicity proof.
It consists of a genuine bi-finite closed correspondence, its Betti kernel,
point fundamental classes, and the low-level incidence primitives, together
with the equality saying that this independently constructed kernel action is
the GST branch action.  The repository has already proved from those
primitives that the action preserves the actual cycle-class range.

This file therefore lowers GST plane completeness one more level.  We require
materialization only for the source-to-target branch events that are actually
used by basis reconstruction, not for every edge of the omniverse.  The Hodge
conclusion is reconstructed directly from range preservation.  No
`BettiRelated`, finite trace, common plane class, separator ghost, target cycle,
or target algebraicity witness is assumed.

The historical ghost-indexed plane packages then become downstream theorems.
The only remaining geometric construction boundary is explicit and local:
materialize the certified source-to-target GST events by the primitive
incidence carrier already defined in the omniverse.
-/

set_option maxHeartbeats 180000000
set_option maxRecDepth 1000000

noncomputable section

open scoped BigOperators
open AlgebraicGeometry

namespace GSTClassicalHodgePrimitiveIncidencePlaneCompleteness

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeRankFreeArsenalIrreducibility
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeSynchronizedDefectOrbit
open GSTClassicalHodgeOmniversalSeparatorGhostCrown
open GSTClassicalHodgeOmniverseCausalBranchPacket
open GSTClassicalHodgeOmniverseStrictRelationRayCompiler
open GSTClassicalHodgeOmniversalGhostBranchClosure
open GSTClassicalHodgeCommonClassPlaneRealization
open GSTClassicalHodgePlaneCompletenessNonCircularity
open GSTClassicalHodgePlaneCompletenessMinimality
open GSTClassicalHodgeOmniverseStrictEventStability
open GSTClassicalHodgeProjectiveTwoGeneratorExternalization

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-! ## 1. Exact primitive-incidence target plane -/

/-- Primitive-incidence realization only for the certified target branches
actually needed from one synchronized seed.

Compared with `SeedTargetStrictRelationCompleteness`, this does not ask for a
finite Betti trace or an assumed `BettiRelated` equation.  The geometric packet
is the lower `StrictlyMaterializedBranch`; preservation of cycle classes has
already been proved from its incidence primitives. -/
def SeedTargetPrimitiveIncidencePlaneCompleteness
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p)) : Prop :=
  ∀ j : ClassicalHodgeBasisIndex V H p,
    ∃ i : HodgeSupportIndex S.hodge,
      HodgeBranchEvent
        (⟨Sector.gstPlus, S.hodge⟩ :
          HodgeBranchNode (V := V) (H := H) (p := p))
        (⟨Sector.gstPlus, hodgeMatrixUnit i.1 j S.hodge⟩ :
          HodgeBranchNode (V := V) (H := H) (p := p))
      ∧ StrictlyMaterializedBranch
        (⟨Sector.gstPlus, S.hodge⟩ :
          HodgeBranchNode (V := V) (H := H) (p := p))
        (⟨Sector.gstPlus, hodgeMatrixUnit i.1 j S.hodge⟩ :
          HodgeBranchNode (V := V) (H := H) (p := p))

/-- A global primitive-event materialization law implies the sharply restricted
seed-target law.  The branch event itself is not postulated: it is generated by
`event_to_arbitrary_target` from the GST omniverse. -/
theorem seedTargetPrimitiveIncidencePlanes_of_eventMaterialization
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (hgeom :
      ∀ {x y : HodgeBranchNode (V := V) (H := H) (p := p)},
        (hodgeBranchGraph (V := V) (H := H) (p := p)).Event x y →
          StrictlyMaterializedBranch x y) :
    SeedTargetPrimitiveIncidencePlaneCompleteness S := by
  intro j
  obtain ⟨i, hevent, _hi⟩ :=
    event_to_arbitrary_target
      (V := V) (H := H)
      S.hodge S.hodge_ne_zero Sector.gstPlus j
  exact ⟨i, hevent, hgeom hevent⟩

/-! ## 2. Direct target-basis realization from primitive incidence -/

/-- The synchronized seed is an algebraic node because its Hodge state is the
cycle class of its actual native cycle. -/
theorem seed_algebraicNode
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p)) :
    AlgebraicNode
      (⟨Sector.gstPlus, S.hodge⟩ :
        HodgeBranchNode (V := V) (H := H) (p := p)) := by
  unfold AlgebraicNode
  exact ⟨S.cycle, S.class_eq⟩

/-- **ONE PRIMITIVE INCIDENCE PLANE -> ONE TARGET BASIS SHEET.**

No trace or common-class equality is needed.  The lower incidence theorem
moves the source cycle-class range through the independently materialized
kernel action.  The GST matrix-unit identity then isolates the target basis
sheet by the nonzero source coordinate. -/
theorem targetBasis_mem_cycleClassRange_of_primitiveIncidencePlanes
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (C : SeedTargetPrimitiveIncidencePlaneCompleteness S)
    (j : ClassicalHodgeBasisIndex V H p) :
    (classicalHodgeBasis V H p j).1 ∈
      LinearMap.range (H.cycleClass p) := by
  obtain ⟨i, _hevent, hmat⟩ := C j
  have htarget :
      AlgebraicNode
        (⟨Sector.gstPlus, hodgeMatrixUnit i.1 j S.hodge⟩ :
          HodgeBranchNode (V := V) (H := H) (p := p)) :=
    strictlyMaterialized_preserves_algebraic hmat (seed_algebraicNode S)
  unfold AlgebraicNode at htarget
  rw [hodgeMatrixUnit_apply] at htarget
  have hi : hodgeCoordinate i.1 S.hodge ≠ 0 := by
    have hsupp :
        i.1 ∈ ((classicalHodgeBasis V H p).repr S.hodge).support := i.2
    exact Finsupp.mem_support_iff.mp hsupp
  have hscaled :=
    (LinearMap.range (H.cycleClass p)).smul_mem
      (hodgeCoordinate i.1 S.hodge)⁻¹ htarget
  simpa [smul_smul, hi] using hscaled

/-- **FIXED-WEIGHT PRIMITIVE-INCIDENCE PLANE COMPLETENESS.**
One real synchronized seed plus primitive incidence materialization of its
certified target branches forces the entire rational Hodge weight into the
true cycle-class range.  This is a direct finite-support basis reconstruction. -/
theorem hodge_weight_of_seedTargetPrimitiveIncidencePlanes
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (C : SeedTargetPrimitiveIncidencePlaneCompleteness S) :
    rationalHodgeSubspace (H.hodgeBigrading p) ≤
      LinearMap.range (H.cycleClass p) := by
  intro alpha halpha
  let alphaH : ClassicalHodgeFiber V H p := ⟨alpha, halpha⟩
  have hbasis :
      ∀ j : ClassicalHodgeBasisIndex V H p,
        (classicalHodgeBasis V H p j).1 ∈
          LinearMap.range (H.cycleClass p) :=
    targetBasis_mem_cycleClassRange_of_primitiveIncidencePlanes S C
  change alphaH.1 ∈ LinearMap.range (H.cycleClass p)
  rw [show alphaH =
      ∑ j ∈ ((classicalHodgeBasis V H p).repr alphaH).support,
        ((classicalHodgeBasis V H p).repr alphaH j) •
          classicalHodgeBasis V H p j by
    exact (classicalHodgeBasis V H p).sum_repr alphaH]
  simp only [Submodule.coe_sum, Submodule.coe_smul_of_tower]
  apply Submodule.sum_mem
  intro j hj
  exact (LinearMap.range (H.cycleClass p)).smul_mem
    ((classicalHodgeBasis V H p).repr alphaH j) (hbasis j)

/-! ## 3. Minimal all-weight primitive plane law -/

/-- The minimal all-weight plane-completeness law at the lowest geometric level
present in the exact base commit.  Only nonzero Hodge weights are constrained,
and only one source-to-target star of the omniverse is materialized in each
such weight. -/
def LiveWeightSeedTargetPrimitiveIncidencePlaneCompleteness : Prop :=
  ∀ q : Nat,
    rationalHodgeSubspace (H.hodgeBigrading q) ≠ ⊥ →
      ∃ S : NativeHodgeOrbitSeed (V := V) (H := H) (p := q),
        SeedTargetPrimitiveIncidencePlaneCompleteness S

/-- **LOWEST-BOUNDARY NONCIRCULAR GST PLANE FINALE.** -/
theorem hodge_of_liveWeightSeedTargetPrimitiveIncidencePlanes
    (C : LiveWeightSeedTargetPrimitiveIncidencePlaneCompleteness
      (V := V) (H := H)) :
    BigradedBettiHodgeStatement V H := by
  intro q alpha halpha
  by_cases hq : rationalHodgeSubspace (H.hodgeBigrading q) = ⊥
  · have hzmem :
        alpha ∈
          (⊥ : Submodule ℚ
            (RationalSingularCohomology H.analytification (2 * q))) := by
      rw [← hq]
      exact halpha
    have hz : alpha = 0 := by
      simpa using hzmem
    subst alpha
    exact LinearMap.zero_mem _
  · obtain ⟨S, hplanes⟩ := C q hq
    exact hodge_weight_of_seedTargetPrimitiveIncidencePlanes S hplanes halpha

/-- A live synchronized source plus global event materialization implies the
minimal primitive plane law.  This strictly factors the older all-event crown
through the smaller source-target star actually consumed by the proof. -/
theorem liveWeightPrimitivePlanes_of_liveSeed_and_eventMaterialization
    (S : LiveWeightNativeSeedExistence (V := V) (H := H))
    (M : ∀ q : Nat,
      ∀ {x y : HodgeBranchNode (V := V) (H := H) (p := q)},
        (hodgeBranchGraph (V := V) (H := H) (p := q)).Event x y →
          StrictlyMaterializedBranch x y) :
    LiveWeightSeedTargetPrimitiveIncidencePlaneCompleteness
      (V := V) (H := H) := by
  intro q hq
  let seed := Classical.choice (S q hq)
  exact ⟨seed, seedTargetPrimitiveIncidencePlanes_of_eventMaterialization seed (M q)⟩

/-- Corresponding all-weight Hodge theorem from the lower incidence boundary. -/
theorem hodge_of_liveSeed_and_eventMaterialization
    (S : LiveWeightNativeSeedExistence (V := V) (H := H))
    (M : ∀ q : Nat,
      ∀ {x y : HodgeBranchNode (V := V) (H := H) (p := q)},
        (hodgeBranchGraph (V := V) (H := H) (p := q)).Event x y →
          StrictlyMaterializedBranch x y) :
    BigradedBettiHodgeStatement V H :=
  hodge_of_liveWeightSeedTargetPrimitiveIncidencePlanes
    (liveWeightPrimitivePlanes_of_liveSeed_and_eventMaterialization S M)

/-! ## 4. Existing GST spine supplies the source side -/

/-- A conserved GST spine already constructs the live native source required by
the new plane law, without a ghost premise.  The construction is the existing
`conservedSpineOrbitSeed`. -/
theorem liveWeightNativeSeedExistence_of_conservedSpine
    (G : GeometricCycleClassSpine V H)
    (D : SpineTowerConservedCharge G) :
    LiveWeightNativeSeedExistence (V := V) (H := H) := by
  intro q hq
  exact ⟨conservedSpineOrbitSeed G D q⟩

/-- The native-mass bridge therefore also supplies the source side internally. -/
theorem liveWeightNativeSeedExistence_of_nativeMass
    (G : GeometricCycleClassSpine V H)
    (M : NativeMassCycleClassBridge V H) :
    LiveWeightNativeSeedExistence (V := V) (H := H) :=
  liveWeightNativeSeedExistence_of_conservedSpine G (M.toConservedCharge G)

/-- **NATIVE-MASS + PRIMITIVE-INCIDENCE GST PLANE FINALE.**
The source-survival premise has disappeared: it is built from the existing
native-mass/spine cosmology.  The only remaining local geometric obligation is
primitive incidence materialization of certified GST branch events. -/
theorem hodge_of_nativeMass_and_eventMaterialization
    (G : GeometricCycleClassSpine V H)
    (N : NativeMassCycleClassBridge V H)
    (M : ∀ q : Nat,
      ∀ {x y : HodgeBranchNode (V := V) (H := H) (p := q)},
        (hodgeBranchGraph (V := V) (H := H) (p := q)).Event x y →
          StrictlyMaterializedBranch x y) :
    BigradedBettiHodgeStatement V H :=
  hodge_of_liveSeed_and_eventMaterialization
    (liveWeightNativeSeedExistence_of_nativeMass G N) M

/-! ## 5. Historical ghost packages are consequences, not foundations -/

/-- Primitive incidence planes imply the old ghost-adaptive common-class plane
package, but only downstream of the direct Hodge reconstruction.  This is the
safe direction of the equivalence proved in the noncircularity module. -/
theorem ghostAdaptiveCommonClassPlaneCompleteness_of_primitiveIncidencePlanes
    (G : GeometricCycleClassSpine V H)
    (C : LiveWeightSeedTargetPrimitiveIncidencePlaneCompleteness
      (V := V) (H := H)) :
    GhostAdaptiveCommonClassPlaneCompleteness G := by
  exact
    (ghostAdaptiveCommonClassPlaneCompleteness_iff_hodge G).2
      (hodge_of_liveWeightSeedTargetPrimitiveIncidencePlanes C)

/-- Primitive incidence planes also make the old ghost-weight source-survival
package a theorem by eliminating the ghost domain. -/
theorem ghostWeightNativeSeedSurvival_of_primitiveIncidencePlanes
    (G : GeometricCycleClassSpine V H)
    (C : LiveWeightSeedTargetPrimitiveIncidencePlaneCompleteness
      (V := V) (H := H)) :
    GhostWeightNativeSeedSurvival G := by
  have hHodge := hodge_of_liveWeightSeedTargetPrimitiveIncidencePlanes C
  have hEmpty := (hodge_iff_no_omniversalSeparatorGhost G).1 hHodge
  intro E
  exact isEmptyElim E

/-- Primitive incidence planes demote the old strict-relation ghost closure to
a derived theorem. -/
theorem ghostWeightPrimitiveStrictClosure_of_primitiveIncidencePlanes
    (G : GeometricCycleClassSpine V H)
    (C : LiveWeightSeedTargetPrimitiveIncidencePlaneCompleteness
      (V := V) (H := H)) :
    GhostWeightPrimitiveStrictClosure G := by
  have hHodge := hodge_of_liveWeightSeedTargetPrimitiveIncidencePlanes C
  have hEmpty := (hodge_iff_no_omniversalSeparatorGhost G).1 hHodge
  intro E
  exact isEmptyElim E

/-- Primitive incidence planes demote the old common-class ghost closure to a
derived theorem as well. -/
theorem ghostWeightPrimitiveCommonClassClosure_of_primitiveIncidencePlanes
    (G : GeometricCycleClassSpine V H)
    (C : LiveWeightSeedTargetPrimitiveIncidencePlaneCompleteness
      (V := V) (H := H)) :
    GhostWeightPrimitiveCommonClassClosure G := by
  have hHodge := hodge_of_liveWeightSeedTargetPrimitiveIncidencePlanes C
  have hEmpty := (hodge_iff_no_omniversalSeparatorGhost G).1 hHodge
  intro E
  exact isEmptyElim E

#check SeedTargetPrimitiveIncidencePlaneCompleteness
#check seedTargetPrimitiveIncidencePlanes_of_eventMaterialization
#check seed_algebraicNode
#check targetBasis_mem_cycleClassRange_of_primitiveIncidencePlanes
#check hodge_weight_of_seedTargetPrimitiveIncidencePlanes
#check LiveWeightSeedTargetPrimitiveIncidencePlaneCompleteness
#check hodge_of_liveWeightSeedTargetPrimitiveIncidencePlanes
#check liveWeightPrimitivePlanes_of_liveSeed_and_eventMaterialization
#check hodge_of_liveSeed_and_eventMaterialization
#check liveWeightNativeSeedExistence_of_conservedSpine
#check liveWeightNativeSeedExistence_of_nativeMass
#check hodge_of_nativeMass_and_eventMaterialization
#check ghostAdaptiveCommonClassPlaneCompleteness_of_primitiveIncidencePlanes
#check ghostWeightNativeSeedSurvival_of_primitiveIncidencePlanes
#check ghostWeightPrimitiveStrictClosure_of_primitiveIncidencePlanes
#check ghostWeightPrimitiveCommonClassClosure_of_primitiveIncidencePlanes

#print axioms targetBasis_mem_cycleClassRange_of_primitiveIncidencePlanes
#print axioms hodge_weight_of_seedTargetPrimitiveIncidencePlanes
#print axioms hodge_of_liveWeightSeedTargetPrimitiveIncidencePlanes
#print axioms hodge_of_nativeMass_and_eventMaterialization
#print axioms ghostAdaptiveCommonClassPlaneCompleteness_of_primitiveIncidencePlanes
#print axioms ghostWeightNativeSeedSurvival_of_primitiveIncidencePlanes
#print axioms ghostWeightPrimitiveStrictClosure_of_primitiveIncidencePlanes
#print axioms ghostWeightPrimitiveCommonClassClosure_of_primitiveIncidencePlanes

end GSTClassicalHodgePrimitiveIncidencePlaneCompleteness
