import GSTClassicalHodgeMinimalPrimitiveSeparatorGhost

/-!
# GST CLASSICAL HODGE — PRIMITIVE GEOMETRIC QUOTIENT

A least-weight separator is invisible to every verified graded geometric
program arriving from a strictly lower Hodge weight.  Instead of recording
those infinitely many vanishing equations separately, quotient the target
ambient cohomology by the entire submodule generated by all such lower-weight
program images.

The detected Hodge sheet survives this quotient.  Thus any Stage-2G failure
produces a canonical nontrivial primitive remainder after *all* lower-weight
projective/principal-cut geometry has been divided out at once.

This construction contains no algebraicity assumption and no abstract
matrix-unit naturality.  The only operators used in the quotient are the
already verified `GradedGeometricProgram`s.
-/

set_option maxHeartbeats 90000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgePrimitiveGeometricQuotient

open GSTProjectiveOverC
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeGradedGeometricProgramOrbit
open GSTClassicalHodgeMinimalPrimitiveSeparatorGhost

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}

/-- All target-weight cohomology states obtained from genuine Hodge states in
strictly smaller weights by verified mixed geometric programs. -/
def lowerGeometricImage
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    Submodule ℚ
      (RationalSingularCohomology H.analytification (2 * p)) :=
  Submodule.span ℚ
    { y | ∃ q : Nat, q < p ∧
      ∃ P : GradedGeometricProgram V q p,
      ∃ alpha : ClassicalHodgeFiber V H q,
        y = P.cohomologyEval G alpha.1 }

/-- Quotient remaining after every verified lower-weight geometric image has
been removed. -/
abbrev PrimitiveGeometricQuotient
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :=
  RationalSingularCohomology H.analytification (2 * p) ⧸
    lowerGeometricImage G p

/-- The detector of a minimal primitive ghost kills the complete lower
geometric image submodule, not merely its generating program states. -/
theorem minimalGhost_lowerGeometricImage_le_ker
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    lowerGeometricImage G M.weight ≤ LinearMap.ker M.separator.detector := by
  apply Submodule.span_le.mpr
  intro y hy
  rcases hy with ⟨q, hq, P, alpha, rfl⟩
  exact M.primitive q hq P alpha

/-- The Hodge basis sheet detected by a minimal primitive ghost cannot already
belong to the full lower-weight geometric image. -/
theorem minimalGhost_basis_not_mem_lowerGeometricImage
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    (classicalHodgeBasis V H M.weight M.sheet).1 ∉
      lowerGeometricImage G M.weight := by
  intro hmem
  have hker := minimalGhost_lowerGeometricImage_le_ker G M hmem
  exact M.separator.detects_basis hker

/-- Consequently the lower geometric image is a proper submodule.  This is the
nontriviality receipt for the primitive quotient. -/
theorem lowerGeometricImage_ne_top
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    lowerGeometricImage G M.weight ≠ ⊤ := by
  intro htop
  apply minimalGhost_basis_not_mem_lowerGeometricImage G M
  rw [htop]
  trivial

/-- Failure of Stage-2G therefore yields a weight and a genuine Hodge basis
sheet which survives after quotienting by *every* verified lower-weight mixed
geometric program image. -/
theorem not_hodge_yields_nontrivial_primitive_geometric_remainder
    (G : GeometricCycleClassSpine V H)
    (hnot : ¬ BigradedBettiHodgeStatement V H) :
    ∃ p : Nat,
    ∃ i : ClassicalHodgeBasisIndex V H p,
      (classicalHodgeBasis V H p i).1 ∉ lowerGeometricImage G p := by
  let M := minimalPrimitiveGhostOfFailure G hnot
  exact ⟨M.weight, M.sheet,
    minimalGhost_basis_not_mem_lowerGeometricImage G M⟩

/-- **PRIMITIVE-QUOTIENT CROWN.**  Every failure leaves a nonzero primitive
geometric remainder after the entire lower-weight projective/cut cosmology is
factored out. -/
theorem primitive_geometric_quotient_crown
    (G : GeometricCycleClassSpine V H)
    (hnot : ¬ BigradedBettiHodgeStatement V H) :
    ∃ M : MinimalPrimitiveGhost G,
      lowerGeometricImage G M.weight ≠ ⊤ ∧
      (classicalHodgeBasis V H M.weight M.sheet).1 ∉
        lowerGeometricImage G M.weight := by
  let M := minimalPrimitiveGhostOfFailure G hnot
  exact ⟨M,
    lowerGeometricImage_ne_top G M,
    minimalGhost_basis_not_mem_lowerGeometricImage G M⟩

#check lowerGeometricImage
#check PrimitiveGeometricQuotient
#check minimalGhost_lowerGeometricImage_le_ker
#check minimalGhost_basis_not_mem_lowerGeometricImage
#check lowerGeometricImage_ne_top
#check not_hodge_yields_nontrivial_primitive_geometric_remainder
#check primitive_geometric_quotient_crown

#print axioms minimalGhost_lowerGeometricImage_le_ker
#print axioms minimalGhost_basis_not_mem_lowerGeometricImage
#print axioms primitive_geometric_quotient_crown

end GSTClassicalHodgePrimitiveGeometricQuotient
