import GSTClassicalHodgeGenuineCycleClassGeometry
import GSTClassicalHodgeProjectiveTomographyReadout
import GSTClassicalHodgeProjectiveVisibilitySeparation
import GSTClassicalHodgeTomographyVisibilityCrown
import GSTClassicalHodgeGenuineSemanticClosure

/-!
# GST CLASSICAL HODGE — TWO-BURST CLOSURE RECEIPT

Compiler receipt for the complete genuine cycle-class / projective tomography
upgrade.  This file intentionally contains no new mathematics; it is the
single CI surface handed to the parallel Lean repair lane.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

open AlgebraicGeometry

open GSTClassicalHodgeGenuineCycleClassGeometry
open GSTClassicalHodgeProjectiveTomographyReadout
open GSTClassicalHodgeProjectiveVisibilitySeparation
open GSTClassicalHodgeTomographyVisibilityCrown
open GSTClassicalHodgeGenuineSemanticClosure

#check GSTClassicalHodgeGenuineCycleClassGeometry.ProjectiveOrbitIrreducibility
#check GSTClassicalHodgeGenuineCycleClassGeometry.GenuineCycleClassGeometry
#check GSTClassicalHodgeGenuineCycleClassGeometry.GenuineCycleClassGeometry.point_cycleClass_ne_zero
#check GSTClassicalHodgeGenuineCycleClassGeometry.GenuineCycleClassGeometry.not_nonempty_zeroCycleClassData
#check GSTClassicalHodgeProjectiveTomographyReadout.projectiveDetectorReadout
#check GSTClassicalHodgeProjectiveTomographyReadout.exists_nonzero_projectiveDetectorReadout
#check GSTClassicalHodgeProjectiveTomographyReadout.exists_projectiveDetectorReadout_eq
#check GSTClassicalHodgeProjectiveVisibilitySeparation.ghostSpine_cycleClass_ne_zero
#check GSTClassicalHodgeProjectiveVisibilitySeparation.exists_projectiveDetectorVisible
#check GSTClassicalHodgeProjectiveVisibilitySeparation.exists_projectiveDetectorMomentHit
#check GSTClassicalHodgeProjectiveVisibilitySeparation.exists_projectiveKernel_readout_eq_ghostMoment
#check GSTClassicalHodgeTomographyVisibilityCrown.omniversalGhost_has_projective_visibility
#check GSTClassicalHodgeTomographyVisibilityCrown.omniversalGhost_has_tomography_moment_hit
#check GSTClassicalHodgeTomographyVisibilityCrown.omniversalGhost_false
#check GSTClassicalHodgeTomographyVisibilityCrown.no_omniversalSeparatorGhost
#check GSTClassicalHodgeTomographyVisibilityCrown.tomography_visibility_crown
#check GSTClassicalHodgeGenuineSemanticClosure.not_hodge_impossible
#check GSTClassicalHodgeGenuineSemanticClosure.bigradedBettiHodge_of_genuineCycleClassGeometry
#check GSTClassicalHodgeGenuineSemanticClosure.counterexample_yields_projective_tomography_contradiction
#check GSTClassicalHodgeGenuineSemanticClosure.genuine_semantic_closure_crown

#print axioms GSTClassicalHodgeGenuineCycleClassGeometry.GenuineCycleClassGeometry.not_nonempty_zeroCycleClassData
#print axioms GSTClassicalHodgeProjectiveTomographyReadout.exists_projectiveDetectorReadout_eq
#print axioms GSTClassicalHodgeProjectiveVisibilitySeparation.exists_projectiveDetectorVisible
#print axioms GSTClassicalHodgeProjectiveVisibilitySeparation.exists_projectiveDetectorMomentHit
#print axioms GSTClassicalHodgeTomographyVisibilityCrown.omniversalGhost_false
#print axioms GSTClassicalHodgeTomographyVisibilityCrown.no_omniversalSeparatorGhost
#print axioms GSTClassicalHodgeGenuineSemanticClosure.bigradedBettiHodge_of_genuineCycleClassGeometry
#print axioms GSTClassicalHodgeGenuineSemanticClosure.genuine_semantic_closure_crown
