import GSTClassicalHodgeLocalRegularCutDimension
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# GST CLASSICAL HODGE — SURJECTIVE STALK CUT DIMENSION

Closed immersions of schemes are surjective on stalks.  The remaining local
geometry of a principal projective cut is therefore concentrated in its stalk
kernel.  This module isolates the exact algebraic theorem needed by the
separator-successor grading argument:

if a surjective local map has kernel generated by one nonzero nonunit in a
Noetherian local domain, then its target has Krull dimension exactly one less.

No Hodge data, cycle classes, or reachability assumptions occur here.
-/

set_option maxHeartbeats 30000000
set_option maxRecDepth 1000000

noncomputable section

open Ideal RingTheory
open GSTClassicalHodgeLocalRegularCutDimension

namespace GSTClassicalHodgeSurjectiveStalkCutDimension

/-- First-isomorphism form of the one-regular-equation dimension drop. -/
theorem ringKrullDim_codomain_succ_eq_of_surjective_principal_kernel
    {R S : Type*}
    [CommRing R] [CommRing S]
    [IsDomain R] [IsNoetherianRing R] [IsLocalRing R]
    (φ : R →+* S)
    (hφ : Function.Surjective φ)
    (f : R)
    (hker : RingHom.ker φ = Ideal.span {f})
    (hf0 : f ≠ 0)
    (hfunit : ¬ IsUnit f) :
    ringKrullDim S + 1 = ringKrullDim R := by
  have hquot :
      ringKrullDim (R ⧸ RingHom.ker φ) = ringKrullDim S :=
    ringKrullDim_eq_of_ringEquiv
      (RingHom.quotientKerEquivOfSurjective hφ)
  calc
    ringKrullDim S + 1 =
        ringKrullDim (R ⧸ RingHom.ker φ) + 1 := by
          exact congrArg (fun d => d + 1) hquot.symm
    _ = ringKrullDim (R ⧸ Ideal.span {f}) + 1 := by rw [hker]
    _ = ringKrullDim R :=
      ringKrullDim_quotient_nonzero_nonunit_succ hf0 hfunit

/-- Equivalent crown recording both the quotient presentation and exact
one-step dimension loss. -/
theorem surjective_principal_cut_crown
    {R S : Type*}
    [CommRing R] [CommRing S]
    [IsDomain R] [IsNoetherianRing R] [IsLocalRing R]
    (φ : R →+* S)
    (hφ : Function.Surjective φ)
    (f : R)
    (hker : RingHom.ker φ = Ideal.span {f})
    (hf0 : f ≠ 0)
    (hfunit : ¬ IsUnit f) :
    RingHom.ker φ = Ideal.span {f}
      ∧ ringKrullDim S + 1 = ringKrullDim R := by
  exact ⟨hker,
    ringKrullDim_codomain_succ_eq_of_surjective_principal_kernel
      φ hφ f hker hf0 hfunit⟩

#check ringKrullDim_codomain_succ_eq_of_surjective_principal_kernel
#check surjective_principal_cut_crown

#print axioms ringKrullDim_codomain_succ_eq_of_surjective_principal_kernel
#print axioms surjective_principal_cut_crown

end GSTClassicalHodgeSurjectiveStalkCutDimension
