import GSTClassicalHodgeGenuineCycleClassGeometry
import GSTClassicalHodgeProjectiveTomographyReadout
import GSTClassicalHodgeProjectiveVisibilitySeparation
import GSTClassicalHodgeTomographyVisibilityCrown
import GSTClassicalHodgeGenuineSemanticClosure
import GSTClassicalHodgeProjectiveOrbitIrreducibilityAudit
import GSTClassicalHodgeNormalizedFiberedDefectBarrier
import GSTClassicalHodgeProjectiveVisibilityNoGo
import GSTClassicalHodgeCohomologicalPairingFrontier
import GSTClassicalHodgePolarizedHodgeGhost
import GSTClassicalHodgeAtomicDefectTomographyGhost
import GSTClassicalHodgePolarizedOrthogonalExtinctionAudit
import GSTClassicalHodgeAtomicDefectTomographySynchronization
import GSTClassicalHodgeTomographySynchronizationAudit
import GSTClassicalHodgeMultiplicityForgettingKernel
import GSTClassicalHodgeTwoBurstCorrectedFrontier
import GSTClassicalHodgeAtomicDefectOperatorDescent
import GSTClassicalHodgeAtomicDefectEquivariantIrreducibility
import GSTClassicalHodgeAtomicNaturalLefschetzNonCircularity
import GSTClassicalHodgeAtomicNaturalLefschetzPoincareClosure
import GSTClassicalHodgeLefschetzPoincarePrimitiveNonCircularity

/-!
# GST CLASSICAL HODGE — TWO-BURST CLOSURE RECEIPT

Compiler receipt for the corrected genuine cycle-class / tomography upgrade.
The active source cleanly separates semantic repair, multiplicity-preserving
tomography, quotient synchronization, quotient operator descent, and the
remaining genuinely geometric extinction problem.

The quotient-equivariant irreducibility and Lefschetz–Poincare primitive
splices are intentionally conditional.  The noncircularity files prove why:
on one live algebraic source, atomic naturality of the universal two-slot L²
primitive already forces the target Hodge sheet algebraic.  Consequently an
atomic-natural Lefschetz–Poincare primitive pair is impossible when a separator
annihilates the atomic span and detects that target.  Compression is retained
as a compiler from genuine geometry to Hodge closure, never as the missing
geometry itself.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

open AlgebraicGeometry

#check GSTClassicalHodgeGenuineCycleClassGeometry.GenuineCycleClassGeometry
#check GSTClassicalHodgeGenuineCycleClassGeometry.GenuineCycleClassGeometry.point_cycleClass_ne_zero
#check GSTClassicalHodgeGenuineCycleClassGeometry.GenuineCycleClassGeometry.not_nonempty_zeroCycleClassData
#check GSTClassicalHodgeProjectiveVisibilityNoGo.projectiveDetectorReadout_ghostSpine_eq_zero
#check GSTClassicalHodgeCohomologicalPairingFrontier.failure_yields_pairingOrthogonalGhost
#check GSTClassicalHodgePolarizedHodgeGhost.failure_yields_polarizedHodgeGhost
#check GSTClassicalHodgeAtomicDefectTomographyGhost.not_hodge_iff_nonempty_atomicDefectTomographyGhost
#check GSTClassicalHodgePolarizedOrthogonalExtinctionAudit.algebraicPairingSeparates_iff_hodge
#check GSTClassicalHodgeAtomicDefectTomographySynchronization.failure_yields_synchronizedAtomicDefectGhost
#check GSTClassicalHodgeTomographySynchronizationAudit.not_hodge_iff_nonempty_synchronizedAtomicDefectGhost
#check GSTClassicalHodgeTomographySynchronizationAudit.synchronizedAtomicDefectGhost_empty_iff_hodge
#check GSTClassicalHodgeMultiplicityForgettingKernel.forgetMultiplicityToGST_not_injective_of_two_sheets
#check GSTClassicalHodgeTwoBurstCorrectedFrontier.corrected_two_burst_crown
#check GSTClassicalHodgeAtomicDefectOperatorDescent.atomicDefectOperator
#check GSTClassicalHodgeAtomicDefectOperatorDescent.atomicDefectOperator_comp
#check GSTClassicalHodgeAtomicDefectOperatorDescent.projectiveCorrespondence_atomicSpanStable
#check GSTClassicalHodgeAtomicDefectOperatorDescent.ghostDefectDetector_projectiveDefectOperator
#check GSTClassicalHodgeAtomicDefectEquivariantIrreducibility.AtomicNaturalHodgeOperator
#check GSTClassicalHodgeAtomicDefectEquivariantIrreducibility.AtomicNaturalHodgeOperator.defect_equivariant
#check GSTClassicalHodgeAtomicDefectEquivariantIrreducibility.AtomicNaturalMatrixArsenal
#check GSTClassicalHodgeAtomicDefectEquivariantIrreducibility.bigradedBettiHodge_of_atomicNaturalMatrixArsenal
#check GSTClassicalHodgeAtomicNaturalLefschetzNonCircularity.bareTwoSlotLefschetzHodge_eq_scaled_matrixUnit
#check GSTClassicalHodgeAtomicNaturalLefschetzNonCircularity.targetBasis_algebraic_of_atomicNatural_bareLefschetz
#check GSTClassicalHodgeAtomicNaturalLefschetzNonCircularity.no_atomicNatural_bareLefschetz_to_separatorSheet
#check GSTClassicalHodgeAtomicNaturalLefschetzPoincareClosure.AtomicNaturalLefschetzPoincarePair
#check GSTClassicalHodgeAtomicNaturalLefschetzPoincareClosure.atomicNaturalMatrixArsenal_of_lefschetzPoincare
#check GSTClassicalHodgeAtomicNaturalLefschetzPoincareClosure.bigradedBettiHodge_of_atomicNaturalLefschetzPoincare
#check GSTClassicalHodgeLefschetzPoincarePrimitiveNonCircularity.targetBasis_algebraic_of_lefschetzPoincarePair
#check GSTClassicalHodgeLefschetzPoincarePrimitiveNonCircularity.no_lefschetzPoincarePair_to_separatorSheet
#check GSTClassicalHodgeLefschetzPoincarePrimitiveNonCircularity.lefschetzPoincarePair_false_of_separator

#print axioms GSTClassicalHodgeGenuineCycleClassGeometry.GenuineCycleClassGeometry.not_nonempty_zeroCycleClassData
#print axioms GSTClassicalHodgeProjectiveVisibilityNoGo.projectiveDetectorReadout_ghostSpine_eq_zero
#print axioms GSTClassicalHodgeCohomologicalPairingFrontier.failure_yields_pairingOrthogonalGhost
#print axioms GSTClassicalHodgePolarizedHodgeGhost.failure_yields_polarizedHodgeGhost
#print axioms GSTClassicalHodgeAtomicDefectTomographyGhost.not_hodge_iff_nonempty_atomicDefectTomographyGhost
#print axioms GSTClassicalHodgePolarizedOrthogonalExtinctionAudit.algebraicPairingSeparates_iff_hodge
#print axioms GSTClassicalHodgeAtomicDefectTomographySynchronization.failure_yields_synchronizedAtomicDefectGhost
#print axioms GSTClassicalHodgeTomographySynchronizationAudit.not_hodge_iff_nonempty_synchronizedAtomicDefectGhost
#print axioms GSTClassicalHodgeTomographySynchronizationAudit.synchronizedAtomicDefectGhost_empty_iff_hodge
#print axioms GSTClassicalHodgeMultiplicityForgettingKernel.forgetMultiplicityToGST_not_injective_of_two_sheets
#print axioms GSTClassicalHodgeTwoBurstCorrectedFrontier.corrected_two_burst_crown
#print axioms GSTClassicalHodgeAtomicDefectOperatorDescent.atomicDefectOperator_comp
#print axioms GSTClassicalHodgeAtomicDefectEquivariantIrreducibility.bigradedBettiHodge_of_atomicNaturalMatrixArsenal
#print axioms GSTClassicalHodgeAtomicNaturalLefschetzNonCircularity.targetBasis_algebraic_of_atomicNatural_bareLefschetz
#print axioms GSTClassicalHodgeAtomicNaturalLefschetzNonCircularity.no_atomicNatural_bareLefschetz_to_separatorSheet
#print axioms GSTClassicalHodgeAtomicNaturalLefschetzPoincareClosure.atomicNaturalMatrixArsenal_of_lefschetzPoincare
#print axioms GSTClassicalHodgeLefschetzPoincarePrimitiveNonCircularity.no_lefschetzPoincarePair_to_separatorSheet
