import GSTGeometricRealizationStage2G
import GSTGlobalPureHodgeCosmology
import GSTTruncatedWorldCohomologyRing
import CardinalWorlds
import CardinalWorldsPrefixClassifier
import CardinalWorldsV2
import GSTAnalyticAbsorption
import GSTAnalyticAbsorptionV2
import GSTCanonicalCarryDynamics
import GSTCanonicalSevenAxisBridge
import GSTCanonicalTailLTE
import GSTCanonicalTailStateIso
import GSTClayOfficial
import GSTClayOfficialV2
import GSTExactWorldOperatorPresentation
import GSTFinalPrefixOneStep6Infinite
import GSTFinalPurePowerResidueTransplant
import GSTFourPowerAffineBadState
import GSTFourPowerAffineChannelAutomaton
import GSTFourPowerAffineClassifierBridge
import GSTFourPowerAffineExponentPeel
import GSTFourPowerAffineOrbit
import GSTFourPowerAffinePeelClassifier
import GSTFourPowerAffineTwoTritClassifier
import GSTFourPowerDirectAdditionCarry
import GSTFourPowerDirectChat2Application
import GSTFourPowerDirectCreationMaster
import GSTFourPowerDirectExistence
import GSTFourPowerDirectExistenceFromHappy
import GSTFourPowerDirectExistenceNoAxiom
import GSTFourPowerDirectExistenceProviderPipeline
import GSTFourPowerDirectFailedRelocationState
import GSTFourPowerDirectHappyBridge
import GSTFourPowerDirectNo22
import GSTFourPowerDirectResidue
import GSTFourPowerDirectResidue27
import GSTFourPowerDirectResidue81
import GSTFourPowerExactExponentPeriod
import GSTFourPowerExponentTritObstruction
import GSTFourPowerHappyProvider
import GSTFourPowerNo22Magnitude
import GSTFourPowerOntologicalAdapter
import GSTFourPowerThirdWave
import GSTGhostRayExclusion
import GSTGraphV2CanonicalDescentOntology
import GSTGraphV2CanonicalEscape
import GSTGraphV2CanonicalInfiniteCycle
import GSTGraphV2CanonicalNWave
import GSTGraphV2CanonicalPhaseSteering
import GSTGraphV2CanonicalPhaseWaveProbe
import GSTGraphV2CanonicalRenormalization
import GSTGraphV2CanonicalSheetTranslation
import GSTGraphV2CanonicalSignedPrefixBridge
import GSTGraphV2CanonicalTerminalExtinctionProbe
import GSTGraphV2CanonicalTransparentBridgeProbe
import GSTGraphV2CoupledUFlux
import GSTGraphV2CoupledUPhysicalBridge
import GSTGraphV2FourPowerResidueObstruction
import GSTGraphV2HandwrittenExponentialCascade
import GSTGraphV2HandwrittenExponentialLTE
import GSTGraphV2HandwrittenOmegaUBlock
import GSTGraphV2InfiniteControl
import GSTGraphV2NonEuclidean
import GSTGraphV2NonEuclideanLaws
import GSTGraphV2NonlocalCascade
import GSTGraphV2OmegaWaveLaw
import GSTGraphV2PerfectPowerAncestry
import GSTGraphV2PhysicalSignedKernelTelescopeScratch
import GSTGraphV2Production
import GSTGraphV2ProductionLaws
import GSTGraphV2ScaleEquivariance
import GSTGraphV2SeededPrefix
import GSTGraphV2SixAdicOntologicalGeometryLaws
import GSTGraphV2SixAdicUnitIsometry
import GSTGraphV2TransparentWidthThree
import GSTHodgeAssault
import GSTHodgeAssaultV2
import GSTInfiniteBadTransport
import GSTInfiniteCollision
import GSTInfiniteCoupledLedger
import GSTInfiniteFourPowerNavigation
import GSTInfiniteGateTransport
import GSTInfiniteWorldRenormalization
import GSTLefschetzCrown
import GSTLefschetzCrownV2
import GSTMultiAxisCohomology
import GSTMultiAxisCosmology
import GSTMultiAxisGradedDynamics
import GSTPerfectPowerTailNavigation
import GSTPrefixOneOntologicalEscape
import GSTPrefixOneSeedCore
import GSTSeedOneShift
import GSTTactic
import GSTTailFFourthDimension
import GSTTailFInfiniteRead
import GSTTailFOneLane
import GSTTailFProof
import GSTTheAct
import GSTTheActConstruction
import GSTTransferBridge
import GSTTransferBridgeV2
import GSTV2InfiniteCore
import GSTWorldtraceArithmetic
import GSTWorldtraceMahlerRelativePrecision
import HodgeDeRhamBridge
import HodgeDeRhamBridgeV2
import InformationBadTraceScratch
import InformationDescentScratch
import InformationGeometryScratch
import InformationRegenerationScratch
import InformationStateScratch
import OriginTransducerScratch
import waves.CardinalWorldsPostulateLaw
import waves.CardinalWorldsPostulateLawV2
import waves.GSTNCohomology
import waves.GSTNCohomologyV2
import waves.GSTVortexSingularity
import waves.GSTVortexSingularityV2
import waves.GSTWaveCohomology
import waves.GSTWaveCohomologyV2

/-! Transitive axiom audit of original and direct in-place strengthening APIs. -/
#print axioms GSTMultiAxisCosmology.shift
#print axioms GSTMultiAxisCosmology.shift_zero
#print axioms GSTMultiAxisCosmology.shift_add
#print axioms GSTMultiAxisCosmology.shifts_commute
#print axioms GSTMultiAxisCosmology.shift_boundary
#print axioms GSTMultiAxisCosmology.shiftEndo
#print axioms GSTMultiAxisCosmology.shiftEndo_apply
#print axioms GSTMultiAxisCosmology.shiftEndo_mul
#print axioms GSTMultiAxisCosmology.origin
#print axioms GSTMultiAxisCosmology.delta
#print axioms GSTMultiAxisCosmology.shift_origin
#print axioms GSTMultiAxisCosmology.delta_expansion
#print axioms GSTMultiAxisCosmology.synthesis
#print axioms GSTMultiAxisCosmology.synthesis_origin
#print axioms GSTMultiAxisCosmology.synthesis_injective
#print axioms GSTMultiAxisCosmology.commuting_operator_delta
#print axioms GSTMultiAxisCosmology.commuting_operator_ext
#print axioms GSTMultiAxisCosmology.synthesis_commutes
#print axioms GSTMultiAxisCosmology.commuting_operator_classification
#print axioms GSTMultiAxisCosmology.commutantEquiv
#print axioms GSTMultiAxisCosmology.dual
#print axioms GSTMultiAxisCosmology.dual_involutive
#print axioms GSTMultiAxisCosmology.pairing
#print axioms GSTMultiAxisCosmology.pairing_extract
#print axioms GSTMultiAxisCosmology.pairing_nondegenerate
#print axioms GSTMultiAxisCosmology.degree_dual
#print axioms GSTMultiAxisCosmology.rectangleEquiv
#print axioms GSTMultiAxisCohomology.boundaryIdeal
#print axioms GSTMultiAxisCohomology.axis
#print axioms GSTMultiAxisCohomology.boundaryIdeal_eq_span_powers
#print axioms GSTMultiAxisCohomology.mem_boundaryIdeal_iff
#print axioms GSTMultiAxisCohomology.mem_boundaryIdeal_iff_coeff
#print axioms GSTMultiAxisCohomology.quotient_eq_iff_coeff
#print axioms GSTMultiAxisCohomology.axis_pow_depth
#print axioms GSTMultiAxisCohomology.monomial_class_ne_zero
#print axioms GSTMultiAxisCohomology.bounded_polynomial_faithful
#print axioms GSTMultiAxisCohomology.represent
#print axioms GSTMultiAxisCohomology.represent_axis
#print axioms GSTMultiAxisCohomology.representation_ext
#print axioms GSTMultiAxisCohomology.existsUnique_representation
#print axioms GSTMultiAxisCohomology.finite_polarization_bound
#print axioms GSTMultiAxisCohomology.weighted_axis_polarization_bound
#print axioms GSTMultiAxisCohomology.rectangular_boundary
#print axioms GSTMultiAxisCohomology.rectangular_L_pow_boundary
#print axioms GSTMultiAxisGradedDynamics.degree
#print axioms GSTMultiAxisGradedDynamics.topDegree
#print axioms GSTMultiAxisGradedDynamics.sector
#print axioms GSTMultiAxisGradedDynamics.degree_le_top
#print axioms GSTMultiAxisGradedDynamics.sector_idempotent
#print axioms GSTMultiAxisGradedDynamics.sector_orthogonal
#print axioms GSTMultiAxisGradedDynamics.sector_sum
#print axioms GSTMultiAxisGradedDynamics.sector_zero_above
#print axioms GSTMultiAxisGradedDynamics.shift_sector
#print axioms GSTMultiAxisGradedDynamics.weighted_dual_degree
#print axioms GSTMultiAxisGradedDynamics.Raises
#print axioms GSTMultiAxisGradedDynamics.raises_pow
#print axioms GSTMultiAxisGradedDynamics.raising_operator_extinction
#print axioms GSTMultiAxisGradedDynamics.raising_operator_nilpotent
#print axioms GSTExactWorldOperatorPresentation.evalEndo
#print axioms GSTExactWorldOperatorPresentation.origin
#print axioms GSTExactWorldOperatorPresentation.cellExponent
#print axioms GSTExactWorldOperatorPresentation.origin_coefficient
#print axioms GSTExactWorldOperatorPresentation.ker_evalWorldPoly_exact
#print axioms GSTExactWorldOperatorPresentation.worldOperatorHom_injective
#print axioms GSTExactWorldOperatorPresentation.evalWorldPoly_surjective
#print axioms GSTExactWorldOperatorPresentation.worldOperatorEquiv
#print axioms GSTExactWorldOperatorPresentation.L_pow_top_ne_zero
#print axioms GSTExactWorldOperatorPresentation.L_pow_eq_zero_iff
#print axioms GSTInfiniteWorldRenormalization.worldPrefix
#print axioms GSTInfiniteWorldRenormalization.tail
#print axioms GSTInfiniteWorldRenormalization.graft
#print axioms GSTInfiniteWorldRenormalization.innovation_tail
#print axioms GSTInfiniteWorldRenormalization.innovation_graft
#print axioms GSTInfiniteWorldRenormalization.prefix_graft
#print axioms GSTInfiniteWorldRenormalization.tail_graft
#print axioms GSTInfiniteWorldRenormalization.graft_prefix_tail
#print axioms GSTInfiniteWorldRenormalization.splitEquiv
#print axioms GSTInfiniteWorldRenormalization.tail_zero
#print axioms GSTInfiniteWorldRenormalization.tail_add
#print axioms GSTInfiniteWorldRenormalization.tail_surjective
#print axioms GSTInfiniteWorldRenormalization.graft_injective
#print axioms GSTInfiniteWorldRenormalization.level_eq_iff_prefix
#print axioms GSTInfiniteWorldRenormalization.cylinderEquiv
#print axioms GSTInfiniteWorldRenormalization.fiberEquiv
#print axioms GSTInfiniteWorldRenormalization.fiber_card
#print axioms GSTInfiniteWorldRenormalization.cylinder_current
#print axioms GSTInfiniteWorldRenormalization.cylinder_no_countable_catalogue
#print axioms hasTwoInFirstKStruct_iff_digit
#print axioms CardinalWorldsPrefixClassifier.four_pow_has_two_iff_unique_first_prefix
#print axioms CardinalWorldsV2.joined_prefix_add
#print axioms GSTAnalyticAbsorption.hc_period_eq_zero
#print axioms GSTAnalyticAbsorptionV2.hc_descent_flow_bijective
#print axioms GSTCanonicalCarryDynamics.carry4_block_exact
#print axioms GSTCanonicalSevenAxisBridge.event_nextCarry_injective
#print axioms GSTCanonicalTailLTE.pow4_three_power_lte_not_dvd_next
#print axioms GSTCanonicalTailStateIso.prefix_slice_carry_seed_exact
#print axioms GSTClayOfficial.rational_cycle_coefficient_integral
#print axioms GSTClayOfficialV2.rational_hodge_iff_all_weights
#print axioms GSTFinalPrefixOneStep6Infinite.reverseMixedCode_add
#print axioms GSTFinalPurePowerResidueTransplant.pow4_exponent_lift_digit_all
#print axioms GSTFourPowerAffineBadState.pairCommonTwo_iff_low_or_tail
#print axioms GSTFourPowerAffineChannelAutomaton.channelRun
#print axioms GSTFourPowerAffineChannelAutomaton.badChannel_iff_run
#print axioms GSTFourPowerAffineChannelAutomaton.channelNext_lt_four
#print axioms GSTFourPowerAffineClassifierBridge.noCommonTwo_iff_affine_run
#print axioms GSTFourPowerAffineExponentPeel.affineOrbit_three_mul_add
#print axioms GSTFourPowerAffineExponentPeel.peel0_le_iff
#print axioms GSTFourPowerAffineOrbit.affineOrbit_add
#print axioms GSTFourPowerAffineOrbit.affineOrbit_strictMono
#print axioms GSTFourPowerAffineOrbit.affineOrbit_injective
#print axioms GSTFourPowerAffinePeelClassifier.noCommonTwo_iff_quotient_peel
#print axioms GSTFourPowerAffineTwoTritClassifier.commonTwo_three_mul_iff_second
#print axioms GSTFourPowerDirectAdditionCarry.directCarry4_eq_iff_band
#print axioms GSTFourPowerDirectAdditionCarry.digit3_four_mul_eq_iff
#print axioms GSTFourPowerDirectChat2Application.chat2_bad_channel_iff_all_prefix_obstructions
#print axioms GSTFourPowerDirectCreationMaster.commonTwo_iff_creation_certificate
#print axioms GSTFourPowerDirectCreationMaster.directExistence_iff_creation_master
#print axioms GSTFourPowerDirectExistence.commonTwo_of_periodic_row
#print axioms GSTFourPowerDirectExistence.commonTwo_has_periodic_progression
#print axioms GSTFourPowerDirectExistenceFromHappy.directBadDossier_iff_noCommonTwo
#print axioms GSTFourPowerDirectExistenceFromHappy.directExistence_iff_no_dossier
#print axioms GSTFourPowerDirectExistenceNoAxiom.fourPowerDirectExistence_iff_ge_eight
#print axioms GSTFourPowerDirectExistenceNoAxiom.fourPowerDirectExistence_from_physical_happy_positive
#print axioms GSTFourPowerDirectExistenceProviderPipeline.happy_provider_iff_commonTwoGeThree_provider
#print axioms GSTFourPowerDirectExistenceProviderPipeline.happy_provider_iff_prefix_hits
#print axioms GSTFourPowerDirectFailedRelocationState.no_common_source_two_forces_state
#print axioms GSTFourPowerDirectFailedRelocationState.carry_three_forward_exact
#print axioms GSTFourPowerDirectHappyBridge.physical_happy_iff_row_pair
#print axioms GSTFourPowerDirectHappyBridge.physical_happy_cutoff_iff
#print axioms GSTFourPowerDirectNo22.source_22_forces_common_in_pair
#print axioms GSTFourPowerDirectResidue.pow4_exponent_lift_digit
#print axioms GSTFourPowerDirectResidue.pow4_digit_reduce_offset
#print axioms GSTFourPowerDirectResidue27.row_three_overlap_iff_mod27_classes
#print axioms GSTFourPowerDirectResidue81.row_four_overlap_iff_mod81_classes
#print axioms GSTFourPowerExactExponentPeriod.next_digit_translation_iff
#print axioms GSTFourPowerExponentTritObstruction.no_common_two_iff_all_trit_obstructions
#print axioms GSTFourPowerHappyProvider.commonTwoGeThree_iff_prefixHitGeThree
#print axioms GSTFourPowerHappyProvider.commonTwoGeThree_iff_physical_happy
#print axioms GSTFourPowerNo22Magnitude.no22_iff_tail_and_boundary
#print axioms GSTFourPowerOntologicalAdapter.creation_certificate_iff_positive_happy
#print axioms GSTFourPowerThirdWave.thirdWaveRow_reduce_offset
#print axioms GSTFourPowerThirdWave.thirdWaveRow_period
#print axioms GSTGhostRay.ghostRay_iff_residue_shape
#print axioms GSTGraphV2CanonicalDescentOntology.canonical_left_descent_all_depths
#print axioms GSTGraphV2CanonicalEscape.canonicalTail_pow_dvd_iff
#print axioms GSTGraphV2CanonicalInfiniteCycle.coupledOrbit_cycle_all_offsets
#print axioms GSTGraphV2CanonicalInfiniteCycle.coupledOrbit_cycle_mod_exact
#print axioms GSTGraphV2CanonicalNWave.nWaveShift_add_exact
#print axioms GSTGraphV2CanonicalNWave.nWaveEnergy_add_exact
#print axioms GSTGraphV2CanonicalPhaseSteering.canonical_right_next_seed_phase_iff
#print axioms GSTGraphV2CanonicalPhaseWaveProbe.canonical_parent_row_one_happy_iff
#print axioms GSTGraphV2CanonicalRenormalization.canonicalTail_residue_three_exact
#print axioms GSTGraphV2CanonicalRenormalization.canonicalTail_prefix_local
#print axioms GSTGraphV2CanonicalSheetTranslation.canonicalEnergy_block_translate
#print axioms GSTGraphV2CanonicalSignedPrefixBridge.canonical_graph_u_gap_lower_bound
#print axioms GSTGraphV2CanonicalTerminalExtinctionProbe.seeded_coupled_weighted_u_gap_lower_bound
#print axioms GSTGraphV2CanonicalTerminalExtinctionProbe.unit_window_vacuum_of_pow_lt
#print axioms GSTGraphV2CanonicalTransparentBridgeProbe.canonicalWidth_three_dvd_iff
#print axioms GSTGraphV2CoupledUFlux.orbitWith_add
#print axioms GSTGraphV2CoupledUFlux.coupled_u_flux_window_exact
#print axioms GSTGraphV2CoupledUPhysicalBridge.potential_shared_rewrite_iff
#print axioms GSTGraphV2FourPowerResidueObstruction.pow4_digit_eq_of_exponent_mod
#print axioms GSTGraphV2HandwrittenExponentialCascade.originSuffix_zero_iff
#print axioms GSTGraphV2HandwrittenExponentialCascade.exhausted_cut_stable
#print axioms GSTGraphV2HandwrittenExponentialLTE.pow4_scaled_mod_all_lower
#print axioms GSTGraphV2HandwrittenOmegaUBlock.origin_coordinates_iff
#print axioms GSTGraphV2HandwrittenOmegaUBlock.originTail_lt
#print axioms GSTGraphV2InfiniteControl.graph_local_mass_conservation
#print axioms GSTGraphV2NonEuclidean.forwardEdge_axes_iff
#print axioms GSTGraphV2NonEuclidean.forwardPath_node_injective
#print axioms GSTGraphV2NonEuclideanLaws.forward_displacement_exact
#print axioms GSTGraphV2NonEuclideanLaws.boundary_displacement_strict_iff
#print axioms GSTGraphV2NonlocalCascade.latent_next_happy_iff
#print axioms GSTGraphV2OmegaWaveLaw.omega_observed_digit_iff_interval
#print axioms GSTGraphV2PerfectPowerAncestry.scaled_origin_observables_exact
#print axioms GSTPhysicalKernel.signedKernelTwice_boundary_lower_bound
#print axioms GSTPhysicalKernel.signedKernelTwice_eq_boundary_iff_no_survive
#print axioms GSTGraphV2Production.originCoordinates_decode
#print axioms GSTGraphV2Production.originFrame_absolute_energy
#print axioms GSTGraphV2ProductionLaws.production_charges_eq_of_absolute_energy
#print axioms GSTGraphV2ScaleEquivariance.physicalPacket_eq_of_absolute_energy
#print axioms GSTGraphV2ScaleEquivariance.uPhaseShift_mono
#print axioms GSTGraphV2SeededPrefix.seededResidue_strip_block
#print axioms GSTGraphV2SeededPrefix.seeded_observables_strip_block
#print axioms GSTGraphV2SeededPrefix.seedHappy_strip_block
#print axioms GSTGraphV2SixAdicOntologicalGeometryLaws.six_iso_weaken_of_le
#print axioms GSTGraphV2SixAdicOntologicalGeometryLaws.intersecting_balls_nested
#print axioms GSTGraphV2SixAdicOntologicalGeometryLaws.six_child_resolution_iff
#print axioms GSTGraphV2SixAdicUnitIsometry.six_scale_power_translate_iff
#print axioms GSTGraphV2TransparentWidthThree.power_width_three_u_derivative_lower_bound
#print axioms GSTHodgeAssault.hodge_weight_intersection
#print axioms GSTHodgeAssaultV2.pure_hodge_iff_unique_expansion
#print axioms GSTV2.seededBadTrace_split_iff
#print axioms GSTV2.coupledOrbit_add
#print axioms GSTV2.infinite_coupled_control_restart
#print axioms GSTV2.seededPast_eq_mass_mod
#print axioms GSTV2.seededPast_add
#print axioms GSTInfiniteFourPowerNavigation.gst_u_jump_negative_iff_happy
#print axioms GSTV2.happy_iff_output_and_next
#print axioms GSTLefschetzCrown.S12_eq_iff
#print axioms GSTLefschetzCrownV2.lefschetz_degree0_image_iff
#print axioms GSTPerfectPowerTailNavigation.canonical_tail_navigation_iff
#print axioms GSTPrefixOneOntologicalEscape.gst_prefix_one_escape_all_tails_of_master
#print axioms GSTPrefixOneSeedCore.prefix_one_tail_residue_quotient
#print axioms GSTSeedOneShift.seedOneCarry_step
#print axioms gst_positive_iff_endpoint
#print axioms alt_negative_iff_interior
#print axioms GSTTailFFourthDimension.omega_observed_digit_sheet_independent
#print axioms GSTTailFInfiniteRead.dustAt_add_multiple_iff
#print axioms GSTTailFOneLane.one_lane_three_free_unique
#print axioms GSTTailFProof.tower_observation_iff_interval
#print axioms GSTTheAct.front_residue_law
#print axioms GSTTheActConstruction.feedback_fire_iff_residue
#print axioms GSTTransferBridge.addr_linear_combination
#print axioms GSTTransferBridgeV2.transferred_unique_iff_live
#print axioms GSTV2.omega_future_step
#print axioms GSTV2.omega_window_conservation
#print axioms GSTWorldtraceArithmetic.pair_read_fire_iff
#print axioms GSTWorldtraceMahler.worldtraceWitness_relative_dvd_iff
#print axioms GSTWorldtraceMahler.relativeLock_iff_normalized
#print axioms HodgeDeRhamBridge.current_sharp_bounds
#print axioms HodgeDeRhamBridgeV2.zero_current_exact
#print axioms gst_bad_two_state_exactS
#print axioms gst_affine_carry_semigroup_generalS
#print axioms gst_information_digit_shiftS
#print axioms gst_information_coordinates_iffS
#print axioms gst_seeded_bad_trace_cut_iffS
#print axioms gst_shared_information_high_coordinates_exactS
#print axioms affine_origin_step_coordinatesS
#print axioms CardinalWorldsPostulateLaw.controlled_level_constant
#print axioms CardinalWorldsPostulateLaw.controlled_presentation_iff_constant
#print axioms CardinalWorldsPostulateLawV2.transport_injective
#print axioms GSTNCohomology.waveIIAmplitude_telescope
#print axioms GSTNCohomologyV2.weighted_interference_separates
#print axioms GSTVortexSingularity.core_rotation_injective
#print axioms GSTVortexSingularityV2.core_rotation_no_early_return
#print axioms GSTWaveCohomology.finite_weighted_wave_decomposition
#print axioms GSTWaveCohomologyV2.rowClass_faithful

#print axioms GSTMultiAxisCosmology.shiftEndo_pow

#print axioms GSTMultiAxisCosmology.shiftEndo_pow_eq_zero_iff

#print axioms GSTMultiAxisGradedDynamics.raises_mul

#print axioms GSTMultiAxisGradedDynamics.raises_list_prod

#print axioms GSTMultiAxisGradedDynamics.raising_sequence_extinction

#print axioms GSTInfiniteWorldClassification.windowTower_eq_iff_cofinal_levels

#print axioms GSTInfiniteWorldRenormalization.level_eq_iff_prefix_tail

#print axioms GSTInfiniteWorldRenormalization.graft_level_eq_iff

#print axioms GSTMultiAxisCohomology.all_depths_separate

#print axioms GSTMultiAxisCohomology.axis_pow_eq_zero_of_depth_le

#print axioms GSTMultiAxisCohomology.boundedNormalForm

#print axioms GSTMultiAxisCohomology.boundedNormalForm_add

#print axioms GSTMultiAxisCohomology.boundedNormalForm_comp

#print axioms GSTMultiAxisCohomology.boundedNormalForm_eq_iff

#print axioms GSTMultiAxisCohomology.boundedNormalForm_eq_of_quotient_eq

#print axioms GSTMultiAxisCohomology.boundedNormalForm_idempotent

#print axioms GSTMultiAxisCohomology.boundedNormalForm_mul

#print axioms GSTMultiAxisCohomology.boundedNormalForm_support

#print axioms GSTMultiAxisCohomology.bounded_quotient_injective

#print axioms GSTMultiAxisCohomology.coeff_boundedNormalForm_of_live

#print axioms GSTMultiAxisCohomology.coeff_boundedNormalForm_of_not_live

#print axioms GSTMultiAxisCohomology.depthRestriction

#print axioms GSTMultiAxisCohomology.depthRestriction_comp

#print axioms GSTMultiAxisCohomology.depthRestriction_eq_iff

#print axioms GSTMultiAxisCohomology.depthRestriction_mk

#print axioms GSTMultiAxisCohomology.depthRestriction_surjective

#print axioms GSTMultiAxisCohomology.existsUnique_bounded_representative

#print axioms GSTMultiAxisCohomology.monomial_class_eq_zero_iff

#print axioms GSTMultiAxisCohomology.quotient_boundedNormalForm

#print axioms GSTTruncatedWorldCohomologyRing.H_pow_eq_zero_of_depth_le

#print axioms GSTTruncatedWorldCohomologyRing.L_binomial

#print axioms GSTTruncatedWorldCohomologyRing.L_pow_boundary

#print axioms GSTTruncatedWorldCohomologyRing.L_pow_eq_zero_of_boundary_le

#print axioms GSTTruncatedWorldCohomologyRing.V_pow_eq_zero_of_depth_le

#print axioms GSTTruncatedWorldCohomologyRing.mem_worldOperatorHom_ker_iff_annihilates

#print axioms GSTTruncatedWorldCohomologyRing.worldAct_eq_iff_operator_eq

#print axioms GSTTruncatedWorldCohomologyRing.worldAct_monomial_zero

#print axioms GSTTruncatedWorldCohomologyRing.worldAct_neg

#print axioms GSTTruncatedWorldCohomologyRing.worldAct_pow_add

#print axioms GSTGlobalPureHodgeCosmology.pureCoordinates_residual

#print axioms GSTGlobalPureHodgeCosmology.pureProjection

#print axioms GSTGlobalPureHodgeCosmology.pure_hodge_basis_expansion

#print axioms GSTGlobalPureHodgeCosmology.pure_hodge_eq_iff_coordinates

#print axioms GSTGlobalPureHodgeCosmology.pure_hodge_eq_zero_iff_coordinates_zero

#print axioms GSTGlobalPureHodgeCosmology.pure_residual_decomposition

#print axioms GSTWaveCohomology.rowClassAt_recovered_exact

#print axioms GSTWaveCohomology.rowClass_add_exact

#print axioms GSTWaveCohomology.rowClass_all_zero_iff_exact

#print axioms GSTWaveCohomology.rowClass_cut_exact

#print axioms GSTWaveCohomology.rowClass_prefix_complete

#print axioms GSTWaveCohomologyV2.rowClassAt_recovered

#print axioms GSTWaveCohomologyV2.rowClass_all_zero_iff

#print axioms GSTWaveCohomologyV2.rowClass_complete_observable

#print axioms GSTNCohomology.waveIIAmplitude_prefix_recovered

#print axioms GSTNCohomology.waveII_channel_reconstruction

#print axioms GSTNCohomology.waveII_prefix_add

#print axioms GSTNCohomology.waveII_prefix_all_zero_iff

#print axioms GSTNCohomology.waveII_prefix_complete_observable

#print axioms GSTNCohomologyV2.weightedInterference_delta

#print axioms GSTNCohomologyV2.weighted_interference_energy

#print axioms GSTNCohomologyV2.weighted_interference_ext

#print axioms GSTNCohomologyV2.weighted_interference_single_probe

#print axioms GSTNCohomology.ncoho_rank

#print axioms GSTNCohomologyV2.canonicalNCohoBasis

#print axioms GSTNCohomologyV2.ncoho_rank_unconditional

#print axioms GSTNCohomologyV2.canonicalNCohoBasis_injective

#print axioms GSTGeometricRealizationStage2G.complexificationMapQ

#print axioms GSTGeometricRealizationStage2G.complexificationMapQ_apply

#print axioms GSTGeometricRealizationStage2G.ppIndex


#print axioms GSTGeometricRealizationStage2G.rationalHodgeSubspace

#print axioms GSTGeometricRealizationStage2G.mem_rationalHodgeSubspace_iff


#print axioms GSTGeometricRealizationStage2G.BigradedBettiHodgeStatement

#print axioms GSTGeometricRealizationStage2G.bigradedBettiHodgeStatement_iff_stage2f

#print axioms GSTGeometricRealizationStage2G.hodge_class_has_bigraded_cycle

#print axioms GSTGeometricRealizationStage2G.bigraded_betti_hodge_of_stage2g_family

#print axioms GSTGeometricRealizationStage2G.Stage2GRealizationObligation

#print axioms GSTGeometricRealizationStage2G.bigraded_betti_hodge_of_stage2g_obligation

#print axioms GSTGeometricRealizationStage2G.cosmologyCoordinateBasis

#print axioms GSTGeometricRealizationStage2G.cosmology_coordinate_reconstruct

#print axioms GSTGeometricRealizationStage2G.cosmologyCycleWitness

#print axioms GSTGeometricRealizationStage2G.cosmologyCycleWitness_spec

#print axioms GSTGeometricRealizationStage2G.cosmologyCycleLift

#print axioms GSTGeometricRealizationStage2G.cosmologyCycleLift_section

#print axioms GSTGeometricRealizationStage2G.cosmology_cycle_fiber_exact

#print axioms GSTGeometricRealizationStage2G.hodge_class_has_cosmology_cycle

#print axioms GSTGeometricRealizationStage2G.bigraded_betti_hodge_of_cosmology_family

#print axioms GSTGeometricRealizationStage2G.CosmologyStage2GRealizationObligation

#print axioms GSTGeometricRealizationStage2G.bigraded_betti_hodge_of_cosmology_obligation

#print axioms GSTGeometricRealizationStage2G.cosmology_chart_realization_iff

#print axioms GSTGeometricRealizationStage2G.zero_cycleClass_hodge_iff

#print axioms GSTGeometricRealizationStage2G.HodgeBigrading.ppComponent

#print axioms GSTGeometricRealizationStage2G.HodgeBigradedBettiData.toBettiHodgeData
