import GSTClassicalHodgeAtomicDefectDuality

/-!
# GST CLASSICAL HODGE — ATOMIC ANNIHILATOR SEPARATION

The atomic-span formulation admits a dual form: a Hodge class fails to lie in
the algebraic atomic span exactly when some rational linear detector vanishes
on every genuine codimension-p point-cycle class but detects that Hodge class.

This module formalizes the algebraic separation mechanism through the quotient
by a submodule and a coordinate functional on a chosen quotient basis.
Consequently the Stage-2G Hodge target is equivalent to the nonexistence of
such separating detectors in every weight.
-/

set_option maxHeartbeats 10000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry
open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTNativeCodimensionCyclePresentation
open GSTClassicalHodgeAtomicSpan
open GSTClassicalHodgeAtomicDefectDuality

namespace GSTClassicalHodgeAtomicAnnihilator

universe u v

/-- Pure linear-algebra separation: if `x` is outside a submodule `W`, there
is a rational linear functional annihilating `W` but not `x`. -/
theorem exists_linearFunctional_separating_submodule
    {M : Type u} [AddCommGroup M] [Module ℚ M]
    (W : Submodule ℚ M)
    (x : M)
    (hx : x ∉ W) :
    ∃ ell : M →ₗ[ℚ] ℚ,
      (∀ w : M, w ∈ W → ell w = 0) ∧ ell x ≠ 0 := by
  let Q := M ⧸ W
  let q : Q := Submodule.Quotient.mk x
  have hq : q ≠ 0 := by
    intro hzero
    apply hx
    exact (Submodule.Quotient.mk_eq_zero W).mp hzero
  let b := Module.Free.chooseBasis ℚ Q
  have hrepr : b.repr q ≠ 0 := by
    intro hzero
    apply hq
    exact b.repr.injective (by simpa using hzero)
  have hsupp : (b.repr q).support.Nonempty :=
    Finsupp.support_nonempty_iff.mpr hrepr
  let i := hsupp.choose
  have hi : (b.repr q) i ≠ 0 := by
    exact Finsupp.mem_support_iff.mp hsupp.choose_spec
  let coord : Q →ₗ[ℚ] ℚ :=
    (Finsupp.lapply i).comp b.repr.toLinearMap
  let ell : M →ₗ[ℚ] ℚ :=
    coord.comp (Submodule.mkQ W)
  refine ⟨ell, ?_, ?_⟩
  · intro w hw
    change coord (Submodule.mkQ W w) = 0
    have h0 : Submodule.mkQ W w = 0 :=
      (Submodule.Quotient.mk_eq_zero W).mpr hw
    rw [h0]
    exact coord.map_zero
  · change coord q ≠ 0
    simpa [coord, q, i] using hi

/-- Predicate saying a rational detector kills every genuine codimension-p
point-cycle class. -/
def AnnihilatesPointCycleClasses
    {X : Scheme.{u}}
    {Coh : Type v} [AddCommGroup Coh] [Module ℚ Coh]
    (p : Nat)
    (cl : codimensionCycles X p →ₗ[ℚ] Coh)
    (ell : Coh →ₗ[ℚ] ℚ) : Prop :=
  ∀ x : CodimensionPoint X p,
    ell (cl (codimensionPointCycle X p x)) = 0

/-- Killing every atomic point-cycle class is equivalent to killing the whole
atomic span generated by those classes. -/
theorem annihilatesPointCycles_iff_atomicSpan_le_ker
    {X : Scheme.{u}}
    {Coh : Type v} [AddCommGroup Coh] [Module ℚ Coh]
    (p : Nat)
    (cl : codimensionCycles X p →ₗ[ℚ] Coh)
    (ell : Coh →ₗ[ℚ] ℚ) :
    AnnihilatesPointCycleClasses p cl ell ↔
      pointCycleClassSpan p cl ≤ LinearMap.ker ell := by
  constructor
  · intro h
    apply Submodule.span_le.mpr
    rintro y ⟨x, rfl⟩
    exact h x
  · intro h x
    exact h (Submodule.subset_span ⟨x, rfl⟩)

/-- One weight satisfies atomic algebraicity exactly when every detector that
kills all codimension-p point-cycle classes also kills the entire rational
`(p,p)` Hodge subspace. -/
theorem hodgeSubspace_le_atomicSpan_iff_annihilator
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V)
    (p : Nat) :
    rationalHodgeSubspace (H.hodgeBigrading p) ≤
        pointCycleClassSpan p (H.cycleClass p) ↔
      ∀ ell :
          RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ] ℚ,
        AnnihilatesPointCycleClasses p (H.cycleClass p) ell →
        ∀ alpha : RationalSingularCohomology H.analytification (2 * p),
          alpha ∈ rationalHodgeSubspace (H.hodgeBigrading p) →
          ell alpha = 0 := by
  constructor
  · intro hle ell hell alpha halpha
    have hker :
        pointCycleClassSpan p (H.cycleClass p) ≤ LinearMap.ker ell :=
      (annihilatesPointCycles_iff_atomicSpan_le_ker
        p (H.cycleClass p) ell).mp hell
    exact hker (hle halpha)
  · intro hann alpha halpha
    by_contra hnot
    obtain ⟨ell, hellSpan, hellAlpha⟩ :=
      exists_linearFunctional_separating_submodule
        (pointCycleClassSpan p (H.cycleClass p)) alpha hnot
    have hellAtoms :
        AnnihilatesPointCycleClasses p (H.cycleClass p) ell := by
      intro x
      apply hellSpan
      exact Submodule.subset_span ⟨x, rfl⟩
    exact hellAlpha (hann ell hellAtoms alpha halpha)

/-- **ATOMIC ANNIHILATOR FORM OF THE CLASSICAL HODGE TARGET.**

The Stage-2G statement holds exactly when no rational linear detector can
vanish on every genuine codimension-p algebraic atom while remaining nonzero
on a rational `(p,p)` Hodge class. -/
theorem bigradedBettiHodgeStatement_iff_no_atomic_separator
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V) :
    BigradedBettiHodgeStatement V H ↔
      ∀ p : Nat,
        ∀ ell :
          RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ] ℚ,
          AnnihilatesPointCycleClasses p (H.cycleClass p) ell →
          ∀ alpha : RationalSingularCohomology H.analytification (2 * p),
            alpha ∈ rationalHodgeSubspace (H.hodgeBigrading p) →
            ell alpha = 0 := by
  rw [bigradedBettiHodgeStatement_iff_atomic_span V H]
  constructor
  · intro h p
    exact (hodgeSubspace_le_atomicSpan_iff_annihilator V H p).mp (h p)
  · intro h p
    exact (hodgeSubspace_le_atomicSpan_iff_annihilator V H p).mpr (h p)

/-- Contrapositive witness form: failure of the Stage-2G target produces a
specific weight, Hodge class and rational detector separating that class from
all genuine algebraic atoms. -/
theorem not_bigradedBettiHodgeStatement_iff_exists_atomic_separator
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V) :
    ¬ BigradedBettiHodgeStatement V H ↔
      ∃ p : Nat,
      ∃ alpha : RationalSingularCohomology H.analytification (2 * p),
        alpha ∈ rationalHodgeSubspace (H.hodgeBigrading p) ∧
        ∃ ell :
          RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ] ℚ,
          AnnihilatesPointCycleClasses p (H.cycleClass p) ell ∧
          ell alpha ≠ 0 := by
  constructor
  · intro hnot
    rw [bigradedBettiHodgeStatement_iff_atomic_span V H] at hnot
    push_neg at hnot
    obtain ⟨p, hle⟩ := hnot
    have hle' : ¬ (∀ ⦃α : RationalSingularCohomology H.analytification (2 * p)⦄,
        α ∈ rationalHodgeSubspace (H.hodgeBigrading p) →
        α ∈ pointCycleClassSpan p (H.cycleClass p)) := hle
    push_neg at hle'
    obtain ⟨alpha, halpha, hnotmem⟩ := hle'
    obtain ⟨ell, hellSpan, hellAlpha⟩ :=
      exists_linearFunctional_separating_submodule
        (pointCycleClassSpan p (H.cycleClass p)) alpha hnotmem
    refine ⟨p, alpha, halpha, ell, ?_, hellAlpha⟩
    intro x
    apply hellSpan
    exact Submodule.subset_span ⟨x, rfl⟩
  · rintro ⟨p, alpha, halpha, ell, hellAtoms, hellAlpha⟩ hHodge
    have hsep :=
      (bigradedBettiHodgeStatement_iff_no_atomic_separator V H).mp
        hHodge p ell hellAtoms alpha halpha
    exact hellAlpha hsep

#check exists_linearFunctional_separating_submodule
#check AnnihilatesPointCycleClasses
#check annihilatesPointCycles_iff_atomicSpan_le_ker
#check hodgeSubspace_le_atomicSpan_iff_annihilator
#check bigradedBettiHodgeStatement_iff_no_atomic_separator
#check not_bigradedBettiHodgeStatement_iff_exists_atomic_separator

#print axioms exists_linearFunctional_separating_submodule
#print axioms hodgeSubspace_le_atomicSpan_iff_annihilator
#print axioms bigradedBettiHodgeStatement_iff_no_atomic_separator
#print axioms not_bigradedBettiHodgeStatement_iff_exists_atomic_separator

end GSTClassicalHodgeAtomicAnnihilator
