import GSTClassicalHodgeGeometricCycleClassSpine
import GSTClassicalHodgeLimitlessTowerOrbitCrown
import GSTClassicalHodgeLimitlessProjectiveLefschetzTower
import GSTClassicalHodgeRankFreeArsenalIrreducibility

/-!
# GST CLASSICAL HODGE — LIMITLESS SPINE PROPAGATION

The earlier projective/cosmic tower crown packaged a family of Hodge seeds and
its successor formula as data.  That is unnecessary once the genuine
cycle-class spine has been constructed.

The native projective successor operator already exists geometrically.  The
spine gives its exact cohomological realization and proves Hodge-sector
preservation.  The limitless cosmic Lefschetz theory supplies the canonical
nonzero successor scalar.  Therefore both the native tower and its Hodge state
can be generated recursively with no separately supplied seed family or
intertwining structure.

At every step we normalize by the inverse cosmic coefficient.  Naturality of
the spine then proves that the recursively generated native cycle has exactly
the recursively generated Hodge class.

The strengthened layer below also isolates a conserved geometric charge.  A
single native readout, a compatible cohomological readout, one nonzero base
value, and one successor transport law force the normalized charge to remain
constant through the entire unbounded projective tower.  Consequently the
cycle class of every tower level is nonzero.  This reduces infinitely many
nonvanishing obligations to one base case and one recursive geometric law.
-/

set_option maxHeartbeats 90000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeLimitlessSpinePropagation

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeRankFreeArsenalIrreducibility
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgePrincipalCutSuccessorOperator
open GSTClassicalHodgeCodimensionZeroFundamentalCycle
open GSTClassicalHodgeLimitlessTowerOrbitCrown

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}

/-- Canonical Hodge state generated recursively by the genuine projective
principal-cut cohomology action and normalized by the true limitless cosmic
Lefschetz coefficient. -/
noncomputable def spineHodgeSeed
    (G : GeometricCycleClassSpine V H) :
    (p : Nat) → ClassicalHodgeFiber V H p
  | 0 =>
      ⟨H.cycleClass 0 (codimensionZeroFundamentalCycle V),
        G.codimensionZeroFundamentalClass_is_hodge⟩
  | p + 1 =>
      let prev := spineHodgeSeed G p
      let raw := (G.principalCutPair p).cohomologyOperator prev.1
      ⟨(successorScalar p)⁻¹ • raw,
        (rationalHodgeSubspace (H.hodgeBigrading (p + 1))).smul_mem
          ((successorScalar p)⁻¹)
          (G.principalCut_hodge p prev.1 prev.2)⟩

/-- Canonical native cycle generated by the same recursively normalized
projective principal-cut operator. -/
noncomputable def spineNativeTower
    (G : GeometricCycleClassSpine V H) :
    (p : Nat) → codimensionCycles V.X p
  | 0 => codimensionZeroFundamentalCycle V
  | p + 1 =>
      (successorScalar p)⁻¹ •
        successorNativeOperator V p (spineNativeTower G p)

@[simp]
theorem spineHodgeSeed_zero
    (G : GeometricCycleClassSpine V H) :
    spineHodgeSeed G 0 =
      ⟨H.cycleClass 0 (codimensionZeroFundamentalCycle V),
        G.codimensionZeroFundamentalClass_is_hodge⟩ := by
  rfl

@[simp]
theorem spineNativeTower_zero
    (G : GeometricCycleClassSpine V H) :
    spineNativeTower G 0 = codimensionZeroFundamentalCycle V := by
  rfl

/-- The unnormalized cohomological principal-cut image is exactly the true
cosmic successor coefficient times the normalized next Hodge seed. -/
theorem spineHodgeSeed_successor_formula
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    (G.principalCutPair p).cohomologyOperator (spineHodgeSeed G p).1 =
      successorScalar p • (spineHodgeSeed G (p + 1)).1 := by
  change (G.principalCutPair p).cohomologyOperator (spineHodgeSeed G p).1 =
    successorScalar p •
      ((successorScalar p)⁻¹ •
        (G.principalCutPair p).cohomologyOperator (spineHodgeSeed G p).1)
  rw [smul_smul]
  simp [successorScalar_ne_zero]

/-- Native recursion law. -/
theorem spineNativeTower_succ
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    spineNativeTower G (p + 1) =
      (successorScalar p)⁻¹ •
        successorNativeOperator V p (spineNativeTower G p) := by
  rfl

/-- **EXACT SPINE-TOWER CYCLE-CLASS LAW.**
The recursively generated native projective cycle has cycle class exactly equal
to the recursively generated genuine Hodge state in every weight. -/
theorem spineNativeTower_cycleClass
    (G : GeometricCycleClassSpine V H) :
    ∀ p : Nat,
      H.cycleClass p (spineNativeTower G p) = (spineHodgeSeed G p).1 := by
  intro p
  induction p with
  | zero => rfl
  | succ p ih =>
      rw [spineNativeTower_succ]
      rw [LinearMap.map_smul]
      have hnat := (G.principalCutPair p).cycleClass_natural
        (spineNativeTower G p)
      rw [G.principalCutPair_native p] at hnat
      rw [hnat, ih]
      rfl

/-- Every recursively generated Hodge state is algebraic, because it is the
actual class of the recursively generated native projective cycle. -/
theorem spineHodgeSeed_algebraic
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    spineHodgeSeed G p ∈ AlgebraicHodgeSubspace V H p := by
  rw [mem_AlgebraicHodgeSubspace_iff]
  rw [← GSTClassicalHodgeAtomicSpan.smoothProjective_cycleClass_range_eq_atomic_span
    V H p]
  exact ⟨spineNativeTower G p, spineNativeTower_cycleClass G p⟩

/-- Nonvanishing of the recursively generated cycle class is exactly
nonvanishing of the corresponding Hodge seed. -/
theorem spineHodgeSeed_ne_zero_iff_cycleClass_ne_zero
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    spineHodgeSeed G p ≠ 0 ↔
      H.cycleClass p (spineNativeTower G p) ≠ 0 := by
  rw [spineNativeTower_cycleClass G p]
  constructor
  · intro h hval
    apply h
    apply Subtype.ext
    exact hval
  · intro h hseed
    apply h
    simpa [hseed]

/-! ## Conserved geometric charge

The previous theorem identifies the exact remaining nonvanishing question.  We
now compress the whole infinite tower to a conserved one-dimensional readout.
This package is deliberately weaker than Hodge surjectivity and contains no
basis-cycle witness: it only says that one geometric charge is visible both on
native cycles and after applying the genuine cycle-class map, and that the
unnormalized principal cut multiplies that charge by the same scalar used to
normalize the limitless tower. -/

/-- A conserved native/cohomological charge for the canonical projective spine.

`nativeRead` measures a rational charge on native codimension cycles.
`cohomologyRead` measures the same charge after geometric realization.
`cycleClass_read` is the separating square between the two measurements.
`base_ne_zero` is one codimension-zero geometric fact.
`successor_read` is the single recursive transport law.

Because `spineNativeTower` divides by `successorScalar p`, the measured charge
is exactly conserved at every weight. -/
structure SpineTowerConservedCharge
    (G : GeometricCycleClassSpine V H) where
  nativeRead :
    ∀ p : Nat, codimensionCycles V.X p →ₗ[ℚ] ℚ
  cohomologyRead :
    ∀ p : Nat,
      RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ] ℚ
  cycleClass_read :
    ∀ p : Nat, ∀ Z : codimensionCycles V.X p,
      cohomologyRead p (H.cycleClass p Z) = nativeRead p Z
  base_ne_zero :
    nativeRead 0 (codimensionZeroFundamentalCycle V) ≠ 0
  successor_read :
    ∀ p : Nat, ∀ Z : codimensionCycles V.X p,
      nativeRead (p + 1) (successorNativeOperator V p Z) =
        successorScalar p * nativeRead p Z

namespace SpineTowerConservedCharge

/-- **CONSERVATION LAW.**  The normalized projective tower has exactly the
same native charge in every weight as its codimension-zero fundamental seed. -/
theorem nativeRead_spineNativeTower
    (D : SpineTowerConservedCharge (V := V) (H := H) G) :
    ∀ p : Nat,
      D.nativeRead p (spineNativeTower G p) =
        D.nativeRead 0 (codimensionZeroFundamentalCycle V) := by
  intro p
  induction p with
  | zero => rfl
  | succ p ih =>
      rw [spineNativeTower_succ]
      rw [LinearMap.map_smul]
      rw [D.successor_read p (spineNativeTower G p)]
      simp [successorScalar_ne_zero, ih]

/-- The conserved native charge is nonzero at every level of the unbounded
normalized projective tower. -/
theorem nativeRead_spineNativeTower_ne_zero
    (D : SpineTowerConservedCharge (V := V) (H := H) G)
    (p : Nat) :
    D.nativeRead p (spineNativeTower G p) ≠ 0 := by
  rw [D.nativeRead_spineNativeTower p]
  exact D.base_ne_zero

/-- Compatibility of the charge with the actual cycle-class map converts the
native conservation law into genuine cohomological nonvanishing. -/
theorem cycleClass_spineNativeTower_ne_zero
    (D : SpineTowerConservedCharge (V := V) (H := H) G)
    (p : Nat) :
    H.cycleClass p (spineNativeTower G p) ≠ 0 := by
  intro hz
  have hcompat := D.cycleClass_read p (spineNativeTower G p)
  rw [hz] at hcompat
  simp only [LinearMap.map_zero] at hcompat
  exact D.nativeRead_spineNativeTower_ne_zero p hcompat.symm

/-- Hence every recursively generated Hodge seed is nonzero.  No per-weight
nonvanishing assumption remains once the conserved charge is constructed. -/
theorem spineHodgeSeed_ne_zero
    (D : SpineTowerConservedCharge (V := V) (H := H) G)
    (p : Nat) :
    spineHodgeSeed G p ≠ 0 :=
  (spineHodgeSeed_ne_zero_iff_cycleClass_ne_zero G p).2
    (D.cycleClass_spineNativeTower_ne_zero p)

/-- The conserved charge simultaneously certifies that the algebraic Hodge
subspace is nontrivial in every weight. -/
theorem algebraicHodgeSubspace_ne_bot
    (D : SpineTowerConservedCharge (V := V) (H := H) G)
    (p : Nat) :
    AlgebraicHodgeSubspace V H p ≠ ⊥ :=
  algebraicHodgeSubspace_ne_bot_of_spineSeed G p
    (D.spineHodgeSeed_ne_zero p)

end SpineTowerConservedCharge

/-- Whenever the canonical spine tower is nonzero in a weight, it supplies the
nontrivial algebraic Hodge subspace required by rank-free limitless
irreducibility. -/
theorem algebraicHodgeSubspace_ne_bot_of_spineSeed
    (G : GeometricCycleClassSpine V H)
    (p : Nat)
    (hne : spineHodgeSeed G p ≠ 0) :
    AlgebraicHodgeSubspace V H p ≠ ⊥ := by
  intro hbot
  have hmem := spineHodgeSeed_algebraic G p
  rw [hbot] at hmem
  have hz : spineHodgeSeed G p = 0 := by simpa using hmem
  exact hne hz

/-- The old tower-intertwining successor formula is now a theorem generated
from the spine rather than supplied as data. -/
theorem spine_limitless_successor_crown
    (G : GeometricCycleClassSpine V H) :
    ∀ p : Nat,
      (G.principalCutPair p).cohomologyOperator (spineHodgeSeed G p).1 =
        successorScalar p • (spineHodgeSeed G (p + 1)).1
      ∧ H.cycleClass (p + 1) (spineNativeTower G (p + 1)) =
        (spineHodgeSeed G (p + 1)).1 := by
  intro p
  exact ⟨spineHodgeSeed_successor_formula G p,
    spineNativeTower_cycleClass G (p + 1)⟩

#check spineHodgeSeed
#check spineNativeTower
#check spineHodgeSeed_successor_formula
#check spineNativeTower_cycleClass
#check spineHodgeSeed_algebraic
#check spineHodgeSeed_ne_zero_iff_cycleClass_ne_zero
#check SpineTowerConservedCharge
#check SpineTowerConservedCharge.nativeRead_spineNativeTower
#check SpineTowerConservedCharge.nativeRead_spineNativeTower_ne_zero
#check SpineTowerConservedCharge.cycleClass_spineNativeTower_ne_zero
#check SpineTowerConservedCharge.spineHodgeSeed_ne_zero
#check SpineTowerConservedCharge.algebraicHodgeSubspace_ne_bot
#check algebraicHodgeSubspace_ne_bot_of_spineSeed
#check spine_limitless_successor_crown

#print axioms spineHodgeSeed_successor_formula
#print axioms spineNativeTower_cycleClass
#print axioms spineHodgeSeed_algebraic
#print axioms SpineTowerConservedCharge.nativeRead_spineNativeTower
#print axioms SpineTowerConservedCharge.cycleClass_spineNativeTower_ne_zero
#print axioms SpineTowerConservedCharge.spineHodgeSeed_ne_zero
#print axioms SpineTowerConservedCharge.algebraicHodgeSubspace_ne_bot
#print axioms spine_limitless_successor_crown

end GSTClassicalHodgeLimitlessSpinePropagation
