import GSTClassicalHodgePointNormalForm

/-!
# GST CLASSICAL HODGE — ATOMIC CYCLE-CLASS SPAN

The limitless global atlas normal form can be compressed further without
choosing a Hodge basis.  On a smooth projective carrier every native
codimension-p algebraic cycle has finite global support, hence is a finite
rational combination of genuine codimension-p point cycles.

Consequently the range of the full native cycle-class map is exactly the
linear span of the classes of those point cycles.  The Stage-2G Hodge target
can therefore be expressed as one basis-free submodule inclusion in every
weight.
-/

set_option maxHeartbeats 10000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry
open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTNativeCodimensionCyclePresentation
open GSTCompactNativeCyclePresentation
open GSTClassicalHodgePointNormalForm

namespace GSTClassicalHodgeAtomicSpan

universe u v

variable {X : Scheme.{u}}
variable {Coh : Type v} [AddCommGroup Coh] [Module ℚ Coh]

/-- The genuine codimension-p atomic cycle classes for a supplied rational
cycle-class map. -/
def pointCycleClassSet
    (p : Nat)
    (cl : codimensionCycles X p →ₗ[ℚ] Coh) : Set Coh :=
  Set.range (fun x : CodimensionPoint X p =>
    cl (codimensionPointCycle X p x))

/-- Basis-free submodule generated by all genuine codimension-p point-cycle
classes. -/
def pointCycleClassSpan
    (p : Nat)
    (cl : codimensionCycles X p →ₗ[ℚ] Coh) : Submodule ℚ Coh :=
  Submodule.span ℚ (pointCycleClassSet p cl)

/-- The finite-presentation class map.  This is the free linear extension of
point-cycle classes from genuine codimension-p points. -/
noncomputable def finitePointCycleClassMap
    (p : Nat)
    (cl : codimensionCycles X p →ₗ[ℚ] Coh) :
    FiniteCodimensionPresentation X p →ₗ[ℚ] Coh :=
  Finsupp.total (CodimensionPoint X p) Coh ℚ
    (fun x => cl (codimensionPointCycle X p x))

/-- The free point-class map computes exactly the supplied cycle class of the
native finite presentation. -/
theorem finitePointCycleClassMap_eq_cycleClass_realize
    (p : Nat)
    (cl : codimensionCycles X p →ₗ[ℚ] Coh)
    (φ : FiniteCodimensionPresentation X p) :
    finitePointCycleClassMap p cl φ =
      cl (realizeFiniteCodimensionPresentation X p φ) := by
  classical
  rw [linearMap_realizeFiniteCodimensionPresentation]
  rfl

/-- The range of the free point-class map is exactly the span of genuine
codimension-p point-cycle classes. -/
theorem range_finitePointCycleClassMap
    (p : Nat)
    (cl : codimensionCycles X p →ₗ[ℚ] Coh) :
    LinearMap.range (finitePointCycleClassMap p cl) =
      pointCycleClassSpan p cl := by
  simpa [finitePointCycleClassMap, pointCycleClassSpan, pointCycleClassSet]
    using Finsupp.range_total (R := ℚ)
      (M := Coh)
      (v := fun x : CodimensionPoint X p =>
        cl (codimensionPointCycle X p x))

/-- On a compact carrier, every class in the full native cycle-class range
already lies in the atomic point-cycle span. -/
theorem cycleClass_range_le_pointCycleClassSpan
    [CompactSpace X]
    (p : Nat)
    (cl : codimensionCycles X p →ₗ[ℚ] Coh) :
    LinearMap.range cl ≤ pointCycleClassSpan p cl := by
  intro alpha halpha
  rcases halpha with ⟨Z, rfl⟩
  let φ := presentationOfNativeCycle X p Z
  have hround : realizeFiniteCodimensionPresentation X p φ = Z := by
    exact realize_presentationOfNativeCycle X p Z
  rw [← hround]
  rw [← finitePointCycleClassMap_eq_cycleClass_realize p cl φ]
  rw [← range_finitePointCycleClassMap p cl]
  exact ⟨φ, rfl⟩

/-- Every point-cycle class belongs to the full native cycle-class range, so
its span does as well. -/
theorem pointCycleClassSpan_le_cycleClass_range
    (p : Nat)
    (cl : codimensionCycles X p →ₗ[ℚ] Coh) :
    pointCycleClassSpan p cl ≤ LinearMap.range cl := by
  rw [← range_finitePointCycleClassMap p cl]
  rintro alpha ⟨φ, rfl⟩
  refine ⟨realizeFiniteCodimensionPresentation X p φ, ?_⟩
  symm
  exact finitePointCycleClassMap_eq_cycleClass_realize p cl φ

/-- **ATOMIC RANGE THEOREM.**  On a compact scheme the full native
codimension-p cycle-class range equals the span of genuine codimension-p
point-cycle classes. -/
theorem cycleClass_range_eq_pointCycleClassSpan
    [CompactSpace X]
    (p : Nat)
    (cl : codimensionCycles X p →ₗ[ℚ] Coh) :
    LinearMap.range cl = pointCycleClassSpan p cl := by
  apply le_antisymm
  · exact cycleClass_range_le_pointCycleClassSpan p cl
  · exact pointCycleClassSpan_le_cycleClass_range p cl

/-- Smooth projectivity supplies compactness, so the atomic range theorem
applies directly to every Stage-2G cycle-class map. -/
theorem smoothProjective_cycleClass_range_eq_atomic_span
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V)
    (p : Nat) :
    LinearMap.range (H.cycleClass p) =
      pointCycleClassSpan p (H.cycleClass p) := by
  letI : CompactSpace V.X := smoothProjectiveCompactSpace V
  exact cycleClass_range_eq_pointCycleClassSpan p (H.cycleClass p)

/-- **BASIS-FREE CLASSICAL HODGE NORMAL FORM.**  The genuine Stage-2G Hodge
statement is equivalent to saying that, in every codimension, the rational
`(p,p)` Hodge subspace is contained in the span of the classes of genuine
codimension-p point cycles. -/
theorem bigradedBettiHodgeStatement_iff_atomic_span
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V) :
    BigradedBettiHodgeStatement V H ↔
      ∀ p : Nat,
        rationalHodgeSubspace (H.hodgeBigrading p) ≤
          pointCycleClassSpan p (H.cycleClass p) := by
  constructor
  · intro h p alpha halpha
    rcases h p halpha with ⟨Z, hZ⟩
    rw [← smoothProjective_cycleClass_range_eq_atomic_span V H p]
    exact ⟨Z, hZ⟩
  · intro h p alpha halpha
    have hspan := h p halpha
    rw [← smoothProjective_cycleClass_range_eq_atomic_span V H p] at hspan
    exact hspan

/-- Atomic-span version of the classical target with the limitless GST
fibered theorem attached weight by weight. -/
theorem atomic_span_with_limitless_cosmic_crown
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V) :
    BigradedBettiHodgeStatement V H ↔
      (∀ p : Nat,
        rationalHodgeSubspace (H.hodgeBigrading p) ≤
          pointCycleClassSpan p (H.cycleClass p))
      ∧ (∀ p : Nat, ∀ i :
          GSTClassicalHodgeFiberedCosmology.ClassicalHodgeBasisIndex V H p,
        GSTClassicalHodgeFiberedCosmology.forgetMultiplicityToGST
            (GSTClassicalHodgeFiberedCosmology.fiberedWeightCoordinates
              V H p
              (GSTClassicalHodgeFiberedCosmology.classicalHodgeBasis V H p i)) =
          Finsupp.single
            (GSTUniversalAddressBridge.cosmicAddressEquiv (p, p)) 1) := by
  constructor
  · intro h
    refine ⟨(bigradedBettiHodgeStatement_iff_atomic_span V H).mp h, ?_⟩
    exact GSTClassicalHodgeFiberedCosmology.classical_basis_projects_to_cosmic_diagonal V H
  · rintro ⟨hspan, _hcosmic⟩
    exact (bigradedBettiHodgeStatement_iff_atomic_span V H).mpr hspan

#check pointCycleClassSet
#check pointCycleClassSpan
#check finitePointCycleClassMap
#check finitePointCycleClassMap_eq_cycleClass_realize
#check range_finitePointCycleClassMap
#check cycleClass_range_le_pointCycleClassSpan
#check pointCycleClassSpan_le_cycleClass_range
#check cycleClass_range_eq_pointCycleClassSpan
#check smoothProjective_cycleClass_range_eq_atomic_span
#check bigradedBettiHodgeStatement_iff_atomic_span
#check atomic_span_with_limitless_cosmic_crown

#print axioms cycleClass_range_eq_pointCycleClassSpan
#print axioms smoothProjective_cycleClass_range_eq_atomic_span
#print axioms bigradedBettiHodgeStatement_iff_atomic_span
#print axioms atomic_span_with_limitless_cosmic_crown

end GSTClassicalHodgeAtomicSpan
