import GSTClassicalHodgePrimitiveProjectiveDefectModule

/-!
# GST CLASSICAL HODGE — PRIMITIVE PROJECTIVE FAILURE CROWN

This module assembles the latest noncircular reductions into one first-failure
statement.

Assume the standard geometric infrastructure now isolated in the repository:

* genuine cycle-class geometry with Hodge-functorial projective pushforwards;
* projective-degree trace semantics;
* a purely cohomological Lefschetz/primitive decomposition;
* one known algebraic nonzero-trace anchor at the failed weight.

If weight p has zero atomic Hodge defect but weight p+1 does not, then the new
obstruction is forced into the primitive sector.  That primitive defect then
produces a trace-zero Hodge ghost carrying:

* nonzero atomic defect;
* a separator annihilating every algebraic point-cycle class;
* a nonzero full-fibered tomography moment;
* a nonzero rational module generated by the actual projective endomorphism
  word algebra, stable under every genuine projective word.

No same-weight GST matrix unit is externalized.  No normalized spectral atom is
declared defect-free.  No projective image of an algebraic source is required
to have nonzero separator read.  The surviving object is the defect module
itself.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgePrimitiveProjectiveFailureCrown

open GSTClassicalHodgeAtomicDefectDuality
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeProjectiveDegreeTrace
open GSTClassicalHodgePrimitiveAtomicDefectReduction
open GSTClassicalHodgePrimitiveDefectTomographyGhost
open GSTClassicalHodgeAtomicDefectTraceNormalization
open GSTClassicalHodgeTraceZeroPrimitiveTomographyGhost
open GSTClassicalHodgeHodgeFunctorialProjectiveDynamics
open GSTClassicalHodgePrimitiveProjectiveDefectModule

variable {V : GSTProjectiveOverC.SmoothProjectiveComplexScheme}
variable {H : GSTGeometricRealizationStage2G.HodgeBigradedBettiData V}
variable {p : Nat}

/-- Complete packet attached to one first positive-weight defect. -/
structure PrimitiveProjectiveFailurePacket
    (R : HodgeFunctorialGeometricSemantics V H)
    (T : ProjectiveDegreeTraceSemantics V H)
    (D : LefschetzPrimitiveDecomposition R.spine)
    (A : TraceAnchor R.spine T p) where
  ghost : TraceZeroPrimitiveTomographyGhost A D
  projectiveModuleNonzero :
    HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.defectOrbitModule
        (R := R) ghost.defectState ≠ ⊥
  projectiveModuleInvariant :
    ∀ w : HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord R p,
    ∀ z ∈
      HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.defectOrbitModule
        (R := R) ghost.defectState,
      w.defectOperator z ∈
        HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.defectOrbitModule
          (R := R) ghost.defectState

/-- A nonzero primitive defect canonically produces the full projective failure
packet. -/
noncomputable def packetOfPrimitiveDefect
    (R : HodgeFunctorialGeometricSemantics V H)
    (T : ProjectiveDegreeTraceSemantics V H)
    (D : LefschetzPrimitiveDecomposition R.spine)
    (A : TraceAnchor R.spine T p)
    (hprim : D.primitiveDefectMap p ≠ 0) :
    PrimitiveProjectiveFailurePacket R T D A := by
  let E : TraceZeroPrimitiveTomographyGhost A D :=
    Classical.choice
      (primitiveDefect_yields_traceZeroTomographyGhost
        (D := D) A hprim)
  refine {
    ghost := E
    projectiveModuleNonzero :=
      primitiveGhost_projectiveDefectModule_ne_bot
        (R := R) (D := D) (T := T) (A := A) E
    projectiveModuleInvariant := ?_
  }
  intro w z hz
  exact
    HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.defectOrbitModule_invariant
      w E.defectState z hz

/-- **FIRST-FAILURE TRANSFORMATION.**
If weight p is defect-free and weight p+1 fails, the failure becomes a
trace-zero primitive projective defect module at weight p+1. -/
noncomputable def packetOfNextWeightFailure
    (R : HodgeFunctorialGeometricSemantics V H)
    (T : ProjectiveDegreeTraceSemantics V H)
    (D : LefschetzPrimitiveDecomposition R.spine)
    (A : TraceAnchor R.spine T (p + 1))
    (hsource : atomicDefectLinearMap V H p = 0)
    (htarget : atomicDefectLinearMap V H (p + 1) ≠ 0) :
    PrimitiveProjectiveFailurePacket R T D A := by
  have hprim : D.primitiveDefectMap (p + 1) ≠ 0 :=
    D.primitiveDefect_ne_zero_of_target_ne_zero p hsource htarget
  exact packetOfPrimitiveDefect R T D A hprim

/-- Elementwise first-failure form exposing all four nonzero/invariance facts. -/
theorem nextWeightFailure_yields_projectivePrimitiveGhost
    (R : HodgeFunctorialGeometricSemantics V H)
    (T : ProjectiveDegreeTraceSemantics V H)
    (D : LefschetzPrimitiveDecomposition R.spine)
    (A : TraceAnchor R.spine T (p + 1))
    (hsource : atomicDefectLinearMap V H p = 0)
    (htarget : atomicDefectLinearMap V H (p + 1) ≠ 0) :
    ∃ E : TraceZeroPrimitiveTomographyGhost A D,
      E.defectState ≠ 0
      ∧ E.source.detector E.traceZeroClass.1 ≠ 0
      ∧ E.tomography_nonzero
      ∧ HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.defectOrbitModule
          (R := R) E.defectState ≠ ⊥ := by
  let P := packetOfNextWeightFailure R T D A hsource htarget
  exact ⟨P.ghost,
    P.ghost.defectState_ne_zero,
    P.ghost.separator_detects,
    P.ghost.tomography_nonzero,
    P.projectiveModuleNonzero⟩

/-- Any theorem excluding these nonzero primitive projective packets at every
successor weight propagates zero atomic defect inductively from weight zero. -/
theorem all_atomicDefects_zero_of_no_projectivePrimitivePackets
    (R : HodgeFunctorialGeometricSemantics V H)
    (T : ProjectiveDegreeTraceSemantics V H)
    (D : LefschetzPrimitiveDecomposition R.spine)
    (anchor : ∀ q : Nat, TraceAnchor R.spine T q)
    (hzero : atomicDefectLinearMap V H 0 = 0)
    (hexclude :
      ∀ q : Nat,
        IsEmpty (PrimitiveProjectiveFailurePacket R T D (anchor (q + 1)))) :
    ∀ q : Nat, atomicDefectLinearMap V H q = 0 := by
  intro q
  induction q with
  | zero => exact hzero
  | succ q ih =>
      by_contra hbad
      have P := packetOfNextWeightFailure
        R T D (anchor (q + 1)) ih hbad
      exact (hexclude q).false P

/-- **PROJECTIVE PRIMITIVE FAILURE CROWN.**
Excluding the transformed primitive projective modules, together with the
weight-zero base case, proves the full Stage-2G Hodge statement. -/
theorem bigradedBettiHodge_of_no_projectivePrimitivePackets
    (R : HodgeFunctorialGeometricSemantics V H)
    (T : ProjectiveDegreeTraceSemantics V H)
    (D : LefschetzPrimitiveDecomposition R.spine)
    (anchor : ∀ q : Nat, TraceAnchor R.spine T q)
    (hzero : atomicDefectLinearMap V H 0 = 0)
    (hexclude :
      ∀ q : Nat,
        IsEmpty (PrimitiveProjectiveFailurePacket R T D (anchor (q + 1)))) :
    GSTGeometricRealizationStage2G.BigradedBettiHodgeStatement V H := by
  exact (bigradedBettiHodgeStatement_iff_atomicDefect_zero V H).2
    (all_atomicDefects_zero_of_no_projectivePrimitivePackets
      R T D anchor hzero hexclude)

#check PrimitiveProjectiveFailurePacket
#check packetOfPrimitiveDefect
#check packetOfNextWeightFailure
#check nextWeightFailure_yields_projectivePrimitiveGhost
#check all_atomicDefects_zero_of_no_projectivePrimitivePackets
#check bigradedBettiHodge_of_no_projectivePrimitivePackets

#print axioms packetOfPrimitiveDefect
#print axioms packetOfNextWeightFailure
#print axioms nextWeightFailure_yields_projectivePrimitiveGhost
#print axioms all_atomicDefects_zero_of_no_projectivePrimitivePackets
#print axioms bigradedBettiHodge_of_no_projectivePrimitivePackets

end GSTClassicalHodgePrimitiveProjectiveFailureCrown
