import GSTClassicalHodgeFiniteSpineMomentOrbit
import GSTClassicalHodgeKernelStableOperatorAlgebra
import GSTClassicalHodgePrimitivePushforwardNaturality

/-!
# GST CLASSICAL HODGE — PROJECTIVE WORD ORBIT

The rational projective-correspondence span is closed under linear
combinations, but the GST arsenal is intrinsically noncommutative: projectors,
Lefschetz moves and recoordination are assembled by composition as well as by
addition and scaling.

Instead of pretending that a composite filtered native pushforward is itself
the pushforward of one scheme endomorphism, this module builds the honest
free finite operator-word closure generated by actual projective self-maps.
Its primitives are genuine scheme endomorphisms; its constructors are exactly
the operator operations already used by the limitless cosmology:

* identity;
* addition;
* rational scaling;
* noncommutative composition.

Every primitive has kernel stability from genuine cycle-class functoriality,
and the existing kernel-stable operator algebra propagates that law through
all finite words.  Hence every projective word automatically acquires a
canonical ambient cohomological realization with an exact cycle-class square.

Combining this word algebra with the finite relevant-spine moment crown removes
another unnecessary restriction: the live-source target operator no longer
has to belong to the mere linear span of primitive pushforwards.  It may be an
arbitrarily deep finite noncommutative word in actual geometric transports.
-/

set_option maxHeartbeats 90000000
set_option maxRecDepth 1000000

noncomputable section

open CategoryTheory
open AlgebraicGeometry

namespace GSTClassicalHodgeProjectiveWordOrbit

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeRankFreeArsenalIrreducibility
open GSTClassicalHodgeProjectivePointTransport
open GSTClassicalHodgeNativeOperatorCohomologyRealization
open GSTClassicalHodgeKernelStableOperatorAlgebra
open GSTClassicalHodgePrimitivePushforwardNaturality
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeLimitlessSpinePropagation
open GSTClassicalHodgeSynchronizedDefectOrbit
open GSTClassicalHodgeFiniteSpineMomentOrbit
open GSTClassicalHodgeRankFreeLimitlessAssembly

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-- Free finite noncommutative word algebra generated by genuine projective
self-transports.  This is syntax for geometric operator construction, not a
claim that a composite word is one primitive scheme pushforward. -/
inductive ProjectiveOperatorWord
    (V : SmoothProjectiveComplexScheme)
    (p : Nat) : Type
  | id : ProjectiveOperatorWord V p
  | geometric (f : V.X ⟶ V.X) : ProjectiveOperatorWord V p
  | add (A B : ProjectiveOperatorWord V p) : ProjectiveOperatorWord V p
  | smul (q : ℚ) (A : ProjectiveOperatorWord V p) : ProjectiveOperatorWord V p
  | comp (A B : ProjectiveOperatorWord V p) : ProjectiveOperatorWord V p

namespace ProjectiveOperatorWord

/-- Native-cycle interpretation of one finite projective operator word. -/
noncomputable def eval :
    ProjectiveOperatorWord V p →
      (codimensionCycles V.X p →ₗ[ℚ] codimensionCycles V.X p)
  | .id => LinearMap.id
  | .geometric f => smoothProjectiveNativePushforward V f p
  | .add A B => A.eval + B.eval
  | .smul q A => q • A.eval
  | .comp A B => A.eval.comp B.eval

@[simp]
theorem eval_id :
    (ProjectiveOperatorWord.id (V := V) (p := p)).eval = LinearMap.id :=
  rfl

@[simp]
theorem eval_geometric
    (f : V.X ⟶ V.X) :
    (ProjectiveOperatorWord.geometric (V := V) (p := p) f).eval =
      smoothProjectiveNativePushforward V f p :=
  rfl

@[simp]
theorem eval_add
    (A B : ProjectiveOperatorWord V p) :
    (ProjectiveOperatorWord.add A B).eval = A.eval + B.eval :=
  rfl

@[simp]
theorem eval_smul
    (q : ℚ) (A : ProjectiveOperatorWord V p) :
    (ProjectiveOperatorWord.smul q A).eval = q • A.eval :=
  rfl

@[simp]
theorem eval_comp
    (A B : ProjectiveOperatorWord V p) :
    (ProjectiveOperatorWord.comp A B).eval = A.eval.comp B.eval :=
  rfl

/-- **GEOMETRIC WORD KERNEL STABILITY.**
Every finite noncommutative projective word preserves the kernel of the genuine
cycle-class map.  The only geometric input is primitive pushforward
functoriality already contained in the genuine cycle-class spine. -/
theorem eval_kernelStable
    (G : GeometricCycleClassSpine V H) :
    ∀ W : ProjectiveOperatorWord V p,
      KernelStable (H := H) W.eval
  | .id => id_kernelStable
  | .geometric f => (G.pushforward_naturality p f).kernelStable
  | .add A B =>
      add_kernelStable (eval_kernelStable G A) (eval_kernelStable G B)
  | .smul q A =>
      smul_kernelStable q (eval_kernelStable G A)
  | .comp A B =>
      comp_kernelStable (eval_kernelStable G A) (eval_kernelStable G B)

/-- Every projective word therefore has a canonical cohomological realization
and exact cycle-class commuting square. -/
noncomputable def operatorPair
    (G : GeometricCycleClassSpine V H)
    (W : ProjectiveOperatorWord V p) :
    GSTClassicalHodgeCycleOperatorNaturality.CycleClassOperatorPair V H p :=
  toCycleClassOperatorPair W.eval (eval_kernelStable G W)

@[simp]
theorem operatorPair_cycleOperator
    (G : GeometricCycleClassSpine V H)
    (W : ProjectiveOperatorWord V p) :
    (W.operatorPair G).cycleOperator = W.eval :=
  rfl

/-- Exact naturality receipt for the interpreted projective word. -/
theorem cycleClass_eval
    (G : GeometricCycleClassSpine V H)
    (W : ProjectiveOperatorWord V p)
    (Z : codimensionCycles V.X p) :
    H.cycleClass p (W.eval Z) =
      (W.operatorPair G).cohomologyOperator (H.cycleClass p Z) := by
  exact (W.operatorPair G).cycleClass_cycleOperator Z

end ProjectiveOperatorWord

/-- A projective operator word whose canonical cohomological realization has
the required action on one selected live source state.  No behavior on any
other Hodge vector is supplied. -/
structure ProjectiveWordLiveSourceTarget
    (G : GeometricCycleClassSpine V H)
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (j : ClassicalHodgeBasisIndex V H p) where
  word : ProjectiveOperatorWord V p
  source_action :
    (word.operatorPair G).cohomologyOperator S.hodge.1 =
      (classicalHodgeBasis V H p).repr S.hodge S.sourceIndex •
        (classicalHodgeBasis V H p j).1

namespace ProjectiveWordLiveSourceTarget

/-- Normalize the geometric word image of the live native source. -/
noncomputable def targetCycle
    {G : GeometricCycleClassSpine V H}
    {S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p)}
    {j : ClassicalHodgeBasisIndex V H p}
    (R : ProjectiveWordLiveSourceTarget G S j) :
    codimensionCycles V.X p :=
  let c := (classicalHodgeBasis V H p).repr S.hodge S.sourceIndex
  c⁻¹ • R.word.eval S.cycle

/-- **PROJECTIVE WORD ORBIT EXTRACTION.**
The normalized word image is an actual native cycle representing the requested
genuine Hodge basis direction. -/
theorem targetCycle_spec
    {G : GeometricCycleClassSpine V H}
    {S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p)}
    {j : ClassicalHodgeBasisIndex V H p}
    (R : ProjectiveWordLiveSourceTarget G S j) :
    H.cycleClass p R.targetCycle =
      (classicalHodgeBasis V H p j).1 := by
  let c := (classicalHodgeBasis V H p).repr S.hodge S.sourceIndex
  have hc : c ≠ 0 := S.sourceCoefficient_ne_zero
  have hpair := R.word.cycleClass_eval G S.cycle
  rw [S.class_eq, R.source_action] at hpair
  unfold targetCycle
  rw [LinearMap.map_smul, hpair]
  simp [c, hc]

end ProjectiveWordLiveSourceTarget

/-- Projective-word source realizations produce a genuine basis-cycle bridge. -/
noncomputable def projectiveWordBasisCycleBridge
    (G : GeometricCycleClassSpine V H)
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (R : ∀ j : ClassicalHodgeBasisIndex V H p,
      ProjectiveWordLiveSourceTarget G S j) :
    HodgeConjecture.HodgeBasisCycleBridge V H p where
  basisCycle j := (R j).targetCycle
  basisCycle_spec j := (R j).targetCycle_spec

/-- Fixed-weight Hodge landing from one live source and arbitrary finite
noncommutative projective words. -/
theorem hodge_weight_of_projective_word_live_source
    (G : GeometricCycleClassSpine V H)
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (R : ∀ j : ClassicalHodgeBasisIndex V H p,
      ProjectiveWordLiveSourceTarget G S j) :
    rationalHodgeSubspace (H.hodgeBigrading p) ≤
      LinearMap.range (H.cycleClass p) := by
  intro alpha halpha
  exact HodgeConjecture.hodge_class_has_cycle_of_basis_bridge
    V H (projectiveWordBasisCycleBridge G S R) alpha halpha

/-- **FINITE SPINE + NONCOMMUTATIVE PROJECTIVE WORD FINALE.**
Only weights with nonzero genuine Hodge fiber request a finite moment chain.
At such a weight, arbitrary-depth finite words generated by actual projective
self-transports may be used to spread the canonical live spine seed across the
entire Hodge basis. -/
theorem bigradedBettiHodge_of_finite_spine_moments_and_projective_words
    (G : GeometricCycleClassSpine V H)
    (D : ∀ q : Nat,
      rationalHodgeSubspace (H.hodgeBigrading q) ≠ ⊥ →
        FiniteSpineMomentChain G q)
    (R : ∀ q : Nat,
      ∀ hq : rationalHodgeSubspace (H.hodgeBigrading q) ≠ ⊥,
      ∀ j : ClassicalHodgeBasisIndex V H q,
        ProjectiveWordLiveSourceTarget G (D q hq).topOrbitSeed j) :
    BigradedBettiHodgeStatement V H := by
  intro q alpha halpha
  by_cases hq : rationalHodgeSubspace (H.hodgeBigrading q) = ⊥
  · have hzero : alpha = 0 := by
      have hz : alpha ∈
          (⊥ : Submodule ℚ
            (RationalSingularCohomology H.analytification (2 * q))) := by
        simpa [hq] using halpha
      simpa using hz
    subst alpha
    exact ⟨0, by simp⟩
  · exact hodge_weight_of_projective_word_live_source
      G (D q hq).topOrbitSeed (R q hq) halpha

/-- Explicit native-cycle witness form of the projective-word finale. -/
theorem every_hodge_class_has_native_cycle_of_projective_words
    (G : GeometricCycleClassSpine V H)
    (D : ∀ q : Nat,
      rationalHodgeSubspace (H.hodgeBigrading q) ≠ ⊥ →
        FiniteSpineMomentChain G q)
    (R : ∀ q : Nat,
      ∀ hq : rationalHodgeSubspace (H.hodgeBigrading q) ≠ ⊥,
      ∀ j : ClassicalHodgeBasisIndex V H q,
        ProjectiveWordLiveSourceTarget G (D q hq).topOrbitSeed j)
    (q : Nat)
    (alpha : RationalSingularCohomology H.analytification (2 * q))
    (halpha : alpha ∈ rationalHodgeSubspace (H.hodgeBigrading q)) :
    ∃ Z : codimensionCycles V.X q,
      H.cycleClass q Z = alpha := by
  exact bigradedBettiHodge_of_finite_spine_moments_and_projective_words
    G D R q halpha

#check ProjectiveOperatorWord
#check ProjectiveOperatorWord.eval
#check ProjectiveOperatorWord.eval_kernelStable
#check ProjectiveOperatorWord.operatorPair
#check ProjectiveOperatorWord.cycleClass_eval
#check ProjectiveWordLiveSourceTarget
#check ProjectiveWordLiveSourceTarget.targetCycle
#check ProjectiveWordLiveSourceTarget.targetCycle_spec
#check projectiveWordBasisCycleBridge
#check hodge_weight_of_projective_word_live_source
#check bigradedBettiHodge_of_finite_spine_moments_and_projective_words
#check every_hodge_class_has_native_cycle_of_projective_words

#print axioms ProjectiveOperatorWord.eval_kernelStable
#print axioms ProjectiveOperatorWord.cycleClass_eval
#print axioms ProjectiveWordLiveSourceTarget.targetCycle_spec
#print axioms hodge_weight_of_projective_word_live_source
#print axioms bigradedBettiHodge_of_finite_spine_moments_and_projective_words
#print axioms every_hodge_class_has_native_cycle_of_projective_words

end GSTClassicalHodgeProjectiveWordOrbit