import GSTClassicalHodgeTraceZeroAtomicOperatorRepresentation
import GSTClassicalHodgePrimitivePushforwardNaturality

/-!
# GST CLASSICAL HODGE — HODGE-FUNCTORIAL PROJECTIVE DYNAMICS

The geometric cycle-class spine already records exact cycle-class functoriality
for every actual scheme endomorphism.  To act on the genuine Hodge fiber we
also need the independent standard Hodge-theoretic fact that the corresponding
cohomological pushforward preserves Hodge type.

This file adds exactly that missing semantic artery and nothing stronger.
There is no Hodge-surjectivity field and no prescribed action on a chosen Hodge
basis.

From it we construct:

* an `AtomicNaturalHodgeOperator` for every actual scheme endomorphism;
* a syntax of genuine projective/Hodge words generated by identity,
  endomorphism pushforwards, rational sums, scalings and compositions;
* an atomic-natural Hodge operator for every such word;
* after choosing one projective-degree trace anchor, a trace-zero action of
  every genuine projective word whose atomic-defect dynamics are exactly the
  original quotient dynamics.

Thus the primitive trace-zero ghost now carries a bona fide representation of
the actual projective endomorphism algebra without any same-weight GST matrix
unit being declared geometric.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open CategoryTheory
open AlgebraicGeometry

namespace GSTClassicalHodgeHodgeFunctorialProjectiveDynamics

open GSTProjectiveOverC
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeAtomicDefectDuality
open GSTClassicalHodgeGeneratorwiseAtomicStability
open GSTClassicalHodgePrimitivePushforwardNaturality
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeAtomicDefectEquivariantIrreducibility
open GSTClassicalHodgeProjectiveDegreeTrace
open GSTClassicalHodgeAtomicDefectTraceNormalization
open GSTClassicalHodgeTraceZeroAtomicOperatorRepresentation

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-- Genuine cycle-class geometry plus standard Hodge functoriality of actual
projective self-maps.  This is strictly operator-theoretic: it does not assert
that a new Hodge vector is algebraic. -/
structure HodgeFunctorialGeometricSemantics
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V) where
  spine : GeometricCycleClassSpine V H
  pushforward_hodge :
    ∀ p : Nat, ∀ f : V.X ⟶ V.X,
    ∀ alpha : RationalSingularCohomology H.analytification (2 * p),
      alpha ∈ rationalHodgeSubspace (H.hodgeBigrading p) →
        (spine.pushforward_naturality p f).cohomologyPushforward alpha ∈
          rationalHodgeSubspace (H.hodgeBigrading p)

namespace HodgeFunctorialGeometricSemantics

/-- Hodge-fiber restriction of one actual projective pushforward. -/
noncomputable def projectivePushforwardHodge
    (R : HodgeFunctorialGeometricSemantics V H)
    (p : Nat)
    (f : V.X ⟶ V.X) :
    Module.End ℚ (ClassicalHodgeFiber V H p) where
  toFun alpha :=
    ⟨(R.spine.pushforward_naturality p f).cohomologyPushforward alpha.1,
      R.pushforward_hodge p f alpha.1 alpha.2⟩
  map_add' := by
    intro a b
    apply Subtype.ext
    simp
  map_smul' := by
    intro c a
    apply Subtype.ext
    simp

/-- **ACTUAL PROJECTIVE PUSHFORWARD IS ATOMIC-NATURAL ON HODGE.** -/
noncomputable def projectiveGenerator
    (R : HodgeFunctorialGeometricSemantics V H)
    (p : Nat)
    (f : V.X ⟶ V.X) :
    AtomicNaturalHodgeOperator V H p where
  ambient := (R.spine.pushforward_naturality p f).cohomologyPushforward
  hodge := R.projectivePushforwardHodge p f
  atomicStable :=
    (R.spine.pushforward_naturality p f).atomicSpan_stable
  restricts := by
    intro alpha
    rfl

/-- Genuine projective word syntax generated only by actual self-maps and the
rational operator algebra operations. -/
inductive ProjectiveHodgeWord
    (R : HodgeFunctorialGeometricSemantics V H)
    (p : Nat) : Type
  | id : ProjectiveHodgeWord R p
  | generator (f : V.X ⟶ V.X) : ProjectiveHodgeWord R p
  | add (u v : ProjectiveHodgeWord R p) : ProjectiveHodgeWord R p
  | smul (q : ℚ) (u : ProjectiveHodgeWord R p) : ProjectiveHodgeWord R p
  | comp (u v : ProjectiveHodgeWord R p) : ProjectiveHodgeWord R p

namespace ProjectiveHodgeWord

/-- Evaluate one genuine projective word as an atomic-natural Hodge operator. -/
noncomputable def eval
    {R : HodgeFunctorialGeometricSemantics V H}
    {p : Nat} : ProjectiveHodgeWord R p → AtomicNaturalHodgeOperator V H p
  | .id => AtomicNaturalHodgeOperator.id
  | .generator f => R.projectiveGenerator p f
  | .add u v => (eval u).add (eval v)
  | .smul q u => (eval u).smul q
  | .comp u v => (eval u).comp (eval v)

@[simp]
theorem eval_id
    (R : HodgeFunctorialGeometricSemantics V H)
    (p : Nat) :
    eval (ProjectiveHodgeWord.id (R := R) (p := p)) =
      AtomicNaturalHodgeOperator.id := by
  rfl

@[simp]
theorem eval_generator
    (R : HodgeFunctorialGeometricSemantics V H)
    (p : Nat)
    (f : V.X ⟶ V.X) :
    eval (ProjectiveHodgeWord.generator (R := R) (p := p) f) =
      R.projectiveGenerator p f := by
  rfl

/-- Every genuine projective word preserves the algebraic Hodge kernel. -/
theorem preserves_algebraicHodge
    {R : HodgeFunctorialGeometricSemantics V H}
    {p : Nat}
    (w : ProjectiveHodgeWord R p)
    {alpha : ClassicalHodgeFiber V H p}
    (halpha : alpha ∈
      GSTClassicalHodgeRankFreeArsenalIrreducibility.AlgebraicHodgeSubspace
        V H p) :
    (eval w).hodge alpha ∈
      GSTClassicalHodgeRankFreeArsenalIrreducibility.AlgebraicHodgeSubspace
        V H p :=
  (eval w).preserves_algebraicHodge halpha

/-- Every genuine projective word acts canonically on the atomic defect
quotient. -/
noncomputable def defectOperator
    {R : HodgeFunctorialGeometricSemantics V H}
    {p : Nat}
    (w : ProjectiveHodgeWord R p) :
    AtomicDefectSpace V H p →ₗ[ℚ] AtomicDefectSpace V H p :=
  (eval w).defectOperator

/-- Defect equivariance for an arbitrary genuine projective word. -/
theorem defect_equivariant
    {R : HodgeFunctorialGeometricSemantics V H}
    {p : Nat}
    (w : ProjectiveHodgeWord R p)
    (alpha : ClassicalHodgeFiber V H p) :
    atomicDefectLinearMap V H p ((eval w).hodge alpha) =
      w.defectOperator (atomicDefectLinearMap V H p alpha) :=
  (eval w).defect_equivariant alpha

/-- Trace-zero realization of a genuine projective word. -/
noncomputable def traceZeroEval
    {R : HodgeFunctorialGeometricSemantics V H}
    {D : ProjectiveDegreeTraceSemantics V H}
    {p : Nat}
    (A : TraceAnchor R.spine D p)
    (w : ProjectiveHodgeWord R p) :
    Module.End ℚ (TraceZeroHodgeFiber D p) :=
  traceZeroOperator A (eval w)

/-- **PROJECTIVE WORD ACTION SURVIVES TRACE NORMALIZATION EXACTLY ON DEFECT.** -/
theorem traceZero_defect_equivariant
    {R : HodgeFunctorialGeometricSemantics V H}
    {D : ProjectiveDegreeTraceSemantics V H}
    {p : Nat}
    (A : TraceAnchor R.spine D p)
    (w : ProjectiveHodgeWord R p)
    (alpha : TraceZeroHodgeFiber D p) :
    traceZeroAtomicDefectMap D p (traceZeroEval A w alpha) =
      w.defectOperator (traceZeroAtomicDefectMap D p alpha) :=
  GSTClassicalHodgeTraceZeroAtomicOperatorRepresentation.traceZero_defect_equivariant
    A (eval w) alpha

end ProjectiveHodgeWord

end HodgeFunctorialGeometricSemantics

#check HodgeFunctorialGeometricSemantics
#check HodgeFunctorialGeometricSemantics.projectivePushforwardHodge
#check HodgeFunctorialGeometricSemantics.projectiveGenerator
#check HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord
#check HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.eval
#check HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.defectOperator
#check HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.traceZeroEval
#check HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.traceZero_defect_equivariant

#print axioms HodgeFunctorialGeometricSemantics.projectiveGenerator
#print axioms HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.preserves_algebraicHodge
#print axioms HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.defect_equivariant
#print axioms HodgeFunctorialGeometricSemantics.ProjectiveHodgeWord.traceZero_defect_equivariant

end GSTClassicalHodgeHodgeFunctorialProjectiveDynamics
