import GSTClassicalHodgeGSTDegreeCertifiedSource
import GSTClassicalHodgeGradedCorrespondenceProgramOrbit

/-!
# GST CLASSICAL HODGE — DEGREE-CERTIFIED FULL-CORRESPONDENCE COMPILER

This is the direct junction between the upgraded GST source cosmology and the
strict realized-correspondence algebra.

The previous source-specific compiler accepted only the older graded geometric
program language.  The strict Betti/correspondence burst subsequently enlarged
the verified geometric arena to `GradedCorrespondenceProgram`, generated by
actual realized finite closed correspondences, genuine principal cuts,
rational linear combinations, and ordered composition.

The degree-certified GST source already supplies an actual algebraic Hodge
class with a provably nonzero source coordinate, using projective intersection
degree rather than native mass.  Therefore one source-specific full
correspondence program with the GST-predicted action on that ONE source is
enough to construct an exact algebraic cycle for the chosen target Hodge basis
sheet.

No global orbit cyclicity, Hodge saturation, arbitrary matrix-unit
externalization, native-mass bridge, or target algebraicity is assumed here.
The only target-specific geometric datum is the action of an actual verified
full correspondence program on the already algebraic degree-certified source.
-/

set_option maxHeartbeats 120000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeDegreeCertifiedFullCorrespondenceCompiler

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeSynchronizedDefectOrbit
open GSTClassicalHodgeGradedCorrespondenceProgramOrbit
open GSTClassicalHodgeGradedCorrespondenceProgramOrbit.GradedCorrespondenceProgram
open GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra
open GSTClassicalHodgeRealizedCorrespondenceExpressionAlgebra.RealizedCorrespondenceExpr
open GSTClassicalHodgeGSTDegreeCertifiedSource
open GSTClassicalHodgeProjectiveDegreeTrace
open GSTClassicalHodgePointClosureRelativeCut
open GSTClassicalHodgeSingleExactSuccessorSurvival

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-- A source-specific program in the FULL verified correspondence algebra.

The source is already a genuine native cycle synchronized with a nonzero Hodge
state.  The certificate records only the cohomological action of an actual
full correspondence program on that one source. -/
structure FullCorrespondenceSourceTargetProgram
    (G : GeometricCycleClassSpine V H)
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (j : ClassicalHodgeBasisIndex V H p) where
  program : GradedCorrespondenceProgram V H p p
  source_action :
    program.cohomologyEval G S.hodge.1 =
      (classicalHodgeBasis V H p).repr S.hodge S.sourceIndex •
        (classicalHodgeBasis V H p j).1

namespace FullCorrespondenceSourceTargetProgram

/-- The nonzero GST coordinate carried by the synchronized source. -/
noncomputable def sourceScalar
    {G : GeometricCycleClassSpine V H}
    {S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p)}
    {j : ClassicalHodgeBasisIndex V H p}
    (R : FullCorrespondenceSourceTargetProgram G S j) : ℚ :=
  (classicalHodgeBasis V H p).repr S.hodge S.sourceIndex

/-- Source normalization is legal. -/
theorem sourceScalar_ne_zero
    {G : GeometricCycleClassSpine V H}
    {S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p)}
    {j : ClassicalHodgeBasisIndex V H p}
    (R : FullCorrespondenceSourceTargetProgram G S j) :
    R.sourceScalar ≠ 0 := by
  exact S.sourceCoefficient_ne_zero

/-- Execute the actual full correspondence program on the actual native source
cycle and divide by the nonzero source coordinate. -/
noncomputable def targetCycle
    {G : GeometricCycleClassSpine V H}
    {S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p)}
    {j : ClassicalHodgeBasisIndex V H p}
    (R : FullCorrespondenceSourceTargetProgram G S j) :
    codimensionCycles V.X p :=
  R.sourceScalar⁻¹ • R.program.cycleEval G S.cycle

/-- **FULL-CORRESPONDENCE GST SYNCHRONIZATION.**
Exact naturality of the verified program algebra turns the source-action
identity into an explicit native cycle representing the target Hodge sheet. -/
theorem targetCycle_spec
    {G : GeometricCycleClassSpine V H}
    {S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p)}
    {j : ClassicalHodgeBasisIndex V H p}
    (R : FullCorrespondenceSourceTargetProgram G S j) :
    H.cycleClass p R.targetCycle =
      (classicalHodgeBasis V H p j).1 := by
  have hnat := R.program.cycleClass_cycleEval G S.cycle
  rw [S.class_eq, R.source_action] at hnat
  unfold targetCycle
  rw [LinearMap.map_smul, hnat]
  simp [sourceScalar, R.sourceScalar_ne_zero, smul_smul]

/-- The chosen target sheet is in the genuine cycle-class range. -/
theorem target_mem_cycleClass_range
    {G : GeometricCycleClassSpine V H}
    {S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p)}
    {j : ClassicalHodgeBasisIndex V H p}
    (R : FullCorrespondenceSourceTargetProgram G S j) :
    (classicalHodgeBasis V H p j).1 ∈
      LinearMap.range (H.cycleClass p) := by
  exact ⟨R.targetCycle, R.targetCycle_spec⟩

/-- A genuine realized-correspondence expression is already a source-specific
full program once its action on the synchronized source has been calculated. -/
noncomputable def ofCorrespondenceExpr
    (G : GeometricCycleClassSpine V H)
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (j : ClassicalHodgeBasisIndex V H p)
    (E : RealizedCorrespondenceExpr V H p)
    (hE :
      E.cohomologyOperator S.hodge.1 =
        (classicalHodgeBasis V H p).repr S.hodge S.sourceIndex •
          (classicalHodgeBasis V H p j).1) :
    FullCorrespondenceSourceTargetProgram G S j where
  program := .correspondence E
  source_action := by
    simpa [GradedCorrespondenceProgram.cohomologyEval,
      GradedCorrespondenceProgram.toPair] using hE

/-- The exact target-cycle theorem specialized to one actual realized
correspondence expression. -/
theorem targetCycle_ofCorrespondenceExpr
    (G : GeometricCycleClassSpine V H)
    (S : NativeHodgeOrbitSeed (V := V) (H := H) (p := p))
    (j : ClassicalHodgeBasisIndex V H p)
    (E : RealizedCorrespondenceExpr V H p)
    (hE :
      E.cohomologyOperator S.hodge.1 =
        (classicalHodgeBasis V H p).repr S.hodge S.sourceIndex •
          (classicalHodgeBasis V H p j).1) :
    ∃ Z : codimensionCycles V.X p,
      H.cycleClass p Z = (classicalHodgeBasis V H p j).1 := by
  let R := ofCorrespondenceExpr G S j E hE
  exact ⟨R.targetCycle, R.targetCycle_spec⟩

end FullCorrespondenceSourceTargetProgram

/-- Degree-certified specialization: the source nonvanishing is supplied by
projective intersection degree, not by native mass. -/
abbrev DegreeCertifiedFullCorrespondenceProgram
    (G : GeometricCycleClassSpine V H)
    (D : ProjectiveDegreeTraceSemantics V H)
    (p : Nat)
    (x : CodimensionPoint V.X p)
    (hlive : ProjectivelyLiveSource V.projective.n
      (V.projective.immersion x.1))
    (hExact :
      Order.coheight
        (ambientSuccessorPoint V x.1
          (relativeHeightOneSeparatorSuccessor V x.1 hlive)) = p + 1)
    (j : ClassicalHodgeBasisIndex V H (p + 1)) :=
  FullCorrespondenceSourceTargetProgram G
    (degreeCertifiedSuccessorSeed G D p x hlive hExact) j

/-- One full-correspondence execution from the degree-certified source gives an
exact native cycle for the requested basis sheet. -/
theorem degreeCertifiedFullProgram_targetCycle
    (G : GeometricCycleClassSpine V H)
    (D : ProjectiveDegreeTraceSemantics V H)
    (p : Nat)
    (x : CodimensionPoint V.X p)
    (hlive : ProjectivelyLiveSource V.projective.n
      (V.projective.immersion x.1))
    (hExact :
      Order.coheight
        (ambientSuccessorPoint V x.1
          (relativeHeightOneSeparatorSuccessor V x.1 hlive)) = p + 1)
    (j : ClassicalHodgeBasisIndex V H (p + 1))
    (R : DegreeCertifiedFullCorrespondenceProgram
      G D p x hlive hExact j) :
    ∃ Z : codimensionCycles V.X (p + 1),
      H.cycleClass (p + 1) Z =
        (classicalHodgeBasis V H (p + 1) j).1 := by
  exact ⟨R.targetCycle, R.targetCycle_spec⟩

/-- **WEIGHTWISE FULL-CORRESPONDENCE CROWN.**
If one degree-certified source admits a verified full-correspondence program to
each target basis sheet, then the entire Hodge fiber in that weight lies in the
true cycle-class range. -/
theorem hodge_weight_of_degreeCertifiedFullCorrespondencePrograms
    (G : GeometricCycleClassSpine V H)
    (D : ProjectiveDegreeTraceSemantics V H)
    (p : Nat)
    (x : CodimensionPoint V.X p)
    (hlive : ProjectivelyLiveSource V.projective.n
      (V.projective.immersion x.1))
    (hExact :
      Order.coheight
        (ambientSuccessorPoint V x.1
          (relativeHeightOneSeparatorSuccessor V x.1 hlive)) = p + 1)
    (R : ∀ j : ClassicalHodgeBasisIndex V H (p + 1),
      DegreeCertifiedFullCorrespondenceProgram
        G D p x hlive hExact j) :
    rationalHodgeSubspace (H.hodgeBigrading (p + 1)) ≤
      LinearMap.range (H.cycleClass (p + 1)) := by
  intro alpha halpha
  let alphaH : ClassicalHodgeFiber V H (p + 1) := ⟨alpha, halpha⟩
  have hbasis : ∀ j : ClassicalHodgeBasisIndex V H (p + 1),
      (classicalHodgeBasis V H (p + 1) j).1 ∈
        LinearMap.range (H.cycleClass (p + 1)) := by
    intro j
    exact (R j).target_mem_cycleClass_range
  rw [show alphaH =
      ∑ j ∈ ((classicalHodgeBasis V H (p + 1)).repr alphaH).support,
        ((classicalHodgeBasis V H (p + 1)).repr alphaH j) •
          classicalHodgeBasis V H (p + 1) j by
    exact (classicalHodgeBasis V H (p + 1)).sum_repr alphaH]
  simp only [Submodule.coe_sum, Submodule.coe_smul_of_tower]
  apply Submodule.sum_mem
  intro j hj
  exact (LinearMap.range (H.cycleClass (p + 1))).smul_mem
    ((classicalHodgeBasis V H (p + 1)).repr alphaH j) (hbasis j)

/-- Elementwise constructive form of the weightwise crown. -/
theorem everyHodgeClass_weightSucc_hasCycle
    (G : GeometricCycleClassSpine V H)
    (D : ProjectiveDegreeTraceSemantics V H)
    (p : Nat)
    (x : CodimensionPoint V.X p)
    (hlive : ProjectivelyLiveSource V.projective.n
      (V.projective.immersion x.1))
    (hExact :
      Order.coheight
        (ambientSuccessorPoint V x.1
          (relativeHeightOneSeparatorSuccessor V x.1 hlive)) = p + 1)
    (R : ∀ j : ClassicalHodgeBasisIndex V H (p + 1),
      DegreeCertifiedFullCorrespondenceProgram
        G D p x hlive hExact j)
    (alpha : RationalSingularCohomology H.analytification (2 * (p + 1)))
    (halpha : alpha ∈ rationalHodgeSubspace (H.hodgeBigrading (p + 1))) :
    ∃ Z : codimensionCycles V.X (p + 1),
      H.cycleClass (p + 1) Z = alpha := by
  exact hodge_weight_of_degreeCertifiedFullCorrespondencePrograms
    G D p x hlive hExact R halpha

#check FullCorrespondenceSourceTargetProgram
#check FullCorrespondenceSourceTargetProgram.targetCycle
#check FullCorrespondenceSourceTargetProgram.targetCycle_spec
#check FullCorrespondenceSourceTargetProgram.ofCorrespondenceExpr
#check FullCorrespondenceSourceTargetProgram.targetCycle_ofCorrespondenceExpr
#check DegreeCertifiedFullCorrespondenceProgram
#check degreeCertifiedFullProgram_targetCycle
#check hodge_weight_of_degreeCertifiedFullCorrespondencePrograms
#check everyHodgeClass_weightSucc_hasCycle

#print axioms FullCorrespondenceSourceTargetProgram.targetCycle_spec
#print axioms FullCorrespondenceSourceTargetProgram.targetCycle_ofCorrespondenceExpr
#print axioms degreeCertifiedFullProgram_targetCycle
#print axioms hodge_weight_of_degreeCertifiedFullCorrespondencePrograms

end GSTClassicalHodgeDegreeCertifiedFullCorrespondenceCompiler
