import GSTClassicalHodgeFiniteClosedCorrespondenceOperator
import GSTClassicalHodgeGeometricCycleClassSpine
import GSTClassicalHodgeNativeArsenalRepresentation

/-!
# GST CLASSICAL HODGE — REALIZED CLOSED-CORRESPONDENCE ALGEBRA

The internal GST matrix-unit arsenal is already complete, but Astra's native
descent theorem rules out the shortcut of treating multiplicity operators as
if they automatically descended to algebraic cycles.  The correct geometric
arena is therefore the algebra generated by ACTUAL closed correspondences in
`X × X` whose pointwise cycle-class action has been proved.

This file packages that arena without inserting a Hodge conclusion.

A `RealizedFiniteClosedCorrespondence` contains:

* a genuine finite closed correspondence `K`;
* an ambient cohomological endomorphism `T`;
* an exact theorem on every genuine codimension-p point atom saying that the
  class of the correspondence image is `T` of the original class.

The point-kernel engine then upgrades this to a commuting square on ALL native
cycles.  We close these realized operators under rational scaling and finite
addition at the operator-pair level.  Hodge preservation is deliberately kept
separate: a realized correspondence need not preserve the `(p,p)` fiber unless
that is independently proved.

Actual endomorphism graphs are nonempty inhabitants of this geometry-first
algebra, supplied directly by `GeometricCycleClassSpine.pushforward_naturality`.
Thus the new arena strictly extends the old graph span while remaining anchored
in genuine projective geometry.
-/

set_option maxHeartbeats 80000000
set_option maxRecDepth 1000000

noncomputable section

open CategoryTheory
open AlgebraicGeometry

namespace GSTClassicalHodgeRealizedClosedCorrespondenceAlgebra

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeFiniteClosedCorrespondence
open GSTClassicalHodgeFiniteClosedCorrespondenceOperator
open GSTClassicalHodgeCycleOperatorNaturality
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeRankFreeArsenalIrreducibility
open GSTClassicalHodgeNativeArsenalRepresentation

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-- A genuine finite closed correspondence together with an independently
proved cohomological realization on point-cycle generators. -/
structure RealizedFiniteClosedCorrespondence
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V)
    (p : Nat) where
  geometry : FiniteClosedCorrespondence V
  cohomologyOperator :
    RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ]
      RationalSingularCohomology H.analytification (2 * p)
  realizes_on_points :
    geometry.RealizesAmbientOnPoints (H := H) cohomologyOperator

namespace RealizedFiniteClosedCorrespondence

/-- The exact native/cohomology operator pair manufactured from the genuine
closed correspondence. -/
noncomputable def operatorPair
    (R : RealizedFiniteClosedCorrespondence V H p) :
    CycleClassOperatorPair V H p :=
  R.geometry.toCycleClassOperatorPair R.cohomologyOperator R.realizes_on_points

@[simp]
theorem operatorPair_cycle
    (R : RealizedFiniteClosedCorrespondence V H p) :
    R.operatorPair.cycleOperator = R.geometry.nativeOperator p :=
  rfl

@[simp]
theorem operatorPair_cohomology
    (R : RealizedFiniteClosedCorrespondence V H p) :
    R.operatorPair.cohomologyOperator = R.cohomologyOperator :=
  rfl

/-- Every realized closed correspondence preserves the genuine native
cycle-class range, without any Hodge-surjectivity premise. -/
theorem cycleClass_range_stable
    (R : RealizedFiniteClosedCorrespondence V H p) :
    ∀ alpha,
      alpha ∈ LinearMap.range (H.cycleClass p) →
      R.cohomologyOperator alpha ∈ LinearMap.range (H.cycleClass p) :=
  R.operatorPair.cycleClass_range_stable

/-- Exact naturality on every native cycle. -/
theorem cycleClass_natural
    (R : RealizedFiniteClosedCorrespondence V H p)
    (Z : codimensionCycles V.X p) :
    H.cycleClass p (R.geometry.nativeOperator p Z) =
      R.cohomologyOperator (H.cycleClass p Z) := by
  simpa [operatorPair] using R.operatorPair.cycleClass_cycleOperator Z

/-- Hodge compatibility is intentionally a separate property.  It is weaker
than realizing a prescribed matrix unit and must be proved from geometry for
the correspondence at hand. -/
def HodgeCompatible
    (R : RealizedFiniteClosedCorrespondence V H p) : Prop :=
  ∀ alpha : ClassicalHodgeFiber V H p,
    R.cohomologyOperator alpha.1 ∈
      rationalHodgeSubspace (H.hodgeBigrading p)

/-- A Hodge-compatible realized correspondence acts on the genuine Hodge
fiber, with no choice of basis or multiplicity coordinate in the definition. -/
noncomputable def hodgeOperator
    (R : RealizedFiniteClosedCorrespondence V H p)
    (hR : R.HodgeCompatible) :
    Module.End ℚ (ClassicalHodgeFiber V H p) where
  toFun alpha := ⟨R.cohomologyOperator alpha.1, hR alpha⟩
  map_add' := by
    intro a b
    ext
    simp
  map_smul' := by
    intro q a
    ext
    simp

/-- Hodge-compatible realized correspondences preserve the algebraic Hodge
subspace simply because their native/cohomology square is genuine. -/
theorem maps_algebraicHodgeSubspace
    (R : RealizedFiniteClosedCorrespondence V H p)
    (hR : R.HodgeCompatible)
    (alpha : ClassicalHodgeFiber V H p)
    (halpha : alpha ∈ AlgebraicHodgeSubspace V H p) :
    R.hodgeOperator hR alpha ∈ AlgebraicHodgeSubspace V H p := by
  rcases halpha with ⟨Z, hZ⟩
  refine ⟨R.geometry.nativeOperator p Z, ?_⟩
  change H.cycleClass p (R.geometry.nativeOperator p Z) =
    R.cohomologyOperator alpha.1
  rw [R.cycleClass_natural]
  simpa [hZ]

/-! ## Graphs are certified realized correspondences from the geometric spine. -/

/-- Every actual scheme endomorphism graph is a realized finite closed
correspondence.  Its realization theorem is the primitive projective
cycle-class naturality already stored in the genuine geometric spine. -/
noncomputable def graphRealized
    (G : GeometricCycleClassSpine V H)
    (f : GSTClassicalHodgeAnalytificationFunctoriality.ComplexSchemeEndomorphism V) :
    RealizedFiniteClosedCorrespondence V H p where
  geometry := FiniteClosedCorrespondence.graphCorrespondence f
  cohomologyOperator := (G.pushforward_naturality p f.hom).cohomologyPushforward
  realizes_on_points := by
    intro x
    rw [FiniteClosedCorrespondence.graphCorrespondence_nativePointImage_eq]
    exact (G.pushforward_naturality p f.hom).naturality
      (GSTNativeCodimensionCyclePresentation.codimensionPointCycle V.X p x)

/-- The graph inhabitant recovers exactly the existing geometric pushforward
pair from the spine. -/
theorem graphRealized_cycleOperator
    (G : GeometricCycleClassSpine V H)
    (f : GSTClassicalHodgeAnalytificationFunctoriality.ComplexSchemeEndomorphism V) :
    (graphRealized (p := p) G f).operatorPair.cycleOperator =
      GSTClassicalHodgeProjectivePointTransport.smoothProjectiveNativePushforward
        V f.hom p := by
  rw [operatorPair_cycle,
    FiniteClosedCorrespondence.graphCorrespondence_nativeOperator_eq_pushforward]

end RealizedFiniteClosedCorrespondence

/-! ## Rational operator-pair algebra

Rather than quotienting syntax immediately, use finite words of rationally
weighted realized correspondences.  Their operator pair is defined recursively;
this already gives the exact algebra needed for geometric orbit arguments and
avoids attaching arbitrary cohomology operators after the fact. -/

/-- Rationally weighted genuine realized correspondence. -/
abbrev WeightedRealizedCorrespondence
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V)
    (p : Nat) :=
  ℚ × RealizedFiniteClosedCorrespondence V H p

/-- Finite rational word in realized closed correspondences. -/
abbrev RealizedCorrespondenceWord
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V)
    (p : Nat) :=
  List (WeightedRealizedCorrespondence V H p)

namespace CycleClassOperatorPair

/-- Zero realized operator pair. -/
noncomputable def zero : CycleClassOperatorPair V H p where
  cycleOperator := 0
  cohomologyOperator := 0
  cycleClass_natural := by
    ext Z
    simp

/-- Rational scaling of an exact cycle-class operator pair. -/
noncomputable def smul
    (q : ℚ)
    (A : CycleClassOperatorPair V H p) :
    CycleClassOperatorPair V H p where
  cycleOperator := q • A.cycleOperator
  cohomologyOperator := q • A.cohomologyOperator
  cycleClass_natural := by
    ext Z
    simp [A.cycleClass_cycleOperator]

/-- Sum of two exact cycle-class operator pairs. -/
noncomputable def add
    (A B : CycleClassOperatorPair V H p) :
    CycleClassOperatorPair V H p where
  cycleOperator := A.cycleOperator + B.cycleOperator
  cohomologyOperator := A.cohomologyOperator + B.cohomologyOperator
  cycleClass_natural := by
    ext Z
    simp [A.cycleClass_cycleOperator, B.cycleClass_cycleOperator]

/-- Composition of exact cycle-class operator pairs.  This is the operation
that turns geometric generators into genuine correspondence words. -/
noncomputable def comp
    (A B : CycleClassOperatorPair V H p) :
    CycleClassOperatorPair V H p where
  cycleOperator := A.cycleOperator.comp B.cycleOperator
  cohomologyOperator := A.cohomologyOperator.comp B.cohomologyOperator
  cycleClass_natural := by
    ext Z
    simp [A.cycleClass_cycleOperator, B.cycleClass_cycleOperator]

end CycleClassOperatorPair

/-- Exact operator pair of a finite rational word in genuine realized closed
correspondences. -/
noncomputable def realizedWordPair :
    RealizedCorrespondenceWord V H p → CycleClassOperatorPair V H p
  | [] => CycleClassOperatorPair.zero
  | (q,R) :: W =>
      CycleClassOperatorPair.add
        (CycleClassOperatorPair.smul q R.operatorPair)
        (realizedWordPair W)

/-- Every realized rational word preserves the actual cycle-class range. -/
theorem realizedWord_range_stable
    (W : RealizedCorrespondenceWord V H p) :
    ∀ alpha,
      alpha ∈ LinearMap.range (H.cycleClass p) →
      (realizedWordPair W).cohomologyOperator alpha ∈
        LinearMap.range (H.cycleClass p) :=
  (realizedWordPair W).cycleClass_range_stable

/-- Every realized rational word is atomic-span stable. -/
theorem realizedWord_atomic_stable
    (W : RealizedCorrespondenceWord V H p) :
    ∀ alpha,
      alpha ∈ GSTClassicalHodgeAtomicSpan.pointCycleClassSpan p (H.cycleClass p) →
      (realizedWordPair W).cohomologyOperator alpha ∈
        GSTClassicalHodgeAtomicSpan.pointCycleClassSpan p (H.cycleClass p) :=
  (realizedWordPair W).atomicSpan_stable

/-- Geometry-first realization predicate for one GST rank-free matrix unit:
not an arbitrary native-lift hypothesis, but the existence of a finite word in
actual realized closed correspondences whose cohomological action on the Hodge
fiber is exactly `E_ij`. -/
def MatrixUnitReachableByClosedCorrespondences
    (i j : ClassicalHodgeBasisIndex V H p) : Prop :=
  ∃ W : RealizedCorrespondenceWord V H p,
    ∀ alpha : ClassicalHodgeFiber V H p,
      (realizedWordPair W).cohomologyOperator alpha.1 =
        (hodgeMatrixUnit i j alpha).1

/-- If every GST matrix unit is reachable by genuine realized closed
correspondence words, the repo's native-arsenal representation is no longer an
interface: it is constructed from actual geometry. -/
noncomputable def nativeArsenalOfClosedCorrespondenceReachability
    (hreach : ∀ i j : ClassicalHodgeBasisIndex V H p,
      MatrixUnitReachableByClosedCorrespondences (V := V) (H := H) i j) :
    NativeArsenalRepresentation V H p where
  operator := fun i j =>
    realizedWordPair (Classical.choose (hreach i j))
  hodge_action := by
    intro i j alpha
    exact Classical.choose_spec (hreach i j) alpha

/-- One nonzero algebraic Hodge seed plus genuine closed-correspondence
reachability of the GST rank-free arsenal saturates the whole Hodge fiber. -/
theorem algebraicHodgeSubspace_eq_top_of_closedCorrespondenceReachability
    (seed : ClassicalHodgeFiber V H p)
    (hseed0 : seed ≠ 0)
    (hseedAlg : seed ∈ AlgebraicHodgeSubspace V H p)
    (hreach : ∀ i j : ClassicalHodgeBasisIndex V H p,
      MatrixUnitReachableByClosedCorrespondences (V := V) (H := H) i j) :
    AlgebraicHodgeSubspace V H p = ⊤ := by
  exact (nativeArsenalOfClosedCorrespondenceReachability hreach).
    algebraicHodgeSubspace_eq_top seed hseed0 hseedAlg

#check RealizedFiniteClosedCorrespondence
#check RealizedFiniteClosedCorrespondence.operatorPair
#check RealizedFiniteClosedCorrespondence.graphRealized
#check CycleClassOperatorPair.zero
#check CycleClassOperatorPair.smul
#check CycleClassOperatorPair.add
#check CycleClassOperatorPair.comp
#check realizedWordPair
#check realizedWord_range_stable
#check MatrixUnitReachableByClosedCorrespondences
#check nativeArsenalOfClosedCorrespondenceReachability
#check algebraicHodgeSubspace_eq_top_of_closedCorrespondenceReachability

#print axioms RealizedFiniteClosedCorrespondence.graphRealized
#print axioms realizedWord_range_stable
#print axioms nativeArsenalOfClosedCorrespondenceReachability
#print axioms algebraicHodgeSubspace_eq_top_of_closedCorrespondenceReachability

end GSTClassicalHodgeRealizedClosedCorrespondenceAlgebra
