import GSTClassicalHodgePrimitiveArsenalRationalization

/-!
# GST CLASSICAL HODGE — TWO-GENERATOR LEFSCHETZ–POINCARE GENERATION

The previous finite GST arsenal used three primitive operators:

* the exact sheet projectors;
* universal Lefschetz transport;
* square-world Poincare reversal.

The projector is not primitive.

On the rational pure diagonal, the two-step Lefschetz operator has the exact
kernel

  L^2 e_p = 2 e_{p+1}

away from the top boundary.  Hence the normalized operator

  U = (1/2) L^2

is the unilateral raising shift.  Poincare reversal `P` turns it into the
lowering shift

  D = P U P.

Consequently

  Pi_0 = I - U D

is the exact bottom-sheet projector, and every matrix unit is generated by

  E_ij = U^j Pi_0 D^i.

Thus the whole finite matrix algebra is generated by only the native
Lefschetz and Poincare operators.  The spectral sheet projectors are derived,
not supplied.  This materially reduces the geometric externalization burden
in the Hodge attack: after one algebraic seed, the remaining operator problem
is reduced to genuine cycle-class naturality of Lefschetz and Poincare
transport.
-/

set_option maxHeartbeats 60000000
set_option maxRecDepth 1000000

noncomputable section

open scoped BigOperators
open GSTWorldCosmology
open GSTWorldPoincareDuality
open GSTDimensionFreeHodgeDiagonal
open GSTGlobalPureHodgeCosmology
open GSTTruncatedWorldCohomologyRing
open GSTPureHodgeLefschetzKernel
open GSTClassicalHodgeFullArsenalIrreducibility
open GSTClassicalHodgeExplicitArsenalGeneration
open GSTClassicalHodgePrimitiveArsenalIrreducibility
open GSTClassicalHodgePrimitiveArsenalRationalization

namespace GSTClassicalHodgeTwoGeneratorLefschetzPoincareGeneration

/-- Normalized two-step Lefschetz motion on the pure diagonal.  The universal
kernel gives coefficient `2` on the immediately following pure sheet, so this
is the unit raising shift. -/
noncomputable def raiseQ (N : Nat) : Module.End ℚ (RationalPureWindow N) :=
  (1 / 2 : ℚ) • diagonalLefschetzQ N 2

/-- Poincare-conjugate of the unit raising shift. -/
noncomputable def lowerQ (N : Nat) : Module.End ℚ (RationalPureWindow N) :=
  poincareConjugate (raiseQ N)

/-- Bottom boundary defect of the two mutually conjugate shifts. -/
noncomputable def bottomProjectorFromLP (N : Nat) :
    Module.End ℚ (RationalPureWindow N) :=
  LinearMap.id - (raiseQ N).comp (lowerQ N)

/-- Iterate an endomorphism using explicit composition. -/
noncomputable def iterEnd {N : Nat}
    (T : Module.End ℚ (RationalPureWindow N)) : Nat →
      Module.End ℚ (RationalPureWindow N)
  | 0 => LinearMap.id
  | n + 1 => T.comp (iterEnd T n)

@[simp] theorem iterEnd_zero {N : Nat}
    (T : Module.End ℚ (RationalPureWindow N)) :
    iterEnd T 0 = LinearMap.id := rfl

@[simp] theorem iterEnd_succ_apply {N : Nat}
    (T : Module.End ℚ (RationalPureWindow N)) (n : Nat)
    (a : RationalPureWindow N) :
    iterEnd T (n+1) a = T (iterEnd T n a) := rfl

/-- Matrix-unit word made only from normalized `L^2`, Poincare reversal and
linear operations. -/
noncomputable def twoGeneratorMatrixUnit
    {N : Nat} (i j : Fin N) : Module.End ℚ (RationalPureWindow N) :=
  (iterEnd (raiseQ N) j.1).comp
    ((bottomProjectorFromLP N).comp
      (iterEnd (lowerQ N) i.1))

/-- Exact coefficient form of the normalized two-step Lefschetz operator.
This is the crucial kernel identity: it is one on the immediate successor and
zero on every other pure diagonal target. -/
theorem raiseQ_basis_coeff
    {N : Nat} (p q : Fin N) :
    raiseQ N (rationalPureBasis p) q =
      if q.1 = p.1 + 1 then 1 else 0 := by
  classical
  simp only [raiseQ, LinearMap.smul_apply, smul_eq_mul]
  rw [diagonalLefschetzQ_basis]
  rw [GSTPureHodgeLefschetzKernel.pure_diagonal_lefschetz_kernel]
  simp only [Fin.val_castLE]
  by_cases hpq : p.1 ≤ q.1
  · rw [dif_pos hpq]
    by_cases htime :
        2 = 2 * (q.1 - p.1)
    · rw [dif_pos]
      · have hgap : q.1 = p.1 + 1 := by omega
        rw [if_pos hgap]
        have hchoose : Nat.choose 2 (q.1 - p.1) = 2 := by
          have : q.1 - p.1 = 1 := by omega
          simp [this]
        norm_num [hchoose]
      · simpa [pureWeightGap] using htime
    · rw [dif_neg]
      · rw [if_neg]
        · simp
        · intro hsucc
          apply htime
          omega
      · simpa [pureWeightGap] using htime
  · rw [dif_neg hpq]
    rw [if_neg]
    · simp
    · intro hsucc
      omega

/-- The normalized Lefschetz operator is literally the one-step raising shift
on basis sheets. -/
theorem raiseQ_basis
    {N : Nat} (p : Fin N) :
    raiseQ N (rationalPureBasis p) =
      if h : p.1 + 1 < N then
        rationalPureBasis (⟨p.1 + 1, h⟩ : Fin N)
      else 0 := by
  classical
  funext q
  rw [raiseQ_basis_coeff]
  by_cases h : p.1 + 1 < N
  · rw [dif_pos h]
    by_cases hq : q.1 = p.1 + 1
    · have heq : q = (⟨p.1 + 1, h⟩ : Fin N) := Fin.ext hq
      subst q
      simp [rationalPureBasis]
    · simp [rationalPureBasis, hq]
  · rw [dif_neg h]
    have hnosucc : q.1 ≠ p.1 + 1 := by
      intro hq
      have := q.2
      omega
    simp [hnosucc]

/-- Poincare conjugation makes the exact lowering shift. -/
theorem lowerQ_basis
    {N : Nat} (p : Fin N) :
    lowerQ N (rationalPureBasis p) =
      if h : 0 < p.1 then
        rationalPureBasis (⟨p.1 - 1, by omega⟩ : Fin N)
      else 0 := by
  classical
  unfold lowerQ
  rw [poincareConjugate_apply]
  rw [poincareReverseQ_basis]
  rw [raiseQ_basis]
  by_cases hp : 0 < p.1
  · have hmir : (windowMirror p).1 + 1 < N := by
      unfold windowMirror
      simp only
      have := p.2
      omega
    rw [dif_pos hmir]
    rw [poincareReverseQ_basis]
    rw [dif_pos hp]
    apply congrArg rationalPureBasis
    apply Fin.ext
    unfold windowMirror
    simp only
    have := p.2
    omega
  · have hp0 : p.1 = 0 := by omega
    have htop : ¬ ((windowMirror p).1 + 1 < N) := by
      unfold windowMirror
      simp only
      omega
    rw [dif_neg htop, map_zero, dif_neg (by omega : ¬ 0 < p.1)]

/-- The boundary defect `I - U D` is exactly the bottom-sheet projector. -/
theorem bottomProjectorFromLP_eq
    {N : Nat} (hN : 0 < N) :
    bottomProjectorFromLP N =
      sheetProjectorQ (⟨0, hN⟩ : Fin N) := by
  classical
  apply LinearMap.ext
  intro a
  rw [rationalPureWindow_eq_sum_basis a]
  simp only [map_sum, map_smul]
  apply Finset.sum_congr rfl
  intro p _
  by_cases hp : p.1 = 0
  · have peq : p = (⟨0, hN⟩ : Fin N) := Fin.ext hp
    subst p
    simp [bottomProjectorFromLP, lowerQ_basis, sheetProjectorQ_basis_self]
  · have hpPos : 0 < p.1 := by omega
    have hpPredLt : p.1 - 1 + 1 < N := by
      have := p.2
      omega
    rw [bottomProjectorFromLP]
    simp only [LinearMap.sub_apply, LinearMap.id_apply, LinearMap.comp_apply]
    rw [lowerQ_basis p, dif_pos hpPos]
    rw [raiseQ_basis, dif_pos hpPredLt]
    have hback : (⟨p.1 - 1 + 1, hpPredLt⟩ : Fin N) = p := by
      apply Fin.ext
      omega
    rw [hback]
    simp [sheetProjectorQ_basis_other (⟨0, hN⟩ : Fin N) p
      (by intro h; have := congrArg Fin.val h; omega)]

/-- Iterated raising sends the bottom sheet to the requested sheet. -/
theorem raise_iter_bottom
    {N : Nat} (hN : 0 < N) (j : Fin N) :
    iterEnd (raiseQ N) j.1
        (rationalPureBasis (⟨0, hN⟩ : Fin N)) =
      rationalPureBasis j := by
  classical
  induction j.1 using Nat.rec with
  | zero =>
      have hj : j = (⟨0, hN⟩ : Fin N) := by
        apply Fin.ext
        omega
      subst j
      rfl
  | succ n ih =>
      have hn : n < N := by omega
      have hn1 : n + 1 < N := by omega
      have hprev : (⟨n, hn⟩ : Fin N).1 = n := rfl
      have ih' := raise_iter_bottom hN (⟨n, hn⟩ : Fin N)
      rw [iterEnd_succ_apply]
      rw [show iterEnd (raiseQ N) n
          (rationalPureBasis (⟨0, hN⟩ : Fin N)) =
        rationalPureBasis (⟨n, hn⟩ : Fin N) by exact ih']
      rw [raiseQ_basis, dif_pos hn1]
      apply congrArg rationalPureBasis
      apply Fin.ext
      omega

/-- Iterated lowering takes a basis sheet back to the bottom sheet. -/
theorem lower_iter_to_bottom
    {N : Nat} (hN : 0 < N) (i : Fin N) :
    iterEnd (lowerQ N) i.1 (rationalPureBasis i) =
      rationalPureBasis (⟨0, hN⟩ : Fin N) := by
  classical
  induction i.1 using Nat.rec with
  | zero =>
      have hi : i = (⟨0, hN⟩ : Fin N) := by
        apply Fin.ext
        omega
      subst i
      rfl
  | succ n ih =>
      have hn : n < N := by omega
      rw [iterEnd_succ_apply]
      rw [lowerQ_basis]
      have hpos : 0 < n + 1 := by omega
      rw [dif_pos hpos]
      have hpred : (⟨n + 1 - 1, by omega⟩ : Fin N) = (⟨n, hn⟩ : Fin N) := by
        apply Fin.ext
        omega
      rw [hpred]
      exact lower_iter_to_bottom hN (⟨n, hn⟩ : Fin N)

/-- Too much lowering kills a different source before the boundary projector
can pass it. -/
theorem bottom_after_lower_iter_basis
    {N : Nat} (hN : 0 < N) (i r : Fin N) :
    bottomProjectorFromLP N
      (iterEnd (lowerQ N) i.1 (rationalPureBasis r)) =
        if r = i then rationalPureBasis (⟨0, hN⟩ : Fin N) else 0 := by
  classical
  rw [bottomProjectorFromLP_eq hN]
  by_cases hri : r = i
  · subst r
    rw [lower_iter_to_bottom hN i, if_pos rfl,
      sheetProjectorQ_basis_self]
  · rw [if_neg hri]
    -- Iterated lowering either remains above zero, or has already vanished;
    -- in either case its bottom coordinate is zero unless the source index was i.
    induction i.1 generalizing r with
    | zero =>
        simp at hri
        have hr0 : r ≠ (⟨0, hN⟩ : Fin N) := hri
        simp [sheetProjectorQ_basis_other (⟨0, hN⟩ : Fin N) r hr0]
    | succ n ih =>
        rw [iterEnd_succ_apply]
        rw [lowerQ_basis]
        by_cases hrpos : 0 < r.1
        · rw [dif_pos hrpos]
          have hrpredLt : r.1 - 1 < N := by omega
          apply ih
          intro heq
          apply hri
          apply Fin.ext
          have := congrArg Fin.val heq
          omega
        · rw [dif_neg hrpos]
          simp

/-- **TWO-GENERATOR MATRIX-UNIT FORMULA.**
Every matrix unit is a word in normalized `L^2` and Poincare reversal only. -/
theorem twoGeneratorMatrixUnit_eq
    {N : Nat} (i j : Fin N) :
    twoGeneratorMatrixUnit i j = pureMatrixUnit i j := by
  classical
  have hN : 0 < N := Nat.pos_of_ne_zero (by
    intro hN0
    subst N
    exact Fin.elim0 i)
  apply LinearMap.ext
  intro a
  rw [rationalPureWindow_eq_sum_basis a]
  simp only [map_sum, map_smul]
  apply Finset.sum_congr rfl
  intro r _
  unfold twoGeneratorMatrixUnit
  simp only [LinearMap.comp_apply]
  rw [bottom_after_lower_iter_basis hN i r]
  by_cases hri : r = i
  · subst r
    rw [if_pos rfl, raise_iter_bottom hN j,
      pureMatrixUnit_basis_source]
  · rw [if_neg hri, map_zero,
      pureMatrixUnit_basis_other i j r hri]

/-- Any submodule invariant under only normalized `L^2` and Poincare reversal
is automatically invariant under every finite matrix unit. -/
def TwoGeneratorInvariant
    {N : Nat} (S : Submodule ℚ (RationalPureWindow N)) : Prop :=
  (∀ a ∈ S, raiseQ N a ∈ S)
    ∧ (∀ a ∈ S, poincareReverseQ N a ∈ S)

/-- Two-generator invariance automatically supplies lowering, boundary
projector, and every matrix unit. -/
theorem fullArsenalInvariant_of_twoGenerator
    {N : Nat} (S : Submodule ℚ (RationalPureWindow N))
    (h : TwoGeneratorInvariant S) :
    FullArsenalInvariant S := by
  rcases h with ⟨hU, hP⟩
  have hD : ∀ a ∈ S, lowerQ N a ∈ S := by
    intro a ha
    unfold lowerQ
    rw [poincareConjugate_apply]
    exact hP _ (hU _ (hP a ha))
  have hiterU : ∀ n a, a ∈ S → iterEnd (raiseQ N) n a ∈ S := by
    intro n
    induction n with
    | zero => intro a ha; simpa using ha
    | succ n ih => intro a ha; exact hU _ (ih a ha)
  have hiterD : ∀ n a, a ∈ S → iterEnd (lowerQ N) n a ∈ S := by
    intro n
    induction n with
    | zero => intro a ha; simpa using ha
    | succ n ih => intro a ha; exact hD _ (ih a ha)
  have hPi0 : ∀ a ∈ S, bottomProjectorFromLP N a ∈ S := by
    intro a ha
    unfold bottomProjectorFromLP
    exact S.sub_mem ha (hU _ (hD a ha))
  intro i j a ha
  rw [← twoGeneratorMatrixUnit_eq i j]
  unfold twoGeneratorMatrixUnit
  exact hiterU j.1 _ (hPi0 _ (hiterD i.1 a ha))

/-- **TWO-GENERATOR IRREDUCIBILITY.**
A nonzero submodule stable under `L^2` and Poincare reversal is the entire
finite pure-Hodge window. -/
theorem twoGeneratorInvariant_eq_top
    {N : Nat} (S : Submodule ℚ (RationalPureWindow N))
    (h : TwoGeneratorInvariant S)
    (hne : S ≠ ⊥) :
    S = ⊤ :=
  fullArsenalInvariant_eq_top S
    (fullArsenalInvariant_of_twoGenerator S h) hne

/-- Final GST algebra crown: projectors and all matrix units are consequences
of Lefschetz plus Poincare. -/
theorem two_generator_lefschetz_poincare_crown :
    (∀ N (S : Submodule ℚ (RationalPureWindow N)),
      TwoGeneratorInvariant S → S ≠ ⊥ → S = ⊤)
    ∧ (∀ N (i j : Fin N),
      twoGeneratorMatrixUnit i j = pureMatrixUnit i j) := by
  exact ⟨
    fun N S hS hn => twoGeneratorInvariant_eq_top S hS hn,
    fun N i j => twoGeneratorMatrixUnit_eq i j⟩

#check raiseQ
#check lowerQ
#check bottomProjectorFromLP
#check twoGeneratorMatrixUnit
#check raiseQ_basis
#check lowerQ_basis
#check bottomProjectorFromLP_eq
#check twoGeneratorMatrixUnit_eq
#check TwoGeneratorInvariant
#check fullArsenalInvariant_of_twoGenerator
#check twoGeneratorInvariant_eq_top
#check two_generator_lefschetz_poincare_crown

#print axioms raiseQ_basis
#print axioms lowerQ_basis
#print axioms bottomProjectorFromLP_eq
#print axioms twoGeneratorMatrixUnit_eq
#print axioms fullArsenalInvariant_of_twoGenerator
#print axioms twoGeneratorInvariant_eq_top
#print axioms two_generator_lefschetz_poincare_crown

end GSTClassicalHodgeTwoGeneratorLefschetzPoincareGeneration
