import GSTClassicalHodgeGradedFiniteClosedCorrespondence
import GSTClassicalHodgeAtomicAnnihilator
import GSTClassicalHodgeTraceZeroPrimitiveTomographyGhost

/-!
# GST CLASSICAL HODGE — CORRESPONDENCE GHOST GAUGE FREEDOM

`GradedCorrespondencePointNaturality` fixes the cohomological action of a
finite closed correspondence only on genuine algebraic point-cycle classes.
That is sufficient for naturality on native cycles, but it does NOT determine
how the chosen ambient linear extension acts on a nonalgebraic Hodge class.

This distinction becomes decisive at the first ghost.  A first-ghost separator
annihilates every point-cycle class and reads the ghost nontrivially.  Hence for
any pointwise-natural correspondence action N and any target vector v we may
add the rank-one operator

    alpha |-> separator(alpha) * v

without changing a single point-generator naturality equation.  On the ghost,
however, the action changes whenever v is nonzero.

Therefore pointwise cycle-class naturality alone cannot be used as evidence for
the action of an ACTUAL geometric correspondence on the canonical first ghost.
Any first-ghost transpose packet must obtain its ghost action from an
independent geometric cohomology construction (or a theorem identifying that
action), not from arbitrary extension of the algebraic range.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeCorrespondenceGhostGaugeFreedom

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2G
open GSTNativeCodimensionCyclePresentation
open GSTClassicalHodgeAtomicAnnihilator
open GSTClassicalHodgeGradedFiniteClosedCorrespondence
open GSTClassicalHodgeTraceZeroPrimitiveTomographyGhost
open GSTClassicalHodgePrimitiveAtomicDefectReduction
open GSTClassicalHodgeAtomicDefectTraceNormalization
open GSTClassicalHodgeProjectiveDegreeTrace
open GSTClassicalHodgeGeometricCycleClassSpine

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p q : Nat}

/-- Rank-one ambient perturbation generated by a scalar detector and one target
cohomology vector. -/
noncomputable def detectorPerturbation
    (d : RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ] ℚ)
    (v : RationalSingularCohomology H.analytification (2 * q)) :
    RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ]
      RationalSingularCohomology H.analytification (2 * q) where
  toFun alpha := d alpha • v
  map_add' := by
    intro a b
    rw [map_add, add_smul]
  map_smul' := by
    intro c a
    rw [map_smul]
    simp [smul_smul]

@[simp]
theorem detectorPerturbation_apply
    (d : RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ] ℚ)
    (v : RationalSingularCohomology H.analytification (2 * q))
    (alpha : RationalSingularCohomology H.analytification (2 * p)) :
    detectorPerturbation (H := H) d v alpha = d alpha • v :=
  rfl

/-- A detector annihilating all point-cycle classes produces a perturbation
which is identically zero on every genuine point generator. -/
theorem detectorPerturbation_point_zero
    (d : RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ] ℚ)
    (hd : AnnihilatesPointCycleClasses p (H.cycleClass p) d)
    (v : RationalSingularCohomology H.analytification (2 * q))
    (x : CodimensionPoint V.X p) :
    detectorPerturbation (H := H) d v
        (H.cycleClass p (codimensionPointCycle V.X p x)) = 0 := by
  rw [detectorPerturbation_apply, hd x]
  simp

/-- **POINT-NATURALITY GAUGE TRANSFORMATION.**
Adding a detector perturbation to any pointwise-natural cohomological action
preserves every defining naturality equation for the same actual closed
correspondence. -/
noncomputable def perturbPointNaturality
    {K : GSTClassicalHodgeFiniteClosedCorrespondence.FiniteClosedCorrespondence V}
    (N : GradedCorrespondencePointNaturality K H p q)
    (d : RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ] ℚ)
    (hd : AnnihilatesPointCycleClasses p (H.cycleClass p) d)
    (v : RationalSingularCohomology H.analytification (2 * q)) :
    GradedCorrespondencePointNaturality K H p q where
  cohomologyOperator := N.cohomologyOperator + detectorPerturbation (H := H) d v
  point_natural := by
    intro x
    rw [LinearMap.add_apply, detectorPerturbation_point_zero d hd v x]
    simp
    exact N.point_natural x

@[simp]
theorem perturbPointNaturality_apply
    {K : GSTClassicalHodgeFiniteClosedCorrespondence.FiniteClosedCorrespondence V}
    (N : GradedCorrespondencePointNaturality K H p q)
    (d : RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ] ℚ)
    (hd : AnnihilatesPointCycleClasses p (H.cycleClass p) d)
    (v : RationalSingularCohomology H.analytification (2 * q))
    (alpha : RationalSingularCohomology H.analytification (2 * p)) :
    (perturbPointNaturality N d hd v).cohomologyOperator alpha =
      N.cohomologyOperator alpha + d alpha • v := by
  rfl

/-- If the detector sees an ambient class and the perturbation direction is
nonzero, the perturbed pointwise-natural action genuinely differs on that
class. -/
theorem perturbPointNaturality_changes_detected_class
    {K : GSTClassicalHodgeFiniteClosedCorrespondence.FiniteClosedCorrespondence V}
    (N : GradedCorrespondencePointNaturality K H p q)
    (d : RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ] ℚ)
    (hd : AnnihilatesPointCycleClasses p (H.cycleClass p) d)
    (v : RationalSingularCohomology H.analytification (2 * q))
    (hv : v ≠ 0)
    (alpha : RationalSingularCohomology H.analytification (2 * p))
    (hdetect : d alpha ≠ 0) :
    (perturbPointNaturality N d hd v).cohomologyOperator alpha ≠
      N.cohomologyOperator alpha := by
  rw [perturbPointNaturality_apply]
  intro heq
  have hzero : d alpha • v = 0 := by
    exact add_left_cancel (heq.trans (add_zero _).symm)
  exact (smul_ne_zero hdetect hv) hzero

/-- **FIRST-GHOST GAUGE FREEDOM.**
For a trace-zero primitive tomography ghost, its own primitive separator gives
an explicit rank-one freedom that leaves ALL point naturality equations of K
unchanged while changing K's declared cohomological action on the ghost.

This formally certifies that `GradedCorrespondencePointNaturality` by itself is
not a sufficient semantic notion of genuine correspondence action on the
first ghost. -/
theorem firstGhost_pointNaturality_not_rigid
    {G : GeometricCycleClassSpine V H}
    {D : LefschetzPrimitiveDecomposition G}
    {T : ProjectiveDegreeTraceSemantics V H}
    {A : TraceAnchor G T p}
    (E : TraceZeroPrimitiveTomographyGhost A D)
    {K : GSTClassicalHodgeFiniteClosedCorrespondence.FiniteClosedCorrespondence V}
    (N : GradedCorrespondencePointNaturality K H p q)
    (v : RationalSingularCohomology H.analytification (2 * q))
    (hv : v ≠ 0) :
    ∃ N' : GradedCorrespondencePointNaturality K H p q,
      N'.cohomologyOperator E.traceZeroClass.1 ≠
        N.cohomologyOperator E.traceZeroClass.1 := by
  let d := E.source.detector
  have hd : AnnihilatesPointCycleClasses p (H.cycleClass p) d :=
    E.source.annihilates_atoms
  let N' := perturbPointNaturality N d hd v
  refine ⟨N', ?_⟩
  exact perturbPointNaturality_changes_detected_class
    N d hd v hv E.traceZeroClass.1 E.separator_detects

#check detectorPerturbation
#check detectorPerturbation_point_zero
#check perturbPointNaturality
#check perturbPointNaturality_changes_detected_class
#check firstGhost_pointNaturality_not_rigid

#print axioms detectorPerturbation_point_zero
#print axioms perturbPointNaturality
#print axioms perturbPointNaturality_changes_detected_class
#print axioms firstGhost_pointNaturality_not_rigid

end GSTClassicalHodgeCorrespondenceGhostGaugeFreedom
