import Mathlib.AlgebraicGeometry.Morphisms.QuasiFinite
import GSTClassicalHodgeGradedPointKernelLift
import GSTClassicalHodgeProjectivePointTransport

/-!
# GST CLASSICAL HODGE — QUASI-FINITE POINT CORRESPONDENCES

The existing projective operator algebra is generated by graphs of actual
self-endomorphisms.  For an arbitrary smooth projective carrier that horizontal
geometry can be very small.  The natural enlargement is a genuine algebraic
correspondence with a finite left fibre.

This file deliberately stays below Chow intersection theory, which the pinned
Mathlib algebraic-cycle API does not yet expose in the form needed here.
Instead we extract exactly the geometric datum that *is* currently available:

* a genuine scheme `C`;
* genuine left and right morphisms `C -> X`;
* the left morphism is locally quasi-finite and quasi-compact, hence every
  set-theoretic fibre over a point of `X` is finite;
* right images of points lying over codimension-p source points remain in
  codimension p.

The finite left fibre therefore produces an honest finite multivalued
codimension-p point presentation on `X`.  No cohomological operator is invented
here.  A separate pointwise class equation is still required before the
existing `GradedPointKernelLift` promotes this geometric relation to a genuine
cycle-class-natural operator.

Thus this module enlarges the geometric carrier beyond endomorphism graphs
without hiding the still-substantive Hodge/cycle-class compatibility step.
-/

set_option maxHeartbeats 90000000
set_option maxRecDepth 1000000

noncomputable section

open CategoryTheory
open AlgebraicGeometry

namespace GSTClassicalHodgeQuasiFinitePointCorrespondence

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTNativeCodimensionCyclePresentation
open GSTClassicalHodgeProjectivePointTransport
open GSTClassicalHodgeGradedPointKernelLift

universe u

variable {X : Scheme.{u}}

/-- Genuine multivalued algebraic point correspondence on `X` whose left
projection has finite fibres and whose right projection preserves the chosen
codimension on every relevant fibre point. -/
structure QuasiFinitePointCorrespondence (X : Scheme.{u}) (p : Nat) where
  carrier : Scheme.{u}
  left : carrier ⟶ X
  right : carrier ⟶ X
  left_locallyQuasiFinite : LocallyQuasiFinite left
  left_quasiCompact : QuasiCompact left
  right_codimension :
    ∀ z : carrier,
      Order.coheight (left z) = p → Order.coheight (right z) = p

namespace QuasiFinitePointCorrespondence

variable {p : Nat}

/-- The actual set-theoretic fibre of the left projection over one source
codimension-p point. -/
def sourceFiber
    (C : QuasiFinitePointCorrespondence X p)
    (x : CodimensionPoint X p) : Set C.carrier :=
  C.left ⁻¹' ({x.1} : Set X)

/-- The left fibre is finite by Mathlib's quasi-finite/quasi-compact fibre
theorem. -/
theorem sourceFiber_finite
    (C : QuasiFinitePointCorrespondence X p)
    (x : CodimensionPoint X p) :
    (C.sourceFiber x).Finite := by
  letI : LocallyQuasiFinite C.left := C.left_locallyQuasiFinite
  letI : QuasiCompact C.left := C.left_quasiCompact
  exact C.left.finite_preimage_singleton x.1

/-- A point in a left fibre has source codimension exactly p. -/
theorem left_coheight_of_mem_sourceFiber
    (C : QuasiFinitePointCorrespondence X p)
    (x : CodimensionPoint X p)
    (z : C.carrier)
    (hz : z ∈ C.sourceFiber x) :
    Order.coheight (C.left z) = p := by
  have hz' : C.left z = x.1 := by
    simpa [sourceFiber] using hz
  rw [hz']
  exact x.2

/-- Hence its right image is a genuine codimension-p target point. -/
noncomputable def targetPoint
    (C : QuasiFinitePointCorrespondence X p)
    (x : CodimensionPoint X p)
    (z : C.carrier)
    (hz : z ∈ C.sourceFiber x) : CodimensionPoint X p :=
  ⟨C.right z,
    C.right_codimension z (C.left_coheight_of_mem_sourceFiber x z hz)⟩

/-- Finite set of actual correspondence points above one source point. -/
noncomputable def sourceFiberFinset
    (C : QuasiFinitePointCorrespondence X p)
    (x : CodimensionPoint X p) : Finset C.carrier := by
  classical
  exact (C.sourceFiber_finite x).toFinset

/-- The multivalued point transition induced by the genuine finite left fibre.
Each correspondence point contributes its actual right image.  Coefficient one
is used intentionally: this is the set-theoretic correspondence relation, not
a claim about a Chow pullback multiplicity that has not been formalized. -/
noncomputable def transition
    (C : QuasiFinitePointCorrespondence X p)
    (x : CodimensionPoint X p) :
    FiniteCodimensionPresentation X p := by
  classical
  exact (C.sourceFiberFinset x).sum fun z =>
    Finsupp.single
      ⟨C.right z, C.right_codimension z (by
        have hz : z ∈ C.sourceFiber x := by
          simpa [sourceFiberFinset] using
            (Set.Finite.mem_toFinset (C.sourceFiber_finite x)).mp
              (by
                have : z ∈ C.sourceFiberFinset x := by simp
                simpa [sourceFiberFinset] using this)
        exact C.left_coheight_of_mem_sourceFiber x z hz)⟩ 1

/-- Cleaner extensional formula for the transition, retaining the proof that
each summand is a genuine target codimension-p point. -/
theorem transition_supported_on_right_images
    (C : QuasiFinitePointCorrespondence X p)
    (x : CodimensionPoint X p)
    (y : CodimensionPoint X p)
    (hy : C.transition x y ≠ 0) :
    ∃ z : C.carrier,
      z ∈ C.sourceFiber x ∧ C.right z = y.1 := by
  classical
  unfold transition at hy
  rw [Finset.sum_apply] at hy
  by_contra hnone
  push_neg at hnone
  have hz : ∀ z ∈ C.sourceFiberFinset x,
      (Finsupp.single
        (⟨C.right z, C.right_codimension z (by
          have hzf : z ∈ C.sourceFiber x := by
            simpa [sourceFiberFinset] using
              (Set.Finite.mem_toFinset (C.sourceFiber_finite x)).mp
                (by simpa [sourceFiberFinset]))⟩ : CodimensionPoint X p) 1) y = 0 := by
    intro z hzfin
    have hzf : z ∈ C.sourceFiber x := by
      simpa [sourceFiberFinset] using hzfin
    have hne :
        (⟨C.right z, C.right_codimension z
          (C.left_coheight_of_mem_sourceFiber x z hzf)⟩ : CodimensionPoint X p) ≠ y := by
      intro heq
      apply hnone z hzf
      exact congrArg Subtype.val heq
    simp [hne]
  exact hy (Finset.sum_eq_zero hz)

/-- The genuine correspondence relation is a graded point kernel. -/
noncomputable def toGradedPointKernel
    (C : QuasiFinitePointCorrespondence X p) :
    GradedPointKernel X p p :=
  C.transition

#check QuasiFinitePointCorrespondence
#check QuasiFinitePointCorrespondence.sourceFiber
#check QuasiFinitePointCorrespondence.sourceFiber_finite
#check QuasiFinitePointCorrespondence.targetPoint
#check QuasiFinitePointCorrespondence.transition
#check QuasiFinitePointCorrespondence.transition_supported_on_right_images
#check QuasiFinitePointCorrespondence.toGradedPointKernel

#print axioms QuasiFinitePointCorrespondence.sourceFiber_finite
#print axioms QuasiFinitePointCorrespondence.transition_supported_on_right_images

end QuasiFinitePointCorrespondence

end GSTClassicalHodgeQuasiFinitePointCorrespondence
