import GSTClassicalHodgePrimitiveQuotientProjectiveAction
import GSTClassicalHodgePrimitiveQuotientDetector
import GSTClassicalHodgeGradedSeparatorBackpropagation

/-!
# GST CLASSICAL HODGE — DUAL PROJECTIVE ACTION ON THE PRIMITIVE QUOTIENT

The quotient by all lower-weight verified geometry carries every genuine
same-weight projective word.  Its algebraic dual therefore carries the exact
contragredient action by precomposition.

For the minimal primitive separator this dual action is not an abstract new
operator.  It is literally the quotient descent of the ambient separator
backpropagated through the same genuine projective word.  Thus the earlier
separator-backpropagation cosmology survives passage to the primitive quotient
without loss.

No abstract Hodge matrix unit, basis permutation, or full correspondence
naturality is used here.  Every operator comes from the already verified
`ProjectiveOperatorWord` algebra generated by actual scheme endomorphisms.
-/

set_option maxHeartbeats 90000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgePrimitiveQuotientDualProjectiveAction

open GSTProjectiveOverC
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeProjectiveWordOrbit
open GSTClassicalHodgePrimitiveGeometricQuotient
open GSTClassicalHodgePrimitiveQuotientDetector
open GSTClassicalHodgePrimitiveQuotientProjectiveAction
open GSTClassicalHodgeMinimalPrimitiveSeparatorGhost

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}

/-- Contragredient action of one genuine projective word on a primitive
quotient detector. -/
noncomputable def primitiveProjectiveDualAction
    (G : GeometricCycleClassSpine V H)
    (p : Nat)
    (W : ProjectiveOperatorWord V p)
    (ell : PrimitiveGeometricQuotient G p →ₗ[ℚ] ℚ) :
    PrimitiveGeometricQuotient G p →ₗ[ℚ] ℚ :=
  ell.comp (primitiveProjectiveAction G p W)

/-- Representative formula for the quotient dual action. -/
theorem primitiveProjectiveDualAction_mk
    (G : GeometricCycleClassSpine V H)
    (p : Nat)
    (W : ProjectiveOperatorWord V p)
    (ell : PrimitiveGeometricQuotient G p →ₗ[ℚ] ℚ)
    (x : RationalSingularCohomology H.analytification (2 * p)) :
    primitiveProjectiveDualAction G p W ell (Submodule.Quotient.mk x) =
      ell (Submodule.Quotient.mk
        ((W.operatorPair G).cohomologyOperator x)) := by
  rfl

/-- Ambient detector obtained by backpropagating the minimal separator through
one genuine projective word. -/
noncomputable def backpropagatedAmbientDetector
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G)
    (W : ProjectiveOperatorWord V M.weight) :
    RationalSingularCohomology H.analytification (2 * M.weight) →ₗ[ℚ] ℚ :=
  M.separator.detector.comp (W.operatorPair G).cohomologyOperator

/-- The backpropagated ambient detector still annihilates the complete lower
geometric image, because that image is projective-word stable and the original
minimal separator kills it. -/
theorem lowerGeometricImage_le_ker_backpropagated
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G)
    (W : ProjectiveOperatorWord V M.weight) :
    lowerGeometricImage G M.weight ≤
      LinearMap.ker (backpropagatedAmbientDetector G M W) := by
  intro x hx
  have hstable := lowerGeometricImage_stable_projectiveWord
    G M.weight W hx
  exact minimalGhost_lowerGeometricImage_le_ker G M hstable

/-- Quotient descent of the ambient backpropagated detector. -/
noncomputable def backpropagatedPrimitiveDetector
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G)
    (W : ProjectiveOperatorWord V M.weight) :
    PrimitiveGeometricQuotient G M.weight →ₗ[ℚ] ℚ :=
  (lowerGeometricImage G M.weight).liftQ
    (backpropagatedAmbientDetector G M W)
    (lowerGeometricImage_le_ker_backpropagated G M W)

/-- **DUAL-DESCENT IDENTITY.**
Dualizing the descended projective action is exactly the same as first
backpropagating the ambient separator and then descending the resulting
functional to the primitive quotient. -/
theorem primitive_dualAction_eq_backpropagated
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G)
    (W : ProjectiveOperatorWord V M.weight) :
    primitiveProjectiveDualAction G M.weight W
        (primitiveQuotientDetector G M) =
      backpropagatedPrimitiveDetector G M W := by
  apply LinearMap.quotient_ext
  intro x
  rfl

/-- Exact readout of one backpropagated primitive detector on a quotient
representative. -/
theorem backpropagatedPrimitiveDetector_mk
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G)
    (W : ProjectiveOperatorWord V M.weight)
    (x : RationalSingularCohomology H.analytification (2 * M.weight)) :
    backpropagatedPrimitiveDetector G M W (Submodule.Quotient.mk x) =
      M.separator.detector
        ((W.operatorPair G).cohomologyOperator x) := by
  rfl

/-- If a genuine projective word sends any quotient class to a nonzero scalar
multiple of the detected primitive basis class, the dual-backpropagated
minimal detector is necessarily nonzero on that source class. -/
theorem dual_backprop_nonzero_of_hits_detected_basis
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G)
    (W : ProjectiveOperatorWord V M.weight)
    (x : PrimitiveGeometricQuotient G M.weight)
    (c : ℚ)
    (hc : c ≠ 0)
    (hhit : primitiveProjectiveAction G M.weight W x =
      c • primitiveBasisClass G M) :
    primitiveProjectiveDualAction G M.weight W
        (primitiveQuotientDetector G M) x ≠ 0 := by
  rw [primitiveProjectiveDualAction, LinearMap.comp_apply, hhit,
    LinearMap.map_smul]
  exact mul_ne_zero hc (primitive_primal_dual_pairing_nonzero G M)

/-- The minimal primitive obstruction therefore carries an exact primal/dual
representation of the verified projective-word algebra. -/
theorem primitive_projective_primal_dual_crown
    (G : GeometricCycleClassSpine V H)
    (M : MinimalPrimitiveGhost G) :
    primitiveBasisClass G M ≠ 0
      ∧ primitiveQuotientDetector G M ≠ 0
      ∧ (∀ W : ProjectiveOperatorWord V M.weight,
          primitiveProjectiveDualAction G M.weight W
              (primitiveQuotientDetector G M) =
            backpropagatedPrimitiveDetector G M W) := by
  exact ⟨primitiveBasisClass_ne_zero G M,
    primitiveQuotientDetector_ne_zero G M,
    fun W => primitive_dualAction_eq_backpropagated G M W⟩

#check primitiveProjectiveDualAction
#check primitiveProjectiveDualAction_mk
#check backpropagatedAmbientDetector
#check lowerGeometricImage_le_ker_backpropagated
#check backpropagatedPrimitiveDetector
#check primitive_dualAction_eq_backpropagated
#check dual_backprop_nonzero_of_hits_detected_basis
#check primitive_projective_primal_dual_crown

#print axioms primitive_dualAction_eq_backpropagated
#print axioms dual_backprop_nonzero_of_hits_detected_basis
#print axioms primitive_projective_primal_dual_crown

end GSTClassicalHodgePrimitiveQuotientDualProjectiveAction
