import Mathlib
import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Proper
import GSTNativeCodimensionCyclePresentation
import GSTProjectiveOverC

set_option maxHeartbeats 10000000
set_option maxRecDepth 1000000

noncomputable section

open CategoryTheory
open AlgebraicGeometry
open GSTGeometricRealizationStage2D
open GSTNativeCodimensionCyclePresentation
open GSTProjectiveOverC

namespace GSTCompactNativeCyclePresentation

universe u

attribute [local instance] MvPolynomial.gradedAlgebra

/-- On a compact scheme every locally finite algebraic cycle has globally
finite support. -/
theorem native_cycle_support_finite
    (X : Scheme.{u}) [CompactSpace X]
    (Z : AlgebraicCycle X ℚ) :
    Z.support.Finite := by
  simpa using
    Z.locallyFiniteSupport.finite_inter_support_of_isCompact
      (W := Set.univ) isCompact_univ

/-- Restrict a compactly supported native codimension-p cycle to its genuine
codimension-p points, producing a finite rational presentation. -/
noncomputable def presentationOfNativeCycle
    (X : Scheme.{u}) [CompactSpace X] (p : Nat)
    (Z : codimensionCycles X p) :
    FiniteCodimensionPresentation X p :=
  Finsupp.ofSupportFinite
    (fun x : CodimensionPoint X p => (Z.1 : AlgebraicCycle X ℚ) x.1)
    (by
      have hfin : (Z.1 : AlgebraicCycle X ℚ).support.Finite :=
        native_cycle_support_finite X Z.1
      have hpre :
          ((fun x : CodimensionPoint X p => x.1) ⁻¹'
            (Z.1 : AlgebraicCycle X ℚ).support).Finite :=
        hfin.preimage (fun a _ b _ h => Subtype.ext h)
      simpa [Function.support] using hpre)

@[simp]
theorem presentationOfNativeCycle_apply
    (X : Scheme.{u}) [CompactSpace X] (p : Nat)
    (Z : codimensionCycles X p)
    (x : CodimensionPoint X p) :
    presentationOfNativeCycle X p Z x = (Z.1 : AlgebraicCycle X ℚ) x.1 := by
  rfl

/-- Standard projective space over C is compact in its Zariski topology. -/
theorem projectiveSpace_isCompact_univ (n : Nat) :
    IsCompact (Set.univ : Set (projectiveSpace n)) := by
  change IsCompact (Set.univ : Set (Proj (ProjectiveGrading n)))
  -- The standard graded ring is generated by its finitely many variables as
  -- an algebra over its degree-zero piece, so the graded ring is of finite
  -- type over `𝒜 0` and Mathlib's projective-spectrum compactness applies.
  haveI : Algebra.FiniteType ↥(ProjectiveGrading n 0) (MvPolynomial (Fin (n + 1)) ℂ) := by
    constructor
    refine ⟨Finset.univ.image
      (MvPolynomial.X (σ := Fin (n + 1)) (R := ℂ)), ?_⟩
    rw [Finset.coe_image, Finset.coe_univ, Set.image_univ]
    set S := Algebra.adjoin ↥(ProjectiveGrading n 0)
      (Set.range (MvPolynomial.X (σ := Fin (n + 1)) (R := ℂ)))
    refine top_unique fun p hp => ?_
    clear hp
    induction p using MvPolynomial.induction_on with
    | C a =>
        exact S.algebraMap_mem
          ⟨MvPolynomial.C a,
            MvPolynomial.isHomogeneous_C (σ := Fin (n + 1)) (R := ℂ) a⟩
    | add p q hp hq => exact S.add_mem hp hq
    | mul_X p i hp =>
        exact S.mul_mem hp (Algebra.subset_adjoin (Set.mem_range_self i))
  have hbase :
      IsCompact (Set.univ : Set (Spec (.of (ProjectiveGrading n 0)))) :=
    isCompact_univ
  have hpre :=
    QuasiCompact.isCompact_preimage
      (f := Proj.toSpecZero (ProjectiveGrading n))
      Set.univ isOpen_univ hbase
  simpa using hpre

/-- Every bundled smooth projective complex scheme has compact underlying
Zariski space, obtained from its closed immersion into projective space. -/
theorem smoothProjective_isCompact_univ
    (V : SmoothProjectiveComplexScheme) :
    IsCompact (Set.univ : Set V.X) := by
  letI : IsClosedImmersion V.projective.immersion :=
    V.projective.closedImmersion
  have hpre :=
    QuasiCompact.isCompact_preimage
      (f := V.projective.immersion)
      Set.univ isOpen_univ
      (projectiveSpace_isCompact_univ V.projective.n)
  simpa using hpre

/-- Local compact-space instance usable inside downstream constructions. -/
noncomputable def smoothProjectiveCompactSpace
    (V : SmoothProjectiveComplexScheme) : CompactSpace V.X :=
  ⟨smoothProjective_isCompact_univ V⟩

#check native_cycle_support_finite
#check presentationOfNativeCycle
#check presentationOfNativeCycle_apply
#check projectiveSpace_isCompact_univ
#check smoothProjective_isCompact_univ
#check smoothProjectiveCompactSpace

#print axioms native_cycle_support_finite
#print axioms presentationOfNativeCycle_apply
#print axioms projectiveSpace_isCompact_univ
#print axioms smoothProjective_isCompact_univ

end GSTCompactNativeCyclePresentation