import GSTClassicalHodgeFullArsenalIrreducibility
import GSTSquarePureHodgeDuality
import GSTPureHodgeLefschetzKernel

/-!
# GST CLASSICAL HODGE — EXPLICIT ARSENAL GENERATION

`GSTClassicalHodgeFullArsenalIrreducibility` established the exact Lefschetz
matrix coefficients and the irreducibility of the matrix-unit action, but the
matrix units themselves were still introduced by their coordinate formula.
This module removes that compression.

We rationalize the *actual* finite-world Lefschetz action on the pure diagonal.
For `p <= q`, the operator word

  P_q ∘ L^(2(q-p)) ∘ P_p

is the central-binomial scalar times the matrix unit E_pq.  Since that scalar
is positive, it is invertible over Q and E_pq is literally generated by the
GST sheet projectors and the native universal Lefschetz operator.  Backward
matrix units are obtained by conjugating the corresponding forward word by
square-world Poincare reversal.

Thus the full finite matrix algebra used in the Hodge attack is not an
independent coordinate gadget: it lies in the operator algebra generated by
the existing GST projector/Lefschetz/Poincare universe.
-/

set_option maxHeartbeats 30000000
set_option maxRecDepth 1000000

noncomputable section

open scoped BigOperators
open GSTWorldCosmology
open GSTWorldPoincareDuality
open GSTDimensionFreeHodgeDiagonal
open GSTGlobalPureHodgeCosmology
open GSTTruncatedWorldCohomologyRing
open GSTUniversalLefschetzKernel
open GSTPureHodgeLefschetzKernel
open GSTSquarePureHodgeDuality
open GSTClassicalHodgeFullArsenalIrreducibility

namespace GSTClassicalHodgeExplicitArsenalGeneration

/-- Rationalization of the actual `L^t` action, restricted to the complete
pure diagonal of one finite square world. -/
noncomputable def diagonalLefschetzQ
    (N t : Nat) : Module.End ℚ (RationalPureWindow N) where
  toFun a := fun q =>
    ∑ p : Fin N,
      (worldAct N N ((L N N)^t)
        (worldBasis (pureDiagonalState (Fin.castLE (show N ≤ min N N by omega) p)))
        (pureDiagonalState (Fin.castLE (show N ≤ min N N by omega) q)) : ℚ) * a p
  map_add' := by
    intro a b
    funext q
    simp [mul_add, Finset.sum_add_distrib]
  map_smul' := by
    intro c a
    funext q
    simp [Finset.mul_sum, smul_eq_mul, mul_left_comm]

-- The window mirror defined natively at Fin N, avoiding the Fin (min N N)
-- type boundary inside equiv field elaboration.
/-- Mirror one pure-window coordinate natively at Fin N. -/
def windowMirror {N : Nat} (q : Fin N) : Fin N :=
  ⟨N - 1 - q.1, by have := q.2; omega⟩

@[simp]
theorem windowMirror_involutive {N : Nat} (q : Fin N) :
    windowMirror (windowMirror q) = q := by
  apply Fin.ext
  unfold windowMirror
  simp only
  have := q.2
  omega

/-- Rational Poincare reversal on the finite pure window. -/
noncomputable def poincareReverseQ
    (N : Nat) :
    RationalPureWindow N ≃ₗ[ℚ] RationalPureWindow N where
  toFun a := fun q => a (windowMirror q)
  invFun a := fun q => a (windowMirror q)
  left_inv := by
    intro a
    funext q
    simp
  right_inv := by
    intro a
    funext q
    simp
  map_add' := by
    intro a b
    rfl
  map_smul' := by
    intro c a
    rfl

/-- Pointwise action of the Poincare reversal equiv. -/
@[simp]
theorem poincareReverseQ_apply
    {N : Nat} (a : RationalPureWindow N) (q : Fin N) :
    poincareReverseQ N a q = a (windowMirror q) := rfl

@[simp]
theorem poincareReverseQ_basis
    {N : Nat} (p : Fin N) :
    poincareReverseQ N (rationalPureBasis p) =
      rationalPureBasis (windowMirror p) := by
  funext q
  simp only [poincareReverseQ_apply, rationalPureBasis]
  by_cases hL : windowMirror q = p
  · rw [if_pos hL, if_pos
      ((windowMirror_involutive q).symm.trans (congrArg windowMirror hL))]
  · rw [if_neg hL, if_neg (by
      intro hq
      exact hL ((congrArg windowMirror hq).trans (windowMirror_involutive p)))]


/-- Raw forward arsenal word before central-binomial normalization. -/
noncomputable def rawForwardWord
    {N : Nat} (p q : Fin N) : Module.End ℚ (RationalPureWindow N) :=
  (sheetProjectorQ q).comp
    ((diagonalLefschetzQ N (2 * pureWeightGap (Fin.castLE (show N ≤ min N N by omega) p) (Fin.castLE (show N ≤ min N N by omega) q))).comp
      (sheetProjectorQ p))

/-- The raw forward word has the exact GST central-binomial coefficient on its
source sheet. -/
theorem rawForwardWord_basis_source
    {N : Nat} (p q : Fin N) (hpq : p.1 ≤ q.1) :
    rawForwardWord p q (rationalPureBasis p) =
      (forwardScalar p q : ℚ) • rationalPureBasis q := by
  funext r
  by_cases hrq : r = q
  · subst r
    simp [rawForwardWord, diagonalLefschetzQ, sheetProjectorQ,
      rationalPureBasis]
    rw [gst_forward_scalar_receipt p q hpq]
    norm_num
  · simp [rawForwardWord, diagonalLefschetzQ, sheetProjectorQ,
      rationalPureBasis, hrq]

/-- The raw forward word kills every other pure source sheet because the first
factor is the exact source projector. -/
theorem rawForwardWord_basis_other
    {N : Nat} (p q r : Fin N) (hrp : r ≠ p) :
    rawForwardWord p q (rationalPureBasis r) = 0 := by
  simp [rawForwardWord, sheetProjectorQ_basis_other p r hrp]

/-- Normalized forward GST word. -/
noncomputable def forwardArsenalWord
    {N : Nat} (p q : Fin N) : Module.End ℚ (RationalPureWindow N) :=
  (forwardScalar p q : ℚ)⁻¹ • rawForwardWord p q

/-- **FORWARD MATRIX UNIT IS AN ACTUAL GST OPERATOR WORD.** -/
theorem forwardArsenalWord_eq_matrixUnit
    {N : Nat} (p q : Fin N) (hpq : p.1 ≤ q.1) :
    forwardArsenalWord p q = pureMatrixUnit p q := by
  apply LinearMap.ext
  intro a
  rw [rationalPureWindow_eq_sum_basis a]
  simp only [map_sum, map_smul]
  apply Finset.sum_congr rfl
  intro r _
  by_cases hrp : r = p
  · subst r
    simp only [forwardArsenalWord, LinearMap.smul_apply]
    rw [rawForwardWord_basis_source p q hpq]
    have hscalar : (forwardScalar p q : ℚ) ≠ 0 := by
      exact_mod_cast (ne_of_gt (forwardScalar_pos p q))
    simp [pureMatrixUnit_basis_source, hscalar]
  · simp only [forwardArsenalWord, LinearMap.smul_apply]
    rw [rawForwardWord_basis_other p q r hrp]
    simp [pureMatrixUnit_basis_other p q r hrp]

/-- Poincare conjugate of an operator on a finite pure window. -/
noncomputable def poincareConjugate
    {N : Nat} (T : Module.End ℚ (RationalPureWindow N)) :
    Module.End ℚ (RationalPureWindow N) :=
  (poincareReverseQ N).toLinearMap.comp
    (T.comp (poincareReverseQ N).toLinearMap)

/-- Pointwise action of Poincare conjugation. -/
theorem poincareConjugate_apply
    {N : Nat} (T : Module.End ℚ (RationalPureWindow N))
    (a : RationalPureWindow N) :
    poincareConjugate T a
      = poincareReverseQ N (T (poincareReverseQ N a)) := rfl

/-- Native `Fin N` mirror matching `pureMirror` through the canonical
min-casts, so the backward-word construction crosses no type boundary
(the same cure already applied to `windowMirror`). -/
def mirrorFin {N : Nat} (p : Fin N) : Fin N :=
  Fin.castLE (show min N N ≤ N by omega)
    (pureMirror (Fin.castLE (show N ≤ min N N by omega) p))

theorem mirrorFin_val {N : Nat} (p : Fin N) :
    (mirrorFin p).1 = N - 1 - p.1 := by
  simp [mirrorFin, pureMirror, Fin.val_castLE]

theorem windowMirror_eq_mirrorFin {N : Nat} (p : Fin N) :
    windowMirror p = mirrorFin p := by
  apply Fin.ext
  rw [mirrorFin_val]
  rfl

theorem mirrorFin_involutive {N : Nat} (p : Fin N) :
    mirrorFin (mirrorFin p) = p := by
  rw [← windowMirror_eq_mirrorFin (mirrorFin p),
    ← windowMirror_eq_mirrorFin p, windowMirror_involutive]

theorem mirrorFin_injective {N : Nat} :
    Function.Injective (mirrorFin (N := N)) := by
  intro a b h
  apply Fin.ext
  rw [mirrorFin_val, mirrorFin_val] at h
  have := a.2
  have := b.2
  omega

/-- Poincare conjugation turns the mirrored matrix unit back into the original
matrix unit. -/
theorem poincareConjugate_matrixUnit
    {N : Nat} (p q : Fin N) :
    poincareConjugate
        (pureMatrixUnit (mirrorFin p) (mirrorFin q)) =
      pureMatrixUnit p q := by
  apply LinearMap.ext
  intro a
  rw [rationalPureWindow_eq_sum_basis a]
  simp only [map_sum, map_smul]
  apply Finset.sum_congr rfl
  intro r _
  by_cases hrp : r = p
  · subst r
    have hrev : poincareReverseQ N (rationalPureBasis p)
        = rationalPureBasis (mirrorFin p) := by
      rw [poincareReverseQ_basis, windowMirror_eq_mirrorFin]
    have hmid : (pureMatrixUnit (mirrorFin p) (mirrorFin q))
        (poincareReverseQ N (rationalPureBasis p))
        = rationalPureBasis (mirrorFin q) := by
      rw [hrev, pureMatrixUnit_basis_source]
    have hout : poincareReverseQ N (rationalPureBasis (mirrorFin q))
        = rationalPureBasis q := by
      rw [poincareReverseQ_basis, windowMirror_eq_mirrorFin,
        mirrorFin_involutive]
    calc a p • poincareConjugate
            (pureMatrixUnit (mirrorFin p) (mirrorFin q))
            (rationalPureBasis p)
        = a p • poincareReverseQ N
            ((pureMatrixUnit (mirrorFin p) (mirrorFin q))
              (poincareReverseQ N (rationalPureBasis p))) := by
          rw [poincareConjugate_apply]
      _ = a p • rationalPureBasis q := by
          rw [hmid, hout]
      _ = a p • pureMatrixUnit p q (rationalPureBasis p) := by
          rw [pureMatrixUnit_basis_source]
  · have hmirror : mirrorFin r ≠ mirrorFin p := fun h =>
      hrp (mirrorFin_injective h)
    have hrev : poincareReverseQ N (rationalPureBasis r)
        = rationalPureBasis (mirrorFin r) := by
      rw [poincareReverseQ_basis, windowMirror_eq_mirrorFin]
    rw [poincareConjugate_apply, hrev,
      pureMatrixUnit_basis_other _ _ _ hmirror]
    simp

/-- Backward GST word: mirror, perform the now-forward transfer, mirror back. -/
noncomputable def backwardArsenalWord
    {N : Nat} (p q : Fin N) : Module.End ℚ (RationalPureWindow N) :=
  poincareConjugate
    (forwardArsenalWord (mirrorFin p) (mirrorFin q))

/-- **BACKWARD MATRIX UNIT IS AN ACTUAL GST OPERATOR WORD.** -/
theorem backwardArsenalWord_eq_matrixUnit
    {N : Nat} (p q : Fin N) (hqp : q.1 ≤ p.1) :
    backwardArsenalWord p q = pureMatrixUnit p q := by
  have hforward : (mirrorFin p).1 ≤ (mirrorFin q).1 := by
    rw [mirrorFin_val, mirrorFin_val]
    omega
  simp only [backwardArsenalWord]
  rw [forwardArsenalWord_eq_matrixUnit (mirrorFin p) (mirrorFin q) hforward]
  exact poincareConjugate_matrixUnit p q

/-- Every finite matrix unit is generated by the actual GST
projector/Lefschetz/Poincare operator algebra. -/
theorem matrixUnit_generated_by_GST_arsenal
    {N : Nat} (p q : Fin N) :
    (p.1 ≤ q.1 ∧ forwardArsenalWord p q = pureMatrixUnit p q)
    ∨ (q.1 ≤ p.1 ∧ backwardArsenalWord p q = pureMatrixUnit p q) := by
  by_cases hpq : p.1 ≤ q.1
  · exact Or.inl ⟨hpq, forwardArsenalWord_eq_matrixUnit p q hpq⟩
  · have hqp : q.1 ≤ p.1 := by omega
    exact Or.inr ⟨hqp, backwardArsenalWord_eq_matrixUnit p q hqp⟩

/-- Explicit full-arsenal generation crown. -/
theorem explicit_arsenal_generation_crown :
    ∀ N (p q : Fin N),
      (p.1 ≤ q.1 ∧ forwardArsenalWord p q = pureMatrixUnit p q)
      ∨ (q.1 ≤ p.1 ∧ backwardArsenalWord p q = pureMatrixUnit p q) :=
  fun _ p q => matrixUnit_generated_by_GST_arsenal p q

#check diagonalLefschetzQ
#check poincareReverseQ
#check rawForwardWord
#check forwardArsenalWord
#check forwardArsenalWord_eq_matrixUnit
#check backwardArsenalWord
#check backwardArsenalWord_eq_matrixUnit
#check matrixUnit_generated_by_GST_arsenal

#print axioms forwardArsenalWord_eq_matrixUnit
#print axioms backwardArsenalWord_eq_matrixUnit
#print axioms matrixUnit_generated_by_GST_arsenal
#print axioms explicit_arsenal_generation_crown

end GSTClassicalHodgeExplicitArsenalGeneration
