import GSTClassicalHodgeProperCutCodimensionOne
import GSTNativeCodimensionCyclePresentation

/-!
# GST CLASSICAL HODGE — NATIVE CYCLE OF A PRINCIPAL PROJECTIVE CUT

The projective cutting engine now reaches the native Stage-2D cycle space.
For an irreducible smooth projective carrier and a source point, the selected
positive-degree principal section has only finitely many ambient coheight-one
points.  Summing the unit cycles at those points therefore gives a literal
finite rational codimension-one algebraic cycle.

This construction is independent of the Hodge package and of the cycle-class
map.  It is a genuine geometric source cycle manufactured from the projective
embedding, the relevance-selected homogeneous separator, Noetherianity, and
Mathlib's coheight convention.
-/

set_option maxHeartbeats 30000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry
open GSTProjectiveOverC
open GSTNativeCodimensionCyclePresentation
open GSTClassicalHodgePrincipalSectionDescent
open GSTClassicalHodgeProperCutCodimensionOne

namespace GSTClassicalHodgePrincipalCutNativeCycle

/-- Finite presentation containing every coheight-one point of the selected
principal cut, each with coefficient one. -/
noncomputable def principalCutPresentation
    (V : SmoothProjectiveComplexScheme)
    [IrreducibleSpace V.X]
    (x : V.X) : FiniteCodimensionPresentation V.X 1 := by
  classical
  exact (principalCutCodimensionOneFinset V x).sum
    (fun y => Finsupp.single y 1)

/-- Actual native codimension-one algebraic cycle generated by the selected
projective principal cut. -/
noncomputable def principalCutCycle
    (V : SmoothProjectiveComplexScheme)
    [IrreducibleSpace V.X]
    (x : V.X) : codimensionCycles V.X 1 :=
  realizeFiniteCodimensionPresentation V.X 1
    (principalCutPresentation V x)

/-- The principal-cut cycle is definitionally a finite sum of genuine
coheight-one point cycles. -/
theorem principalCutCycle_eq_sum
    (V : SmoothProjectiveComplexScheme)
    [IrreducibleSpace V.X]
    (x : V.X) :
    principalCutCycle V x =
      (principalCutCodimensionOneFinset V x).sum
        (fun y => codimensionPointCycle V.X 1 y) := by
  classical
  unfold principalCutCycle principalCutPresentation
  simp [realizeFiniteCodimensionPresentation, Finset.sum_finsuppSum]

/-- Native codimension receipt. -/
theorem principalCutCycle_is_codimension_one
    (V : SmoothProjectiveComplexScheme)
    [IrreducibleSpace V.X]
    (x : V.X) :
    (principalCutCycle V x : AlgebraicCycle V.X ℚ) ∈
      codimensionCycles V.X 1 :=
  (principalCutCycle V x).2

/-- Under any rational-linear cycle-class map, the class of the projective cut
cycle is the finite sum of the classes of its genuine coheight-one atoms. -/
theorem cycleClass_principalCutCycle
    {Coh : Type*} [AddCommGroup Coh] [Module ℚ Coh]
    (V : SmoothProjectiveComplexScheme)
    [IrreducibleSpace V.X]
    (x : V.X)
    (cl : codimensionCycles V.X 1 →ₗ[ℚ] Coh) :
    cl (principalCutCycle V x) =
      (principalCutPresentation V x).sum
        (fun y q => q • cl (codimensionPointCycle V.X 1 y)) := by
  exact linearMap_realizeFiniteCodimensionPresentation
    V.X 1 cl (principalCutPresentation V x)

/-- Geometric cycle crown: every source point canonically selects a finite
native codimension-one cycle through the projective principal-cut machinery. -/
theorem principal_cut_native_cycle_crown
    (V : SmoothProjectiveComplexScheme)
    [IrreducibleSpace V.X]
    (x : V.X) :
    ∃ Z : codimensionCycles V.X 1,
      Z = principalCutCycle V x :=
  ⟨principalCutCycle V x, rfl⟩

#check principalCutPresentation
#check principalCutCycle
#check principalCutCycle_is_codimension_one
#check cycleClass_principalCutCycle
#check principal_cut_native_cycle_crown

#print axioms principalCutPresentation
#print axioms principalCutCycle
#print axioms principalCutCycle_is_codimension_one
#print axioms cycleClass_principalCutCycle
#print axioms principal_cut_native_cycle_crown

end GSTClassicalHodgePrincipalCutNativeCycle
