import GSTClassicalHodgeGeometricCycleClassSpine
import GSTClassicalHodgeLimitlessTowerOrbitCrown
import GSTClassicalHodgeLimitlessProjectiveLefschetzTower
import GSTClassicalHodgeRankFreeArsenalIrreducibility

/-!
# GST CLASSICAL HODGE — LIMITLESS SPINE PROPAGATION

The earlier projective/cosmic tower crown packaged a family of Hodge seeds and
its successor formula as data.  That is unnecessary once the genuine
cycle-class spine has been constructed.

The native projective successor operator already exists geometrically.  The
spine gives its exact cohomological realization and proves Hodge-sector
preservation.  The limitless cosmic Lefschetz theory supplies the canonical
nonzero successor scalar.  Therefore both the native tower and its Hodge state
can be generated recursively with no separately supplied seed family or
intertwining structure.

At every step we normalize by the inverse cosmic coefficient.  Naturality of
the spine then proves that the recursively generated native cycle has exactly
the recursively generated Hodge class.  This removes the old
`ProjectiveTowerHodgeIntertwining` scaffolding from the mathematical core.
-/

set_option maxHeartbeats 90000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeLimitlessSpinePropagation

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeRankFreeArsenalIrreducibility
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgePrincipalCutSuccessorOperator
open GSTClassicalHodgeCodimensionZeroFundamentalCycle
open GSTClassicalHodgeLimitlessTowerOrbitCrown

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}

/-- Canonical Hodge state generated recursively by the genuine projective
principal-cut cohomology action and normalized by the true limitless cosmic
Lefschetz coefficient. -/
noncomputable def spineHodgeSeed
    (G : GeometricCycleClassSpine V H) :
    (p : Nat) → ClassicalHodgeFiber V H p
  | 0 =>
      ⟨H.cycleClass 0 (codimensionZeroFundamentalCycle V),
        G.codimensionZeroFundamentalClass_is_hodge⟩
  | p + 1 =>
      let prev := spineHodgeSeed G p
      let raw := (G.principalCutPair p).cohomologyOperator prev.1
      ⟨(successorScalar p)⁻¹ • raw,
        (rationalHodgeSubspace (H.hodgeBigrading (p + 1))).smul_mem
          ((successorScalar p)⁻¹)
          (G.principalCut_hodge p prev.1 prev.2)⟩

/-- Canonical native cycle generated by the same recursively normalized
projective principal-cut operator. -/
noncomputable def spineNativeTower
    (G : GeometricCycleClassSpine V H) :
    (p : Nat) → codimensionCycles V.X p
  | 0 => codimensionZeroFundamentalCycle V
  | p + 1 =>
      (successorScalar p)⁻¹ •
        successorNativeOperator V p (spineNativeTower G p)

@[simp]
theorem spineHodgeSeed_zero
    (G : GeometricCycleClassSpine V H) :
    spineHodgeSeed G 0 =
      ⟨H.cycleClass 0 (codimensionZeroFundamentalCycle V),
        G.codimensionZeroFundamentalClass_is_hodge⟩ := by
  rfl

@[simp]
theorem spineNativeTower_zero
    (G : GeometricCycleClassSpine V H) :
    spineNativeTower G 0 = codimensionZeroFundamentalCycle V := by
  rfl

/-- The unnormalized cohomological principal-cut image is exactly the true
cosmic successor coefficient times the normalized next Hodge seed. -/
theorem spineHodgeSeed_successor_formula
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    (G.principalCutPair p).cohomologyOperator (spineHodgeSeed G p).1 =
      successorScalar p • (spineHodgeSeed G (p + 1)).1 := by
  change (G.principalCutPair p).cohomologyOperator (spineHodgeSeed G p).1 =
    successorScalar p •
      ((successorScalar p)⁻¹ •
        (G.principalCutPair p).cohomologyOperator (spineHodgeSeed G p).1)
  rw [smul_smul]
  simp [successorScalar_ne_zero]

/-- Native recursion law. -/
theorem spineNativeTower_succ
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    spineNativeTower G (p + 1) =
      (successorScalar p)⁻¹ •
        successorNativeOperator V p (spineNativeTower G p) := by
  rfl

/-- **EXACT SPINE-TOWER CYCLE-CLASS LAW.**
The recursively generated native projective cycle has cycle class exactly equal
to the recursively generated genuine Hodge state in every weight. -/
theorem spineNativeTower_cycleClass
    (G : GeometricCycleClassSpine V H) :
    ∀ p : Nat,
      H.cycleClass p (spineNativeTower G p) = (spineHodgeSeed G p).1 := by
  intro p
  induction p with
  | zero => rfl
  | succ p ih =>
      rw [spineNativeTower_succ]
      rw [LinearMap.map_smul]
      have hnat := (G.principalCutPair p).cycleClass_natural
        (spineNativeTower G p)
      rw [G.principalCutPair_native p] at hnat
      rw [hnat, ih]
      rfl

/-- Every recursively generated Hodge state is algebraic, because it is the
actual class of the recursively generated native projective cycle. -/
theorem spineHodgeSeed_algebraic
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    spineHodgeSeed G p ∈ AlgebraicHodgeSubspace V H p := by
  rw [mem_AlgebraicHodgeSubspace_iff]
  rw [← GSTClassicalHodgeAtomicSpan.smoothProjective_cycleClass_range_eq_atomic_span
    V H p]
  exact ⟨spineNativeTower G p, spineNativeTower_cycleClass G p⟩

/-- Nonvanishing of the recursively generated cycle class is exactly
nonvanishing of the corresponding Hodge seed. -/
theorem spineHodgeSeed_ne_zero_iff_cycleClass_ne_zero
    (G : GeometricCycleClassSpine V H)
    (p : Nat) :
    spineHodgeSeed G p ≠ 0 ↔
      H.cycleClass p (spineNativeTower G p) ≠ 0 := by
  rw [spineNativeTower_cycleClass G p]
  constructor
  · intro h hval
    apply h
    apply Subtype.ext
    exact hval
  · intro h hseed
    apply h
    simpa [hseed]

/-- Whenever the canonical spine tower is nonzero in a weight, it supplies the
nontrivial algebraic Hodge subspace required by rank-free limitless
irreducibility. -/
theorem algebraicHodgeSubspace_ne_bot_of_spineSeed
    (G : GeometricCycleClassSpine V H)
    (p : Nat)
    (hne : spineHodgeSeed G p ≠ 0) :
    AlgebraicHodgeSubspace V H p ≠ ⊥ := by
  intro hbot
  have hmem := spineHodgeSeed_algebraic G p
  rw [hbot] at hmem
  have hz : spineHodgeSeed G p = 0 := by simpa using hmem
  exact hne hz

/-- The old tower-intertwining successor formula is now a theorem generated
from the spine rather than supplied as data. -/
theorem spine_limitless_successor_crown
    (G : GeometricCycleClassSpine V H) :
    ∀ p : Nat,
      (G.principalCutPair p).cohomologyOperator (spineHodgeSeed G p).1 =
        successorScalar p • (spineHodgeSeed G (p + 1)).1
      ∧ H.cycleClass (p + 1) (spineNativeTower G (p + 1)) =
        (spineHodgeSeed G (p + 1)).1 := by
  intro p
  exact ⟨spineHodgeSeed_successor_formula G p,
    spineNativeTower_cycleClass G (p + 1)⟩

#check spineHodgeSeed
#check spineNativeTower
#check spineHodgeSeed_successor_formula
#check spineNativeTower_cycleClass
#check spineHodgeSeed_algebraic
#check spineHodgeSeed_ne_zero_iff_cycleClass_ne_zero
#check algebraicHodgeSubspace_ne_bot_of_spineSeed
#check spine_limitless_successor_crown

#print axioms spineHodgeSeed_successor_formula
#print axioms spineNativeTower_cycleClass
#print axioms spineHodgeSeed_algebraic
#print axioms spine_limitless_successor_crown

end GSTClassicalHodgeLimitlessSpinePropagation
