import GSTClassicalHodgeGradedFiniteClosedCorrespondence
import GSTClassicalHodgeAtomicSpan
import GSTClassicalHodgeOmniversalSeparatorGhostCrown

/-!
# GST CLASSICAL HODGE — FINITE CORRESPONDENCE OPERATOR ALGEBRA

A single finite closed correspondence already supplies an honest native point
transport.  With point-generator Betti naturality, compact point normal form
promotes it to a complete native/cohomological operator pair.

What was still missing was the operator algebra generated by such genuine
correspondences.  Spectral projectors and cyclic-word arguments require sums,
rational scalings and compositions, not just one atom.

This file constructs that algebra without claiming that every algebraic
combination is represented by one new correspondence scheme.  Its atoms are
actual finite closed correspondences with verified point naturality; all word
operations are performed on their already-verified native/cohomological
operator pairs.  Exact cycle-class naturality is then proved inductively.

Thus polynomial/spectral words can now be formed on the classical side without
postulating a Hodge-basis action or a GST matrix unit.
-/

set_option maxHeartbeats 100000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeFiniteCorrespondenceOperatorAlgebra

open GSTProjectiveOverC
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeAtomicSpan
open GSTClassicalHodgeAtomicAnnihilator
open GSTClassicalHodgeFiniteClosedCorrespondence
open GSTClassicalHodgeGradedFiniteClosedCorrespondence
open GSTClassicalHodgeCrossWeightNativePropagation
open GSTClassicalHodgeOmniversalSeparatorGhostCrown

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-- One genuine same-weight finite-correspondence atom together with its
point-generator Betti naturality. -/
structure FiniteCorrespondenceAtom
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V)
    (p : Nat) where
  correspondence : FiniteClosedCorrespondence V
  naturality :
    GradedCorrespondencePointNaturality correspondence H p p

namespace FiniteCorrespondenceAtom

/-- Native cycle operator of a genuine correspondence atom. -/
noncomputable def cycleOperator
    (A : FiniteCorrespondenceAtom V H p) :
    codimensionCycles V.X p →ₗ[ℚ] codimensionCycles V.X p :=
  A.correspondence.gradedNativeCycleOperator p p

/-- Betti operator of a genuine correspondence atom. -/
noncomputable def cohomologyOperator
    (A : FiniteCorrespondenceAtom V H p) :
    RationalSingularCohomology H.analytification (2 * p) →ₗ[ℚ]
      RationalSingularCohomology H.analytification (2 * p) :=
  A.naturality.cohomologyOperator

/-- Exact cycle-class square for one atom. -/
theorem cycleClass_natural
    (A : FiniteCorrespondenceAtom V H p)
    (Z : codimensionCycles V.X p) :
    H.cycleClass p (A.cycleOperator Z) =
      A.cohomologyOperator (H.cycleClass p Z) :=
  A.naturality.cycleClass_natural Z

/-- The atom as the repo's standard native/cohomological pair. -/
noncomputable def operatorPair
    (A : FiniteCorrespondenceAtom V H p) :
    GradedCycleClassOperatorPair V H p p :=
  A.naturality.toGradedCycleClassOperatorPair

end FiniteCorrespondenceAtom

/-- Rational operator words generated by genuine finite-correspondence atoms. -/
inductive FiniteCorrespondenceWord
    (V : SmoothProjectiveComplexScheme)
    (H : HodgeBigradedBettiData V)
    (p : Nat) : Type
  | id : FiniteCorrespondenceWord V H p
  | atom : FiniteCorrespondenceAtom V H p → FiniteCorrespondenceWord V H p
  | add : FiniteCorrespondenceWord V H p →
      FiniteCorrespondenceWord V H p → FiniteCorrespondenceWord V H p
  | smul : ℚ → FiniteCorrespondenceWord V H p → FiniteCorrespondenceWord V H p
  | comp : FiniteCorrespondenceWord V H p →
      FiniteCorrespondenceWord V H p → FiniteCorrespondenceWord V H p

namespace FiniteCorrespondenceWord

/-- Native-cycle interpretation of a finite-correspondence word. -/
noncomputable def cycleEval :
    FiniteCorrespondenceWord V H p →
      Module.End ℚ (codimensionCycles V.X p)
  | id => LinearMap.id
  | atom A => A.cycleOperator
  | add u v => u.cycleEval + v.cycleEval
  | smul q u => q • u.cycleEval
  | comp u v => u.cycleEval.comp v.cycleEval

/-- Betti-cohomology interpretation of the same word. -/
noncomputable def cohomologyEval :
    FiniteCorrespondenceWord V H p →
      Module.End ℚ
        (RationalSingularCohomology H.analytification (2 * p))
  | id => LinearMap.id
  | atom A => A.cohomologyOperator
  | add u v => u.cohomologyEval + v.cohomologyEval
  | smul q u => q • u.cohomologyEval
  | comp u v => u.cohomologyEval.comp v.cohomologyEval

@[simp]
theorem cycleEval_id :
    (FiniteCorrespondenceWord.id : FiniteCorrespondenceWord V H p).cycleEval =
      LinearMap.id := rfl

@[simp]
theorem cohomologyEval_id :
    (FiniteCorrespondenceWord.id : FiniteCorrespondenceWord V H p).cohomologyEval =
      LinearMap.id := rfl

/-- **WORD NATURALITY.**  Every rational word generated by genuine
finite-correspondence atoms preserves the exact cycle-class square. -/
theorem cycleClass_natural
    (w : FiniteCorrespondenceWord V H p)
    (Z : codimensionCycles V.X p) :
    H.cycleClass p (w.cycleEval Z) =
      w.cohomologyEval (H.cycleClass p Z) := by
  induction w with
  | id => rfl
  | atom A => exact A.cycleClass_natural Z
  | add u v ihu ihv =>
      simp only [cycleEval, cohomologyEval, LinearMap.add_apply]
      rw [map_add, ihu, ihv]
  | smul q u ihu =>
      simp only [cycleEval, cohomologyEval, LinearMap.smul_apply]
      rw [map_smul, ihu]
  | comp u v ihu ihv =>
      simp only [cycleEval, cohomologyEval, LinearMap.comp_apply]
      rw [ihu (v.cycleEval Z), ihv]

/-- Every word sends an actual cycle class to another actual cycle class. -/
theorem maps_cycleClassRange
    (w : FiniteCorrespondenceWord V H p)
    {alpha : RationalSingularCohomology H.analytification (2 * p)}
    (halpha : alpha ∈ LinearMap.range (H.cycleClass p)) :
    w.cohomologyEval alpha ∈ LinearMap.range (H.cycleClass p) := by
  rcases halpha with ⟨Z, rfl⟩
  exact ⟨w.cycleEval Z, w.cycleClass_natural Z⟩

/-- Equivalently, every finite-correspondence word preserves the complete
atomic point-cycle span. -/
theorem maps_atomicSpan
    (w : FiniteCorrespondenceWord V H p)
    {alpha : RationalSingularCohomology H.analytification (2 * p)}
    (halpha : alpha ∈ pointCycleClassSpan p (H.cycleClass p)) :
    w.cohomologyEval alpha ∈ pointCycleClassSpan p (H.cycleClass p) := by
  rw [← smoothProjective_cycleClass_range_eq_atomic_span V H p] at halpha ⊢
  exact w.maps_cycleClassRange halpha

/-- Every omniversal separator annihilates every finite-correspondence word
applied to every actual algebraic cycle class. -/
theorem ghost_detector_word_eq_zero
    {G : GSTClassicalHodgeGeometricCycleClassSpine.GeometricCycleClassSpine V H}
    (E : OmniversalSeparatorGhost G)
    (w : FiniteCorrespondenceWord V H E.weight)
    (Z : codimensionCycles V.X E.weight) :
    E.separator.detector
      (w.cohomologyEval (H.cycleClass E.weight Z)) = 0 := by
  have hspan :
      w.cohomologyEval (H.cycleClass E.weight Z) ∈
        pointCycleClassSpan E.weight (H.cycleClass E.weight) := by
    apply w.maps_atomicSpan
    rw [← smoothProjective_cycleClass_range_eq_atomic_span V H E.weight]
    exact ⟨Z, rfl⟩
  have hker :
      pointCycleClassSpan E.weight (H.cycleClass E.weight) ≤
        LinearMap.ker E.separator.detector :=
    (annihilatesPointCycles_iff_atomicSpan_le_ker
      E.weight (H.cycleClass E.weight) E.separator.detector).mp
      E.separator.annihilates_atoms
  exact hker hspan

/-- Powers of one genuine correspondence word, used by polynomial/spectral
constructions. -/
noncomputable def pow
    (w : FiniteCorrespondenceWord V H p) : Nat → FiniteCorrespondenceWord V H p
  | 0 => id
  | n + 1 => comp w (pow w n)

@[simp]
theorem cycleEval_pow_zero
    (w : FiniteCorrespondenceWord V H p) :
    (w.pow 0).cycleEval = LinearMap.id := rfl

@[simp]
theorem cohomologyEval_pow_zero
    (w : FiniteCorrespondenceWord V H p) :
    (w.pow 0).cohomologyEval = LinearMap.id := rfl

end FiniteCorrespondenceWord

#check FiniteCorrespondenceAtom
#check FiniteCorrespondenceAtom.operatorPair
#check FiniteCorrespondenceWord
#check FiniteCorrespondenceWord.cycleEval
#check FiniteCorrespondenceWord.cohomologyEval
#check FiniteCorrespondenceWord.cycleClass_natural
#check FiniteCorrespondenceWord.maps_cycleClassRange
#check FiniteCorrespondenceWord.maps_atomicSpan
#check FiniteCorrespondenceWord.ghost_detector_word_eq_zero
#check FiniteCorrespondenceWord.pow

#print axioms FiniteCorrespondenceWord.cycleClass_natural
#print axioms FiniteCorrespondenceWord.maps_cycleClassRange
#print axioms FiniteCorrespondenceWord.ghost_detector_word_eq_zero

end GSTClassicalHodgeFiniteCorrespondenceOperatorAlgebra
