import GSTClassicalHodgeGeometricCycleClassSpine
import GSTClassicalHodgeCanonicalCosmicRealizationEquivalence
import GSTClassicalHodgeProjectiveCorrespondenceAlgebra
import GSTClassicalHodgePrimitivePushforwardNaturality

/-!
# GST CLASSICAL HODGE — PROJECTIVE CORRESPONDENCE REALIZATION OF THE COSMIC WORD

The canonical fixed-weight target is now a concrete native-operator problem.
This module connects that target to the genuine projective-correspondence
algebra generated by actual algebraic self-maps of the smooth projective
carrier.

Given the genuine geometric cycle-class spine, every operator in the rational
projective-correspondence span has a canonical cohomological realization with
an exact cycle-class commuting square.  Therefore, if its Hodge restriction is
the true limitless cosmic read/write operator, it automatically supplies the
native canonical realization required by the no-escape theorem.

The remaining construction target is consequently explicit and geometric:
represent the single canonical two-sheet GST read/write word inside the
projective correspondence algebra.  No cycle-class surjectivity or Hodge basis
cycle is assumed here.
-/

set_option maxHeartbeats 70000000
set_option maxRecDepth 1000000

noncomputable section

open AlgebraicGeometry

namespace GSTClassicalHodgeProjectiveCorrespondenceCosmicRealization

open GSTProjectiveOverC
open GSTGeometricRealizationStage2D
open GSTGeometricRealizationStage2F
open GSTGeometricRealizationStage2G
open GSTClassicalHodgeFiberedCosmology
open GSTClassicalHodgeProjectiveCorrespondenceAlgebra
open GSTClassicalHodgePrimitivePushforwardNaturality
open GSTClassicalHodgeGeometricCycleClassSpine
open GSTClassicalHodgeCanonicalCosmicRealizationEquivalence
open GSTClassicalHodgeCanonicalLimitlessNaturalityCrown

variable {V : SmoothProjectiveComplexScheme}
variable {H : HodgeBigradedBettiData V}
variable {p : Nat}

/-- The canonical cohomological action attached to one genuine projective
correspondence operator through the geometric cycle-class spine. -/
noncomputable def projectiveCorrespondencePair
    (G : GeometricCycleClassSpine V H)
    (K : ProjectiveNativeKernel V p) :=
  correspondenceOperatorPair
    (fun f => G.pushforward_naturality p f) K

/-- A concrete projective-correspondence realization of one ordered cosmic
read/write operator.  The native operator is forced to live in the genuine
correspondence span; the only comparison law states that its independently
induced cohomological action agrees, on the true Hodge fiber, with the already
constructed limitless cosmic action. -/
structure ProjectiveCosmicRealization
    (G : GeometricCycleClassSpine V H)
    (i j : ClassicalHodgeBasisIndex V H p) where
  kernel : ProjectiveNativeKernel V p
  acts_as_cosmic :
    ∀ alpha : ClassicalHodgeFiber V H p,
      (projectiveCorrespondencePair G kernel).cohomologyOperator alpha.1 =
        canonicalCosmicAmbient i j alpha.1

namespace ProjectiveCosmicRealization

/-- A projective cosmic realization is automatically a genuine native
canonical cosmic realization. -/
noncomputable def toNativeCanonical
    {G : GeometricCycleClassSpine V H}
    {i j : ClassicalHodgeBasisIndex V H p}
    (R : ProjectiveCosmicRealization G i j) :
    NativeCanonicalCosmicRealization (V := V) (H := H) i j where
  native := R.kernel.1
  naturality := by
    intro Z
    have hpair := (projectiveCorrespondencePair G R.kernel).cycleClass_cycleOperator Z
    have hClassHodge := G.algebraic_is_hodge p Z
    let alphaH : ClassicalHodgeFiber V H p :=
      ⟨H.cycleClass p Z, hClassHodge⟩
    rw [R.acts_as_cosmic alphaH] at hpair
    exact hpair

/-- Consequently the canonical limitless action preserves the genuine
algebraic Hodge fiber. -/
theorem preserves_algebraicFiber
    {G : GeometricCycleClassSpine V H}
    {i j : ClassicalHodgeBasisIndex V H p}
    (R : ProjectiveCosmicRealization G i j)
    (alpha : ClassicalHodgeFiber V H p)
    (halg : alpha ∈
      GSTClassicalHodgeLimitlessTwoSlotFailureDichotomy.AlgebraicFiber
        (V := V) (H := H) (p := p)) :
    GSTClassicalHodgeLimitlessTwoSlotFailureDichotomy.liftCosmicWindowOperator
        (GSTClassicalHodgeLimitlessTwoSlotFailureDichotomy.pairBasisIndex i j)
        (GSTClassicalHodgeLimitlessCosmicMatrixUnits.rationalCosmicMatrixUnit
          GSTClassicalHodgeFullArsenalIrreducibility.sourceSlot.1
          GSTClassicalHodgeFullArsenalIrreducibility.targetSlot.1)
        alpha ∈
      GSTClassicalHodgeLimitlessTwoSlotFailureDichotomy.AlgebraicFiber
        (V := V) (H := H) (p := p) :=
  R.toNativeCanonical.preserves_algebraicFiber alpha halg

end ProjectiveCosmicRealization

/-- A genuine projective-correspondence realization for every ordered pair
supplies canonical cosmic naturality. -/
theorem canonicalCosmicNaturality_of_projectiveCorrespondences
    (G : GeometricCycleClassSpine V H)
    (R : ∀ i j : ClassicalHodgeBasisIndex V H p,
      ProjectiveCosmicRealization G i j) :
    CanonicalCosmicNaturality (V := V) (H := H) p := by
  apply canonicalCosmicNaturality_of_nativeRealizations
  intro i j
  exact (R i j).toNativeCanonical

/-- One nonzero algebraic seed plus projective realization of the one canonical
limitless read/write operation saturates the entire Hodge fiber. -/
theorem algebraicFiber_eq_top_of_projectiveCosmicRealizations
    (G : GeometricCycleClassSpine V H)
    (hseed :
      GSTClassicalHodgeLimitlessTwoSlotFailureDichotomy.AlgebraicFiber
        (V := V) (H := H) (p := p) ≠ ⊥)
    (R : ∀ i j : ClassicalHodgeBasisIndex V H p,
      ProjectiveCosmicRealization G i j) :
    GSTClassicalHodgeLimitlessTwoSlotFailureDichotomy.AlgebraicFiber
        (V := V) (H := H) (p := p) = ⊤ := by
  exact algebraicFiber_eq_top hseed
    (canonicalCosmicNaturality_of_projectiveCorrespondences G R)

/-- Exact fixed-weight Stage-2G landing through the genuine projective
correspondence algebra. -/
theorem hodge_weight_of_projectiveCosmicRealizations
    (G : GeometricCycleClassSpine V H)
    (hseed :
      GSTClassicalHodgeLimitlessTwoSlotFailureDichotomy.AlgebraicFiber
        (V := V) (H := H) (p := p) ≠ ⊥)
    (R : ∀ i j : ClassicalHodgeBasisIndex V H p,
      ProjectiveCosmicRealization G i j) :
    rationalHodgeSubspace (H.hodgeBigrading p) ≤
      LinearMap.range (H.cycleClass p) := by
  exact GSTClassicalHodgeCanonicalLimitlessNaturalityCrown.hodge_weight
    hseed (canonicalCosmicNaturality_of_projectiveCorrespondences G R)

#check projectiveCorrespondencePair
#check ProjectiveCosmicRealization
#check ProjectiveCosmicRealization.toNativeCanonical
#check canonicalCosmicNaturality_of_projectiveCorrespondences
#check algebraicFiber_eq_top_of_projectiveCosmicRealizations
#check hodge_weight_of_projectiveCosmicRealizations

#print axioms ProjectiveCosmicRealization.toNativeCanonical
#print axioms canonicalCosmicNaturality_of_projectiveCorrespondences
#print axioms algebraicFiber_eq_top_of_projectiveCosmicRealizations
#print axioms hodge_weight_of_projectiveCosmicRealizations

end GSTClassicalHodgeProjectiveCorrespondenceCosmicRealization
