import GSTGraphV2OmniversalCore

/-!
# GST GRAPH V2 — SELF-EXPANDING THREE-ROOT COSMOLOGY

This file implements a stronger interpretation of the historical three GST
spaces.

The three spaces are not labels on a fixed graph.  They are three root worlds
of a recursively generated universe of worlds.  Every world may have its own
state type and its own law type.  A causal birth may consume an arbitrarily
indexed family of existing worlds and produce a new world; that new world can
immediately participate in later births.  Thus the ontology itself branches.

Nothing forces two worlds to have the same geometry, dimension language,
coordinate language, state carrier, or law carrier.  Arithmetic is therefore
one branch, not the ambient ontology.

The least world-closure below is impredicative rather than bounded by a finite
rectangle or a fixed construction depth.  It characterizes exactly the
predicates containing the roots and closed under every certified world-birth.
-/

universe u v w z

namespace GSTGraphV2SelfExpandingCosmology

open GSTGraphV2OmniversalCore

/-- A recursively branching GST cosmos.

`World` is a universe of spaces rather than a universe of points.
`State W` is the internal state carrier of world `W`.
`Law W` is the world-specific law/certificate carrier.

A `Birth src target` is a certified causal event saying that the arbitrarily
indexed family of worlds `src` can generate the new world `target`.  Since the
target is itself a `World`, generation can recurse without changing ontology. -/
structure SelfExpandingCosmos where
  World : Type u
  State : World → Type v
  Law : World → Type w
  root : Sector → World
  LocalEvent : {W : World} → State W → State W → Sort z
  Transport : {A B : World} → State A → State B → Sort z
  Birth : {I : Type u} → (I → World) → World → Sort z

namespace SelfExpandingCosmos

variable (C : SelfExpandingCosmos.{u,v,w,z})

/-- A predicate on worlds is cosmologically closed when every certified birth
whose source worlds satisfy the predicate produces another world satisfying
it.  The source family may have any arity in the ambient universe. -/
def WorldClosed (P : C.World → Prop) : Prop :=
  ∀ {I : Type u} {src : I → C.World} {target : C.World},
    C.Birth src target →
    (∀ i, P (src i)) →
    P target

/-- Least closure generated by a seed family and all certified world births.

This definition does not expose a fixed numerical stage.  `W` is in the
closure precisely when every birth-closed predicate containing the seeds must
contain `W`. -/
def WorldClosure (Seed : C.World → Prop) (W : C.World) : Prop :=
  ∀ P : C.World → Prop,
    (∀ X, Seed X → P X) →
    WorldClosed C P →
    P W

/-- Every seed world is already present in its generated cosmos. -/
theorem seed_mem_worldClosure
    (Seed : C.World → Prop) {W : C.World}
    (hW : Seed W) :
    WorldClosure C Seed W := by
  intro P hSeed _hClosed
  exact hSeed W hW

/-- A certified birth from already-generated source worlds produces another
generated world.  This is the recursive expansion rule. -/
theorem birth_mem_worldClosure
    {Seed : C.World → Prop}
    {I : Type u} {src : I → C.World} {target : C.World}
    (e : C.Birth src target)
    (hsrc : ∀ i, WorldClosure C Seed (src i)) :
    WorldClosure C Seed target := by
  intro P hSeed hClosed
  apply hClosed e
  intro i
  exact hsrc i P hSeed hClosed

/-- Elimination/induction principle for the impredicative world closure. -/
theorem worldClosure_induction
    {Seed P : C.World → Prop}
    (hSeed : ∀ W, Seed W → P W)
    (hBirth : WorldClosed C P)
    {W : C.World}
    (hW : WorldClosure C Seed W) :
    P W :=
  hW P hSeed hBirth

/-- The three historical GST sectors are now the three root worlds. -/
def RootSeed (W : C.World) : Prop :=
  ∃ s : Sector, C.root s = W

/-- A world belongs to the generated GST cosmos when it lies in the recursive
closure of the three roots. -/
def Generated (W : C.World) : Prop :=
  WorldClosure C (RootSeed C) W

/-- Every one of the three roots is generated. -/
theorem root_generated (s : Sector) :
    Generated C (C.root s) := by
  apply seed_mem_worldClosure C (RootSeed C)
  exact ⟨s, rfl⟩

/-- Recursive generation is closed under arbitrary-arity world births. -/
theorem birth_generated
    {I : Type u} {src : I → C.World} {target : C.World}
    (e : C.Birth src target)
    (hsrc : ∀ i, Generated C (src i)) :
    Generated C target := by
  exact birth_mem_worldClosure C e hsrc

/-- Provenance of one historical root through an arbitrarily deep branch.
A world can carry more than one root in its ancestry, so the old three-way
partition can generate genuinely mixed descendants. -/
inductive UsesRoot (s : Sector) : C.World → Prop
  | root : UsesRoot s (C.root s)
  | birth
      {I : Type u} {src : I → C.World} {target : C.World}
      (e : C.Birth src target)
      (i : I)
      (h : UsesRoot s (src i)) :
      UsesRoot s target

/-- The root-origin profile of a world.  This is not restricted to a single
sector: descendants may retain ancestry from any subset of the three roots. -/
def OriginProfile (W : C.World) (s : Sector) : Prop :=
  UsesRoot C s W

/-- A world is mixed when at least two distinct GST roots occur in its causal
ancestry. -/
def MixedOrigin (W : C.World) : Prop :=
  ∃ s t : Sector,
    s ≠ t ∧ UsesRoot C s W ∧ UsesRoot C t W

/-- A world is triadic when all three GST roots occur in its ancestry. -/
def TriadicOrigin (W : C.World) : Prop :=
  ∀ s : Sector, UsesRoot C s W

/-- An emergent world is generated by the root cosmos but is not itself one of
the three roots. -/
def EmergentWorld (W : C.World) : Prop :=
  Generated C W ∧ ∀ s : Sector, C.root s ≠ W

/-- Root provenance propagates through every later birth using that branch. -/
theorem usesRoot_of_birth
    {s : Sector}
    {I : Type u} {src : I → C.World} {target : C.World}
    (e : C.Birth src target)
    (i : I)
    (h : UsesRoot C s (src i)) :
    UsesRoot C s target :=
  UsesRoot.birth e i h

/-- Any semantic predicate containing the three roots and stable under world
births holds on the entire recursively generated cosmos. -/
theorem generated_induction
    {P : C.World → Prop}
    (hRoot : ∀ s : Sector, P (C.root s))
    (hBirth : WorldClosed C P)
    {W : C.World}
    (hW : Generated C W) :
    P W := by
  apply worldClosure_induction C (P := P) _ hBirth hW
  intro X hX
  rcases hX with ⟨s, rfl⟩
  exact hRoot s

/-- The ontology has no globally fixed internal state type: each world selects
its own dependent state carrier. -/
abbrev InternalState (W : C.World) := C.State W

/-- Likewise the law language is world-dependent.  A born world can therefore
carry a law type unrelated to the law types of its causal parents. -/
abbrev InternalLaw (W : C.World) := C.Law W

#check SelfExpandingCosmos
#check SelfExpandingCosmos.WorldClosure
#check SelfExpandingCosmos.Generated
#check SelfExpandingCosmos.UsesRoot
#check SelfExpandingCosmos.MixedOrigin
#check SelfExpandingCosmos.TriadicOrigin
#check SelfExpandingCosmos.generated_induction

end SelfExpandingCosmos
end GSTGraphV2SelfExpandingCosmology
