import GSTGeneralSpace

/-!
# GST GRAPH V2 — OMNIVERSAL THREE-SECTOR EVENT CORE

The historical GST Graph V2 carries three physical spaces, but its canonical
implementation obtains those spaces from x4/base3 arithmetic state.  This file
separates the ontology from that realization.

The primitive data are now:

* an arbitrary node carrier;
* one of the three historical GST sectors on every node;
* a typed event between arbitrary pairs of nodes.

No natural-number coordinate, radix, metric, dimension, carry, digit, energy,
or finite horizon occurs in the core.  Number theory, manifolds, schemes,
Hodge geometry, and future cosmological models are intended to be independent
realizations of this same event ontology.

The path and closure constructions below are generated from actual events.
Thus "closure" has an exact formal meaning: the least reachability closure of
a seed predicate under the event system.
-/

universe u v

namespace GSTGraphV2OmniversalCore

/-- The three distinguished GST ontological sectors, now independent of any
number-theoretic carry coordinate. -/
inductive Sector
  | null
  | altMinus
  | gstPlus
  deriving Repr, DecidableEq

/-- A carrier-agnostic GST event cosmos.

`Node` may be a number-theoretic state, a manifold point, a scheme point, an
algebraic cycle, a cohomology class, a correspondence, a local stalk state, or
any future geometric/cosmological object.  `Event x y` is the type of certified
causal transitions from `x` to `y`. -/
structure OmniversalGraph where
  Node : Type u
  sector : Node → Sector
  Event : Node → Node → Sort v

namespace OmniversalGraph

variable (G : OmniversalGraph.{u,v})

/-- The full fiber of one of the three ontological sectors.  Each sector may
therefore carry an arbitrarily large family of different concrete space
states. -/
abbrev SectorFiber (s : Sector) := {x : G.Node // G.sector x = s}

/-- Finite composable causal history generated by primitive events. -/
inductive Path : G.Node → G.Node → Type (max u v)
  | nil (x : G.Node) : Path x x
  | cons {x y z : G.Node} (e : G.Event x y) (tail : Path y z) : Path x z

namespace Path

/-- Concatenate two causal histories. -/
def comp {x y z : G.Node} : Path G x y → Path G y z → Path G x z
  | .nil _, q => q
  | .cons e p, q => .cons e (comp p q)

@[simp]
theorem nil_comp {x y : G.Node} (p : Path G x y) :
    comp (.nil x) p = p := rfl

@[simp]
theorem comp_nil {x y : G.Node} (p : Path G x y) :
    comp p (.nil y) = p := by
  induction p with
  | nil => rfl
  | cons e tail ih =>
      simp [comp, ih]

@[simp]
theorem comp_assoc
    {w x y z : G.Node}
    (p : Path G w x) (q : Path G x y) (r : Path G y z) :
    comp (comp p q) r = comp p (comp q r) := by
  induction p with
  | nil => rfl
  | cons e tail ih =>
      simp [comp, ih]

/-- A primitive event is a one-step causal history. -/
def single {x y : G.Node} (e : G.Event x y) : Path G x y :=
  .cons e (.nil y)

end Path

/-- Event-generated reachability. -/
def Reachable (x y : G.Node) : Prop := Nonempty (Path G x y)

@[simp]
theorem reachable_refl (x : G.Node) : Reachable G x x :=
  ⟨Path.nil x⟩

/-- Every primitive event is a reachable causal transition. -/
theorem reachable_of_event {x y : G.Node} (e : G.Event x y) :
    Reachable G x y :=
  ⟨Path.single G e⟩

/-- Reachability is transitively closed by path concatenation. -/
theorem reachable_trans {x y z : G.Node}
    (hxy : Reachable G x y) (hyz : Reachable G y z) :
    Reachable G x z := by
  rcases hxy with ⟨p⟩
  rcases hyz with ⟨q⟩
  exact ⟨Path.comp G p q⟩

/-- The General-Space realization generated by the event graph itself.  No
external coordinates are introduced: paths are precisely event histories. -/
def toGeneralSpace : GSTGeneralSpace.GeneralSpace where
  Point := G.Node
  Path := Path G
  idPath := Path.nil
  compPath := Path.comp G
  comp_id_left := by
    intro x y p
    rfl
  comp_id_right := by
    intro x y p
    exact Path.comp_nil G p
  comp_assoc := by
    intro w x y z p q r
    exact Path.comp_assoc G p q r

/-- Least event-reachability closure of a seed predicate. -/
def Closure (Seed : G.Node → Prop) (y : G.Node) : Prop :=
  ∃ x : G.Node, Seed x ∧ Reachable G x y

/-- Every seed already belongs to its event closure. -/
theorem seed_mem_closure (Seed : G.Node → Prop) {x : G.Node}
    (hx : Seed x) : Closure G Seed x :=
  ⟨x, hx, reachable_refl G x⟩

/-- Closure is monotone in the seed family. -/
theorem closure_mono
    {Seed₁ Seed₂ : G.Node → Prop}
    (h : ∀ x, Seed₁ x → Seed₂ x) :
    ∀ x, Closure G Seed₁ x → Closure G Seed₂ x := by
  intro x hx
  rcases hx with ⟨s, hs, hsx⟩
  exact ⟨s, h s hs, hsx⟩

/-- Closing an already closed family adds nothing: event closure is idempotent. -/
theorem closure_idempotent (Seed : G.Node → Prop) (x : G.Node) :
    Closure G (Closure G Seed) x ↔ Closure G Seed x := by
  constructor
  · rintro ⟨y, ⟨s, hs, hsy⟩, hyx⟩
    exact ⟨s, hs, reachable_trans G hsy hyx⟩
  · intro hx
    exact seed_mem_closure G (Closure G Seed) hx

/-- A semantic predicate is event-stable when every primitive event preserves
it.  This is the key interface for importing genuine mathematical meaning into
the otherwise carrier-agnostic graph. -/
def EventStable (P : G.Node → Prop) : Prop :=
  ∀ {x y : G.Node}, G.Event x y → P x → P y

/-- Event stability propagates through an arbitrary causal history. -/
theorem Path.preserves
    {P : G.Node → Prop}
    (hP : EventStable G P)
    {x y : G.Node}
    (p : Path G x y) :
    P x → P y := by
  induction p with
  | nil => exact fun hx => hx
  | cons e tail ih =>
      intro hx
      exact ih (hP e hx)

/-- **SEMANTIC CLOSURE PRINCIPLE.**
If every seed has a property and every event preserves that property, then the
entire unbounded event closure has that property. -/
theorem closure_sound
    {Seed P : G.Node → Prop}
    (hSeed : ∀ x, Seed x → P x)
    (hStable : EventStable G P) :
    ∀ x, Closure G Seed x → P x := by
  intro x hx
  rcases hx with ⟨s, hs, p⟩
  rcases p with ⟨p⟩
  exact Path.preserves G hStable p (hSeed s hs)

/-- Optional acyclicity capability for genuinely causal realizations.  It is
not forced on the universal ontology because reversible geometries and
symmetries are also legitimate realizations. -/
def CausallyAcyclic : Prop :=
  ∀ {x y : G.Node}, Reachable G x y → Reachable G y x → x = y

/-- Omniversal closure crown: reflexivity, transitivity, and idempotence are
properties of the event-generated ontology itself, independent of the concrete
realization. -/
theorem omniversal_closure_crown (Seed : G.Node → Prop) :
    (∀ x, Seed x → Closure G Seed x)
      ∧ (∀ x y z, Reachable G x y → Reachable G y z → Reachable G x z)
      ∧ (∀ x, Closure G (Closure G Seed) x ↔ Closure G Seed x) := by
  exact ⟨
    fun _ hx => seed_mem_closure G Seed hx,
    fun _ _ _ hxy hyz => reachable_trans G hxy hyz,
    fun x => closure_idempotent G Seed x⟩

#check Sector
#check OmniversalGraph
#check OmniversalGraph.Path
#check OmniversalGraph.Reachable
#check OmniversalGraph.Closure
#check OmniversalGraph.EventStable
#check OmniversalGraph.closure_sound
#check OmniversalGraph.CausallyAcyclic
#check OmniversalGraph.omniversal_closure_crown

end OmniversalGraph
end GSTGraphV2OmniversalCore
