import Mathlib
import Mathlib.RingTheory.MvPolynomial.Ideal
import GSTUniversalLefschetzCosmology
import GSTGradedWorldAlgebra

/-!
# GST TRUNCATED WORLD COHOMOLOGY RING

The separate axis, grading and Lefschetz laws of a rectangular GST world
come from one commutative operator algebra.

For an A x B world let H be the digit-axis shift and V the carry-axis shift.
They commute and satisfy H^B = 0, V^A = 0.  Hence the polynomial action of
Z[H,V] factors canonically through

    Z[H,V] / (H^B, V^A).

This file constructs that quotient and its representation on WorldCoef A B.
The original 4 x 3 crown is therefore the specialization

    Z[H,V] / (H^3, V^4).

No fixed twelve-cell argument appears in the construction.
-/

set_option maxHeartbeats 20000000
set_option maxRecDepth 1000000

noncomputable section

namespace GSTTruncatedWorldCohomologyRing

open GSTWorldCosmology
open GSTUniversalLefschetzCosmology
open GSTGradedWorldAlgebra
open MvPolynomial
open scoped IsMulCommutative

variable (A B : Nat)

/-! ## 1. The commutative operator ring generated by the two GST axes -/

private theorem axis_generators_commute
    {x y : Module.End ℤ (WorldCoef A B)}
    (hx : x ∈ ({digitEndo A B, carryEndo A B} :
      Set (Module.End ℤ (WorldCoef A B))))
    (hy : y ∈ ({digitEndo A B, carryEndo A B} :
      Set (Module.End ℤ (WorldCoef A B)))) :
    x * y = y * x := by
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx hy
  rcases hx with rfl | rfl <;> rcases hy with rfl | rfl
  · rfl
  · exact (digit_carry_commute (A:=A) (B:=B)).eq
  · exact (digit_carry_commute (A:=A) (B:=B)).eq.symm
  · rfl

/-- The commutative subring generated by the native digit and carry
endomorphisms.  The ambient endomorphism ring need not be commutative. -/
abbrev WorldOperatorRing : Type :=
  Subring.closure
    ({digitEndo A B, carryEndo A B} :
      Set (Module.End ℤ (WorldCoef A B)))

instance : IsMulCommutative (WorldOperatorRing A B) :=
  Subring.isMulCommutative_closure
    (fun x hx y hy => axis_generators_commute A B hx hy)

def hOp : WorldOperatorRing A B :=
  ⟨digitEndo A B,
    Subring.subset_closure (Set.mem_insert _ _)⟩

def vOp : WorldOperatorRing A B :=
  ⟨carryEndo A B,
    Subring.subset_closure
      (Set.mem_insert_of_mem _ (Set.mem_singleton _))⟩

@[simp]
theorem hOp_val :
    (hOp A B : Module.End ℤ (WorldCoef A B)) = digitEndo A B :=
  rfl

@[simp]
theorem vOp_val :
    (vOp A B : Module.End ℤ (WorldCoef A B)) = carryEndo A B :=
  rfl

@[simp]
theorem hOp_pow_depth :
    (hOp A B)^B = 0 := by
  apply Subtype.ext
  exact digitEndo_pow_depth (A:=A) (B:=B)

@[simp]
theorem vOp_pow_depth :
    (vOp A B)^A = 0 := by
  apply Subtype.ext
  exact carryEndo_pow_depth (A:=A) (B:=B)

/-! ## 2. Universal polynomial presentation -/

abbrev WorldPoly : Type := MvPolynomial (Fin 2) ℤ

abbrev Hpoly : WorldPoly := X (0 : Fin 2)

abbrev Vpoly : WorldPoly := X (1 : Fin 2)

/-- The truncation ideal (H^B,V^A). -/
def truncIdeal : Ideal WorldPoly :=
  Ideal.span
    ({Hpoly ^ B, Vpoly ^ A} : Set WorldPoly)

/-- Polynomial evaluation at the native GST axis operators. -/
def evalWorldPoly :
    WorldPoly →+* WorldOperatorRing A B :=
  eval₂Hom (Int.castRingHom (WorldOperatorRing A B))
    ![hOp A B, vOp A B]

@[simp]
theorem evalWorldPoly_H :
    evalWorldPoly A B Hpoly = hOp A B := by
  simp [evalWorldPoly, Hpoly]

@[simp]
theorem evalWorldPoly_V :
    evalWorldPoly A B Vpoly = vOp A B := by
  simp [evalWorldPoly, Vpoly]

/-- The native representation kills both truncation generators. -/
theorem truncIdeal_le_ker_evalWorldPoly :
    truncIdeal A B ≤ RingHom.ker (evalWorldPoly A B) := by
  rw [truncIdeal, Ideal.span_le]
  intro p hp
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hp
  rcases hp with rfl | rfl
  · simp [evalWorldPoly]
  · simp [evalWorldPoly]

/-- The abstract cohomology ring of an A x B GST world. -/
abbrev WorldCohomologyRing : Type :=
  WorldPoly ⧸ truncIdeal A B

/-- Class of the digit-axis generator. -/
def H : WorldCohomologyRing A B :=
  Ideal.Quotient.mk (truncIdeal A B) Hpoly

/-- Class of the carry-axis generator. -/
def V : WorldCohomologyRing A B :=
  Ideal.Quotient.mk (truncIdeal A B) Vpoly

@[simp]
theorem H_pow_depth :
    (H A B)^B = 0 := by
  unfold H
  rw [← map_pow]
  apply Ideal.Quotient.eq_zero_iff_mem.2
  exact Ideal.subset_span (Set.mem_insert _ _)

@[simp]
theorem V_pow_depth :
    (V A B)^A = 0 := by
  unfold V
  rw [← map_pow]
  apply Ideal.Quotient.eq_zero_iff_mem.2
  exact Ideal.subset_span
    (Set.mem_insert_of_mem _ (Set.mem_singleton _))

/-- Every digit-axis power at or beyond the native depth vanishes already
inside the cohomology ring, before applying the representation. -/
theorem H_pow_eq_zero_of_depth_le (n : Nat) (h : B ≤ n) :
    (H A B)^n = 0 :=
  pow_eq_zero_of_le h (H_pow_depth A B)

/-- Every carry-axis power at or beyond the native depth vanishes already
inside the cohomology ring. -/
theorem V_pow_eq_zero_of_depth_le (n : Nat) (h : A ≤ n) :
    (V A B)^n = 0 :=
  pow_eq_zero_of_le h (V_pow_depth A B)

/-- The polynomial GST action descends canonically through the quotient. -/
def worldOperatorHom :
    WorldCohomologyRing A B →+* WorldOperatorRing A B :=
  Ideal.Quotient.lift
    (truncIdeal A B)
    (evalWorldPoly A B)
    (truncIdeal_le_ker_evalWorldPoly A B)

@[simp]
theorem worldOperatorHom_H :
    worldOperatorHom A B (H A B) = hOp A B := by
  simp [worldOperatorHom, H, evalWorldPoly]

@[simp]
theorem worldOperatorHom_V :
    worldOperatorHom A B (V A B) = vOp A B := by
  simp [worldOperatorHom, V, evalWorldPoly]

/-! ## 3. The quotient ring acts on the world coefficient lattice -/

/-- Action of a cohomology-ring element through its native operator
representation. -/
def worldAct
    (r : WorldCohomologyRing A B)
    (g : WorldCoef A B) :
    WorldCoef A B :=
  ((worldOperatorHom A B r :
      WorldOperatorRing A B) :
    Module.End ℤ (WorldCoef A B)) g

@[simp]
theorem worldAct_zero (g : WorldCoef A B) :
    worldAct A B 0 g = 0 := by
  simp [worldAct]

@[simp]
theorem worldAct_one (g : WorldCoef A B) :
    worldAct A B 1 g = g := by
  simp [worldAct]

theorem worldAct_add
    (r s : WorldCohomologyRing A B)
    (g : WorldCoef A B) :
    worldAct A B (r+s) g =
      fun c => worldAct A B r g c + worldAct A B s g c := by
  funext c
  simp [worldAct]

theorem worldAct_mul
    (r s : WorldCohomologyRing A B)
    (g : WorldCoef A B) :
    worldAct A B (r*s) g =
      worldAct A B r (worldAct A B s g) := by
  simp [worldAct, Module.End.mul_apply]

/-- Exact additive inverse compatibility of the native action. -/
theorem worldAct_neg
    (r : WorldCohomologyRing A B)
    (g : WorldCoef A B) :
    worldAct A B (-r) g = - worldAct A B r g := by
  simp [worldAct]

/-- Powers in the cohomology ring compose as powers of the native action. -/
theorem worldAct_pow_add
    (r : WorldCohomologyRing A B)
    (m n : Nat)
    (g : WorldCoef A B) :
    worldAct A B (r^(m+n)) g =
      worldAct A B (r^m) (worldAct A B (r^n) g) := by
  rw [pow_add, worldAct_mul]

/-- Two classes induce the same action on every world coefficient exactly
when their native operator representatives are equal.  This is the precise
operational extensionality law, valid even for degenerate rectangles. -/
theorem worldAct_eq_iff_operator_eq
    (r s : WorldCohomologyRing A B) :
    (∀ g : WorldCoef A B, worldAct A B r g = worldAct A B s g) ↔
      worldOperatorHom A B r = worldOperatorHom A B s := by
  constructor
  · intro h
    apply Subtype.ext
    apply LinearMap.ext
    intro g
    exact h g
  · intro h g
    unfold worldAct
    rw [h]

/-- The representation kernel is exactly the set of cohomology classes that
annihilate every native world coefficient. -/
theorem mem_worldOperatorHom_ker_iff_annihilates
    (r : WorldCohomologyRing A B) :
    r ∈ RingHom.ker (worldOperatorHom A B) ↔
      ∀ g : WorldCoef A B, worldAct A B r g = 0 := by
  change worldOperatorHom A B r = 0 ↔ _
  constructor
  · intro h g
    unfold worldAct
    rw [h]
    rfl
  · intro h
    apply Subtype.ext
    apply LinearMap.ext
    intro g
    exact h g

@[simp]
theorem worldAct_H (g : WorldCoef A B) :
    worldAct A B (H A B) g = digitShiftN 1 g := by
  simp [worldAct, hOp]

@[simp]
theorem worldAct_V (g : WorldCoef A B) :
    worldAct A B (V A B) g = carryShiftN 1 g := by
  simp [worldAct, vOp]

/-- Every monomial H^m V^n acts by the corresponding mixed native shift. -/
theorem worldAct_monomial
    (m n : Nat) (g : WorldCoef A B) :
    worldAct A B ((H A B)^m * (V A B)^n) g =
      digitShiftN m (carryShiftN n g) := by
  simp [worldAct, Module.End.mul_apply, digitEndo_pow_apply,
    carryEndo_pow_apply]

/-- Exact mixed-transport extinction. A monomial annihilates every world
if and only if one displacement crosses its corresponding boundary. -/
theorem worldAct_monomial_zero
    (m n : Nat) :
    (∀ g : WorldCoef A B, worldAct A B ((H A B)^m * (V A B)^n) g = 0) ↔
      B ≤ m ∨ A ≤ n := by
  constructor
  · intro h
    by_contra hn
    have hmB : m < B := by omega
    have hnA : n < A := by omega
    have ht := congrFun (h (fun _ => 1)) (⟨n, hnA⟩, ⟨m, hmB⟩)
    simpa [worldAct_monomial, digitShiftN, carryShiftN] using ht
  · intro h g
    rw [worldAct_monomial]
    exact mixed_boundary_extinction g (by
      rcases h with hm | hn
      · exact Or.inr hm
      · exact Or.inl hn)

/-! ## 4. Lefschetz element and recovery of the old crown -/

/-- The universal Lefschetz class L = H+V. -/
def L : WorldCohomologyRing A B :=
  H A B + V A B

@[simp]
theorem worldAct_L (g : WorldCoef A B) :
    worldAct A B (L A B) g = lefschetzEndo A B g := by
  ext c
  simp [L, worldAct, lefschetzEndo]

/-- Exact binomial calculus for every power of the Lefschetz class inside
the cohomology ring itself. -/
theorem L_binomial (n : Nat) :
    (L A B)^n =
      ∑ m ∈ Finset.range (n+1),
        (H A B)^m * (V A B)^(n-m) *
          (n.choose m : WorldCohomologyRing A B) := by
  exact (Commute.all (H A B) (V A B)).add_pow n

/-- The universal Lefschetz class vanishes in the quotient ring itself at
the rectangular ceiling; this is strictly stronger than action-level
annihilation. -/
@[simp]
theorem L_pow_boundary :
    (L A B)^(A+B-1) = 0 := by
  simpa [L, Nat.add_comm] using
    (Commute.all (H A B) (V A B)).add_pow_add_eq_zero_of_pow_eq_zero
      (H_pow_depth A B) (V_pow_depth A B)

/-- Every higher Lefschetz power also vanishes in the cohomology ring. -/
theorem L_pow_eq_zero_of_boundary_le
    (n : Nat) (h : A+B-1 ≤ n) :
    (L A B)^n = 0 :=
  pow_eq_zero_of_le h (L_pow_boundary A B)

/-- The universal Lefschetz class is nilpotent at the sharp rectangular
ceiling inherited from the native operator action. -/
theorem worldAct_L_pow_boundary
    (g : WorldCoef A B) :
    worldAct A B ((L A B)^(A+B-1)) g = 0 := by
  rw [L_pow_boundary, worldAct_zero]

/-- The historical HC chart is exactly the quotient Z[H,V]/(H^3,V^4). -/
abbrev HCCohomologyRing : Type :=
  WorldCohomologyRing 4 3

theorem hc_H_cube :
    (H 4 3)^3 = 0 :=
  H_pow_depth 4 3

theorem hc_V_fourth :
    (V 4 3)^4 = 0 :=
  V_pow_depth 4 3

theorem hc_L_six_acts_zero
    (g : WorldCoef 4 3) :
    worldAct 4 3 ((L 4 3)^6) g = 0 := by
  simpa using worldAct_L_pow_boundary 4 3 g

/-- One capstone: the rectangular GST world is represented by a canonical
truncated two-generator commutative cohomology ring. -/
theorem truncated_world_ring_crown :
    (∀ A B, (H A B)^B = 0)
    ∧ (∀ A B, (V A B)^A = 0)
    ∧ (∀ A B (g : WorldCoef A B),
      worldAct A B (H A B) g = digitShiftN 1 g)
    ∧ (∀ A B (g : WorldCoef A B),
      worldAct A B (V A B) g = carryShiftN 1 g)
    ∧ (∀ A B (g : WorldCoef A B),
      worldAct A B ((L A B)^(A+B-1)) g = 0) := by
  exact ⟨
    fun A B => H_pow_depth A B,
    fun A B => V_pow_depth A B,
    fun A B g => worldAct_H A B g,
    fun A B g => worldAct_V A B g,
    fun A B g => worldAct_L_pow_boundary A B g⟩

#check WorldOperatorRing
#check H
#check V
#check L
#check H_pow_depth
#check V_pow_depth
#check H_pow_eq_zero_of_depth_le
#check V_pow_eq_zero_of_depth_le
#check worldOperatorHom
#check worldAct_neg
#check worldAct_pow_add
#check worldAct_eq_iff_operator_eq
#check mem_worldOperatorHom_ker_iff_annihilates
#check worldAct_H
#check worldAct_V
#check worldAct_monomial
#check worldAct_monomial_zero
#check worldAct_L
#check L_binomial
#check L_pow_boundary
#check L_pow_eq_zero_of_boundary_le
#check worldAct_L_pow_boundary
#check HCCohomologyRing
#check truncated_world_ring_crown

#print axioms truncIdeal_le_ker_evalWorldPoly
#print axioms H_pow_eq_zero_of_depth_le
#print axioms V_pow_eq_zero_of_depth_le
#print axioms worldAct_pow_add
#print axioms worldAct_eq_iff_operator_eq
#print axioms mem_worldOperatorHom_ker_iff_annihilates
#print axioms worldAct_monomial
#print axioms L_binomial
#print axioms L_pow_boundary
#print axioms L_pow_eq_zero_of_boundary_le
#print axioms worldAct_L_pow_boundary
#print axioms truncated_world_ring_crown

end GSTTruncatedWorldCohomologyRing
