import Mathlib
import Mathlib.RingTheory.MvPolynomial.Ideal
import GSTUniversalLefschetzCosmology
import GSTGradedWorldAlgebra

/-!
# GST TRUNCATED WORLD COHOMOLOGY RING

The separate axis, grading and Lefschetz laws of a rectangular GST world
come from one commutative operator algebra.

For an A x B world let H be the digit-axis shift and V the carry-axis shift.
They commute and satisfy H^B = 0, V^A = 0.  Hence the polynomial action of
Z[H,V] factors canonically through

    Z[H,V] / (H^B, V^A).

This file constructs that quotient and its representation on WorldCoef A B.
The original 4 x 3 crown is therefore the specialization

    Z[H,V] / (H^3, V^4).

No fixed twelve-cell argument appears in the construction.
-/

set_option maxHeartbeats 20000000
set_option maxRecDepth 1000000

namespace GSTTruncatedWorldCohomologyRing

open GSTWorldCosmology
open GSTUniversalLefschetzCosmology
open GSTGradedWorldAlgebra
open MvPolynomial
open scoped IsMulCommutative

variable (A B : Nat)

/-! ## 1. The commutative operator ring generated by the two GST axes -/

private theorem axis_generators_commute
    {x y : Module.End ℤ (WorldCoef A B)}
    (hx : x ∈ ({digitEndo A B, carryEndo A B} :
      Set (Module.End ℤ (WorldCoef A B))))
    (hy : y ∈ ({digitEndo A B, carryEndo A B} :
      Set (Module.End ℤ (WorldCoef A B)))) :
    x * y = y * x := by
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx hy
  rcases hx with rfl | rfl <;>
    rcases hy with rfl | rfl <;>
      simp [digit_carry_commute (A:=A) (B:=B)]

/-- The commutative subring generated by the native digit and carry
endomorphisms.  The ambient endomorphism ring need not be commutative. -/
def WorldOperatorRing : Type :=
  Subring.closure
    ({digitEndo A B, carryEndo A B} :
      Set (Module.End ℤ (WorldCoef A B)))

instance : IsMulCommutative (WorldOperatorRing A B) :=
  Subring.isMulCommutative_closure
    (axis_generators_commute A B)

def hOp : WorldOperatorRing A B :=
  ⟨digitEndo A B,
    Subring.subset_closure (Set.mem_insert _ _)⟩

def vOp : WorldOperatorRing A B :=
  ⟨carryEndo A B,
    Subring.subset_closure
      (Set.mem_insert_of_mem _ (Set.mem_singleton _))⟩

@[simp]
theorem hOp_val :
    (hOp A B : Module.End ℤ (WorldCoef A B)) = digitEndo A B :=
  rfl

@[simp]
theorem vOp_val :
    (vOp A B : Module.End ℤ (WorldCoef A B)) = carryEndo A B :=
  rfl

@[simp]
theorem hOp_pow_depth :
    (hOp A B)^B = 0 := by
  apply Subtype.ext
  exact digitEndo_pow_depth (A:=A) (B:=B)

@[simp]
theorem vOp_pow_depth :
    (vOp A B)^A = 0 := by
  apply Subtype.ext
  exact carryEndo_pow_depth (A:=A) (B:=B)

/-! ## 2. Universal polynomial presentation -/

abbrev WorldPoly : Type := MvPolynomial (Fin 2) ℤ

abbrev Hpoly : WorldPoly := X (0 : Fin 2)

abbrev Vpoly : WorldPoly := X (1 : Fin 2)

/-- The truncation ideal (H^B,V^A). -/
def truncIdeal : Ideal WorldPoly :=
  Ideal.span
    ({Hpoly ^ B, Vpoly ^ A} : Set WorldPoly)

/-- Polynomial evaluation at the native GST axis operators. -/
def evalWorldPoly :
    WorldPoly →+* WorldOperatorRing A B :=
  eval₂Hom (Int.castRingHom (WorldOperatorRing A B))
    ![hOp A B, vOp A B]

@[simp]
theorem evalWorldPoly_H :
    evalWorldPoly A B Hpoly = hOp A B := by
  simp [evalWorldPoly, Hpoly]

@[simp]
theorem evalWorldPoly_V :
    evalWorldPoly A B Vpoly = vOp A B := by
  simp [evalWorldPoly, Vpoly]

/-- The native representation kills both truncation generators. -/
theorem truncIdeal_le_ker_evalWorldPoly :
    truncIdeal A B ≤ RingHom.ker (evalWorldPoly A B) := by
  rw [truncIdeal, Ideal.span_le]
  intro p hp
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hp
  rcases hp with rfl | rfl
  · simp [evalWorldPoly]
  · simp [evalWorldPoly]

/-- The abstract cohomology ring of an A x B GST world. -/
abbrev WorldCohomologyRing : Type :=
  WorldPoly ⧸ truncIdeal A B

/-- Class of the digit-axis generator. -/
def H : WorldCohomologyRing A B :=
  Ideal.Quotient.mk (truncIdeal A B) Hpoly

/-- Class of the carry-axis generator. -/
def V : WorldCohomologyRing A B :=
  Ideal.Quotient.mk (truncIdeal A B) Vpoly

@[simp]
theorem H_pow_depth :
    (H A B)^B = 0 := by
  apply Ideal.Quotient.eq_zero_iff_mem.2
  exact Ideal.subset_span (Set.mem_insert _ _)

@[simp]
theorem V_pow_depth :
    (V A B)^A = 0 := by
  apply Ideal.Quotient.eq_zero_iff_mem.2
  exact Ideal.subset_span
    (Set.mem_insert_of_mem _ (Set.mem_singleton _))

/-- The polynomial GST action descends canonically through the quotient. -/
def worldOperatorHom :
    WorldCohomologyRing A B →+* WorldOperatorRing A B :=
  Ideal.Quotient.lift
    (truncIdeal A B)
    (evalWorldPoly A B)
    (truncIdeal_le_ker_evalWorldPoly A B)

@[simp]
theorem worldOperatorHom_H :
    worldOperatorHom A B (H A B) = hOp A B := by
  simp [worldOperatorHom, H, evalWorldPoly]

@[simp]
theorem worldOperatorHom_V :
    worldOperatorHom A B (V A B) = vOp A B := by
  simp [worldOperatorHom, V, evalWorldPoly]

/-! ## 3. The quotient ring acts on the world coefficient lattice -/

/-- Action of a cohomology-ring element through its native operator
representation. -/
def worldAct
    (r : WorldCohomologyRing A B)
    (g : WorldCoef A B) :
    WorldCoef A B :=
  ((worldOperatorHom A B r :
      WorldOperatorRing A B) :
    Module.End ℤ (WorldCoef A B)) g

@[simp]
theorem worldAct_zero (g : WorldCoef A B) :
    worldAct A B 0 g = 0 := by
  simp [worldAct]

@[simp]
theorem worldAct_one (g : WorldCoef A B) :
    worldAct A B 1 g = g := by
  simp [worldAct]

theorem worldAct_add
    (r s : WorldCohomologyRing A B)
    (g : WorldCoef A B) :
    worldAct A B (r+s) g =
      fun c => worldAct A B r g c + worldAct A B s g c := by
  simp [worldAct]

theorem worldAct_mul
    (r s : WorldCohomologyRing A B)
    (g : WorldCoef A B) :
    worldAct A B (r*s) g =
      worldAct A B r (worldAct A B s g) := by
  simp [worldAct, Module.End.mul_apply]

@[simp]
theorem worldAct_H (g : WorldCoef A B) :
    worldAct A B (H A B) g = digitShiftN 1 g := by
  simp [worldAct, hOp]

@[simp]
theorem worldAct_V (g : WorldCoef A B) :
    worldAct A B (V A B) g = carryShiftN 1 g := by
  simp [worldAct, vOp]

/-- Every monomial H^m V^n acts by the corresponding mixed native shift. -/
theorem worldAct_monomial
    (m n : Nat) (g : WorldCoef A B) :
    worldAct A B ((H A B)^m * (V A B)^n) g =
      digitShiftN m (carryShiftN n g) := by
  rw [worldAct_mul]
  have hh :
      worldAct A B ((H A B)^m)
        (worldAct A B ((V A B)^n) g) =
      digitShiftN m
        (worldAct A B ((V A B)^n) g) := by
    induction m with
    | zero =>
        simp
    | succ m ih =>
        rw [pow_succ, worldAct_mul, worldAct_H, ih]
        rw [digitShiftN_add]
        congr 1
        omega
  rw [hh]
  congr 1
  induction n with
  | zero =>
      simp
  | succ n ih =>
      rw [pow_succ, worldAct_mul, worldAct_V, ih]
      rw [carryShiftN_add]
      congr 1
      omega

/-- Mixed monomials crossing either rectangle boundary act as zero. -/
theorem worldAct_monomial_zero
    (m n : Nat) (g : WorldCoef A B)
    (h : B ≤ m ∨ A ≤ n) :
    worldAct A B ((H A B)^m * (V A B)^n) g = 0 := by
  rw [worldAct_monomial]
  exact mixed_boundary_extinction g (by
    rcases h with hm | hn
    · exact Or.inr hm
    · exact Or.inl hn)

/-! ## 4. Lefschetz element and recovery of the old crown -/

/-- The universal Lefschetz class L = H+V. -/
def L : WorldCohomologyRing A B :=
  H A B + V A B

@[simp]
theorem worldAct_L (g : WorldCoef A B) :
    worldAct A B (L A B) g = lefschetzEndo A B g := by
  ext c
  simp [L, worldAct, lefschetzEndo]

/-- The universal Lefschetz class is nilpotent at the sharp rectangular
ceiling inherited from the native operator action. -/
theorem worldAct_L_pow_boundary
    (g : WorldCoef A B) :
    worldAct A B ((L A B)^(A+B-1)) g = 0 := by
  change
    ((worldOperatorHom A B ((L A B)^(A+B-1)) :
      WorldOperatorRing A B) :
      Module.End ℤ (WorldCoef A B)) g = 0
  rw [map_pow]
  have hL :
      worldOperatorHom A B (L A B) =
        ⟨lefschetzEndo A B, by
          rw [lefschetzEndo]
          exact Subring.add_mem _
            (Subring.subset_closure (Set.mem_insert _ _))
            (Subring.subset_closure
              (Set.mem_insert_of_mem _ (Set.mem_singleton _)))⟩ := by
    apply Subtype.ext
    ext x
    simp [L, lefschetzEndo, worldOperatorHom_H, worldOperatorHom_V]
  rw [hL]
  have hz :
      (lefschetzEndo A B)^(A+B-1) = 0 :=
    lefschetz_pow_boundary (A:=A) (B:=B)
  have hz' :
      (⟨lefschetzEndo A B, by
          rw [lefschetzEndo]
          exact Subring.add_mem _
            (Subring.subset_closure (Set.mem_insert _ _))
            (Subring.subset_closure
              (Set.mem_insert_of_mem _ (Set.mem_singleton _)))⟩ :
        WorldOperatorRing A B)^(A+B-1) = 0 := by
    apply Subtype.ext
    exact hz
  rw [hz']
  rfl

/-- The historical HC chart is exactly the quotient Z[H,V]/(H^3,V^4). -/
abbrev HCCohomologyRing : Type :=
  WorldCohomologyRing 4 3

theorem hc_H_cube :
    (H 4 3)^3 = 0 :=
  H_pow_depth 4 3

theorem hc_V_fourth :
    (V 4 3)^4 = 0 :=
  V_pow_depth 4 3

theorem hc_L_six_acts_zero
    (g : WorldCoef 4 3) :
    worldAct 4 3 ((L 4 3)^6) g = 0 := by
  simpa using worldAct_L_pow_boundary 4 3 g

/-- One capstone: the rectangular GST world is represented by a canonical
truncated two-generator commutative cohomology ring. -/
theorem truncated_world_ring_crown :
    (∀ A B, (H A B)^B = 0)
    ∧ (∀ A B, (V A B)^A = 0)
    ∧ (∀ A B (g : WorldCoef A B),
      worldAct A B (H A B) g = digitShiftN 1 g)
    ∧ (∀ A B (g : WorldCoef A B),
      worldAct A B (V A B) g = carryShiftN 1 g)
    ∧ (∀ A B (g : WorldCoef A B),
      worldAct A B ((L A B)^(A+B-1)) g = 0) := by
  exact ⟨
    fun A B => H_pow_depth A B,
    fun A B => V_pow_depth A B,
    fun A B g => worldAct_H A B g,
    fun A B g => worldAct_V A B g,
    fun A B g => worldAct_L_pow_boundary A B g⟩

#check WorldOperatorRing
#check H
#check V
#check L
#check H_pow_depth
#check V_pow_depth
#check worldOperatorHom
#check worldAct_H
#check worldAct_V
#check worldAct_monomial
#check worldAct_monomial_zero
#check worldAct_L
#check worldAct_L_pow_boundary
#check HCCohomologyRing
#check truncated_world_ring_crown

#print axioms truncIdeal_le_ker_evalWorldPoly
#print axioms worldAct_monomial
#print axioms worldAct_L_pow_boundary
#print axioms truncated_world_ring_crown


/-! ## Universal coordinate geometry and its inverse system of quotients -/
/-- Every finite geometry is projected from the same two-generator algebra. -/
def coordinateProjection : WorldPoly →+* WorldCohomologyRing A B :=
  Ideal.Quotient.mk (truncIdeal A B)

/-- Enlarging a window weakens its ideal; restriction is a genuine ring map. -/
def quotientRestriction {C D : ℕ} (hA : A ≤ C) (hB : B ≤ D) :
    WorldCohomologyRing C D →+* WorldCohomologyRing A B :=
  Ideal.Quotient.lift (truncIdeal C D) (coordinateProjection A B) (by
    rw [truncIdeal, Ideal.span_le]
    intro p hp
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hp
    rcases hp with rfl | rfl
    · change coordinateProjection A B (Hpoly^D) = 0
      rw [map_pow]
      exact pow_eq_zero_of_le hB (H_pow_depth A B)
    · change coordinateProjection A B (Vpoly^C) = 0
      rw [map_pow]
      exact pow_eq_zero_of_le hA (V_pow_depth A B))

@[simp] theorem quotientRestriction_projection {C D : ℕ}
    (hA : A ≤ C) (hB : B ≤ D) (p : WorldPoly) :
    quotientRestriction A B hA hB (coordinateProjection C D p) =
      coordinateProjection A B p := rfl

theorem quotientRestriction_trans {C D E F : ℕ}
    (hAC : A ≤ C) (hBD : B ≤ D) (hCE : C ≤ E) (hDF : D ≤ F)
    (x : WorldCohomologyRing E F) :
    quotientRestriction A B hAC hBD (quotientRestriction C D hCE hDF x) =
      quotientRestriction A B (hAC.trans hCE) (hBD.trans hDF) x := by
  refine Quotient.inductionOn x ?_
  intro p
  rfl

/-- Formal coordinate completion is explicitly a compatible family of
quotient geometries; no unsupported identification with algebraic fields. -/
def FormalCoordinateCosmos :=
  {x : ∀ A B, WorldCohomologyRing A B //
    ∀ A B C D (hA : A ≤ C) (hB : B ≤ D),
      quotientRestriction A B hA hB (x C D) = x A B}

def polynomialCompletion (p : WorldPoly) : FormalCoordinateCosmos :=
  ⟨fun A B => coordinateProjection A B p, by intros; rfl⟩


/-- Exact generic support criterion for the window ideal: every monomial
lies beyond at least one of the two observation depths. -/
theorem mem_truncIdeal_iff (p : WorldPoly) :
    p ∈ truncIdeal A B ↔ ∀ d ∈ p.support, B ≤ d 0 ∨ A ≤ d 1 := by
  have h := (MvPolynomial.mem_ideal_span_monomial_image
    (x:=p) (s:=({Finsupp.single (0 : Fin 2) B,
      Finsupp.single (1 : Fin 2) A} : Set (Fin 2 →₀ ℕ))))
  simpa [truncIdeal, Hpoly, Vpoly, Set.image_insert_eq, Set.image_singleton,
    ← MvPolynomial.X_pow_eq_monomial, Finsupp.single_le_iff] using h

end GSTTruncatedWorldCohomologyRing
